CREATE TABLE IF NOT EXISTS manager_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manager_name TEXT NOT NULL,
  market_fit_score INT DEFAULT 0,
  style_clarity_score INT DEFAULT 0,
  recent_activity_score INT DEFAULT 0,
  risk_control_score INT DEFAULT 0,
  trend_fit_reason TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_manager_scores_manager_created_at
ON manager_scores (manager_name, created_at DESC);

CREATE TABLE IF NOT EXISTS stock_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL,
  market_type TEXT DEFAULT '',
  report_type TEXT DEFAULT '',
  report_content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stock_reports_cache_lookup
ON stock_reports (ticker, report_type, market_type, created_at DESC);

CREATE TABLE IF NOT EXISTS trade_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL,
  action TEXT NOT NULL,
  buy_price NUMERIC,
  sell_price NUMERIC,
  reason TEXT DEFAULT '',
  result TEXT DEFAULT '',
  lesson TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_trade_reviews_ticker_created_at
ON trade_reviews (ticker, created_at DESC);
