import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1] / "desktop"


class CommandCenterHomeOrdinaryEntryTests(unittest.TestCase):
    def setUp(self):
        self.source = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")

    def test_daily_command_center_summary_shows_user_decision_fields_first(self):
        source = self.source

        self.assertIn("<h1>今日作战台</h1>", source)
        self.assertIn("先看下一步、数据来源、缺少证据和仅供研究边界", source)
        self.assertIn('title="本地 FastAPI 接线速读"', source)
        self.assertLess(source.index('title="本地 FastAPI 接线速读"'), source.index('title="今日作战台摘要"'))
        self.assertIn('title="使用者可用化进度"', source)
        self.assertLess(source.index('title="本地 FastAPI 接线速读"'), source.index('title="使用者可用化进度"'))
        self.assertLess(source.index('title="使用者可用化进度"'), source.index('title="P0 现在能不能用"'))
        self.assertIn('title="P0 现在能不能用"', source)
        self.assertLess(source.index('title="本地 FastAPI 接线速读"'), source.index('title="P0 现在能不能用"'))
        self.assertLess(source.index('title="P0 现在能不能用"'), source.index('title="今日作战台摘要"'))
        self.assertIn('title="今日作战台摘要"', source)
        self.assertIn('title="P3 可解释结果一眼读懂"', source)
        self.assertIn('title="P1 Tushare-first 链路速读"', source)
        self.assertLess(source.index('title="首页确认股票代码"'), source.index('title="P1 Tushare-first 链路速读"'))
        self.assertLess(source.index('title="P1 Tushare-first 链路速读"'), source.index('title="当前可用投研链路"'))
        self.assertIn('title="P2 小数据三面速读"', source)
        self.assertLess(source.index('title="当前可用投研链路"'), source.index('title="P2 小数据三面速读"'))
        self.assertLess(source.index('title="P2 小数据三面速读"'), source.index('title="P3 可解释结果一眼读懂"'))
        self.assertLess(source.index('title="P3 可解释结果一眼读懂"'), source.index('title="最近本地任务"'))
        self.assertLess(source.index('title="最近本地任务"'), source.index('title="今日作战台摘要"'))
        self.assertLess(source.index('title="P3 可解释结果一眼读懂"'), source.index('title="今日作战台摘要"'))
        self.assertIn("下一步、来源、缺口、边界和最近可用缓存", source)
        self.assertIn('label: "下一步"', source)
        self.assertIn('label: "主下一步"', source)
        self.assertIn('label: "主下一步边界"', source)
        self.assertIn('label: "本地联通"', source)
        self.assertIn('label: "一键启动"', source)
        self.assertIn('label: "首页读法"', source)
        self.assertIn("多接口本地聚合：health / bootstrap / preflight / radar / factor / next / tasks", source)
        self.assertIn('label: "启动恢复"', source)
        self.assertIn('label: "启动边界"', source)
        self.assertIn('label: "启动成功条件"', source)
        self.assertIn('label: "启动诊断"', source)
        self.assertIn('label: "启动失败处理"', source)
        self.assertIn('label: "恢复回读"', source)
        self.assertIn('label: "回读顺序"', source)
        self.assertIn('label: "回读边界"', source)
        self.assertIn('label: "只读自检"', source)
        self.assertIn('label: "P0 可继续"', source)
        self.assertIn('label: "P0 进入 P1 闸门"', source)
        self.assertIn('label: "联通后行动"', source)
        self.assertIn('label: "一屏行动"', source)
        self.assertIn('label: "确认结果链"', source)
        self.assertIn('label: "确认后回放"', source)
        self.assertIn('label: "量化缓存回放"', source)
        self.assertIn('label: "Factor handoff"', source)
        self.assertIn("dailyCommandFactorCandidateHandoffLabel", source)
        self.assertIn("dailyCommandFactorCandidateHandoffReady", source)
        self.assertIn("dailyCommandStartupReadbackRows", source)
        self.assertIn("dailyCommandHomeAggregateReadbackRows", source)
        self.assertIn("p0LauncherCheckOnlyRows", source)
        self.assertIn("p0OrdinaryQuickActionRows", source)
        self.assertIn("p0CurrentNextActionRows", source)
        self.assertIn("dailyCommandP0EntryGateRows", source)
        self.assertIn("candidatePolicy", source)
        self.assertIn("candidateQuantOneScreenActionRows", source)
        self.assertIn("candidateQuantSmallDataWriteback.ordinary_one_screen_action_rows", source)
        self.assertIn("candidateQuantConfirmOutcomeRows", source)
        self.assertIn("candidateQuantSmallDataWriteback.ordinary_confirm_outcome_rows", source)
        self.assertIn("dailyCommandOneScreenActionRows", source)
        self.assertIn("dailyCommandOneScreenActionLabel", source)
        self.assertIn("dailyCommandConfirmOutcomeRows", source)
        self.assertIn("dailyCommandConfirmOutcomeLabel", source)
        self.assertIn("dailyCommandP2P3ReplayChecklistRows", source)
        self.assertIn("candidateQuantResultCheckpoint", source)
        self.assertIn("candidates.search_quant_projection_result_checkpoint", source)
        self.assertIn("candidates.search_quant_projection_latest_confirmed_symbol", source)
        self.assertIn("candidates.ordinary_result_quick_read_rows", source)
        self.assertIn("candidateQuantDecisionBriefRows", source)
        self.assertIn("candidates.ordinary_result_decision_brief_rows", source)
        self.assertIn("candidates.search_quant_projection_result_decision_brief_rows", source)
        self.assertIn("candidateQuantHandoffRows", source)
        self.assertIn("candidates.ordinary_result_handoff_rows", source)
        self.assertIn("candidates.ordinary_result_checkpoint_rows", source)
        self.assertIn("candidates.search_quant_projection_result_checkpoint_rows", source)
        self.assertIn("dailyCommandP3OneGlanceStatus", source)
        self.assertIn("dailyCommandP3OneGlanceSource", source)
        self.assertIn("dailyCommandP3OneGlanceMissingEvidence", source)
        self.assertIn("dailyCommandP3OneGlanceSafeFields", source)
        self.assertIn("dailyCommandP3OneGlanceModelStateRaw", source)
        self.assertIn("dailyCommandP3OneGlanceUsesModelOutput", source)
        self.assertIn("candidateQuantDeepSeekReadinessRows", source)
        self.assertIn("modelStrategyGovernedExecutor", source)
        self.assertIn("modelStrategyP5RealCallGateRows", source)
        self.assertIn("modelStrategyP5NonblockingRows", source)
        self.assertIn("modelStrategyP5GovernanceRows", source)
        self.assertIn("dailyCommandP5NonblockingRows", source)
        self.assertIn('aria-label="daily command p5 nonblocking one minute read"', source)
        self.assertIn("P5 不阻塞速读", source)
        self.assertIn("本区只读治理状态，不调用模型", source)
        self.assertIn("优先读取 /api/model-strategy/cache 的 governed_executor", source)
        self.assertIn("CandidateRadar governance rows 只作 fallback", source)
        self.assertIn("优先读取 modelStrategy.governed_executor 的 ordinary_status_label", source)
        self.assertIn("CandidateRadar readiness rows 只作 fallback", source)
        self.assertIn("GET /api/model-strategy/cache 只读，不调用 DeepSeek、不创建模型任务", source)
        self.assertIn("real_call_gate_rows", source)
        self.assertIn("ordinary_deepseek_governed_executor_readiness_rows", source)
        self.assertIn("candidates.ordinary_result_deepseek_governed_executor_status", source)
        self.assertIn("DeepSeek 不用等：Tushare-first 和基础图谱可先看；P5 governed executor 单独补", source)
        self.assertIn("DeepSeek 待治理：不阻塞 Tushare-first、P2 写入或 P3 基础图谱", source)
        self.assertIn("factorFailedCacheSummary", source)
        self.assertIn("dailyCommandFactorCacheFallbackActive", source)
        self.assertIn("dailyCommandFactorCacheFallbackLabel", source)
        self.assertIn("dailyCommandFactorCacheFallbackBoundary", source)
        self.assertIn("dailyCommandFactorCacheFallbackRows", source)
        self.assertIn("dailyCommandP6StrictCloseoutReentryRows", source)
        self.assertIn("desktopPreflight.p0_current_next_action_rows", source)
        self.assertIn("dailyCommandP0QuickAction", source)
        self.assertIn("dailyCommandUsablePathStageRailSteps", source)
        self.assertIn("dailyCommandCurrentResearchSnapshotItems", source)
        self.assertIn('aria-label="daily command current research snapshot"', source)
        self.assertIn("最近确认投研快照", source)
        self.assertIn('label: "最近标的"', source)
        self.assertIn('label: "确认任务"', source)
        self.assertIn('label: "数据链"', source)
        self.assertIn('label: "P2 写入"', source)
        self.assertIn('label: "P3 结论"', source)
        self.assertIn('label: "次日图谱"', source)
        self.assertIn("dailyCommandNextSessionReplaySummary", source)
        self.assertIn("next.ordinary_result_replay_summary", source)
        self.assertIn("dailyCommandNextSessionChartReady", source)
        self.assertIn("dailyCommandNextSessionConfirmedSymbol", source)
        self.assertIn("dailyCommandNextSessionChartSymbol", source)
        self.assertIn("dailyCommandNextSessionPreviewSource", source)
        self.assertIn("next.button_gated_local_confirmed_symbol_preview === true", source)
        self.assertIn("次日图谱已绑定 ${dailyCommandNextSessionConfirmedSymbol", source)
        self.assertIn("按钮门控本地预览，非 provider-backed", source)
        self.assertIn("看股票量化推演和次日图谱", source)
        self.assertIn("首屏快照只读已有 cache / ledger / packet；不会创建 task、不会补调 Tushare/DeepSeek", source)
        self.assertIn("这张首屏快照只读最近确认任务、Tushare-first 数据链、P2 三面、P3 可读结论和次日图谱回放", source)
        self.assertIn('aria-label="daily command local connection readback"', source)
        self.assertIn('aria-label="daily command home aggregate readback"', source)
        self.assertIn('aria-label="daily command usable path stage rail"', source)
        self.assertIn('aria-label="daily command engineering audit and strict closeout details"', source)
        self.assertIn('aria-label="daily command p6 strict closeout reentry"', source)
        self.assertIn('aria-label="daily command p6 reentry links"', source)
        self.assertIn('aria-label="daily command p0 launcher check-only readback"', source)
        self.assertIn('aria-label="daily command p0 p1 entry gate"', source)
        self.assertIn('aria-label="daily command p0 current next action"', source)
        self.assertIn('aria-label="daily command one screen search actions"', source)
        self.assertIn('aria-label="daily command p2 p3 replay checklist"', source)
        self.assertIn('aria-label="daily command p0 quick action handoff"', source)
        self.assertIn('aria-label="daily command factor cache fallback readback"', source)
        self.assertIn("本地联通四段回读", source)
        self.assertIn("首页多接口回读", source)
        self.assertIn("首页是多个本地只读接口合成的作战台，不依赖单个总 cache URL", source)
        self.assertIn("不依赖单个 /api/command-center/cache", source)
        self.assertIn("GET /api/candidate-radar/cache + /api/factor-quant/cache + /api/next-session/cache + /api/tasks", source)
        self.assertIn("工程审计 / P6 strict closeout 明细", source)
        self.assertIn("普通路径已经在上方 P1 确认、P2 三面和 P3 可解释结果", source)
        self.assertIn("普通用户先看上方 P1 确认、P2 三面和 P3 可解释结果", source)
        self.assertIn("P6 strict closeout 回归入口", source)
        self.assertIn("一键启动只读自检", source)
        self.assertIn("P0 进入 P1 闸门", source)
        self.assertIn("P0 当前下一步", source)
        self.assertIn("今日搜票一屏行动", source)
        self.assertIn("确认后回放清单", source)
        self.assertIn("P0 到 P1 快速行动", source)
        self.assertIn("量化缓存降级回放", source)
        self.assertIn("量化缓存已降级为本地可读", source)
        self.assertIn("量化缓存直接可读；未检测到失败持久化 packet 降级", source)
        self.assertIn("failed_factor_quant_cache_summary 安全摘要", source)
        self.assertIn("量化缓存降级只返回安全摘要和本地 builder 结果", source)
        self.assertIn("首页不展开 raw failed packet、provider error、token/key 或 call_ledger", source)
        self.assertIn("如果上次持久化量化 packet 是失败态，首页只读展示安全摘要，并继续使用本地 cache-only 回放", source)
        self.assertIn('回放项: "当前量化缓存"', source)
        self.assertIn('回放项: "失败持久化降级"', source)
        self.assertIn('label: "P0 本地联通"', source)
        self.assertIn('label: "P1 确认按钮"', source)
        self.assertIn('label: "P2 小数据"', source)
        self.assertIn('label: "P3 可解释结果"', source)
        self.assertIn('label: "P4 审计下沉"', source)
        self.assertIn('label: "P5 解释治理"', source)
        self.assertIn('label: "P6 LTG 证据"', source)
        self.assertIn("dailyCommandUsablePathP1Done", source)
        self.assertIn("dailyCommandUsablePathP1State", source)
        self.assertIn("dailyCommandUsablePathP1Detail", source)
        self.assertIn("ledger ready", source)
        self.assertIn("task visible", source)
        self.assertIn("confirm", source)
        self.assertIn("dailyCommandUsablePathP2State", source)
        self.assertIn("dailyCommandUsablePathP3State", source)
        self.assertIn("after P1", source)
        self.assertIn("after P2", source)
        self.assertIn('"cache/ledger/packet"', source)
        self.assertIn('detail: "governed"', source)
        self.assertIn('detail: "0/14"', source)
        self.assertIn('阶段: "P6 回到 14 LTG direct evidence"', source)
        self.assertIn("re-entry gate visible；strict closeout ${dailyCommandP6StrictCloseoutState}", source)
        self.assertIn('回归项: "1. 可用化 checkpoint"', source)
        self.assertIn('回归项: "2. strict closeout 入口"', source)
        self.assertIn('回归项: "3. 任务证据回放"', source)
        self.assertIn("14 LTG strict closeout 仍需 current-head direct evidence", source)
        self.assertIn("打开迁移状态页，按 LTG next acceptance action rows 逐项补证", source)
        self.assertIn("P0-P5 可用化 checkpoint 不是 14 LTG 完成", source)
        self.assertIn("mock、matrix、sanitizer、local receipt 不能关闭 LTG", source)
        self.assertIn("P0-P5 是使用者可用化 checkpoint；14 LTG strict closeout 仍需 current-head direct evidence", source)
        self.assertIn("普通路径已经在上方 P1 确认、P2 三面和 P3 可解释结果", source)
        snapshot_start = source.index('aria-label="daily command current research snapshot"')
        snapshot_end = source.index("DataLineageTable rows={dailyCommandUsableShortestPathPrimaryRows}", snapshot_start)
        snapshot_slice = source[snapshot_start:snapshot_end]
        self.assertIn("MetricGrid items={dailyCommandCurrentResearchSnapshotItems}", snapshot_slice)
        for forbidden in ("task_id", "ledger", "packet", "boundary", "DeepSeek skipped"):
            self.assertNotIn(forbidden, snapshot_slice)
        self.assertNotIn("launchHomeQuantProjection", snapshot_slice)
        self.assertNotIn("postCandidateRadarQuantProjection", snapshot_slice)
        self.assertNotIn("onClick=", snapshot_slice)
        self.assertNotIn("postTask(", snapshot_slice)
        self.assertLess(source.index('aria-label="daily command current research snapshot"'), source.index('title="首页确认股票代码"'))
        self.assertIn("先看 FastAPI、bootstrap runtime-mode packet、desktop preflight cache、React/Vite 前端四段是否变绿", source)
        self.assertIn("优先读取 desktop preflight 的 p0_launcher_check_only_rows", source)
        self.assertIn("check-only 只打印配置，不启动 FastAPI/Vite、不探测 URL、不打开浏览器、不创建 task", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_one_screen_action_rows", source)
        self.assertIn("确认、任务、写回、结果合成首页速读", source)
        self.assertIn("首页只读回放，不创建 task、不调用模型", source)
        self.assertIn('aria-label="daily command confirm outcome readback"', source)
        self.assertIn("确认结果链速读", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_confirm_outcome_rows", source)
        self.assertIn("确认任务是否接收、P2 三面是否回放、P3 结果入口是否可读", source)
        self.assertIn("首页只读回放，不创建第二个 task", source)
        self.assertIn('确认结果: "P1 确认结果"', source)
        self.assertIn('确认结果: "P2 写回结果"', source)
        self.assertIn('确认结果: "P3 回放结果"', source)
        self.assertIn("确认回执 -> 任务状态 -> P2 写回 -> P3 结果", source)
        self.assertIn("确认按钮返回 task 后，按确认回执、任务状态、P2 写回三面、P3 结果顺序回放", source)
        self.assertIn("本卡只读 CandidateRadar cache / ledger / packet，不创建第二个 task、不补调 Tushare/DeepSeek", source)
        self.assertIn('title="首页确认股票代码"', source)
        self.assertIn("首页确认按钮复用 POST /api/candidate-radar/quant-projection", source)
        self.assertIn("candidateQuantTushareFirstRows", source)
        self.assertIn("candidates.ordinary_tushare_first_chain_rows", source)
        self.assertIn("candidateQuantConfirmedTaskReceiptRows", source)
        self.assertIn("candidateQuantTaskReadbackRows", source)
        self.assertIn("candidates.search_quant_projection_confirmed_task_receipt_rows", source)
        self.assertIn("candidates.search_quant_projection_task_readback_rows", source)
        self.assertIn("dailyCommandP1ConfirmTaskReadbackRows", source)
        self.assertIn("candidateQuantConfirmChainCheckpoint", source)
        self.assertIn("dailyCommandTushareFirstLedgerLabel", source)
        self.assertIn("candidateQuantSmallDataWriteback.source_task_tushare_provider_ledger_ready", source)
        self.assertIn("candidateQuantSmallDataWriteback.provider_call_ledger_replayed_from_source_task", source)
        self.assertIn("candidateQuantSmallDataWriteback.provider_call_ledger_written", source)
        self.assertIn("candidateQuantSmallDataWriteback.ledger_ready", source)
        self.assertIn("Number(candidateQuantSmallDataWriteback.provider_api_success_count ?? 0) > 0", source)
        self.assertIn("dailyCommandTushareFirstLedgerReady", source)
        self.assertIn("CandidateRadar small_data_writeback_summary + source task call_ledger", source)
        self.assertIn("直接看 P2 小数据三面和 P3 可解释结果；新标的再点确认按钮", source)
        self.assertIn("确认任务已可见：${homeQuantVisibleTaskId}；等待 Tushare-first ledger 回放", source)
        self.assertIn("P1 链路四步", source)
        self.assertIn('aria-label="daily command p1 tushare first front row"', source)
        self.assertIn("输入是否静默、确认按钮是否创建 task、Tushare ledger 是否回放、DeepSeek 是否 skipped", source)
        self.assertIn("P1 速读只回放已写入的 POST task / call_ledger / packet 证据", source)
        self.assertIn('aria-label="daily command p1 confirm task readback proof"', source)
        self.assertIn("P1 确认任务回放", source)
        self.assertIn('label: "确认回执"', source)
        self.assertIn('label: "任务状态"', source)
        self.assertIn("只读 search_quant_projection_confirmed_task_receipt_rows / task_readback_rows；不创建第二个 task", source)
        self.assertIn("优先读取 CandidateRadar 的 search_quant_projection_confirmed_task_receipt_rows 和 search_quant_projection_task_readback_rows", source)
        self.assertIn("DataLineageTable rows={dailyCommandP1ConfirmTaskReadbackRows}", source)
        self.assertIn("不会从首页回放卡创建第二个 task、补调 Tushare/DeepSeek、读取 token/key、执行交易或修改 strategy action", source)
        self.assertIn('aria-label="daily command ordinary p2 writeback front row"', source)
        self.assertIn("P2 三面回放", source)
        self.assertIn("确认后直接看 cache、call_ledger、packet 是否能本地回放", source)
        self.assertIn("完整工程审计仍下沉在折叠明细", source)
        self.assertIn('aria-label="daily command p2 writeback front actions"', source)
        self.assertIn("这张卡只读已有 P2 写回摘要；不创建第二个 task、不补调 Tushare/DeepSeek、不展示 raw log", source)
        self.assertIn("P2 三面速读只从 CandidateRadar cache / call_ledger / packet 回放", source)
        self.assertIn('回放入口: "1. 确认回执"', source)
        self.assertIn('回放入口: "2. 任务状态"', source)
        self.assertIn('回放入口: "3. P2 写回三面"', source)
        self.assertIn('回放入口: "4. P3 结果"', source)
        self.assertIn("search_quant_projection_confirmed_task_receipt_row_count", source)
        self.assertIn("search_quant_projection_task_readback_row_count", source)
        self.assertIn("CandidateRadar ordinary_confirmed_task_receipt_rows", source)
        self.assertIn("CandidateRadar ordinary_task_readback_rows", source)
        self.assertIn("首页只读 packet；不展示 raw log、token/key 或 provider error", source)
        self.assertIn('行动: "1. 确认"', source)
        self.assertIn('行动: "2. 任务"', source)
        self.assertIn('行动: "3. 写回"', source)
        self.assertIn('行动: "4. 结果"', source)
        self.assertIn("优先读取 desktop preflight 的 p0_ordinary_quick_action_rows", source)
        self.assertIn("优先读取 desktop preflight 的 p0_current_next_action_rows", source)
        self.assertIn("普通用户先看这张清单：health、bootstrap status、desktop preflight 和当前 React 页面四段通过后，才进入首页确认卡", source)
        self.assertIn("输入仍保持静默，只有确认按钮创建 Tushare-first POST task", source)
        self.assertIn("rows={dailyCommandP0EntryGateRows}", source)
        self.assertIn('闸门项: "1. FastAPI health"', source)
        self.assertIn('闸门项: "2. Bootstrap runtime"', source)
        self.assertIn('闸门项: "3. Desktop preflight"', source)
        self.assertIn('闸门项: "4. 进入 P1"', source)
        self.assertIn("P0 未 ready：不要进入 P1", source)
        self.assertIn("P0 ready 不代表 Tushare/DeepSeek 已调用，也不是 release ready 或 14 LTG 完成", source)
        self.assertIn("未 ready 回预检恢复，ready 后先到首页确认卡", source)
        self.assertIn("确认按钮之前不创建 Tushare-first task", source)
        self.assertIn('回读项: "FastAPI health"', source)
        self.assertIn('回读项: "Bootstrap status"', source)
        self.assertIn('回读项: "Desktop preflight cache"', source)
        self.assertIn('回读项: "React/Vite 前端"', source)
        self.assertIn("Command Center 3.0 health JSON 且 external_calls_on_startup=false", source)
        self.assertIn("只读运行模式，不写配置、不创建 live_light task", source)
        self.assertIn("返回 command_center_3_desktop_shell_preflight_cache 一键启动 packet", source)
        self.assertIn("首页只展示预检 packet，不启动 FastAPI/Vite/浏览器", source)
        self.assertIn("首页只展示预检结果，不启动 FastAPI/Vite/浏览器", source)
        self.assertIn('label: "股票量化推演"', source)
        self.assertIn('label: "量化缓存回放"', source)
        self.assertIn('label: "下一票雷达"', source)
        self.assertIn('label: "今日查看顺序"', source)
        self.assertIn('label: "今日结果组成"', source)
        self.assertIn('label: "本地缓存"', source)
        self.assertIn('label: "数据链"', source)
        self.assertIn('label: "解释状态"', source)
        self.assertIn('label: "外联触发边界"', source)
        self.assertIn('label: "待补证据"', source)
        self.assertIn('label: "降级提示"', source)
        self.assertIn('label: "最近成功回放"', source)
        self.assertIn('label: "数据来源"', source)
        self.assertIn('label: "缺少证据"', source)
        self.assertIn('label: "阻断/降级"', source)
        self.assertIn('label: "最近可用缓存"', source)
        self.assertIn('label: "任务边界"', source)
        self.assertIn('label: "缺数据口径"', source)
        self.assertIn('label: "仅供研究"', source)
        self.assertLess(source.index("今日作战台摘要"), source.index("开发 / 审计详情"))
        self.assertLess(source.index('title="今日作战台摘要"'), source.index('<PacketCard title="live_light 手动补证"'))
        self.assertLess(source.index('label: "本地联通"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "一键启动"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "启动诊断"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "恢复回读"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "回读边界"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "只读自检"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "P0 可继续"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index("本地联通四段回读"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("一键启动只读自检"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("P0 进入 P1 闸门"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("P0 当前下一步"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("今日搜票一屏行动"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("P0 进入 P1 闸门"), source.index("P0 当前下一步"))
        self.assertLess(source.index("P0 当前下一步"), source.index("今日搜票一屏行动"))
        self.assertLess(source.index("今日搜票一屏行动"), source.index("确认后回放清单"))
        self.assertLess(source.index("今日搜票一屏行动"), source.index("确认结果链速读"))
        self.assertLess(source.index("确认结果链速读"), source.index("确认后回放清单"))
        confirm_outcome_start = source.index('aria-label="daily command confirm outcome readback"')
        confirm_outcome_end = source.index('aria-label="daily command p2 p3 replay checklist"', confirm_outcome_start)
        confirm_outcome_slice = source[confirm_outcome_start:confirm_outcome_end]
        self.assertNotIn("onClick=", confirm_outcome_slice)
        self.assertNotIn("launch" + "Task", confirm_outcome_slice)
        self.assertNotIn("post" + "Task(", confirm_outcome_slice)
        self.assertLess(source.index("确认后回放清单"), source.index("P0 到 P1 快速行动"))
        self.assertLess(source.index("P0 到 P1 快速行动"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("P3 结果回放入口"), source.index("量化缓存降级回放"))
        self.assertLess(source.index("量化缓存降级回放"), source.index("P5 DeepSeek 单独治理"))
        self.assertLess(source.index("量化缓存降级回放"), source.index("开发 / 审计详情"))
        factor_fallback_start = source.index('aria-label="daily command factor cache fallback readback"')
        factor_fallback_end = source.index('aria-label="daily command p5 deepseek governance quick read"', factor_fallback_start)
        factor_fallback_slice = source[factor_fallback_start:factor_fallback_end]
        self.assertNotIn("onClick=", factor_fallback_slice)
        self.assertNotIn("launch" + "Task", factor_fallback_slice)
        self.assertNotIn("post" + "Task(", factor_fallback_slice)
        self.assertNotIn("postBootstrapLiveStartup", factor_fallback_slice)
        self.assertLess(source.index("P6 strict closeout 回归入口"), source.index("开发 / 审计详情"))
        self.assertLess(source.index('aria-label="daily command p6 reentry links"'), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "本地缓存"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "最近成功回放"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "今日查看顺序"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "今日结果组成"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "缺数据口径"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        summary_slice = source[source.index('title="今日作战台摘要"') : source.index("开发 / 审计详情")]
        for hidden_label in (
            'label: "cache"',
            'label: "Tushare"',
            'label: "DeepSeek"',
            'label: "pending"',
            'label: "degraded"',
            'label: "last_successful_cache/result"',
            'label: "P5 DeepSeek"',
        ):
            self.assertNotIn(hidden_label, summary_slice)
        self.assertNotIn('{ label: "今日作战台"', source)

    def test_ordinary_home_app_visible_now_summary_is_first_screen_read_only(self):
        source = self.source
        card_start = source.index('title="今日可用"')
        visible_start = source.index('aria-label="ordinary home app visible now summary"', card_start)
        controls_start = source.index('aria-label="daily command ordinary home primary controls"', card_start)
        recent_start = source.index('aria-label="ordinary home first screen recent result read"', card_start)
        audit_start = source.index('aria-label="daily command research assist audit details"')
        visible_slice = source[visible_start:controls_start]
        source_before_audit = source[:audit_start]

        self.assertLess(card_start, visible_start)
        self.assertLess(visible_start, controls_start)
        self.assertLess(controls_start, recent_start)
        self.assertLess(visible_start, audit_start)
        self.assertIn("ordinaryHomeAppVisibleNowSentence", source_before_audit)
        self.assertIn("ordinaryHomeAppVisibleNowItems", source_before_audit)
        self.assertIn("打开 app 能看到 ${dailyCommandConfirmedSymbolLabel} 的最近投研结果", source_before_audit)
        self.assertIn("打开 app 能看到本地已接上、股票确认入口和等待结果状态", source_before_audit)
        self.assertIn("打开 app 能看到本地连接待恢复", source_before_audit)
        for label in (
            'label: "打开可见"',
            'label: "本地联通"',
            'label: "当前标的"',
            'label: "最近结果"',
            'label: "来源层"',
            'label: "明确缺口"',
            'label: "下一步入口"',
            'label: "安全说明"',
        ):
            self.assertIn(label, source_before_audit)
        self.assertIn("打开 app 能看到什么", visible_slice)
        self.assertIn('aria-label="ordinary home app visible now sentence"', visible_slice)
        self.assertIn("{ordinaryHomeAppVisibleNowSentence}", visible_slice)
        self.assertIn("MetricGrid items={ordinaryHomeAppVisibleNowItems}", visible_slice)
        self.assertIn('aria-label="ordinary home app visible now local actions"', visible_slice)
        self.assertIn('href={dailyCommandHomeConfirmHref}', visible_slice)
        self.assertIn('href="#factor/factor-score"', visible_slice)
        self.assertIn('href="#next/next-session-chart"', visible_slice)
        self.assertIn("这个条带只回答普通用户打开首页能看到什么", visible_slice)
        self.assertIn("普通链接只切换本地页面或锚点", visible_slice)
        self.assertIn("不启动确认流程、不调用外部服务、不交易、不改策略", visible_slice)
        self.assertNotIn("onClick=", visible_slice)
        self.assertNotIn("fetch(", visible_slice)
        self.assertNotIn("postCandidateRadarQuantProjection", visible_slice)
        self.assertNotIn("TaskStatusPanel", visible_slice)

    def test_local_fastapi_connection_card_is_first_screen_and_read_only(self):
        source = self.source
        card_start = source.index('title="本地 FastAPI 接线速读"')
        card_end = source.index('title="P0 现在能不能用"', card_start)
        card = source[card_start:card_end]

        self.assertIn("打开软件后先看这张卡", card)
        self.assertIn('label: "本地后端"', card)
        self.assertIn("dailyCommandFrontendBackendAutoLinkLabel", card)
        self.assertIn("dailyCommandOpenFastApiProofItems", card)
        self.assertIn("dailyCommandFastApiProgressWatchLabel", source)
        self.assertIn("dailyCommandFastApiProgressWatchNext", source)
        self.assertIn('aria-label="daily command local fastapi open proof"', card)
        open_proof_start = card.index('aria-label="daily command local fastapi open proof"')
        technical_detail_start = card.index(
            '<details className="developer-audit-details" aria-label="daily command local fastapi technical connection details">'
        )
        ordinary_connection_slice = card[:technical_detail_start]
        open_proof_slice = card[open_proof_start:technical_detail_start]
        technical_detail_slice = card[technical_detail_start:]
        self.assertNotIn('label: "接线地址"', ordinary_connection_slice)
        self.assertNotIn('label: "候选地址"', ordinary_connection_slice)
        self.assertIn('label: "接线地址"', card)
        self.assertIn("dailyCommandFrontendBackendSelectedApiBase", card)
        self.assertIn('label: "候选地址"', card)
        self.assertIn('API_BASE_CANDIDATE_DISPLAY_URLS.join(" / ")', card)
        self.assertIn("<summary>本地接线技术明细</summary>", technical_detail_slice)
        self.assertIn('label: "接线地址"', technical_detail_slice)
        self.assertIn('label: "候选地址"', technical_detail_slice)
        self.assertIn("dailyCommandFrontendBackendSelectedApiBase", technical_detail_slice)
        self.assertIn('API_BASE_CANDIDATE_DISPLAY_URLS.join(" / ")', technical_detail_slice)
        self.assertIn('label: "当前页面"', card)
        self.assertIn("FastAPI、bootstrap、desktop preflight 和 React 已接上", card)
        self.assertIn('label: "边用边看"', ordinary_connection_slice)
        self.assertIn("dailyCommandFastApiProgressWatchLabel", ordinary_connection_slice)
        self.assertIn("边用边看：{dailyCommandFastApiProgressWatchNext}", ordinary_connection_slice)
        self.assertIn("这只来自首页已回读的 `/api/tasks` 和 CandidateRadar cache，不创建第二个 task", ordinary_connection_slice)
        self.assertIn('label: "投研入口"', card)
        self.assertIn("在首页确认股票代码；需要详情再进下一票雷达", card)
        self.assertNotIn("去下一票雷达确认输入区输入代码并确认", card)
        self.assertIn('label: "安全边界"', card)
        self.assertIn("打开页面和输入代码不外联；确认按钮才触发 Tushare-first", card)
        self.assertIn("打开后接线证明", open_proof_slice)
        self.assertIn("MetricGrid items={dailyCommandOpenFastApiProofItems}", open_proof_slice)
        self.assertIn('label: "FastAPI health"', source)
        self.assertIn("已接上：health ok，启动不外联", source)
        self.assertIn('label: "运行模式"', source)
        self.assertIn("等待 bootstrap runtime-mode packet", source)
        self.assertIn('label: "一键预检"', source)
        self.assertIn("已回读：desktop preflight 一键启动 packet", source)
        self.assertIn('label: "当前页面"', source)
        self.assertIn("React 页面已加载；只读 GET 回读中", source)
        self.assertIn('label: "继续入口"', source)
        self.assertIn("可以确认股票代码", source)
        self.assertIn("这条证明只合成当前页面已拿到的 health、bootstrap、desktop preflight 和 React 状态", open_proof_slice)
        self.assertIn("不启动 FastAPI/Vite、不创建 task、不调用 Tushare/DeepSeek/GitHub", open_proof_slice)
        self.assertIn("不读取或展示 token/key", open_proof_slice)
        self.assertIn('aria-label="daily command fastapi connected user actions"', card)
        self.assertIn('href={dailyCommandPrimaryActionHref}', card)
        self.assertIn('href="#tasks"', card)
        self.assertIn('href="#desktop"', card)
        self.assertIn("本卡只判断本机前后端能不能继续投研", ordinary_connection_slice)
        self.assertIn("需要排查地址或 fallback 时展开技术明细", ordinary_connection_slice)
        self.assertIn("接线地址来自前端本机 FastAPI 自动接线记录", card)
        self.assertIn("候选地址只展示本机 127.0.0.1/localhost fallback", card)
        self.assertIn("只读 FastAPI health、bootstrap status 和 desktop preflight cache", card)
        self.assertIn("不会启动服务、不会创建任务、不会调用 Tushare/DeepSeek/GitHub", card)
        self.assertIn("不会暴露敏感凭据", card)
        self.assertNotIn("onClick=", card)
        self.assertNotIn("fetch(", card)
        self.assertNotIn("postTask", card)
        self.assertNotIn("postBootstrapLiveStartup", card)

    def test_usable_path_progress_card_is_front_loaded_and_read_only(self):
        source = self.source
        card_start = source.index('title="使用者可用化进度"')
        card_end = source.index('title="P0 现在能不能用"', card_start)
        card = source[card_start:card_end]
        rail_start = card.index('aria-label="daily command usable path front stage rail"')
        table_start = card.index("<DataLineageTable rows={dailyCommandUsableShortestPathPrimaryRows}")
        rail = card[rail_start:table_start]

        self.assertIn("打开即看 P0 到 P3 当前阶段；P4-P6 下沉到摘要和审计", card)
        self.assertIn('status={homeQuantP1P2P3CheckpointReady ? "p1_p2_p3_ready" : dailyCommandP0LocalReadinessReady ? "ready_for_confirm" : "p0_check"}', card)
        self.assertIn("dailyCommandUsablePathPrimaryStageRailSteps.map", rail)
        self.assertIn("state: dailyCommandUsablePathP1State", source)
        self.assertIn("detail: dailyCommandUsablePathP1Detail", source)
        self.assertIn("state: dailyCommandUsablePathP2State", source)
        self.assertIn("detail: dailyCommandUsablePathP2Detail", source)
        self.assertIn("state: dailyCommandUsablePathP3State", source)
        self.assertIn("detail: dailyCommandUsablePathP3Detail", source)
        self.assertIn('aria-label="daily command usable path front readable status"', card)
        self.assertIn("{homeQuantP1P2P3CheckpointLabel}", card)
        self.assertIn("DataLineageTable rows={dailyCommandUsableShortestPathPrimaryRows}", card)
        self.assertIn('aria-label="daily command usable path front actions"', card)
        self.assertIn('href={dailyCommandPrimaryActionHref}', card)
        self.assertIn('href="#factor/factor-score"', card)
        self.assertIn('href="#next/next-session-chart"', card)
        app_source = (ROOT / "src" / "App.tsx").read_text(encoding="utf-8")
        self.assertIn("routeAnchorFromHash", app_source)
        self.assertIn("const target = document.getElementById(anchor)", app_source)
        self.assertIn('target.scrollIntoView({ block: "start" })', app_source)
        self.assertIn("const observer = new MutationObserver", app_source)
        self.assertIn("queueMicrotask(scrollToAnchor)", app_source)
        self.assertIn("[route, localFastapiRefreshNonce]", app_source)
        self.assertIn("只读首页已回放的 health、CandidateRadar cache、任务索引和本地结果", card)
        self.assertIn("不会创建任务、不会调用 Tushare/DeepSeek/GitHub", card)
        self.assertIn("不会读取敏感凭据、不会交易或修改 strategy action", card)
        self.assertNotIn("dailyCommandUsablePathAuditStageRailSteps.map", card)
        self.assertNotIn("dailyCommandUsableShortestPathAuditRows", card)
        self.assertNotIn("onClick=", card)
        self.assertNotIn("fetch(", card)
        self.assertNotIn("postTask", card)
        self.assertNotIn("postBootstrapLiveStartup", card)
        self.assertNotIn("launchLiveBootstrap", card)

    def test_p3_one_glance_card_is_early_read_only_result_summary(self):
        source = self.source
        card_start = source.index('title="P3 可解释结果一眼读懂"')
        card_end = source.index('title="今日作战台摘要"', card_start)
        card = source[card_start:card_end]

        self.assertIn("结论、来源、缺口、下一步和安全边界", card)
        self.assertIn('status={dailyCommandP3OneGlanceStatus}', card)
        self.assertIn('label: "可读结论"', card)
        self.assertIn("dailyCommandExplainableResultLabel", card)
        self.assertIn("dailyCommandP3OneGlanceReadable", card)
        self.assertIn('label: "数据来源"', card)
        self.assertIn("dailyCommandP3OneGlanceSource", card)
        self.assertIn("dailyCommandP3OneGlanceProviderVerified", card)
        self.assertIn('label: "结果证据"', card)
        self.assertIn("dailyCommandP3OneGlanceEvidence", card)
        self.assertIn('label: "来源任务"', card)
        self.assertIn("dailyCommandP3OneGlanceSourceTask", card)
        self.assertIn('label: "结果入口"', card)
        self.assertIn("dailyCommandP3OneGlanceResultEntrances", card)
        self.assertIn('label: "Factor handoff"', card)
        self.assertIn("dailyCommandFactorCandidateHandoffLabel", card)
        self.assertIn('label: "Factor 行数"', card)
        self.assertIn("factorCandidateHandoffRows.length", card)
        self.assertIn('label: "待补缺口"', card)
        self.assertIn("dailyCommandP3OneGlanceMissingEvidence", card)
        self.assertIn('label: "下一步"', card)
        self.assertIn("dailyCommandExplainableResultNext", card)
        self.assertIn('label: "模型状态"', card)
        self.assertIn("dailyCommandP3OneGlanceModelState", card)
        self.assertIn('tone: dailyCommandP3OneGlanceUsesModelOutput ? "warn" : "good"', card)
        self.assertNotIn("dailyCommandP3OneGlanceModelState.includes", card)
        self.assertIn('label: "安全字段"', card)
        self.assertIn("dailyCommandP3OneGlanceSafeFields", card)
        self.assertIn('label: "边界"', card)
        self.assertIn("dailyCommandExplainableResultBoundary", card)
        self.assertIn("dailyCommandP3ExplainableCheckpoint", source)
        self.assertIn("dailyCommandP3ExplainableMissingEvidenceCount", source)
        self.assertIn("dailyCommandP3ExplainableProofItems", source)
        self.assertIn("candidates.search_quant_projection_p3_explainable_result_checkpoint", source)
        self.assertIn('aria-label="daily command p3 explainable result proof"', card)
        self.assertIn("P3 结果证明", card)
        self.assertIn("MetricGrid items={dailyCommandP3ExplainableProofItems}", card)
        self.assertIn('label: "结果状态"', source)
        self.assertIn("可读：${dailyCommandExplainableResultLabel}", source)
        self.assertIn('label: "来源证明"', source)
        self.assertIn("Tushare-first ledger 已参与；${dailyCommandP3OneGlanceSource}", source)
        self.assertIn('label: "缺口数量"', source)
        self.assertIn("dailyCommandP3ExplainableMissingEvidenceCount", source)
        self.assertIn("这条证明只合成 CandidateRadar 本地 cache 的 P3 checkpoint、可读结论、Tushare-first 来源、缺口和模型状态", card)
        self.assertIn("不创建 task、不调用 DeepSeek、不展示 raw packet/token/key", card)
        self.assertIn('aria-label="daily command p3 one glance quick rows"', card)
        self.assertIn('aria-label="daily command p3 one glance decision brief"', card)
        self.assertIn("P3 一分钟决策速读", card)
        self.assertIn("ordinary_result_decision_brief_rows", card)
        self.assertIn("先看结论、再看来源、最后看下一步和边界", card)
        self.assertIn("dailyCommandP3OneGlanceDecisionRows", card)
        self.assertIn("首页只读本地证据，不创建 task", card)
        proof_start = card.index('aria-label="daily command p3 explainable result proof"')
        decision_start = card.index('aria-label="daily command p3 one glance decision brief"')
        proof_slice = card[proof_start:decision_start]
        self.assertLess(proof_start, decision_start)
        self.assertNotIn("onClick=", proof_slice)
        self.assertNotIn("fetch(", proof_slice)
        self.assertNotIn("postCandidateRadar", proof_slice)
        self.assertLess(
            card.index('aria-label="daily command p3 one glance decision brief"'),
            card.index('aria-label="daily command p3 one glance quick rows"'),
        )
        self.assertNotIn('aria-label="daily command p5 nonblocking one minute read"', card)
        self.assertNotIn("P5 DeepSeek 不阻塞速读", card)
        self.assertIn("结果速读全部项", card)
        self.assertIn("ordinary_result_quick_read_rows 全部项", card)
        self.assertIn("缺口和边界", card)
        self.assertIn("dailyCommandP3OneGlanceQuickRows", card)
        self.assertIn("const dailyCommandP3OneGlanceQuickRows = dailyCommandExplainableResultRows;", source)
        self.assertNotIn("dailyCommandExplainableResultRows.slice(0, 3)", source)
        self.assertIn("不展开 raw packet、不创建 task、不调用 provider/model", card)
        self.assertIn("factorCandidateHandoff", source)
        self.assertIn("factor.candidate_radar_quant_projection_handoff", source)
        self.assertIn("factor.ordinary_quant_candidate_handoff_rows", source)
        self.assertIn("dailyCommandFactorCandidateHandoffReadbackRows", source)
        self.assertIn('aria-label="daily command factor candidate handoff readback"', card)
        self.assertIn("股票量化推演 handoff", card)
        self.assertIn("/api/factor-quant/cache 的 ordinary_quant_candidate_handoff_rows", card)
        self.assertIn("只读确认 CandidateRadar 确认任务是否已经接到股票量化推演", card)
        self.assertIn("不创建 task、不补调 provider/model", card)
        self.assertIn("DataLineageTable rows={dailyCommandFactorCandidateHandoffReadbackRows}", card)
        self.assertLess(
            card.index('aria-label="daily command p3 one glance quick rows"'),
            card.index('aria-label="daily command factor candidate handoff readback"'),
        )
        self.assertLess(
            card.index('aria-label="daily command factor candidate handoff readback"'),
            card.index('aria-label="daily command p3 one glance actions"'),
        )
        self.assertIn('aria-label="daily command p3 one glance actions"', card)
        self.assertIn("href={dailyCommandCandidateConfirmHref}", card)
        self.assertIn("open candidate radar confirm input p3 one glance", card)
        self.assertIn('href="#factor"', card)
        self.assertIn('href="#next"', card)
        self.assertIn("只读 `search_quant_projection_result_checkpoint`", card)
        self.assertIn("不会创建 task、不会调用 DeepSeek、不会交易或修改 strategy action", card)
        self.assertNotIn("onClick=", card)
        self.assertNotIn("fetch(", card)
        self.assertNotIn("postBootstrapLiveStartup", card)
        self.assertNotIn("postCandidateRadar", card)

    def test_current_research_workflow_has_readable_sentence_before_tables(self):
        source = self.source
        card_start = source.index('title="当前可用投研链路"')
        card_end = source.index('title="P2 小数据三面速读"', card_start)
        card = source[card_start:card_end]

        self.assertIn("dailyCommandResearchWorkflowReadableSentence", source)
        self.assertIn("已完成 P1/P2/P3 本地回放", source)
        self.assertIn("P3 结论：${dailyCommandExplainableResultLabel}", source)
        self.assertIn("本地联通已 ready", source)
        self.assertIn('aria-label="daily command current research workflow readable result"', card)
        self.assertIn("{dailyCommandResearchWorkflowReadableSentence}", card)
        self.assertIn("DataLineageTable rows={dailyCommandResearchWorkflowRows}", card)
        self.assertLess(
            card.index('aria-label="daily command current research workflow readable result"'),
            card.index("<MetricGrid"),
        )
        self.assertLess(
            card.index('aria-label="daily command current research workflow readable result"'),
            card.index("DataLineageTable rows={dailyCommandResearchWorkflowRows}"),
        )
        self.assertNotIn("onClick=", card)
        self.assertNotIn("fetch(", card)
        self.assertNotIn("postCandidateRadar", card)

    def test_p2_three_surface_proof_is_before_writeback_table_and_read_only(self):
        source = self.source
        card_start = source.index('title="P2 小数据三面速读"')
        card_end = source.index('title="P3 可解释结果一眼读懂"', card_start)
        card = source[card_start:card_end]

        self.assertIn("dailyCommandP2CacheReady", source)
        self.assertIn("dailyCommandP2LedgerReady", source)
        self.assertIn("dailyCommandP2PacketReady", source)
        self.assertIn("dailyCommandP2ThreeSurfaceProofItems", source)
        self.assertIn("candidates.search_quant_projection_p2_cache_ready", source)
        self.assertIn("candidates.search_quant_projection_p2_ledger_ready", source)
        self.assertIn("candidates.search_quant_projection_p2_packet_ready", source)
        self.assertIn('普通读法: String(row["普通读法"] ?? row["普通速读"] ?? row.ordinary_label', source)
        self.assertIn("页面刷新后只读回放本地缓存。", source)
        self.assertIn("只确认 Tushare ledger 是否由确认任务写入。", source)
        self.assertIn("回放 task id、安全步骤、结果入口和下一步。", source)
        self.assertIn('aria-label="daily command p2 three surface proof"', card)
        self.assertIn("P2 三面写回证明", card)
        self.assertIn("MetricGrid items={dailyCommandP2ThreeSurfaceProofItems}", card)
        self.assertIn('label: "cache"', source)
        self.assertIn("已写入本地 cache；页面刷新只读回放", source)
        self.assertIn('label: "call_ledger"', source)
        self.assertIn("已回放 POST task ledger：${dailyCommandP2CallLedgerState}", source)
        self.assertIn('label: "packet"', source)
        self.assertIn("已写入 command_center_3_candidate_radar_cache；不含凭据或交易动作", source)
        self.assertIn('label: "完整度"', source)
        self.assertIn("value: dailyCommandP2SurfaceCompletionLabel", source)
        self.assertIn("这条证明只合成 CandidateRadar 本地 cache 的 cache_ready、ledger_ready、packet_ready 和三面完整度", card)
        self.assertIn("不创建 task、不调用 Tushare/DeepSeek、不展示 token/key/raw log", card)
        proof_start = card.index('aria-label="daily command p2 three surface proof"')
        table_start = card.index('aria-label="daily command ordinary p2 writeback front row"')
        proof_slice = card[proof_start:table_start]
        self.assertLess(proof_start, table_start)
        self.assertNotIn("onClick=", proof_slice)
        self.assertNotIn("fetch(", proof_slice)
        self.assertNotIn("postCandidateRadar", proof_slice)

    def test_p0_now_usable_card_is_short_read_only_status(self):
        source = self.source
        card_start = source.index('title="P0 现在能不能用"')
        card_end = source.index('title="首页确认股票代码"', card_start)
        card = source[card_start:card_end]

        self.assertIn("普通用户打开软件后的 10 秒判断", card)
        self.assertIn('status={dailyCommandP0LocalReadinessReady ? "ready" : "check"}', card)
        self.assertIn('label: "结论"', card)
        self.assertIn("可以用：本地四段已接上", card)
        self.assertIn("先恢复：本地四段还没全部 ready", card)
        self.assertIn('label: "现在点哪里"', card)
        self.assertIn("dailyCommandPrimaryActionLabel", card)
        self.assertIn('label: "失败看哪里"', card)
        self.assertIn("桌面壳预检里的 FastAPI / bootstrap / preflight / React 分段诊断", card)
        self.assertIn('label: "进入 P1 条件"', card)
        self.assertIn("health、bootstrap、desktop preflight、React 四段 ready 后再确认股票代码", card)
        self.assertIn('aria-label="daily command p0 now usable actions"', card)
        self.assertIn('href={dailyCommandPrimaryActionHref}', card)
        self.assertIn('href="#desktop"', card)
        self.assertIn("href={dailyCommandCandidateConfirmHref}", card)
        self.assertIn("open candidate radar confirm input from p0 usable card", card)
        self.assertIn("输入仍保持静默，确认按钮才创建 Tushare-first task", card)
        self.assertIn("这张卡只读本地状态；不启动服务、不创建 task、不调用 provider/model", card)
        self.assertIn("不代表 Tushare 已调用、DeepSeek 可用、release ready 或 14 LTG 完成", card)
        self.assertNotIn("onClick=", card)
        self.assertNotIn("fetch(", card)
        self.assertNotIn("postTask", card)
        self.assertNotIn("postBootstrapLiveStartup", card)
        self.assertNotIn("launchLiveBootstrap", card)

    def test_ordinary_home_first_card_shows_result_routes_without_task_trigger(self):
        source = self.source
        card_start = source.index('title="今日可用"')
        card_end = source.index('aria-label="daily command research assist audit details"', card_start)
        card = source[card_start:card_end]
        recent_result_start = card.index('aria-label="ordinary home first screen recent result read"')
        recent_result_end = card.index('aria-label="ordinary home first screen research route map"', recent_result_start)
        recent_result = card[recent_result_start:recent_result_end]
        route_map_start = card.index('aria-label="ordinary home first screen research route map"')
        candidate_radar_start = card.index('aria-label="ordinary home candidate radar visible slice"', route_map_start)
        route_map_end = candidate_radar_start
        route_map = card[route_map_start:route_map_end]
        candidate_radar_end = card.index('aria-label="ordinary home first screen post confirm status"', candidate_radar_start)
        candidate_radar = card[candidate_radar_start:candidate_radar_end]
        route_start = card.index('aria-label="ordinary home first screen result route"')
        route = card[route_start:]

        self.assertLess(card.index('aria-label="ordinary home confirm status"'), recent_result_start)
        self.assertLess(recent_result_start, route_map_start)
        self.assertLess(card.index('aria-label="ordinary home confirm status"'), route_map_start)
        self.assertLess(route_map_start, candidate_radar_start)
        self.assertLess(candidate_radar_start, card.index('aria-label="ordinary home first screen post confirm status"'))
        self.assertLess(route_map_start, route_start)
        self.assertIn("ordinaryHomeRecentResultItems", source)
        self.assertIn("ordinaryHomeRecentResultSummary", source)
        self.assertIn("ordinaryHomeRecentResultState", source)
        self.assertIn("ordinaryHomePlainConclusionText", source)
        self.assertIn("ordinaryHomePlainConclusionStatus", source)
        self.assertIn("ordinaryHomePlainConclusionMissing", source)
        self.assertIn("ordinaryHomePlainConclusionNext", source)
        self.assertIn("ordinaryHomePlainConclusionItems", source)
        self.assertIn("最近结果速读", recent_result)
        self.assertIn('aria-label="ordinary home recent result summary"', recent_result)
        self.assertIn('aria-label="ordinary home plain result conclusion"', recent_result)
        self.assertIn("普通结论", recent_result)
        self.assertIn('aria-label="ordinary home plain result conclusion text"', recent_result)
        self.assertIn("MetricGrid items={ordinaryHomePlainConclusionItems}", recent_result)
        self.assertIn('label: "一句话结论"', source)
        self.assertIn('label: "结果状态"', source)
        self.assertIn('label: "缺口"', source)
        self.assertIn('label: "现在做什么"', source)
        self.assertIn("最近确认被阻断或降级", source)
        self.assertIn("只读本地最近任务和结果；不创建 task、不调用 provider/model、不交易", source)
        self.assertIn("MetricGrid items={ordinaryHomeRecentResultItems}", recent_result)
        self.assertIn('label: "缺口/degraded"', source)
        self.assertIn("pending/degraded 仍要显示", source)
        self.assertIn("不把空结果当无风险", recent_result)
        self.assertIn("不会重复创建确认任务", recent_result)
        self.assertNotIn("onClick=", recent_result)
        self.assertNotIn("postTask", recent_result)
        self.assertIn("dailyCommandResearchRouteMapItems", source)
        self.assertIn("今日投研路径", route_map)
        self.assertIn("确认股票、看候选、查 ETF/融资风险、再看次日图谱", route_map)
        self.assertIn('aria-label="ordinary home research route map actions"', route_map)
        self.assertIn('aria-label="open candidate confirm from ordinary home route map"', route_map)
        self.assertIn('aria-label="open candidate pool from ordinary home route map"', route_map)
        self.assertIn('aria-label="open margin etf from ordinary home route map"', route_map)
        self.assertIn('aria-label="open next session from ordinary home route map"', route_map)
        self.assertIn('href="#marginEtf"', route_map)
        self.assertNotIn("onClick=", route_map)
        self.assertNotIn("postTask", route_map)
        self.assertIn("candidateCoarseFineScreening", source)
        self.assertIn("candidateTopWatchExcludedRows", source)
        self.assertIn("candidateHomeRows", source)
        self.assertIn("ordinaryHomeCandidateReadableSentence", source)
        self.assertIn("ordinaryHomeCandidateRadarItems", source)
        self.assertIn("ordinaryHomeCandidatePreviewRows", source)
        self.assertIn("下一票雷达速读", candidate_radar)
        self.assertIn('aria-label="ordinary home candidate radar readable sentence"', candidate_radar)
        self.assertIn("MetricGrid items={ordinaryHomeCandidateRadarItems}", candidate_radar)
        self.assertIn('label: "候选结论"', source)
        self.assertIn('label: "Top/Watch/Excluded"', source)
        self.assertIn('label: "来源"', source)
        self.assertIn('label: "ETF/融资提醒"', source)
        self.assertIn('label: "非买入边界"', source)
        self.assertIn("下一票候选池可读", source)
        self.assertIn("候选只表示复核顺序；不是买入、卖出、加仓或融资指令", source)
        self.assertIn('aria-label="ordinary home candidate radar visible actions"', candidate_radar)
        self.assertIn('href={ordinaryHomeCandidatePrimaryHref}', candidate_radar)
        self.assertIn("href={dailyCommandCandidateConfirmHref}", candidate_radar)
        self.assertIn('href="#marginEtf"', candidate_radar)
        self.assertIn('href="#next/next-session-chart"', candidate_radar)
        self.assertIn('aria-label="ordinary home candidate radar preview rows"', candidate_radar)
        self.assertIn("<summary>查看候选预览</summary>", candidate_radar)
        self.assertIn("DataLineageTable rows={ordinaryHomeCandidatePreviewRows}", candidate_radar)
        self.assertIn("页面打开和搜索输入不创建任务、不调用外部数据或模型服务", candidate_radar)
        self.assertNotIn("onClick=", candidate_radar)
        self.assertNotIn("fetch(", candidate_radar)
        self.assertNotIn("postTask", candidate_radar)
        self.assertNotIn("postCandidateRadar", candidate_radar)
        self.assertNotIn("launchHomeQuantProjection", candidate_radar)
        self.assertIn("ordinaryHomeResultRouteSummary", source)
        self.assertIn("ordinaryHomeResultRouteItems", source)
        self.assertIn("确认后结果会从这里去看：股票量化推演、次日图谱、下一票雷达详情。", source)
        self.assertIn("结果写入中：先看任务进度或只读刷新本地回放；缺口会继续显示，不把空结果当无风险。", source)
        self.assertIn("结果已可读：先看股票量化推演，再看次日图谱；需要换标的再回下一票雷达详情。", source)
        self.assertIn('aria-label="ordinary home first screen result route"', card)
        self.assertIn("确认后去哪看", route)
        self.assertIn('aria-label="ordinary home result route summary"', route)
        self.assertIn("MetricGrid items={ordinaryHomeResultRouteItems}", route)
        self.assertIn('label: "确认后去哪看"', source)
        self.assertIn('label: "结果入口"', source)
        self.assertIn('label: "降级读法"', source)
        self.assertIn("暂无结果不等于无风险；先确认股票", source)
        self.assertIn("本地写入中；缺数据会显示 pending / 缺少证据", source)
        self.assertIn("已有可读结论；继续看来源和缺口", source)
        self.assertIn('aria-label="ordinary home first screen result route actions"', route)
        self.assertIn('href="#factor/factor-score"', route)
        self.assertIn('href="#next/next-session-chart"', route)
        self.assertIn("href={dailyCommandCandidateConfirmHref}", route)
        self.assertIn("open factor from ordinary home result route", route)
        self.assertIn("open next session from ordinary home result route", route)
        self.assertIn("open candidate radar from ordinary home result route", route)
        self.assertIn("这些结果入口只切换本地模块；不会新建任务、不会调用外部数据或模型服务", route)
        self.assertIn("不会读取密钥、不会交易或改写策略", route)
        self.assertLess(card.index('aria-label="ordinary home confirm status"'), route_start)
        self.assertNotIn("onClick=", route)
        self.assertNotIn("fetch(", route)
        self.assertNotIn("postTask", route)
        self.assertNotIn("postCandidateRadar", route)
        self.assertNotIn("postBootstrapLiveStartup", route)
        self.assertNotIn("launchHomeQuantProjection", route)

    def test_ordinary_home_first_card_shows_post_confirm_status_without_second_task(self):
        source = self.source
        card_start = source.index('title="今日可用"')
        card_end = source.index('aria-label="daily command research assist audit details"', card_start)
        card = source[card_start:card_end]
        status_start = card.index('aria-label="ordinary home first screen post confirm status"')
        route_start = card.index('aria-label="ordinary home first screen result route"')
        status = card[status_start:route_start]

        self.assertIn("ordinaryHomePostConfirmItems", source)
        self.assertIn("ordinaryHomePostConfirmReplayItems", source)
        self.assertIn("ordinaryHomePostConfirmReplaySummary", source)
        self.assertIn("ordinaryHomePostConfirmReplayPrimaryHref", source)
        self.assertIn("ordinaryHomePostConfirmReplayPrimaryLabel", source)
        self.assertIn("ordinaryHomePostConfirmReplayActionNote", source)
        self.assertIn("homeQuantPostConfirmReadableSentence", source)
        self.assertIn("点击确认后显示本地回执编号", source)
        self.assertIn("确认后回读 CandidateRadar / Factor / Next / Tasks", source)
        self.assertIn("点击确认后，这里会压缩显示回执、进度、本地结果、结果入口和 degraded 状态。", source)
        self.assertIn("只读确认后的本地回放", source)
        self.assertIn("已有本地确认记录：先看任务进度，成功后刷新本地回放并进入结果入口。", source)
        self.assertIn("这张状态只读本地任务和缓存；不重复确认、不调用模型、不交易", source)
        self.assertIn('aria-label="ordinary home first screen post confirm status"', card)
        self.assertIn("确认后状态", status)
        self.assertIn('aria-label="ordinary home post confirm status summary"', status)
        self.assertIn("MetricGrid items={ordinaryHomePostConfirmItems}", status)
        self.assertIn('aria-label="ordinary home post confirm replay state strip"', status)
        self.assertIn("确认后回放速读", status)
        self.assertIn('aria-label="ordinary home post confirm replay summary"', status)
        self.assertIn("MetricGrid items={ordinaryHomePostConfirmReplayItems}", status)
        self.assertIn('aria-label="ordinary home post confirm replay action note"', status)
        self.assertIn('aria-label="ordinary home post confirm replay actions"', status)
        self.assertIn('aria-label="open primary post confirm replay action"', status)
        self.assertIn('aria-label="open progress from post confirm replay"', status)
        self.assertIn('aria-label="open factor from post confirm replay"', status)
        self.assertIn('aria-label="open next session from post confirm replay"', status)
        self.assertIn('href={ordinaryHomePostConfirmReplayPrimaryHref}', status)
        self.assertIn("ordinaryHomeProgressHref", source)
        self.assertIn('href={ordinaryHomeProgressHref}', status)
        self.assertIn('href="#factor/factor-score"', status)
        self.assertIn('href="#next/next-session-chart"', status)
        self.assertIn('label: "确认回执"', source)
        self.assertIn('label: "任务进度"', source)
        self.assertIn('label: "本地回放"', source)
        self.assertIn('label: "下一步"', source)
        self.assertIn('label: "回执"', source)
        self.assertIn('label: "进度"', source)
        self.assertIn('label: "本地结果"', source)
        self.assertIn('label: "结果入口"', source)
        self.assertIn('label: "degraded"', source)
        self.assertIn('label: "边界"', source)
        self.assertIn("缺结果时继续显示 pending/degraded", source)
        self.assertIn("不重复确认、不补调 provider/model、不交易", source)
        self.assertIn("它只读本地任务和缓存", status)
        self.assertIn("不会重复点击确认、不调用外部数据或模型", status)
        self.assertIn("不读取密钥、不交易或改写策略", status)
        self.assertLess(card.index('aria-label="ordinary home confirm status"'), status_start)
        self.assertLess(status_start, route_start)
        self.assertNotIn("onClick=", status)
        self.assertNotIn("fetch(", status)
        self.assertNotIn("postTask", status)
        self.assertNotIn("postCandidateRadar", status)
        self.assertNotIn("postBootstrapLiveStartup", status)
        self.assertNotIn("launchHomeQuantProjection", status)

    def test_home_p0_gate_uses_runtime_packets_before_receipt_detail(self):
        source = self.source
        gate_start = source.index("const dailyCommandP0RuntimePacketsReady =")
        gate_end = source.index("const dailyCommandP0LocalReadinessLabel", gate_start)
        gate = source[gate_start:gate_end]

        self.assertIn("dailyCommandHealthOk", gate)
        self.assertIn('bootstrapStatus.packet_key === "command_center_3_bootstrap_runtime_mode_packet"', gate)
        self.assertIn('desktopPreflight.packet_key === "command_center_3_desktop_shell_preflight_cache"', gate)
        self.assertIn("const dailyCommandP0QuickActionReady = p0CurrentNextActionRows.some", gate)
        self.assertIn("row.p1_entry_enabled === true || row.p0_ready_now === true", gate)
        self.assertIn("const dailyCommandP0ContractEvidenceReady =", gate)
        self.assertIn('oneClickStartupSummary.status === "one_click_frontend_backend_ready"', gate)
        self.assertIn('dailyCommandP0LocalConnectionReceipt.status === "p0_local_connection_receipt_ready"', gate)
        self.assertIn("dailyCommandP0QuickActionReady", gate)
        self.assertIn("dailyCommandP0RuntimePacketsReady &&", gate)
        self.assertIn("dailyCommandP0ContractEvidenceReady", gate)

        self.assertIn("p0_runtime_packets_ready: dailyCommandP0RuntimePacketsReady", source)
        self.assertIn("p0_quick_action_ready: dailyCommandP0QuickActionReady", source)
        self.assertIn("p0_contract_evidence_ready: dailyCommandP0ContractEvidenceReady", source)
        self.assertNotIn("dailyCommandP0RuntimePacketsReady &&\n    dailyCommandP0ConnectionEvidenceReady", gate)

    def test_home_p1_confirm_handoff_keeps_receipt_audit_folded(self):
        source = self.source
        card_start = source.index('title="首页确认股票代码"')
        card_end = source.index('title="P1 Tushare-first 链路速读"', card_start)
        card = source[card_start:card_end]

        self.assertIn("homeQuantPostConfirmHandoffRows", source)
        self.assertIn("homeQuantPostConfirmReadableSentence", source)
        self.assertIn("homeQuantRecoveredTaskId", source)
        self.assertIn("homeQuantVisibleTaskId", source)
        self.assertIn("homeQuantVisibleTaskSource", source)
        self.assertIn("homeQuantVisibleTaskCanPoll", source)
        self.assertIn("homeQuantP1P2P3CheckpointReady", source)
        self.assertIn("homeQuantP1P2P3CheckpointGaps", source)
        self.assertIn("homeQuantP1P2P3CheckpointLabel", source)
        self.assertIn("homeQuantP1P2P3CheckpointItems", source)
        self.assertIn("homeQuantUseConfirmedSymbolLabel", source)
        self.assertIn("homeQuantUseConfirmedSymbolTitle", source)
        self.assertIn("homeQuantSymbolTouched", source)
        self.assertIn("if (homeQuantSymbolTouched) return;", source)
        self.assertIn("if (homeQuantSymbol.trim()) return;", source)
        self.assertIn("if (!dailyCommandConfirmedSymbol) return;", source)
        self.assertIn("只把已回放标的填入输入框；不会创建 task，也不会调用 Tushare/DeepSeek", source)
        self.assertIn("暂无当前确认标的；请手动输入 6 位 A 股代码或带后缀代码", source)
        self.assertIn('aria-label="daily command home p1 symbol autofill boundary"', source)
        self.assertIn("当前标的自动填入只来自 CandidateRadar cache", source)
        self.assertIn("不会自动点击确认、不创建 task、不调用 Tushare/DeepSeek", source)
        self.assertIn("手动修改后不再覆盖输入", source)
        self.assertIn("dailyCommandTushareFirstLedgerReady", source)
        self.assertIn("dailyCommandP2ThreeSurfaceReady", source)
        self.assertIn("dailyCommandP3OneGlanceReadable", source)
        self.assertIn("dailyCommandFactorCandidateHandoffReady", source)
        self.assertIn("CandidateRadar cache 最近确认 task", source)
        self.assertIn("dailyCommandCandidateLatestTaskId", source)
        self.assertIn("homeQuantTaskPanelTaskId || homeQuantRecoveredTaskId", source)
        self.assertIn("homeQuantTaskPanelTaskId || (homeQuantRecoveredTaskId && !dailyCommandLatestTaskIsReplay)", source)
        self.assertIn("homeQuantConfirmButtonChainRows", source)
        self.assertIn('label: "链路 checkpoint"', source)
        self.assertIn('label: "一眼 checkpoint"', source)
        self.assertIn('label: "确认按钮"', source)
        self.assertIn("value: homeQuantCanSubmit ? `可点击：${homeQuantSymbolValidation.normalized} 将创建 Tushare-first POST task` : `不可点击：${homeQuantSubmitDisabledReason}`", source)
        self.assertIn('tone: homeQuantCanSubmit ? "good" : "warn"', source)
        self.assertIn("已完成 P1/P2/P3 本地回放", source)
        self.assertIn("Factor handoff ${dailyCommandFactorCandidateHandoffReady ? \"已接上\" : \"待回放\"}", source)
        self.assertIn("等待 ${homeQuantP1P2P3CheckpointGaps.join", source)
        self.assertIn("P2 三面已可读", source)
        self.assertIn("P3 结论：${dailyCommandExplainableResultLabel}", source)
        self.assertIn("下一步看股票量化推演和次日图谱", source)
        self.assertIn('aria-label="daily command home p1 confirm button chain proof"', card)
        self.assertIn("确认按钮链路证明", card)
        self.assertIn("点击前先看这五步：输入静默、P0 gate、确认按钮创建 task、任务进度、本地三面回放", card)
        self.assertIn("DataLineageTable rows={homeQuantConfirmButtonChainRows}", card)
        self.assertIn('链路段: "1. 输入静默"', source)
        self.assertIn("输入只做本地格式校验；不创建 task、不调用 Tushare/DeepSeek。", source)
        self.assertIn('链路段: "2. P0 gate"', source)
        self.assertIn("homeQuantP0ConfirmGateEvidence", source)
        self.assertIn('链路段: "3. 确认按钮"', source)
        self.assertIn("POST /api/candidate-radar/quant-projection；include_tushare=true；include_deepseek=false", source)
        self.assertIn("只有显式点击按钮才创建 task；页面打开、搜索输入、React render 和 GET cache 不外联。", source)
        self.assertIn('链路段: "4. 任务进度"', source)
        self.assertIn("TaskStatusPanel + /api/tasks 本地轮询", source)
        self.assertIn("任务来源已可见：${homeQuantVisibleTaskId}", source)
        self.assertIn("按 cache / ledger / packet 只读回放最近确认链", source)
        self.assertIn("cache 恢复不会创建第二个 task", source)
        self.assertIn('链路段: "5. 写回回放"', source)
        self.assertIn("P2/P3 已从 cache / call_ledger / packet 回放", source)
        self.assertIn('aria-label="daily command home post confirm handoff"', card)
        self.assertIn("确认后下一步", card)
        self.assertIn("任务编号出现或从本地 cache 恢复后，先看任务进度；成功后按股票量化推演和次日图谱回放", card)
        self.assertIn('aria-label="daily command home post confirm readable result"', card)
        self.assertIn("{homeQuantPostConfirmReadableSentence}", card)
        self.assertIn('aria-label="daily command home p1 p2 p3 checkpoint"', card)
        self.assertIn("P1/P2/P3 一眼 checkpoint", card)
        self.assertIn("MetricGrid items={homeQuantP1P2P3CheckpointItems}", card)
        self.assertIn("这条 checkpoint 只合成现有 task id、Tushare ledger、P2 三面、P3 可读结论和 Factor handoff", card)
        self.assertIn("不创建 task、不补调 provider/model、不展示 raw packet", card)
        self.assertIn("DataLineageTable rows={homeQuantPostConfirmHandoffRows}", card)
        self.assertIn('aria-label="daily command home post confirm handoff actions"', card)
        self.assertIn('href="#tasks"', card)
        self.assertIn('href="#factor"', card)
        self.assertIn('href="#next"', card)
        self.assertIn("href={dailyCommandCandidateConfirmHref}", card)
        self.assertIn("open candidate radar confirm input after home symbol confirm", card)
        self.assertIn("只读任务进度；cache 恢复不创建第二个 Tushare-first task", source)
        self.assertIn("链接只切换本地模块；Factor 页 GET cache 不补调 Tushare/DeepSeek", source)
        self.assertIn("operation_zones 只是复核区间；不是买卖、下单或 strategy action", source)
        self.assertIn("结果回放只读 CandidateRadar cache / ledger / packet；不调用模型", source)
        self.assertIn('aria-label="daily command home recovered task cache-only notice"', card)
        self.assertIn("最近确认 task 来自 CandidateRadar cache 只读回放", card)
        self.assertIn("首页不会启动 TaskStatusPanel，也不会创建第二个 task", card)

        handoff_start = card.index('aria-label="daily command home post confirm handoff"')
        chain_start = card.index('aria-label="daily command home p1 confirm button chain proof"')
        actions_start = card.index('aria-label="daily command home p1 symbol confirm actions"')
        autofill_start = source.index("if (homeQuantSymbolTouched) return;")
        autofill_end = source.index("const dailyCommandConfirmedSymbolLabel", autofill_start)
        fill_symbol_start = card.index("disabled={!dailyCommandConfirmedSymbol}", actions_start)
        confirm_button_start = card.index("onClick={launchHomeQuantProjection}", actions_start)
        task_panel_start = card.index("<TaskStatusPanel taskId={homeQuantVisibleTaskId} onSuccess={refreshHomeResearchReadback} />")
        cache_notice_start = card.index('aria-label="daily command home recovered task cache-only notice"')
        receipt_details_start = card.index('<details className="developer-audit-details" aria-label="daily command home p1 receipt audit details">')
        chain_end = card.index('aria-label="daily command home p1 symbol autofill boundary"', chain_start)
        chain_slice = card[chain_start:chain_end]
        autofill_slice = source[autofill_start:autofill_end]
        fill_symbol_slice = card[fill_symbol_start:confirm_button_start]
        handoff_slice = card[handoff_start:receipt_details_start]
        self.assertLess(actions_start, chain_start)
        self.assertLess(fill_symbol_start, confirm_button_start)
        self.assertIn("setHomeQuantSymbol(dailyCommandConfirmedSymbol)", autofill_slice)
        self.assertNotIn("postCandidateRadarQuantProjection(", autofill_slice)
        self.assertNotIn("launchHomeQuantProjection", autofill_slice)
        self.assertNotIn("onClick=", autofill_slice)
        self.assertIn("setHomeQuantSymbolTouched(true)", fill_symbol_slice)
        self.assertIn("setHomeQuantSymbol(dailyCommandConfirmedSymbol)", fill_symbol_slice)
        self.assertIn("setHomeQuantSubmitError(\"\")", fill_symbol_slice)
        self.assertNotIn("postCandidateRadarQuantProjection(", fill_symbol_slice)
        self.assertNotIn("launchHomeQuantProjection", fill_symbol_slice)
        self.assertNotIn("onClick=", chain_slice)
        self.assertNotIn("postCandidateRadarQuantProjection(", chain_slice)
        self.assertNotIn("launchHomeQuantProjection", chain_slice)
        self.assertNotIn("postCandidateRadarQuantProjection(", handoff_slice)
        self.assertNotIn("launchHomeQuantProjection", handoff_slice)
        self.assertNotIn("onClick=", handoff_slice)
        readable_result_start = card.index('aria-label="daily command home post confirm readable result"', handoff_start)
        checkpoint_start = card.index('aria-label="daily command home p1 p2 p3 checkpoint"', handoff_start)
        post_confirm_one_glance_start = card.index('aria-label="daily command home post confirm one glance"', handoff_start)
        self.assertLess(handoff_start, receipt_details_start)
        self.assertLess(readable_result_start, task_panel_start)
        self.assertLess(readable_result_start, checkpoint_start)
        self.assertLess(checkpoint_start, post_confirm_one_glance_start)
        self.assertLess(handoff_start, task_panel_start)
        self.assertLess(task_panel_start, receipt_details_start)
        self.assertLess(task_panel_start, cache_notice_start)
        self.assertLess(cache_notice_start, receipt_details_start)

        receipt_slice = card[receipt_details_start:]
        self.assertIn('<details className="developer-audit-details" aria-label="daily command home p1 receipt audit details">', receipt_slice)
        self.assertIn("<summary>任务回执 / 审计详情</summary>", receipt_slice)
        self.assertIn("完整 POST task receipt 默认下沉；普通路径先看上方任务进度、量化推演和次日图谱。", receipt_slice)
        self.assertIn("<TaskLaunchReceipt receipt={homeQuantReceipt} />", receipt_slice)

    def test_daily_command_center_source_and_boundary_are_visible(self):
        source = self.source

        self.assertIn("dailyCommandSourceState", source)
        self.assertIn("dailyCommandConnectionState", source)
        self.assertIn("dailyCommandLauncherState", source)
        self.assertIn("dailyCommandReviewOrder", source)
        self.assertIn("dailyCommandResultComposition", source)
        self.assertIn("dailyCommandMissingDataBoundary", source)
        self.assertIn("dailyCommandPrimaryActionLabel", source)
        self.assertIn("dailyCommandHomeConfirmHref", source)
        self.assertIn('const dailyCommandHomeConfirmHref = "#home-p1-symbol-confirm";', source)
        self.assertIn("dailyCommandCandidateConfirmHref", source)
        self.assertIn('const dailyCommandCandidateConfirmHref = "#candidates/candidate-radar-search-quant-projection";', source)
        self.assertIn("dailyCommandPrimaryActionHref", source)
        self.assertIn("dailyCommandPrimaryActionBoundary", source)
        self.assertIn("dailyCommandHealthOk", source)
        self.assertIn("dailyCommandHealthChecked", source)
        self.assertIn("dailyCommandCacheWarning", source)
        self.assertIn("!dailyCommandHealthOk && (loading || Boolean(error) || !dailyCommandHealthChecked)", source)
        self.assertIn("先确认 P0 本地联通，再在首页确认股票代码，之后回放股票量化推演和次日图谱结果", source)
        self.assertIn("先看一键启动预检恢复本地联通，再回今日作战台", source)
        self.assertIn("候选：${Number(candidateCounts?.candidate_count ?? 0) ? String(candidateCounts?.candidate_count) : \"等待缓存\"}", source)
        self.assertIn("量化：${String(factor.status ?? factor.mode ?? \"等待缓存\")}", source)
        self.assertIn("风险：${String(riskCounts?.active_risk_count ?? riskCounts?.risk_count ?? 0)} 项", source)
        self.assertIn("缺数据先看 pending / 缺少证据；不能把空缓存当成无风险", source)
        self.assertIn("不能把空缓存当成无风险，也不能当成生产验收完成", source)
        self.assertIn("今日先按“P0 本地联通 → 首页确认股票代码 → 下一票候选池 → ETF/融资风险 → 股票量化推演 / 次日图谱回放”复核", source)
        self.assertIn("不把空结果当成无风险", source)
        self.assertIn("首页确认股票代码", source)
        self.assertIn("主下一步可在首页输入代码并确认；输入保持静默，确认按钮才创建 Tushare-first POST task", source)
        self.assertNotIn("主下一步只查看本地数据健康；运行快扫仍需进入下一票雷达手动点击", source)
        self.assertIn("本地前后端未联通；请使用桌面快捷方式或本地启动器重新打开", source)
        self.assertIn("本地前后端已联通", source)
        self.assertIn("本地 cache 回读提示：${error}", source)
        self.assertIn("本地后端已联通；普通 cache 回读提示不阻断 P0", source)
        self.assertIn("继续在首页确认股票代码；普通 cache 提示留在待补证据里", source)
        self.assertIn("一键启动入口可用；启动器会等 FastAPI 和页面 ready", source)
        self.assertIn("dailyCommandStartupSuccessCondition", source)
        self.assertIn("dailyCommandStartupFailureAction", source)
        self.assertIn("dailyCommandStartupDiagnosticSurfaces", source)
        self.assertIn("dailyCommandStartupReadbackLabel", source)
        self.assertIn("dailyCommandStartupReadbackOrder", source)
        self.assertIn("dailyCommandStartupReadbackBoundary", source)
        self.assertIn("dailyCommandStartupReadbackRows", source)
        self.assertIn("dailyCommandP0CheckOnlyNext", source)
        self.assertIn("dailyCommandFrontendBackendSelectedApiBase", source)
        self.assertIn("dailyCommandP0LocalReadinessReady", source)
        self.assertIn("dailyCommandP0LocalReadinessLabel", source)
        self.assertIn("dailyCommandP0LocalReadinessBoundary", source)
        self.assertIn("dailyCommandP0EntryGateRows", source)
        self.assertIn('row.api === "frontend_fastapi_request"', source)
        self.assertIn("row.frontend_backend_auto_link_success === true", source)
        self.assertIn("typeof row.api_base === \"string\"", source)
        self.assertIn("?.api_base ?? API_BASE_DISPLAY_URL", source)
        self.assertIn("desktopPreflight.p0_launcher_check_only_rows", source)
        self.assertIn("desktopRuntime?.p0_launcher_check_only_next", source)
        self.assertIn("scripts/check_command_center_3.command", source)
        self.assertNotIn("COMMAND_CENTER_3_LAUNCHER_CHECK_ONLY=1 scripts/start_command_center_3.command", source)
        self.assertIn("desktopPreflight.p0_ordinary_quick_action_rows", source)
        self.assertIn("desktopRuntime?.p0_ordinary_quick_action_next", source)
        self.assertIn("p0CurrentNextActionSourceRows", source)
        self.assertIn("desktopPreflight.p0_current_next_action_rows", source)
        self.assertIn("DataLineageTable rows={p0CurrentNextActionRows}", source)
        self.assertIn("等待 desktop preflight 当前下一步回读", source)
        self.assertIn("代码通过本地校验后点击确认按钮，才创建 Tushare-first POST task；模型解释单独补证。", source)
        self.assertIn("页面打开、搜索输入和本表回读都不外联；只有确认按钮可进入 P1 task / worker。", source)
        self.assertIn("DataLineageTable rows={p0LauncherCheckOnlyRows}", source)
        self.assertIn("联通通过后先在首页输入代码并确认；需要详情再进下一票雷达，同样只有确认按钮触发 Tushare-first 任务", source)
        self.assertIn("DataLineageTable rows={p0OrdinaryQuickActionRows}", source)
        self.assertIn("FastAPI /health 必须返回 Command Center 3.0 健康 JSON", source)
        self.assertIn("/api/bootstrap/status 必须返回 runtime-mode packet", source)
        self.assertIn("/api/desktop/preflight-cache 必须返回一键启动 packet", source)
        self.assertIn("React/Vite 必须返回 Command Center 3.0 前端 HTML", source)
        self.assertIn("先看启动器的可操作诊断：FastAPI、bootstrap status、desktop preflight cache、React/Vite 哪段失败", source)
        self.assertIn("desktop preflight cache one-click packet", source)
        self.assertIn("8710/5173 是否被占用", source)
        self.assertIn("重启后刷新本页；FastAPI、bootstrap、desktop preflight cache、React/Vite 变绿才继续投研", source)
        self.assertIn("联通已由 GET /health 回读；可继续看缓存和投研入口", source)
        self.assertIn("恢复回读顺序：FastAPI /health -> bootstrap status -> desktop preflight cache -> React/Vite 前端 -> 今日作战台摘要", source)
        self.assertIn("恢复回读只读取 GET /health、GET /api/bootstrap/status、GET /api/desktop/preflight-cache；不启动服务、不创建 task、不外联", source)
        self.assertIn("只读健康检查，不启动服务、不创建 task", source)
        self.assertIn("只读运行模式，不写配置、不创建 live_light task", source)
        self.assertIn("首页只展示预检 packet，不启动 FastAPI/Vite/浏览器", source)
        self.assertIn("首页只展示预检结果，不启动 FastAPI/Vite/浏览器", source)
        self.assertIn("恢复回读只看本地 GET health/bootstrap/preflight 结果", source)
        self.assertIn("如果没有变绿，继续回一键启动预检，不进入投研入口", source)
        self.assertIn("selected=${dailyCommandFrontendBackendSelectedApiBase}", source)
        self.assertIn("P0 ready：${dailyCommandFrontendBackendSelectedApiBase} 已联通，当前 React 页面已加载；可在首页确认股票代码", source)
        self.assertIn("P0 check：先让 health、bootstrap status、desktop preflight cache 变绿；未 ready 不进入 P1", source)
        self.assertIn("P0 ready 只证明本地前后端联通；不代表 Tushare 已调用、DeepSeek 可用、release ready 或 14 LTG 完成。", source)
        self.assertIn("四段已通过；可在首页确认股票代码", source)
        self.assertIn("先让 health / bootstrap / preflight / React 四段变绿", source)
        self.assertIn("P0 未 ready：不要进入 P1", source)
        self.assertIn("先把前三段变绿，再回首页确认股票代码", source)
        self.assertIn('联通项: "P0 可继续闸门"', source)
        self.assertIn("health ok + bootstrap runtime-mode packet + desktop preflight one-click packet + current React page", source)
        self.assertIn("输入保持静默，确认按钮才触发 Tushare-first", source)
        self.assertIn("回到一键启动预检；不要进入 P1 投研入口", source)
        self.assertIn("FastAPI /health Command Center 3.0 JSON", source)
        self.assertIn("bootstrap status runtime-mode packet", source)
        self.assertIn("desktop preflight cache one-click packet", source)
        self.assertIn("React/Vite Command Center 3.0 HTML", source)
        self.assertIn("8710/5173 port occupancy guidance", source)
        self.assertIn("启动诊断来自 desktop preflight cache", source)
        self.assertIn("本地联通状态只读来自 FastAPI health 和 desktop preflight cache", source)
        self.assertIn("不会启动服务、不会写配置、不会调用 provider/model", source)
        self.assertIn("本地缓存：${dailyCommandCacheSourceLabel}", source)
        self.assertIn("Tushare 数据：${dailyCommandTushareSourceLabel}", source)
        self.assertIn("DeepSeek 解释：${dailyCommandDeepSeekSourceLabel}", source)
        self.assertIn("运行模式：${dailyCommandRuntimeModeLabel}", source)
        self.assertIn("live_light 已配置；仍需确认按钮触发 Tushare-first task", source)
        self.assertIn("待 governed executor；不随页面打开调用", source)
        self.assertIn("model_ledger 已记录；只读回放安全摘要", source)
        self.assertIn("dailyCommandExternalTriggerBoundary", source)
        self.assertIn("页面打开、搜索输入、React render 和 GET cache 不自动外联", source)
        self.assertIn("只有首页或下一票雷达确认按钮可创建 Tushare-first POST task", source)
        self.assertIn("量化缓存降级只返回安全摘要和本地 builder 结果；首页不展开 raw failed packet、provider error、token/key 或 call_ledger。", source)
        self.assertIn("GET cache 不创建 task、不调用 Tushare/DeepSeek/GitHub、不写 cache", source)
        summary_start = source.index('title="今日作战台摘要"')
        summary_end = source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary_slice = source[summary_start:summary_end]
        self.assertNotIn("轻量实时后台任务", summary_slice)
        self.assertNotIn("待授权解释", summary_slice)
        self.assertIn("dailyCommandPendingSourceLabel", source)
        self.assertIn("dailyCommandDegradedSourceLabel", source)
        self.assertIn("待补：", source)
        self.assertIn("降级：未标记降级", source)
        self.assertNotIn("pending：", summary_slice)
        self.assertNotIn("degraded：", summary_slice)
        self.assertIn("首页 GET cache 只读；live_light 手动补证只允许创建后台 POST task", source)
        self.assertIn("不在 React 渲染中直连 Tushare 或 DeepSeek", source)
        self.assertIn("今日摘要只组织投研证据；不买卖、不下单、不改交易策略", source)
        self.assertNotIn("/api/bootstrap/provider-model-execution-request", source)
        self.assertNotIn("postBootstrapProviderModelExecutionRequest", source)

    def test_daily_command_summary_links_are_local_navigation_only(self):
        summary_start = self.source.index('title="今日作战台摘要"')
        summary_end = self.source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary = self.source[summary_start:summary_end]

        self.assertIn('aria-label="daily command primary next action"', summary)
        self.assertIn('aria-label="open daily command primary next action"', summary)
        self.assertIn('aria-label="daily command next user actions"', summary)
        self.assertIn('aria-label="open candidate radar confirm input from daily command"', summary)
        self.assertIn('aria-label="open margin etf from daily command"', summary)
        self.assertIn("下一票雷达确认代码", summary)
        self.assertIn('aria-label="daily command ordinary readback details"', summary)
        self.assertIn("<summary>本地回放明细</summary>", summary)
        self.assertIn("确认链、P2 写回、P3 检查点和恢复表默认收起", summary)
        self.assertIn("dailyCommandCandidateConfirmHref", summary)
        self.assertIn('href="#factor"', summary)
        self.assertIn('href="#marginEtf"', summary)
        self.assertIn('href="#dataHealth"', summary)
        self.assertIn('href="#desktop"', summary)
        self.assertIn('href="#migration"', summary)
        self.assertIn('href="#tasks"', summary)
        self.assertIn('title="切换到下一票雷达确认输入区；输入代码后仍需确认按钮"', summary)
        self.assertIn('title="切换到股票量化推演模块；只回放缓存结果，不创建 task"', summary)
        self.assertIn('title="切换到 ETF / 融资模块；只读本地风险预算，不生成加融资指令"', summary)
        self.assertIn('title="切换到数据健康模块；只读 cache，不刷新外部数据源"', summary)
        self.assertIn('title="切换到桌面壳预检模块；只读恢复指引，不启动服务"', summary)
        self.assertIn('title="切换到迁移状态页；只读查看 14 LTG direct evidence 缺口"', summary)
        self.assertIn('title="切换到任务目录；只读回放 task/cache/ledger/packet 证据"', summary)
        self.assertIn("这些入口链接只切换本地页面（本地模块路由）", summary)
        self.assertIn("不会创建 task、调用 Tushare/DeepSeek/GitHub、写 cache/config 或改变交易策略", summary)
        self.assertLess(summary.index('aria-label="daily command primary next action"'), summary.index('aria-label="daily command next user actions"'))
        self.assertLess(summary.index('aria-label="daily command primary next action"'), summary.index('aria-label="daily command ordinary readback details"'))
        self.assertLess(summary.index('aria-label="daily command next user actions"'), summary.index('aria-label="daily command ordinary readback details"'))
        self.assertNotIn("onClick=", summary)
        self.assertNotIn("launchLiveBootstrap", summary)
        self.assertNotIn("postBootstrapLiveStartup", summary)

        app_source = (ROOT / "src" / "App.tsx").read_text(encoding="utf-8")
        for route_key in ('"candidates"', '"factor"', '"marginEtf"', '"dataHealth"', '"desktop"', '"migration"', '"tasks"'):
            self.assertIn(route_key, app_source)
        self.assertIn("normalizeRouteKey(window.location.hash)", app_source)
        self.assertIn(".split(/[/?]/)[0]", app_source)
        self.assertIn("normalizeRouteKey(window.location.hash) !== route", app_source)

    def test_engineering_metrics_are_demoted_behind_details(self):
        source = self.source

        self.assertIn('className="developer-audit-details"', source)
        self.assertIn("开发 / 审计详情", source)
        self.assertIn("详细验收记录、开发表格和排障明细默认收起", source)
        self.assertIn("dailyCommandAuditDemotionRows", source)
        self.assertIn('aria-label="daily command engineering audit demotion rules"', source)
        self.assertIn("审计入口下沉规则", source)
        self.assertIn("普通用户先看摘要和三入口；只有排障、验收或补证时展开开发详情。", source)
        self.assertIn("不展示 raw packet、call_ledger、runbook、LTG 表或 provider/model 明细", source)
        self.assertIn("默认折叠，不压过 P0 联通、P1 搜票确认、P2/P3 结果回放", source)
        self.assertIn("手动补证状态、任务状态面板和任务回执", source)
        self.assertIn("页面打开、React render 和 GET cache 不创建 task、不调用 Tushare/DeepSeek/GitHub", source)
        self.assertNotIn("工程合同、receipt、runbook、LTG audit 和 lineage 明细默认收起", source)
        self.assertIn("开发状态速览", source)
        self.assertLess(source.index("开发 / 审计详情"), source.index("开发状态速览"))
        self.assertLess(source.index("开发 / 审计详情"), source.index("审计入口下沉规则"))
        self.assertLess(source.index("审计入口下沉规则"), source.index("开发状态速览"))
        self.assertLess(source.index("今日作战台摘要"), source.index("审计入口下沉规则"))
        self.assertLess(source.index("开发状态速览"), source.index('label: "FastAPI"'))
        self.assertLess(source.index("开发状态速览"), source.index('label: "runtime mode"'))

    def test_usable_path_stage_rail_is_read_only_and_before_audit_details(self):
        source = self.source
        summary_start = source.index('title="今日作战台摘要"')
        summary_end = source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary = source[summary_start:summary_end]
        rail_start = summary.index('<div className="state-clarity-rail" aria-label="daily command usable path stage rail">')
        table_start = summary.index("<DataLineageTable rows={dailyCommandUsableShortestPathPrimaryRows}")
        rail = summary[rail_start:table_start]

        self.assertIn("dailyCommandUsablePathPrimaryStageRailSteps.map", rail)
        self.assertIn("dailyCommandUsablePathAuditStageRailSteps.map", summary)
        self.assertIn("dailyCommandUsableShortestPathAuditRows", summary)
        self.assertIn("dailyCommandP4OrdinaryFirstItems", source)
        self.assertIn('aria-label="daily command p4 ordinary first mode"', summary)
        self.assertIn("普通优先模式", summary)
        self.assertIn("P4 的当前口径是把工程审计噪音下沉", summary)
        self.assertIn("普通优先模式不展示 raw packet、raw log、token/key、provider error 或未脱敏模型输出", source)
        self.assertIn('className="state-clarity-rail"', rail)
        self.assertIn('className="state-clarity-step"', rail)
        self.assertIn("data-step-state={step.state}", rail)
        self.assertIn("{step.label}", rail)
        self.assertIn("{step.detail}", rail)
        self.assertLess(summary.index('aria-label="daily command usable path stage rail"'), table_start)
        p4_start = summary.index('aria-label="daily command p4 ordinary first mode"')
        audit_details_start = summary.index('aria-label="daily command usable path audit stages"')
        developer_details_start = source.index("<summary>开发 / 审计详情</summary>")
        self.assertLess(table_start, p4_start)
        self.assertLess(p4_start, audit_details_start)
        self.assertLess(p4_start, developer_details_start)
        p4_end = summary.index('aria-label="daily command usable path audit stages"', p4_start)
        p4_slice = summary[p4_start:p4_end]
        self.assertNotIn("onClick=", p4_slice)
        self.assertNotIn("fetch(", p4_slice)
        self.assertNotIn("postBootstrapLiveStartup", p4_slice)
        self.assertNotIn("postCandidateRadarQuantProjection", p4_slice)
        self.assertNotIn("onClick=", rail)
        self.assertNotIn("postBootstrapLiveStartup", rail)
        self.assertNotIn("postTask", rail)

    def test_p6_strict_closeout_reentry_is_collapsed_read_only_audit_detail(self):
        source = self.source
        summary_start = source.index('title="今日作战台摘要"')
        summary_end = source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary = source[summary_start:summary_end]
        p6_details_label_start = summary.index('aria-label="daily command engineering audit and strict closeout details"')
        p6_details_start = summary.rindex("<details", 0, p6_details_label_start)
        p6_start = summary.index('aria-label="daily command p6 strict closeout reentry"', p6_details_start)
        p6_end = summary.index('aria-label="daily command local connection readback"', p6_start)
        p6_details = summary[p6_details_start:p6_end]
        p6 = summary[p6_start:p6_end]

        self.assertIn("dailyCommandP6StrictCloseoutReentryRows", source)
        self.assertIn('<details className="developer-audit-details" aria-label="daily command engineering audit and strict closeout details">', p6_details)
        self.assertIn("<summary>工程审计 / P6 strict closeout 明细</summary>", p6_details)
        self.assertIn("普通路径已经在上方 P1 确认、P2 三面和 P3 可解释结果", p6_details)
        self.assertIn("P6 strict closeout 回归入口", p6)
        self.assertIn("P0-P5 是使用者可用化 checkpoint", p6)
        self.assertIn("current-head direct evidence", p6)
        self.assertIn("CI、浏览器、provider、worker、storage 和 package gate", p6)
        self.assertIn('href="#migration"', p6)
        self.assertIn('href="#tasks"', p6)
        self.assertLess(summary.index('aria-label="daily command usable path stage rail"'), p6_details_start)
        self.assertLess(summary.index("P6 strict closeout 回归入口"), summary.index('aria-label="daily command local connection readback"'))
        self.assertNotIn("onClick=", p6)
        self.assertNotIn("fetch(", p6)
        self.assertNotIn("postTask", p6)
        self.assertNotIn("postBootstrapLiveStartup", p6)
        self.assertNotIn("launchLiveBootstrap", p6)
        self.assertNotIn("provider-model", p6)

    def test_daily_command_summary_uses_user_facing_backfill_state_before_audit(self):
        source = self.source
        summary_start = source.index('title="今日作战台摘要"')
        summary_end = source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary = source[summary_start:summary_end]
        audit = source[summary_end:]

        self.assertIn("dailyCommandBackgroundTaskState", source)
        self.assertIn('label: "补证状态"', source)
        self.assertIn("dailyCommandSummaryTechnicalItems", summary)
        self.assertIn("<MetricGrid items={dailyCommandSummaryTechnicalItems} />", summary)
        self.assertNotIn('label: "后台状态"', source)
        self.assertIn("普通路径不自动补证；需要时在开发详情手动确认", source)
        self.assertIn("手动补证任务提交中；页面可继续查看缓存", source)
        self.assertIn("手动补证未完成；已回到只读查看", source)
        self.assertIn("已有本地补证任务；进度在开发详情", source)
        self.assertIn("live_light 补证入口下沉在开发详情；普通路径只看本地缓存、雷达和量化入口", summary)
        self.assertNotIn("等待手动确认按钮", source)
        self.assertNotIn("cache_only/manual 不创建后台任务", source)
        self.assertNotIn("来源关闭，未创建后台任务", source)
        self.assertNotIn("后台任务未接入", source)
        self.assertNotIn("本会话已创建过，不重复", source)
        self.assertNotIn("正在创建本地后台 task", source)
        self.assertNotIn("创建失败，已降级为只读", source)
        self.assertNotIn("liveBootstrapManualStatus", summary)
        self.assertNotIn("auto status", audit)
        self.assertIn("manual status: {liveBootstrapManualStatus}", audit)
        self.assertLess(summary.index("<MetricGrid items={dailyCommandSummaryTechnicalItems} />"), summary.index('aria-label="daily command usable shortest path"'))
        route_map_start = summary.index('aria-label="daily command research route map"')
        route_map_end = summary.index("<DataLineageTable rows={dailyCommandUsableShortestPathPrimaryRows} />", route_map_start)
        route_map = summary[route_map_start:route_map_end]
        self.assertLess(summary.index('aria-label="daily command usable path stage rail"'), route_map_start)
        self.assertIn("dailyCommandResearchRouteMapItems", source)
        self.assertIn("今日投研路径", route_map)
        self.assertIn("确认股票、看候选、查 ETF/融资风险、再看次日图谱", route_map)
        self.assertIn('aria-label="daily command research route map actions"', route_map)
        self.assertIn('aria-label="open candidate confirm from daily command route map"', route_map)
        self.assertIn('aria-label="open candidate pool from daily command route map"', route_map)
        self.assertIn('aria-label="open margin etf from daily command route map"', route_map)
        self.assertIn('aria-label="open next session from daily command route map"', route_map)
        self.assertIn('href="#marginEtf"', route_map)
        self.assertNotIn("onClick=", route_map)
        self.assertNotIn("postTask", route_map)

    def test_live_light_bootstrap_requires_manual_button_not_page_open_autostart(self):
        source = self.source

        self.assertIn("const launchLiveBootstrap = () => {", source)
        self.assertIn('source: "command_center_home_manual"', source)
        self.assertIn("确认 live_light 本地补证 task", source)
        self.assertIn("手动确认后才会创建本地 POST task；页面打开不自动启动", source)
        self.assertIn("页面打开、搜索输入和 render 不直接创建 task", source)
        self.assertIn("Tushare / DeepSeek configured source switches", source)
        self.assertNotIn("Tushare / DeepSeek on open:", source)
        self.assertIn("liveBootstrapManualStatus", source)
        self.assertNotIn("liveBootstrapAutoStatus", source)
        self.assertNotIn('source: "command_center_home_auto"', source)
        self.assertNotIn("cache 渲染完成后才会在 live_light 模式创建一次本地 POST task", source)

    def test_daily_command_page_does_not_embed_provider_model_or_trade_calls(self):
        source = self.source
        forbidden_fragments = (
            "tushare.pro_api",
            "ts.pro_api",
            "deepseek.chat",
            "api.github.com",
            "executeTrade(",
            "placeOrder(",
            "broker.submit",
            "live_order",
        )
        for fragment in forbidden_fragments:
            self.assertNotIn(fragment, source)


if __name__ == "__main__":
    unittest.main()
