import unittest
from pathlib import Path


class CandidateRadarP1ProviderButtonTests(unittest.TestCase):
    def test_provider_acceptance_button_is_explicit_tushare_first_after_execution_request(self):
        root = Path(__file__).resolve().parents[1]
        source = (
            root / "desktop" / "src" / "routes" / "CandidateRadar.tsx"
        ).read_text(encoding="utf-8")

        submit_start = source.index("const launchQuantProjection = () =>")
        submit_end = source.index("const launchQuantProjectionAcceptanceDryRun = () =>", submit_start)
        submit_slice = source[submit_start:submit_end]
        provider_start = source.index("const launchQuantProjectionProviderModelAcceptance = () =>")
        provider_end = source.index("const launchWorkerExecutionRequest = () =>", provider_start)
        provider_slice = source[provider_start:provider_end]
        execution_request_start = source.index("search_quant_projection_execution_request_receipt")
        execution_request_slice = source[execution_request_start:source.index("<DataLineageTable rows={objectRow(searchQuantProjectionExecutionRequest)}", execution_request_start)]
        radar_summary_start = source.index('title="普通用户雷达摘要"')
        radar_summary_slice = source[radar_summary_start:source.index('title="下一票候选池"', radar_summary_start)]
        ordinary_quant_start = source.index('title="搜票量化推演"')
        ordinary_quant_end = source.index('title="快速雷达扫描"', ordinary_quant_start)
        ordinary_quant_slice = source[ordinary_quant_start:ordinary_quant_end]
        p1_p2_details_start = source.index(
            '<details className="developer-audit-details" aria-label="quant projection ordinary p1 p2 engineering details">',
            ordinary_quant_start,
        )
        ordinary_quant_top_slice = source[ordinary_quant_start:p1_p2_details_start]

        self.assertIn("postCandidateRadarQuantProjectionProviderModelAcceptance", source)
        self.assertIn('scan_mode: "quant_projection_provider_model_acceptance"', provider_slice)
        self.assertIn("operator_approved: true", provider_slice)
        self.assertIn("acceptance_scope_hash: String(searchQuantProjectionExecutionRequest.acceptance_scope_hash ?? \"\")", provider_slice)
        self.assertIn("include_deepseek: false", provider_slice)
        self.assertIn('requested_by: "candidate_radar_page"', provider_slice)
        self.assertIn("确认 Tushare-first 补证", execution_request_slice)
        self.assertIn("disabled={!searchQuantProjectionExecutionRequest.acceptance_scope_hash}", execution_request_slice)
        self.assertIn("POST task 触发 Tushare light provider ledger", execution_request_slice)
        self.assertIn("DeepSeek 保持 skipped", execution_request_slice)
        self.assertIn("不交易、不改 strategy action", execution_request_slice)
        self.assertIn("点击后本区域会显示任务创建记录和状态", execution_request_slice)
        self.assertIn("成功后自动刷新本地 cache", execution_request_slice)
        self.assertIn("search_quant_provider_model_acceptance_receipt / call_ledger / packet", execution_request_slice)
        self.assertIn("不在 React render 里补调 provider", execution_request_slice)
        self.assertIn("<TaskLaunchReceipt receipt={taskReceipt} />", execution_request_slice)
        self.assertIn("manualTaskPanelVisible ? (", execution_request_slice)
        self.assertIn("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />", execution_request_slice)
        self.assertIn("manualTaskPanelEmptyNotice", execution_request_slice)
        self.assertIn("quantProjectionTushareFirstState", ordinary_quant_slice)
        self.assertIn("quantProjectionSubmitting", ordinary_quant_slice)
        self.assertIn("quantProjectionSubmitError", ordinary_quant_slice)
        self.assertIn("quantProjectionSubmitErrorLabel", ordinary_quant_slice)
        self.assertIn("quantProjectionSubmitFailureMessage", source)
        self.assertIn("quantProjectionP1ConfirmGateRows", source)
        self.assertIn("requires_p0_gate_ready: true", source)
        self.assertIn('p0_gate_surfaces: ["fastapi_cache_get", "bootstrap_runtime_mode", "desktop_preflight_one_click_packet", "p0_stability_or_local_link_evidence", "candidate_cache_get_readable"]', source)
        self.assertIn("const desktopP0StabilityReady =", source)
        self.assertIn("const desktopP0LocalLinkReady =", source)
        self.assertIn("const desktopP0ConnectionEvidenceReady = desktopP0StabilityReady || desktopP0LocalLinkReady", source)
        self.assertIn("const desktopP0ContractEvidenceReady =", source)
        self.assertIn("desktopP0ConnectionEvidenceReady ||", source)
        self.assertIn("p0_stability_check_ready: desktopP0StabilityReady", source)
        self.assertIn("p0_local_link_ready: desktopP0LocalLinkReady", source)
        self.assertIn("p0_connection_evidence_ready: desktopP0ConnectionEvidenceReady", source)
        self.assertIn("p0_local_link_is_ui_gate_only_not_release_evidence", source)
        self.assertIn("P0 stability check", source)
        self.assertIn("P0 stability dwell 已通过", source)
        self.assertIn("本机 FastAPI / desktop preflight 已接上；缺少启动前 stability receipt，仅作为 P1 UI 闸门，不作 release evidence", source)
        self.assertIn("stability check 或本机连接回读只作为 P1 UI 闸门证据", source)
        self.assertIn(
            'aria-label="quant projection ordinary p1 p2 engineering details"',
            ordinary_quant_slice,
        )
        self.assertIn("<summary>查看任务与回放明细</summary>", ordinary_quant_slice)
        self.assertIn("普通主视图先保留状态轨、可读结论和回放入口", ordinary_quant_slice)
        self.assertNotIn('aria-label="quant projection p1 confirm gate checklist"', ordinary_quant_top_slice)
        self.assertNotIn('aria-label="quant projection ordinary p2 writeback integrity"', ordinary_quant_top_slice)
        self.assertNotIn("确认任务接收回执", ordinary_quant_top_slice)
        self.assertIn('aria-label="quant projection p1 confirm gate checklist"', ordinary_quant_slice)
        self.assertIn("P1 确认门控清单", ordinary_quant_slice)
        self.assertIn("ordinary_confirm_button_readiness_rows", source)
        self.assertIn("quantProjectionServerConfirmButtonReadinessRows", source)
        self.assertIn("quantProjectionP1ConfirmGateFallbackRows", source)
        self.assertIn(
            "const quantProjectionP1ConfirmGateRows = quantProjectionServerConfirmButtonReadinessRows.length",
            source,
        )
        self.assertIn("优先读取服务端 ordinary_confirm_button_readiness_rows", ordinary_quant_slice)
        self.assertIn("先看代码是否通过本地校验，再点击一次确认按钮", ordinary_quant_slice)
        self.assertIn("失败先回 P0 联通恢复", ordinary_quant_slice)
        self.assertIn("这张表只读页面状态，不创建 task", ordinary_quant_slice)
        self.assertIn('readinessKey === "input_local_validation"', source)
        self.assertIn('readinessKey === "confirm_button_post_task_ready"', source)
        self.assertIn('readinessKey === "task_receipt_readback"', source)
        self.assertIn('readinessKey === "cache_replay_after_success"', source)
        self.assertIn('门控项: "1. 输入代码"', source)
        self.assertIn('门控项: "2. 确认按钮"', source)
        self.assertIn('门控项: "3. 任务接收"', source)
        self.assertIn('门控项: "4. 回放结果"', source)
        self.assertIn("允许动作: \"按钮门控 POST /api/candidate-radar/quant-projection\"", source)
        self.assertIn("只有确认按钮可创建 Tushare-first task；DeepSeek skipped，不交易", source)
        self.assertIn("轮询本地 FastAPI 任务状态；不补调 provider/model，不写交易动作", source)
        self.assertIn("cache / ledger / packet 回放不创建第二个 task，不覆盖 strategy action", source)
        self.assertLess(
            ordinary_quant_slice.index('aria-label="quant projection p1 confirm gate checklist"'),
            ordinary_quant_slice.index('label: "确认状态"'),
        )
        self.assertIn("quantProjectionCanLaunch", ordinary_quant_slice)
        self.assertIn("任务提交中：正在创建 Tushare-first POST task", source)
        self.assertIn("正在提交 Tushare-first 后台任务；请等待本地 task id", source)
        self.assertIn("确认任务正在提交：按钮已暂时禁用", source)
        self.assertIn("确认任务创建失败：未生成 task id", source)
        self.assertIn("页面不会补调数据源或模型", source)
        self.assertIn("确认任务创建失败：${quantProjectionSubmitError}", source)
        self.assertIn('if (error === "missing_task_id")', source)
        self.assertIn("const acceptedTaskId = String(res.data?.task_id ?? res.data?.task?.task_id ?? \"\");", submit_slice)
        self.assertIn("if (res.ok && acceptedTaskId) {", submit_slice)
        self.assertIn("setTaskId(acceptedTaskId);", submit_slice)
        self.assertIn('setQuantProjectionSubmitError(quantProjectionSubmitFailureMessage("missing_task_id"));', submit_slice)
        self.assertIn("setTaskReceipt(null);", submit_slice)
        self.assertEqual(submit_slice.count('setTaskId("");'), 3)
        self.assertIn("本地 FastAPI 后端未连接；请先用一键启动器恢复连接。", source)
        self.assertIn("本地任务接口返回失败；请稍后重试或查看系统健康页。", source)
        self.assertIn("quantProjectionSubmitAriaLabel", source)
        self.assertIn("quantProjectionInputBoundaryLabel", source)
        self.assertIn("quantProjectionSubmitButtonLabel", source)
        self.assertIn("quantProjectionConnectionReadyLabel", source)
        self.assertIn("本地 FastAPI 已接上：可以输入股票代码；只有确认按钮会启动本地投研数据链。", source)
        self.assertIn("本地 FastAPI 尚未完全接上：先回一键启动预检；输入保持静默，确认按钮不可用。", source)
        self.assertIn("quantProjectionConfirmRouteRows", source)
        self.assertIn('aria-label="candidate radar p1 confirm actual route"', radar_summary_slice)
        self.assertIn("确认按钮去向", radar_summary_slice)
        self.assertIn("这张表只说明当前按钮会走哪条本地后端链路；输入和页面渲染仍保持静默。", radar_summary_slice)
        self.assertIn("POST /api/candidate-radar/quant-projection", source)
        self.assertIn("只有按钮点击会 POST；页面打开、输入和 GET cache 不创建 task", source)
        self.assertIn("task call_ledger / search_quant_provider_model_acceptance_receipt", source)
        self.assertIn("DeepSeek 留到 P5 单独补", source)
        self.assertIn("Radar candidate 和量化推演都不是买入、卖出或加仓指令", source)
        self.assertIn("title={quantProjectionInputBoundaryLabel}", ordinary_quant_slice)
        self.assertIn("title={quantProjectionSubmitButtonLabel}", ordinary_quant_slice)
        self.assertIn("aria-label={quantProjectionSubmitAriaLabel}", ordinary_quant_slice)
        self.assertIn("disabled={quantProjectionSubmitDisabled}", radar_summary_slice)
        self.assertIn('{quantProjectionSubmitting ? "提交中..." : "确认并生成 3.0 量化推演"}', radar_summary_slice)
        self.assertIn('{quantProjectionConnectionReadyLabel}', radar_summary_slice)
        self.assertLess(
            radar_summary_slice.index("aria-label={quantProjectionSubmitAriaLabel}"),
            radar_summary_slice.index("{quantProjectionConnectionReadyLabel}"),
        )
        self.assertIn('<a href="#factor" aria-label="open stock quant projection result">查看量化推演结果</a>', radar_summary_slice)
        self.assertIn('<a href="#next" title={quantProjectionReplayBoundary} aria-label="open next session map from candidate radar p1 replay">查看次日图谱</a>', radar_summary_slice)
        self.assertLess(
            radar_summary_slice.index('aria-label="open stock quant projection result"'),
            radar_summary_slice.index('aria-label="open next session map from candidate radar p1 replay"'),
        )
        self.assertIn("回放入口区分本地模块路由和页内锚点：#factor/#next 切换到量化推演和次日图谱模块，#candidate-pool 留在候选池；不重新创建 task、不调用 Tushare/DeepSeek、不写 cache", source)
        self.assertIn("disabled={quantProjectionSubmitDisabled}", ordinary_quant_slice)
        self.assertIn('{quantProjectionSubmitting ? "提交中..." : "确认并生成 3.0 量化推演"}', ordinary_quant_slice)
        self.assertIn('{quantProjectionConnectionReadyLabel}', ordinary_quant_slice)
        self.assertIn("点击确认才创建 ${quantProjectionSymbolValidation.normalized} 的 Tushare-first POST task；本页不会从输入或渲染创建 Tushare-first task", source)
        self.assertIn("按钮不可用原因：先输入股票代码；输入本身不会启动数据链", source)
        self.assertIn("search_quant_projection_small_data_writeback_summary", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.summary_label", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_summary", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_next_step", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_boundary", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_stage_label", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_provenance_summary", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_rows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_writeback_action_rows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_writeback_surface_summary_rows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_provider_api_rows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_tushare_first_chain_rows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.provider_api_success_count", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.provider_api_call_count", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.source_task_tushare_provider_ledger_ready", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.provider_call_ledger_replayed_from_source_task", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.provider_call_ledger_written", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ledger_ready", source)
        self.assertIn(
            'tone: quantProjectionProviderLedgerReady ? "good" : taskReceipt?.ok || quantProjectionPersistedTaskId ? "warn" : "neutral"',
            ordinary_quant_slice,
        )
        self.assertNotIn(
            'tone: searchQuantProjectionExecutionRequest.acceptance_scope_hash ? "good" : "warn"',
            ordinary_quant_slice,
        )
        self.assertIn("quantProjectionTushareFirstChainRows", source)
        self.assertIn("const quantProjectionConfirmHandoffRows = quantProjectionTushareFirstChainRows.length ? quantProjectionTushareFirstChainRows", source)
        self.assertIn("优先读取服务端 ordinary_tushare_first_chain_rows", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataOrdinaryReadbackRows", source)
        self.assertIn("quantProjectionSmallDataActionRows", source)
        self.assertIn("quantProjectionWritebackSurfaceSummaryRows", source)
        self.assertIn("quantProjectionWritebackSurfaceRows", source)
        self.assertIn("quantProjectionWritebackIntegrityPacketRows", source)
        self.assertIn("quantProjectionWritebackIntegrityRows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_writeback_integrity_rows", source)
        self.assertIn("quantProjectionSmallDataRows.map", source)
        self.assertIn("写入位置: displayText(row.surface)", source)
        self.assertIn("当前状态: displayText(row.ordinary_label ?? row.status)", source)
        self.assertIn("行动: displayText(row[\"行动\"] ?? row.action_key)", source)
        self.assertIn("用户下一步: displayText(row[\"用户下一步\"] ?? row.next_action, quantProjectionSmallDataNextStep)", source)
        self.assertIn("写入面: displayText(row[\"写入面\"] ?? row.surface)", source)
        self.assertIn("回放来源: displayText(row[\"回放来源\"] ?? row.readback_source, \"GET /api/candidate-radar/cache\")", source)
        self.assertIn("是否齐备: displayText(row[\"是否齐备\"] ?? row.integrity_state)", source)
        self.assertIn("GET cache 只读回放；React render 不补调 provider/model", source)
        self.assertIn('aria-label="quant projection ordinary small data writeback targets"', ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary p2 writeback integrity"', ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary writeback surface summary"', ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary small data writeback actions"', ordinary_quant_slice)
        self.assertIn("P2 三面完整性检查", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_writeback_integrity_rows", ordinary_quant_slice)
        self.assertIn("普通用户只看 cache、call_ledger、packet 三面是否齐备", ordinary_quant_slice)
        self.assertIn("这张表只读回放，不创建 task", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionWritebackIntegrityRows}", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_writeback_surface_summary_rows", ordinary_quant_slice)
        self.assertIn("普通入口只看 cache、call_ledger、packet 三个写入面是否可回放", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionWritebackSurfaceRows}", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_writeback_action_rows", ordinary_quant_slice)
        self.assertIn("不会从回放行创建 task", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionSmallDataActionRows}", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionSmallDataWritebackRows}", ordinary_quant_slice)
        self.assertLess(
            ordinary_quant_slice.index('aria-label="quant projection ordinary p2 writeback integrity"'),
            ordinary_quant_slice.index('aria-label="quant projection ordinary writeback surface summary"'),
        )
        self.assertIn("quantProjectionSmallDataStageLabel", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataProvenance", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataRows", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionSmallDataRows}", ordinary_quant_slice)
        self.assertIn("quantProjectionProviderApiRows", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionProviderApiRows}", ordinary_quant_slice)
        self.assertIn("Tushare light 接口回放", ordinary_quant_slice)
        self.assertIn("trade_cal / daily / daily_basic / moneyflow", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataReady", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataNextStep", ordinary_quant_slice)
        self.assertIn('label: "小数据回放"', ordinary_quant_slice)
        self.assertIn('label: "小数据下一步"', ordinary_quant_slice)
        self.assertIn("当前读回来自 GET cache 的本地 packet", source)
        self.assertIn("search_quant_projection_interpretation_summary", source)
        self.assertIn("quantProjectionInterpretationState", ordinary_quant_slice)
        self.assertIn("ordinaryResultSurfaceLabel", source)
        self.assertIn("quantProjectionOrdinaryResultReadbackRows", source)
        self.assertIn("cache.ordinary_result_readback_rows ?? searchQuantProjectionInterpretation.ordinary_result_readback_rows", source)
        self.assertIn("quantProjectionOrdinaryResultQuickReadRows", source)
        self.assertIn("cache.ordinary_result_quick_read_rows ?? searchQuantProjectionInterpretation.ordinary_result_quick_read_rows", source)
        self.assertIn("cache.ordinary_result_handoff_rows ?? searchQuantProjectionInterpretation.ordinary_result_handoff_rows", source)
        self.assertIn("cache.ordinary_result_checkpoint_rows ?? cache.search_quant_projection_result_checkpoint_rows", source)
        self.assertIn("quantProjectionOrdinaryResultQuickRows", source)
        self.assertIn("quantProjectionModelGovernanceRows", source)
        self.assertIn("quantProjectionDeepSeekGovernanceRows", source)
        self.assertIn("quantProjectionDeepSeekReadinessRows", source)
        self.assertIn("quantProjectionOrdinaryResultActionRows", source)
        self.assertIn("ordinary_result_action_rows", source)
        self.assertIn("ordinary_result_quick_read_rows", source)
        self.assertIn("ordinary_model_governance_rows", source)
        self.assertIn("ordinary_deepseek_governed_executor_readiness_rows", source)
        self.assertIn("ordinaryResultSurfaceLabel(row.surface)", source)
        self.assertIn("当前状态: displayText(row.ordinary_label ?? row.status)", source)
        self.assertIn("来源: displayText(row.readback_source, \"cache / ledger / packet\")", source)
        self.assertIn("边界: displayText(row.boundary, quantProjectionOrdinaryResultBoundary)", source)
        self.assertIn("结论: displayText(row[\"结论\"] ?? row.quick_read_item)", source)
        self.assertIn("证据: displayText(row[\"证据\"] ?? row.evidence, quantProjectionOrdinaryResultEvidence)", source)
        self.assertIn("数据来源", ordinary_quant_slice)
        self.assertIn("量化推演", ordinary_quant_slice)
        self.assertIn("次日图谱", ordinary_quant_slice)
        self.assertIn("安全边界", ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary explainable result quick read"', ordinary_quant_slice)
        self.assertIn("P3 结果速读", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_result_quick_read_rows", ordinary_quant_slice)
        self.assertIn("不会从结果速读创建 task 或调用模型", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionOrdinaryResultQuickRows}", ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary deepseek governance status"', ordinary_quant_slice)
        self.assertIn("<summary>高级：P5 DeepSeek 单独补证</summary>", ordinary_quant_slice)
        self.assertIn("P5 只作为高级单独补证", ordinary_quant_slice)
        self.assertIn("不作为普通用户当前下一步，不阻塞 P1/P2/P3 本地回放", ordinary_quant_slice)
        self.assertIn("优先读取 ordinary_model_governance_rows", ordinary_quant_slice)
        self.assertIn("不会从治理状态创建 task 或调用模型", ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary deepseek governed executor readiness"', ordinary_quant_slice)
        self.assertIn("P5 governed executor readiness", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_deepseek_governed_executor_readiness_rows", ordinary_quant_slice)
        self.assertIn("何时才允许单独补 DeepSeek、当前为什么不能调、以及后续只能写安全摘要", ordinary_quant_slice)
        self.assertIn("这张表只读回放，不创建 task、不调用模型", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionDeepSeekReadinessRows}", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionDeepSeekGovernanceRows}", ordinary_quant_slice)
        self.assertIn("治理项: displayText(row[\"治理项\"] ?? row.governance_item)", source)
        self.assertIn("rows={quantProjectionOrdinaryResultRows}", ordinary_quant_slice)
        self.assertIn("可解释结果行动", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionOrdinaryResultActionRows}", ordinary_quant_slice)
        self.assertIn("读可读结论、回放量化推演、打开次日图谱", ordinary_quant_slice)
        self.assertIn(
            '<details className="developer-audit-details" aria-label="quant projection task cache packet readback">',
            ordinary_quant_slice,
        )
        self.assertIn("<summary>任务 / cache packet 回放详情</summary>", ordinary_quant_slice)
        self.assertIn("普通入口只保留任务状态轨和结果速读", ordinary_quant_slice)
        self.assertIn('label: "解释结果"', ordinary_quant_slice)
        self.assertIn('label: "解释下一步"', ordinary_quant_slice)
        self.assertNotIn("确认 Tushare-first 补证", ordinary_quant_slice)
        self.assertNotIn("disabled={!searchQuantProjectionExecutionRequest.acceptance_scope_hash}", ordinary_quant_slice)
        self.assertIn('label: "Tushare-first"', ordinary_quant_slice)
        self.assertIn('label: "最近任务"', ordinary_quant_slice)
        self.assertIn('label: "任务回放"', ordinary_quant_slice)
        self.assertIn('label: "结果回放"', ordinary_quant_slice)
        self.assertIn("quantProjectionLatestTaskState", ordinary_quant_slice)
        self.assertIn("quantProjectionTaskReadbackState", ordinary_quant_slice)
        self.assertIn("quantProjectionResultReplayState", ordinary_quant_slice)
        self.assertIn('aria-label="candidate radar first screen p1 chain details"', radar_summary_slice)
        self.assertIn("<summary>查看确认后清单</summary>", radar_summary_slice)
        self.assertIn("按钮路由、回放清单和链路排障默认收起", radar_summary_slice)
        self.assertIn('aria-label="candidate radar first screen post confirm readback guide"', radar_summary_slice)
        self.assertIn("点击确认后按这张清单走：先看任务编号，再看任务进度，success 后刷新本地 cache，最后回放量化推演和次日图谱", radar_summary_slice)
        self.assertIn("DataLineageTable rows={quantProjectionPostConfirmActionRows}", radar_summary_slice)
        first_screen_confirm_start = radar_summary_slice.index('aria-label="candidate radar first screen quant projection confirmation"')
        first_screen_p1_chain_details_start = radar_summary_slice.index('aria-label="candidate radar first screen p1 chain details"')
        first_screen_post_confirm_start = radar_summary_slice.index('aria-label="candidate radar first screen post confirm readback guide"')
        first_screen_direct_handoff_start = radar_summary_slice.index('aria-label="candidate radar p1 direct confirmation handoff"')
        self.assertLess(first_screen_confirm_start, first_screen_p1_chain_details_start)
        self.assertLess(first_screen_p1_chain_details_start, first_screen_post_confirm_start)
        self.assertLess(first_screen_post_confirm_start, first_screen_direct_handoff_start)
        first_screen_post_confirm = radar_summary_slice[first_screen_post_confirm_start:first_screen_direct_handoff_start]
        self.assertNotIn("onClick=", first_screen_post_confirm)
        self.assertNotIn("postCandidateRadarQuantProjection", first_screen_post_confirm)
        self.assertNotIn("postCandidateRadarQuantProjectionProviderModelAcceptance", first_screen_post_confirm)
        self.assertNotIn("fetch(", first_screen_post_confirm)
        self.assertIn("quantProjectionReplayDestinationPacketRows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_replay_destination_rows", source)
        self.assertIn("search_quant_provider_model_acceptance_receipt / call_ledger / packet", source)
        self.assertIn("最近任务只显示本地 FastAPI 返回的 task id 和安全步骤", ordinary_quant_slice)
        self.assertIn("最近任务优先显示本次确认返回的 task id", ordinary_quant_slice)
        self.assertIn("页面刷新后再从本地 cache / packet 回放 task id 和安全 current_step", ordinary_quant_slice)
        self.assertIn("const quantProjectionDisplayTaskId = taskId || quantProjectionPersistedTaskId;", source)
        self.assertIn("GET cache 不会因此补调 provider", ordinary_quant_slice)
        self.assertIn("不在普通页面展开审计表", ordinary_quant_slice)
        self.assertIn("DeepSeek 保持 skipped", ordinary_quant_slice)
        self.assertIn("确认后创建 Tushare-first 按钮门控 POST task / worker", ordinary_quant_slice)
        self.assertIn("不交易、不改 strategy action", ordinary_quant_slice)
        self.assertIn("if (!quantProjectionCanSubmit || quantProjectionSubmitting) return;", submit_slice)
        self.assertIn("setQuantProjectionSubmitting(true);", submit_slice)
        self.assertIn('setQuantProjectionSubmitError("");', submit_slice)
        self.assertIn("setQuantProjectionSubmitError(quantProjectionSubmitFailureMessage(res.error));", submit_slice)
        self.assertIn('setQuantProjectionSubmitError(quantProjectionSubmitFailureMessage("missing_task_id"));', submit_slice)
        self.assertIn("}).finally(() => setQuantProjectionSubmitting(false));", submit_slice)
        self.assertNotIn("postCandidateRadarQuantProjectionProviderModelAcceptance", submit_slice)
        self.assertNotIn("operator_approved", submit_slice)
        self.assertIn("include_deepseek: false", submit_slice)
        self.assertIn("user_approved: true", submit_slice)
        self.assertIn("p0_confirm_gate_evidence", submit_slice)
        self.assertIn('schema_version: "candidate_radar_p0_confirm_gate.v1"', submit_slice)
        self.assertIn("p0_ready: quantProjectionP0Ready", submit_slice)
        self.assertIn("fastapi_cache_get_ready: !loading && !error", submit_slice)
        self.assertIn("bootstrap_runtime_mode_ready: bootstrapRuntimeModeReady", submit_slice)
        self.assertIn("desktop_preflight_ready: desktopPreflightReady", submit_slice)
        self.assertIn("p0_stability_check_ready: desktopP0StabilityReady", submit_slice)
        self.assertIn("p0_local_link_ready: desktopP0LocalLinkReady", submit_slice)
        self.assertIn("p0_connection_evidence_ready: desktopP0ConnectionEvidenceReady", submit_slice)
        self.assertIn("candidate_cache_ready: candidateRadarCacheGetReadable", submit_slice)
        self.assertIn('candidate_cache_status: String(cache.status ?? "missing")', submit_slice)
        self.assertIn('bootstrap_packet_key: String(bootstrapStatus.packet_key ?? "missing")', submit_slice)
        self.assertIn('desktop_preflight_packet_key: String(desktopPreflight.packet_key ?? "missing")', submit_slice)
        self.assertIn("creates_task_only_after_button: true", submit_slice)
        self.assertIn("react_render_external_calls: false", submit_slice)
        self.assertIn("get_cache_external_calls: false", submit_slice)
        self.assertIn("contains_secret: false", submit_slice)
        self.assertIn("refreshQuantProjectionReadback();", submit_slice)
        self.assertIn("任务接收后立即回读本地 cache receipt", ordinary_quant_slice)
        self.assertNotIn("fetch(", source)
        self.assertNotIn("TUSHARE_TOKEN", source)
        self.assertNotIn("DEEPSEEK_API_KEY", source)
        self.assertNotIn("GITHUB_TOKEN", source)


if __name__ == "__main__":
    unittest.main()
