import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1] / "desktop"


class CommandCenterHomeOrdinaryEntryTests(unittest.TestCase):
    def setUp(self):
        self.source = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")

    def test_daily_command_center_summary_shows_user_decision_fields_first(self):
        source = self.source

        self.assertIn("<h1>今日作战台</h1>", source)
        self.assertIn("先看下一步、数据来源、缺少证据和仅供研究边界", source)
        self.assertIn('title="本地 FastAPI 接线速读"', source)
        self.assertLess(source.index('title="本地 FastAPI 接线速读"'), source.index('title="今日作战台摘要"'))
        self.assertIn('title="P0 现在能不能用"', source)
        self.assertLess(source.index('title="本地 FastAPI 接线速读"'), source.index('title="P0 现在能不能用"'))
        self.assertLess(source.index('title="P0 现在能不能用"'), source.index('title="今日作战台摘要"'))
        self.assertIn('title="今日作战台摘要"', source)
        self.assertIn('title="P3 可解释结果一眼读懂"', source)
        self.assertLess(source.index('title="最近本地任务"'), source.index('title="P3 可解释结果一眼读懂"'))
        self.assertLess(source.index('title="P3 可解释结果一眼读懂"'), source.index('title="今日作战台摘要"'))
        self.assertIn("下一步、来源、缺口、边界和最近可用缓存", source)
        self.assertIn('label: "下一步"', source)
        self.assertIn('label: "主下一步"', source)
        self.assertIn('label: "主下一步边界"', source)
        self.assertIn('label: "本地联通"', source)
        self.assertIn('label: "一键启动"', source)
        self.assertIn('label: "启动恢复"', source)
        self.assertIn('label: "启动边界"', source)
        self.assertIn('label: "启动成功条件"', source)
        self.assertIn('label: "启动诊断"', source)
        self.assertIn('label: "启动失败处理"', source)
        self.assertIn('label: "恢复回读"', source)
        self.assertIn('label: "回读顺序"', source)
        self.assertIn('label: "回读边界"', source)
        self.assertIn('label: "只读自检"', source)
        self.assertIn('label: "P0 可继续"', source)
        self.assertIn('label: "P0 进入 P1 闸门"', source)
        self.assertIn('label: "联通后行动"', source)
        self.assertIn('label: "一屏行动"', source)
        self.assertIn('label: "确认结果链"', source)
        self.assertIn('label: "确认后回放"', source)
        self.assertIn('label: "量化缓存回放"', source)
        self.assertIn("dailyCommandStartupReadbackRows", source)
        self.assertIn("p0LauncherCheckOnlyRows", source)
        self.assertIn("p0OrdinaryQuickActionRows", source)
        self.assertIn("p0CurrentNextActionRows", source)
        self.assertIn("dailyCommandP0EntryGateRows", source)
        self.assertIn("candidatePolicy", source)
        self.assertIn("candidateQuantOneScreenActionRows", source)
        self.assertIn("candidateQuantSmallDataWriteback.ordinary_one_screen_action_rows", source)
        self.assertIn("candidateQuantConfirmOutcomeRows", source)
        self.assertIn("candidateQuantSmallDataWriteback.ordinary_confirm_outcome_rows", source)
        self.assertIn("dailyCommandOneScreenActionRows", source)
        self.assertIn("dailyCommandOneScreenActionLabel", source)
        self.assertIn("dailyCommandConfirmOutcomeRows", source)
        self.assertIn("dailyCommandConfirmOutcomeLabel", source)
        self.assertIn("dailyCommandP2P3ReplayChecklistRows", source)
        self.assertIn("candidateQuantResultCheckpoint", source)
        self.assertIn("candidates.search_quant_projection_result_checkpoint", source)
        self.assertIn("candidates.ordinary_result_quick_read_rows", source)
        self.assertIn("candidateQuantHandoffRows", source)
        self.assertIn("candidates.ordinary_result_handoff_rows", source)
        self.assertIn("candidates.ordinary_result_checkpoint_rows", source)
        self.assertIn("candidates.search_quant_projection_result_checkpoint_rows", source)
        self.assertIn("dailyCommandP3OneGlanceStatus", source)
        self.assertIn("dailyCommandP3OneGlanceSource", source)
        self.assertIn("dailyCommandP3OneGlanceMissingEvidence", source)
        self.assertIn("dailyCommandP3OneGlanceSafeFields", source)
        self.assertIn("factorFailedCacheSummary", source)
        self.assertIn("dailyCommandFactorCacheFallbackActive", source)
        self.assertIn("dailyCommandFactorCacheFallbackLabel", source)
        self.assertIn("dailyCommandFactorCacheFallbackBoundary", source)
        self.assertIn("dailyCommandFactorCacheFallbackRows", source)
        self.assertIn("dailyCommandP6StrictCloseoutReentryRows", source)
        self.assertIn("desktopPreflight.p0_current_next_action_rows", source)
        self.assertIn("dailyCommandP0QuickAction", source)
        self.assertIn("dailyCommandUsablePathStageRailSteps", source)
        self.assertIn('aria-label="daily command local connection readback"', source)
        self.assertIn('aria-label="daily command usable path stage rail"', source)
        self.assertIn('aria-label="daily command p6 strict closeout reentry details"', source)
        self.assertIn('aria-label="daily command p6 strict closeout reentry"', source)
        self.assertIn('aria-label="daily command p6 reentry links"', source)
        self.assertIn('aria-label="daily command p0 launcher check-only readback"', source)
        self.assertIn('aria-label="daily command p0 p1 entry gate"', source)
        self.assertIn('aria-label="daily command p0 current next action"', source)
        self.assertIn('aria-label="daily command one screen search actions"', source)
        self.assertIn('aria-label="daily command p2 p3 replay checklist"', source)
        self.assertIn('aria-label="daily command p0 quick action handoff"', source)
        self.assertIn('aria-label="daily command factor cache fallback readback"', source)
        self.assertIn("本地联通四段回读", source)
        self.assertIn("P6 / 14 LTG strict closeout 审计入口", source)
        self.assertIn("P6 strict closeout 回归入口", source)
        self.assertIn("一键启动只读自检", source)
        self.assertIn("P0 进入 P1 闸门", source)
        self.assertIn("P0 当前下一步", source)
        self.assertIn("今日搜票一屏行动", source)
        self.assertIn("确认后回放清单", source)
        self.assertIn("P0 到 P1 快速行动", source)
        self.assertIn("量化缓存降级回放", source)
        self.assertIn("量化缓存已降级为本地可读", source)
        self.assertIn("量化缓存直接可读；未检测到失败持久化 packet 降级", source)
        self.assertIn("failed_factor_quant_cache_summary 安全摘要", source)
        self.assertIn("量化缓存降级只返回安全摘要和本地 builder 结果", source)
        self.assertIn("首页不展开 raw failed packet、provider error、token/key 或 call_ledger", source)
        self.assertIn("如果上次持久化量化 packet 是失败态，首页只读展示安全摘要，并继续使用本地 cache-only 回放", source)
        self.assertIn('回放项: "当前量化缓存"', source)
        self.assertIn('回放项: "失败持久化降级"', source)
        self.assertIn('label: "P0 本地联通"', source)
        self.assertIn('label: "P1 确认按钮"', source)
        self.assertIn('label: "P2 小数据"', source)
        self.assertIn('label: "P3 可解释结果"', source)
        self.assertIn('label: "P4 审计下沉"', source)
        self.assertIn('label: "P5 解释治理"', source)
        self.assertIn('label: "P6 LTG 证据"', source)
        self.assertIn('detail: "Tushare-first"', source)
        self.assertIn('"cache/ledger/packet"', source)
        self.assertIn('detail: "governed"', source)
        self.assertIn('detail: "0/14"', source)
        self.assertIn('阶段: "P6 回到 14 LTG direct evidence"', source)
        self.assertIn("re-entry gate visible；strict closeout 仍是 0/14", source)
        self.assertIn('回归项: "1. 可用化 checkpoint"', source)
        self.assertIn('回归项: "2. strict closeout 入口"', source)
        self.assertIn('回归项: "3. 任务证据回放"', source)
        self.assertIn("strict closeout 仍是 0/14；只按 current-head direct evidence 关闭", source)
        self.assertIn("打开迁移状态页，按 LTG next acceptance action rows 逐项补证", source)
        self.assertIn("P0-P5 可用化 checkpoint 不是 14 LTG 完成", source)
        self.assertIn("mock、matrix、sanitizer、local receipt 不能关闭 LTG", source)
        self.assertIn("P0-P5 是使用者可用化 checkpoint；14 LTG strict closeout 仍需 current-head direct evidence", source)
        self.assertIn("P6 留作工程审计和 strict closeout 回归；普通主线先看 P0 联通、P1 确认、P2 写回和 P3 结果", source)
        self.assertIn("先看 FastAPI、bootstrap runtime-mode packet、desktop preflight cache、React/Vite 前端四段是否变绿", source)
        self.assertIn("优先读取 desktop preflight 的 p0_launcher_check_only_rows", source)
        self.assertIn("check-only 只打印配置，不启动 FastAPI/Vite、不探测 URL、不打开浏览器、不创建 task", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_one_screen_action_rows", source)
        self.assertIn("确认、任务、写回、结果合成首页速读", source)
        self.assertIn("首页只读回放，不创建 task、不调用模型", source)
        self.assertIn('aria-label="daily command confirm outcome readback"', source)
        self.assertIn("确认结果链速读", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_confirm_outcome_rows", source)
        self.assertIn("确认任务是否接收、P2 三面是否回放、P3 结果入口是否可读", source)
        self.assertIn("首页只读回放，不创建第二个 task", source)
        self.assertIn('确认结果: "P1 确认结果"', source)
        self.assertIn('确认结果: "P2 写回结果"', source)
        self.assertIn('确认结果: "P3 回放结果"', source)
        self.assertIn("确认回执 -> 任务状态 -> P2 写回 -> P3 结果", source)
        self.assertIn("确认按钮返回 task 后，按确认回执、任务状态、P2 写回三面、P3 结果顺序回放", source)
        self.assertIn("首页只读 CandidateRadar cache / ledger / packet，不创建 task、不补调 Tushare/DeepSeek", source)
        self.assertIn('回放入口: "1. 确认回执"', source)
        self.assertIn('回放入口: "2. 任务状态"', source)
        self.assertIn('回放入口: "3. P2 写回三面"', source)
        self.assertIn('回放入口: "4. P3 结果"', source)
        self.assertIn("search_quant_projection_confirmed_task_receipt_row_count", source)
        self.assertIn("search_quant_projection_task_readback_row_count", source)
        self.assertIn("CandidateRadar ordinary_confirmed_task_receipt_rows", source)
        self.assertIn("CandidateRadar ordinary_task_readback_rows", source)
        self.assertIn("首页只读 packet；不展示 raw log、token/key 或 provider error", source)
        self.assertIn('行动: "1. 确认"', source)
        self.assertIn('行动: "2. 任务"', source)
        self.assertIn('行动: "3. 写回"', source)
        self.assertIn('行动: "4. 结果"', source)
        self.assertIn("优先读取 desktop preflight 的 p0_ordinary_quick_action_rows", source)
        self.assertIn("优先读取 desktop preflight 的 p0_current_next_action_rows", source)
        self.assertIn("普通用户先看这张清单：health、bootstrap status、desktop preflight 和当前 React 页面四段通过后，才进入下一票雷达", source)
        self.assertIn("输入仍保持静默，只有确认按钮创建 Tushare-first POST task", source)
        self.assertIn("rows={dailyCommandP0EntryGateRows}", source)
        self.assertIn('闸门项: "1. FastAPI health"', source)
        self.assertIn('闸门项: "2. Bootstrap runtime"', source)
        self.assertIn('闸门项: "3. Desktop preflight"', source)
        self.assertIn('闸门项: "4. 进入 P1"', source)
        self.assertIn("P0 未 ready：不要进入 P1", source)
        self.assertIn("P0 ready 不代表 Tushare/DeepSeek 已调用，也不是 release ready 或 14 LTG 完成", source)
        self.assertIn("未 ready 回预检恢复，ready 后只切到下一票雷达", source)
        self.assertIn("确认按钮之前不创建 Tushare-first task", source)
        self.assertIn('回读项: "FastAPI health"', source)
        self.assertIn('回读项: "Bootstrap status"', source)
        self.assertIn('回读项: "Desktop preflight cache"', source)
        self.assertIn('回读项: "React/Vite 前端"', source)
        self.assertIn("Command Center 3.0 health JSON 且 external_calls_on_startup=false", source)
        self.assertIn("只读运行模式，不写配置、不创建 live_light task", source)
        self.assertIn("返回 command_center_3_desktop_shell_preflight_cache 一键启动 packet", source)
        self.assertIn("首页只展示预检 packet，不启动 FastAPI/Vite/浏览器", source)
        self.assertIn("首页只展示预检结果，不启动 FastAPI/Vite/浏览器", source)
        self.assertIn('label: "股票量化推演"', source)
        self.assertIn('label: "量化缓存回放"', source)
        self.assertIn('label: "下一票雷达"', source)
        self.assertIn('label: "今日查看顺序"', source)
        self.assertIn('label: "今日结果组成"', source)
        self.assertIn('label: "本地缓存"', source)
        self.assertIn('label: "数据链"', source)
        self.assertIn('label: "解释状态"', source)
        self.assertIn('label: "外联触发边界"', source)
        self.assertIn('label: "待补证据"', source)
        self.assertIn('label: "降级提示"', source)
        self.assertIn('label: "最近成功回放"', source)
        self.assertIn('label: "数据来源"', source)
        self.assertIn('label: "缺少证据"', source)
        self.assertIn('label: "阻断/降级"', source)
        self.assertIn('label: "最近可用缓存"', source)
        self.assertIn('label: "任务边界"', source)
        self.assertIn('label: "缺数据口径"', source)
        self.assertIn('label: "仅供研究"', source)
        self.assertLess(source.index("今日作战台摘要"), source.index("开发 / 审计详情"))
        self.assertLess(source.index('title="今日作战台摘要"'), source.index('<PacketCard title="live_light 手动补证"'))
        self.assertLess(source.index('label: "本地联通"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "一键启动"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "启动诊断"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "恢复回读"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "回读边界"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "只读自检"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "P0 可继续"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index("本地联通四段回读"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("一键启动只读自检"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("P0 进入 P1 闸门"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("P0 当前下一步"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("今日搜票一屏行动"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("P0 进入 P1 闸门"), source.index("P0 当前下一步"))
        self.assertLess(source.index("P0 当前下一步"), source.index("今日搜票一屏行动"))
        self.assertLess(source.index("今日搜票一屏行动"), source.index("确认后回放清单"))
        self.assertLess(source.index("今日搜票一屏行动"), source.index("确认结果链速读"))
        self.assertLess(source.index("确认结果链速读"), source.index("确认后回放清单"))
        confirm_outcome_start = source.index('aria-label="daily command confirm outcome readback"')
        confirm_outcome_end = source.index('aria-label="daily command p2 p3 replay checklist"', confirm_outcome_start)
        confirm_outcome_slice = source[confirm_outcome_start:confirm_outcome_end]
        self.assertNotIn("onClick=", confirm_outcome_slice)
        self.assertNotIn("launch" + "Task", confirm_outcome_slice)
        self.assertNotIn("post" + "Task(", confirm_outcome_slice)
        self.assertLess(source.index("确认后回放清单"), source.index("P0 到 P1 快速行动"))
        self.assertLess(source.index("P0 到 P1 快速行动"), source.index("开发 / 审计详情"))
        self.assertLess(source.index("P3 结果回放入口"), source.index("量化缓存降级回放"))
        self.assertLess(source.index("量化缓存降级回放"), source.index("P5 DeepSeek 单独治理"))
        self.assertLess(source.index("量化缓存降级回放"), source.index("开发 / 审计详情"))
        factor_fallback_start = source.index('aria-label="daily command factor cache fallback readback"')
        factor_fallback_end = source.index('aria-label="daily command p5 deepseek governance quick read"', factor_fallback_start)
        factor_fallback_slice = source[factor_fallback_start:factor_fallback_end]
        self.assertNotIn("onClick=", factor_fallback_slice)
        self.assertNotIn("launch" + "Task", factor_fallback_slice)
        self.assertNotIn("post" + "Task(", factor_fallback_slice)
        self.assertNotIn("postBootstrapLiveStartup", factor_fallback_slice)
        self.assertLess(source.index("P6 strict closeout 回归入口"), source.index("开发 / 审计详情"))
        self.assertLess(source.index('aria-label="daily command p6 reentry links"'), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "本地缓存"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "最近成功回放"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "今日查看顺序"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "今日结果组成"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        self.assertLess(source.index('label: "缺数据口径"', source.index("今日作战台摘要")), source.index("开发 / 审计详情"))
        summary_slice = source[source.index('title="今日作战台摘要"') : source.index("开发 / 审计详情")]
        for hidden_label in (
            'label: "cache"',
            'label: "Tushare"',
            'label: "DeepSeek"',
            'label: "pending"',
            'label: "degraded"',
            'label: "last_successful_cache/result"',
            'label: "P5 DeepSeek"',
        ):
            self.assertNotIn(hidden_label, summary_slice)
        self.assertNotIn('{ label: "今日作战台"', source)

    def test_local_fastapi_connection_card_is_first_screen_and_read_only(self):
        source = self.source
        card_start = source.index('title="本地 FastAPI 接线速读"')
        card_end = source.index('title="P0 现在能不能用"', card_start)
        card = source[card_start:card_end]

        self.assertIn("打开软件后先看这张卡", card)
        self.assertIn('label: "本地后端"', card)
        self.assertIn("dailyCommandFrontendBackendAutoLinkLabel", card)
        self.assertIn('label: "当前页面"', card)
        self.assertIn("FastAPI、bootstrap、desktop preflight 和 React 已接上", card)
        self.assertIn('label: "投研入口"', card)
        self.assertIn("去下一票雷达输入代码并确认", card)
        self.assertIn('label: "安全边界"', card)
        self.assertIn("打开页面和输入代码不外联；确认按钮才触发 Tushare-first", card)
        self.assertIn('aria-label="daily command fastapi connected user actions"', card)
        self.assertIn('href={dailyCommandPrimaryActionHref}', card)
        self.assertIn('href="#tasks"', card)
        self.assertIn('href="#desktop"', card)
        self.assertIn("只读 FastAPI health、bootstrap status 和 desktop preflight cache", card)
        self.assertIn("不会启动服务、不会创建 task、不会调用 Tushare/DeepSeek/GitHub", card)
        self.assertIn("不会暴露 token/key", card)
        self.assertNotIn("onClick=", card)
        self.assertNotIn("fetch(", card)
        self.assertNotIn("postTask", card)
        self.assertNotIn("postBootstrapLiveStartup", card)

    def test_p3_one_glance_card_is_early_read_only_result_summary(self):
        source = self.source
        card_start = source.index('title="P3 可解释结果一眼读懂"')
        card_end = source.index('title="今日作战台摘要"', card_start)
        card = source[card_start:card_end]

        self.assertIn("结论、来源、缺口、下一步和安全边界", card)
        self.assertIn('status={dailyCommandP3OneGlanceStatus}', card)
        self.assertIn('label: "可读结论"', card)
        self.assertIn("dailyCommandExplainableResultLabel", card)
        self.assertIn("dailyCommandP3OneGlanceReadable", card)
        self.assertIn('label: "数据来源"', card)
        self.assertIn("dailyCommandP3OneGlanceSource", card)
        self.assertIn("dailyCommandP3OneGlanceProviderVerified", card)
        self.assertIn('label: "结果证据"', card)
        self.assertIn("dailyCommandP3OneGlanceEvidence", card)
        self.assertIn('label: "来源任务"', card)
        self.assertIn("dailyCommandP3OneGlanceSourceTask", card)
        self.assertIn('label: "结果入口"', card)
        self.assertIn("dailyCommandP3OneGlanceResultEntrances", card)
        self.assertIn('label: "待补缺口"', card)
        self.assertIn("dailyCommandP3OneGlanceMissingEvidence", card)
        self.assertIn('label: "下一步"', card)
        self.assertIn("dailyCommandExplainableResultNext", card)
        self.assertIn('label: "模型状态"', card)
        self.assertIn("dailyCommandP3OneGlanceModelState", card)
        self.assertIn('label: "安全字段"', card)
        self.assertIn("dailyCommandP3OneGlanceSafeFields", card)
        self.assertIn('label: "边界"', card)
        self.assertIn("dailyCommandExplainableResultBoundary", card)
        self.assertIn('aria-label="daily command p3 one glance actions"', card)
        self.assertIn('href="#candidates"', card)
        self.assertIn('href="#factor"', card)
        self.assertIn('href="#next"', card)
        self.assertIn("只读 `search_quant_projection_result_checkpoint`", card)
        self.assertIn("不会创建 task、不会调用 DeepSeek、不会交易或修改 strategy action", card)
        self.assertNotIn("onClick=", card)
        self.assertNotIn("fetch(", card)
        self.assertNotIn("postBootstrapLiveStartup", card)
        self.assertNotIn("postCandidateRadar", card)

    def test_p0_now_usable_card_is_short_read_only_status(self):
        source = self.source
        card_start = source.index('title="P0 现在能不能用"')
        card_end = source.index('title="今日作战台摘要"', card_start)
        card = source[card_start:card_end]

        self.assertIn("普通用户打开软件后的 10 秒判断", card)
        self.assertIn('status={dailyCommandP0LocalReadinessReady ? "ready" : "check"}', card)
        self.assertIn('label: "结论"', card)
        self.assertIn("可以用：本地四段已接上", card)
        self.assertIn("先恢复：本地四段还没全部 ready", card)
        self.assertIn('label: "现在点哪里"', card)
        self.assertIn("dailyCommandPrimaryActionLabel", card)
        self.assertIn('label: "失败看哪里"', card)
        self.assertIn("桌面壳预检里的 FastAPI / bootstrap / preflight / React 分段诊断", card)
        self.assertIn('label: "进入 P1 条件"', card)
        self.assertIn("health、bootstrap、desktop preflight、React 四段 ready 后再确认股票代码", card)
        self.assertIn('aria-label="daily command p0 now usable actions"', card)
        self.assertIn('href={dailyCommandPrimaryActionHref}', card)
        self.assertIn('href="#desktop"', card)
        self.assertIn('href="#candidates"', card)
        self.assertIn("输入仍保持静默，确认按钮才创建 Tushare-first task", card)
        self.assertIn("这张卡只读本地状态；不启动服务、不创建 task、不调用 provider/model", card)
        self.assertIn("不代表 Tushare 已调用、DeepSeek 可用、release ready 或 14 LTG 完成", card)
        self.assertNotIn("onClick=", card)
        self.assertNotIn("fetch(", card)
        self.assertNotIn("postTask", card)
        self.assertNotIn("postBootstrapLiveStartup", card)
        self.assertNotIn("launchLiveBootstrap", card)

    def test_daily_command_center_source_and_boundary_are_visible(self):
        source = self.source

        self.assertIn("dailyCommandSourceState", source)
        self.assertIn("dailyCommandConnectionState", source)
        self.assertIn("dailyCommandLauncherState", source)
        self.assertIn("dailyCommandReviewOrder", source)
        self.assertIn("dailyCommandResultComposition", source)
        self.assertIn("dailyCommandMissingDataBoundary", source)
        self.assertIn("dailyCommandPrimaryActionLabel", source)
        self.assertIn("dailyCommandPrimaryActionHref", source)
        self.assertIn("dailyCommandPrimaryActionBoundary", source)
        self.assertIn("dailyCommandHealthOk", source)
        self.assertIn("dailyCommandHealthChecked", source)
        self.assertIn("dailyCommandCacheWarning", source)
        self.assertIn("!dailyCommandHealthOk && (loading || Boolean(error) || !dailyCommandHealthChecked)", source)
        self.assertIn("先确认 P0 本地联通，再进入下一票雷达确认代码，之后回放股票量化推演和次日图谱结果", source)
        self.assertIn("先看一键启动预检恢复本地联通，再回今日作战台", source)
        self.assertIn("候选：${Number(candidateCounts?.candidate_count ?? 0) ? String(candidateCounts?.candidate_count) : \"等待缓存\"}", source)
        self.assertIn("量化：${String(factor.status ?? factor.mode ?? \"等待缓存\")}", source)
        self.assertIn("风险：${String(riskCounts?.active_risk_count ?? riskCounts?.risk_count ?? 0)} 项", source)
        self.assertIn("缺数据先看 pending / 缺少证据；不能把空缓存当成无风险", source)
        self.assertIn("不能把空缓存当成无风险，也不能当成生产验收完成", source)
        self.assertIn("今日先按“P0 本地联通 → 下一票雷达确认代码 → 股票量化推演 / 次日图谱回放”复核", source)
        self.assertIn("不把空结果当成无风险", source)
        self.assertIn("进入下一票雷达确认代码", source)
        self.assertIn("主下一步只切换到下一票雷达；输入保持静默，确认按钮才创建 Tushare-first POST task", source)
        self.assertNotIn("主下一步只查看本地数据健康；运行快扫仍需进入下一票雷达手动点击", source)
        self.assertIn("本地前后端未联通；请使用桌面快捷方式或本地启动器重新打开", source)
        self.assertIn("本地前后端已联通", source)
        self.assertIn("本地 cache 回读提示：${error}", source)
        self.assertIn("本地后端已联通；普通 cache 回读提示不阻断 P0", source)
        self.assertIn("继续进入下一票雷达；普通 cache 提示留在待补证据里", source)
        self.assertIn("一键启动入口可用；启动器会等 FastAPI 和页面 ready", source)
        self.assertIn("dailyCommandStartupSuccessCondition", source)
        self.assertIn("dailyCommandStartupFailureAction", source)
        self.assertIn("dailyCommandStartupDiagnosticSurfaces", source)
        self.assertIn("dailyCommandStartupReadbackLabel", source)
        self.assertIn("dailyCommandStartupReadbackOrder", source)
        self.assertIn("dailyCommandStartupReadbackBoundary", source)
        self.assertIn("dailyCommandStartupReadbackRows", source)
        self.assertIn("dailyCommandP0CheckOnlyNext", source)
        self.assertIn("dailyCommandFrontendBackendSelectedApiBase", source)
        self.assertIn("dailyCommandP0LocalReadinessReady", source)
        self.assertIn("dailyCommandP0LocalReadinessLabel", source)
        self.assertIn("dailyCommandP0LocalReadinessBoundary", source)
        self.assertIn("dailyCommandP0EntryGateRows", source)
        self.assertIn('row.api === "frontend_fastapi_request"', source)
        self.assertIn("row.frontend_backend_auto_link_success === true", source)
        self.assertIn("typeof row.api_base === \"string\"", source)
        self.assertIn("?.api_base ?? API_BASE_DISPLAY_URL", source)
        self.assertIn("desktopPreflight.p0_launcher_check_only_rows", source)
        self.assertIn("desktopRuntime?.p0_launcher_check_only_next", source)
        self.assertIn("scripts/check_command_center_3.command", source)
        self.assertNotIn("COMMAND_CENTER_3_LAUNCHER_CHECK_ONLY=1 scripts/start_command_center_3.command", source)
        self.assertIn("desktopPreflight.p0_ordinary_quick_action_rows", source)
        self.assertIn("desktopRuntime?.p0_ordinary_quick_action_next", source)
        self.assertIn("p0CurrentNextActionSourceRows", source)
        self.assertIn("desktopPreflight.p0_current_next_action_rows", source)
        self.assertIn("DataLineageTable rows={p0CurrentNextActionRows}", source)
        self.assertIn("等待 desktop preflight 当前下一步回读", source)
        self.assertIn("代码通过本地校验后点击确认按钮，才创建 Tushare-first POST task；DeepSeek skipped。", source)
        self.assertIn("页面打开、搜索输入和本表回读都不外联；只有确认按钮可进入 P1 task / worker。", source)
        self.assertIn("DataLineageTable rows={p0LauncherCheckOnlyRows}", source)
        self.assertIn("联通通过后进入下一票雷达，输入代码，再由确认按钮触发 Tushare-first 任务", source)
        self.assertIn("DataLineageTable rows={p0OrdinaryQuickActionRows}", source)
        self.assertIn("FastAPI /health 必须返回 Command Center 3.0 健康 JSON", source)
        self.assertIn("/api/bootstrap/status 必须返回 runtime-mode packet", source)
        self.assertIn("/api/desktop/preflight-cache 必须返回一键启动 packet", source)
        self.assertIn("React/Vite 必须返回 Command Center 3.0 前端 HTML", source)
        self.assertIn("先看启动器的可操作诊断：FastAPI、bootstrap status、desktop preflight cache、React/Vite 哪段失败", source)
        self.assertIn("desktop preflight cache one-click packet", source)
        self.assertIn("8710/5173 是否被占用", source)
        self.assertIn("重启后刷新本页；FastAPI、bootstrap、desktop preflight cache、React/Vite 变绿才继续投研", source)
        self.assertIn("联通已由 GET /health 回读；可继续看缓存和投研入口", source)
        self.assertIn("恢复回读顺序：FastAPI /health -> bootstrap status -> desktop preflight cache -> React/Vite 前端 -> 今日作战台摘要", source)
        self.assertIn("恢复回读只读取 GET /health、GET /api/bootstrap/status、GET /api/desktop/preflight-cache；不启动服务、不创建 task、不外联", source)
        self.assertIn("只读健康检查，不启动服务、不创建 task", source)
        self.assertIn("只读运行模式，不写配置、不创建 live_light task", source)
        self.assertIn("首页只展示预检 packet，不启动 FastAPI/Vite/浏览器", source)
        self.assertIn("首页只展示预检结果，不启动 FastAPI/Vite/浏览器", source)
        self.assertIn("恢复回读只看本地 GET health/bootstrap/preflight 结果", source)
        self.assertIn("如果没有变绿，继续回一键启动预检，不进入投研入口", source)
        self.assertIn("selected=${dailyCommandFrontendBackendSelectedApiBase}", source)
        self.assertIn("P0 ready：${dailyCommandFrontendBackendSelectedApiBase} 已联通，当前 React 页面已加载；可进入下一票雷达", source)
        self.assertIn("P0 check：先让 health、bootstrap status、desktop preflight cache 变绿；未 ready 不进入 P1", source)
        self.assertIn("P0 ready 只证明本地前后端联通；不代表 Tushare 已调用、DeepSeek 可用、release ready 或 14 LTG 完成。", source)
        self.assertIn("四段已通过；可进入下一票雷达", source)
        self.assertIn("先让 health / bootstrap / preflight / React 四段变绿", source)
        self.assertIn("P0 未 ready：不要进入 P1", source)
        self.assertIn("先把前三段变绿，再进入下一票雷达", source)
        self.assertIn('联通项: "P0 可继续闸门"', source)
        self.assertIn("health ok + bootstrap runtime-mode packet + desktop preflight one-click packet + current React page", source)
        self.assertIn("输入保持静默，确认按钮才触发 Tushare-first", source)
        self.assertIn("回到一键启动预检；不要进入 P1 投研入口", source)
        self.assertIn("FastAPI /health Command Center 3.0 JSON", source)
        self.assertIn("bootstrap status runtime-mode packet", source)
        self.assertIn("desktop preflight cache one-click packet", source)
        self.assertIn("React/Vite Command Center 3.0 HTML", source)
        self.assertIn("8710/5173 port occupancy guidance", source)
        self.assertIn("启动诊断来自 desktop preflight cache", source)
        self.assertIn("本地联通状态只读来自 FastAPI health 和 desktop preflight cache", source)
        self.assertIn("不会启动服务、不会写配置、不会调用 provider/model", source)
        self.assertIn("本地缓存：${dailyCommandCacheSourceLabel}", source)
        self.assertIn("Tushare 数据：${dailyCommandTushareSourceLabel}", source)
        self.assertIn("DeepSeek 解释：${dailyCommandDeepSeekSourceLabel}", source)
        self.assertIn("运行模式：${dailyCommandRuntimeModeLabel}", source)
        self.assertIn("live_light 已配置；仍需确认按钮触发 Tushare-first task", source)
        self.assertIn("待 governed executor；不随页面打开调用", source)
        self.assertIn("model_ledger 已记录；只读回放安全摘要", source)
        self.assertIn("dailyCommandExternalTriggerBoundary", source)
        self.assertIn("页面打开、搜索输入、React render 和 GET cache 不自动外联", source)
        self.assertIn("只有下一票雷达确认按钮可创建 Tushare-first POST task", source)
        self.assertIn("量化缓存降级只返回安全摘要和本地 builder 结果；首页不展开 raw failed packet、provider error、token/key 或 call_ledger。", source)
        self.assertIn("GET cache 不创建 task、不调用 Tushare/DeepSeek/GitHub、不写 cache", source)
        summary_start = source.index('title="今日作战台摘要"')
        summary_end = source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary_slice = source[summary_start:summary_end]
        self.assertNotIn("轻量实时后台任务", summary_slice)
        self.assertNotIn("待授权解释", summary_slice)
        self.assertIn("dailyCommandPendingSourceLabel", source)
        self.assertIn("dailyCommandDegradedSourceLabel", source)
        self.assertIn("待补：", source)
        self.assertIn("降级：未标记降级", source)
        self.assertNotIn("pending：", summary_slice)
        self.assertNotIn("degraded：", summary_slice)
        self.assertIn("首页 GET cache 只读；live_light 手动补证只允许创建后台 POST task", source)
        self.assertIn("不在 React 渲染中直连 Tushare 或 DeepSeek", source)
        self.assertIn("今日摘要只组织投研证据；不买卖、不下单、不改交易策略", source)
        self.assertNotIn("/api/bootstrap/provider-model-execution-request", source)
        self.assertNotIn("postBootstrapProviderModelExecutionRequest", source)

    def test_daily_command_summary_links_are_local_navigation_only(self):
        summary_start = self.source.index('title="今日作战台摘要"')
        summary_end = self.source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary = self.source[summary_start:summary_end]

        self.assertIn('aria-label="daily command primary next action"', summary)
        self.assertIn('aria-label="open daily command primary next action"', summary)
        self.assertIn('aria-label="daily command next user actions"', summary)
        self.assertIn('href="#candidates"', summary)
        self.assertIn('href="#factor"', summary)
        self.assertIn('href="#dataHealth"', summary)
        self.assertIn('href="#desktop"', summary)
        self.assertIn('href="#migration"', summary)
        self.assertIn('href="#tasks"', summary)
        self.assertIn('title="切换到下一票雷达模块；输入代码后仍需确认按钮"', summary)
        self.assertIn('title="切换到股票量化推演模块；只回放缓存结果，不创建 task"', summary)
        self.assertIn('title="切换到数据健康模块；只读 cache，不刷新外部数据源"', summary)
        self.assertIn('title="切换到桌面壳预检模块；只读恢复指引，不启动服务"', summary)
        self.assertIn('title="切换到迁移状态页；只读查看 14 LTG direct evidence 缺口"', summary)
        self.assertIn('title="切换到任务目录；只读回放 task/cache/ledger/packet 证据"', summary)
        self.assertIn("这些入口链接只切换本地页面（本地模块路由）", summary)
        self.assertIn("不会创建 task、调用 Tushare/DeepSeek/GitHub、写 cache/config 或改变交易策略", summary)
        self.assertLess(summary.index('aria-label="daily command primary next action"'), summary.index('aria-label="daily command next user actions"'))
        self.assertNotIn("onClick=", summary)
        self.assertNotIn("launchLiveBootstrap", summary)
        self.assertNotIn("postBootstrapLiveStartup", summary)

        app_source = (ROOT / "src" / "App.tsx").read_text(encoding="utf-8")
        for route_key in ('"candidates"', '"factor"', '"dataHealth"', '"desktop"', '"migration"', '"tasks"'):
            self.assertIn(route_key, app_source)
        self.assertIn("normalizeRouteKey(window.location.hash)", app_source)

    def test_engineering_metrics_are_demoted_behind_details(self):
        source = self.source

        self.assertIn('className="developer-audit-details"', source)
        self.assertIn("开发 / 审计详情", source)
        self.assertIn("详细验收记录、开发表格和排障明细默认收起", source)
        self.assertIn("dailyCommandAuditDemotionRows", source)
        self.assertIn('aria-label="daily command engineering audit demotion rules"', source)
        self.assertIn("审计入口下沉规则", source)
        self.assertIn("普通用户先看摘要和三入口；只有排障、验收或补证时展开开发详情。", source)
        self.assertIn("不展示 raw packet、call_ledger、runbook、LTG 表或 provider/model 明细", source)
        self.assertIn("默认折叠，不压过 P0 联通、P1 搜票确认、P2/P3 结果回放", source)
        self.assertIn("手动补证状态、任务状态面板和任务回执", source)
        self.assertIn("页面打开、React render 和 GET cache 不创建 task、不调用 Tushare/DeepSeek/GitHub", source)
        self.assertNotIn("工程合同、receipt、runbook、LTG audit 和 lineage 明细默认收起", source)
        self.assertIn("开发状态速览", source)
        self.assertLess(source.index("开发 / 审计详情"), source.index("开发状态速览"))
        self.assertLess(source.index("开发 / 审计详情"), source.index("审计入口下沉规则"))
        self.assertLess(source.index("审计入口下沉规则"), source.index("开发状态速览"))
        self.assertLess(source.index("今日作战台摘要"), source.index("审计入口下沉规则"))
        self.assertLess(source.index("开发状态速览"), source.index('label: "FastAPI"'))
        self.assertLess(source.index("开发状态速览"), source.index('label: "runtime mode"'))

    def test_usable_path_stage_rail_is_read_only_and_before_audit_details(self):
        source = self.source
        summary_start = source.index('title="今日作战台摘要"')
        summary_end = source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary = source[summary_start:summary_end]
        rail_start = summary.index('<div className="state-clarity-rail" aria-label="daily command usable path stage rail">')
        table_start = summary.index("<DataLineageTable rows={dailyCommandUsableShortestPathRows}")
        rail = summary[rail_start:table_start]

        self.assertIn("dailyCommandUsablePathStageRailSteps.map", rail)
        self.assertIn('className="state-clarity-rail"', rail)
        self.assertIn('className="state-clarity-step"', rail)
        self.assertIn("data-step-state={step.state}", rail)
        self.assertIn("{step.label}", rail)
        self.assertIn("{step.detail}", rail)
        self.assertLess(summary.index('aria-label="daily command usable path stage rail"'), table_start)
        self.assertNotIn("onClick=", rail)
        self.assertNotIn("postBootstrapLiveStartup", rail)
        self.assertNotIn("postTask", rail)

    def test_p6_strict_closeout_reentry_is_collapsed_read_only_audit_detail(self):
        source = self.source
        summary_start = source.index('title="今日作战台摘要"')
        summary_end = source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary = source[summary_start:summary_end]
        p6_details_label_start = summary.index('aria-label="daily command p6 strict closeout reentry details"')
        p6_details_start = summary.rindex("<details", 0, p6_details_label_start)
        p6_start = summary.index('aria-label="daily command p6 strict closeout reentry"', p6_details_start)
        p6_end = summary.index('aria-label="daily command local connection readback"', p6_start)
        p6_details = summary[p6_details_start:p6_end]
        p6 = summary[p6_start:p6_end]

        self.assertIn("dailyCommandP6StrictCloseoutReentryRows", source)
        self.assertIn('<details className="developer-audit-details" aria-label="daily command p6 strict closeout reentry details">', p6_details)
        self.assertIn("<summary>P6 / 14 LTG strict closeout 审计入口</summary>", p6_details)
        self.assertIn("普通主线先看 P0 联通、P1 确认、P2 写回和 P3 结果", p6_details)
        self.assertIn("P6 strict closeout 回归入口", p6)
        self.assertIn("P0-P5 是使用者可用化 checkpoint", p6)
        self.assertIn("current-head direct evidence", p6)
        self.assertIn("CI、浏览器、provider、worker、storage 和 package gate", p6)
        self.assertIn('href="#migration"', p6)
        self.assertIn('href="#tasks"', p6)
        self.assertLess(summary.index('aria-label="daily command usable path stage rail"'), p6_details_start)
        self.assertLess(summary.index("P6 strict closeout 回归入口"), summary.index('aria-label="daily command local connection readback"'))
        self.assertNotIn("onClick=", p6)
        self.assertNotIn("fetch(", p6)
        self.assertNotIn("postTask", p6)
        self.assertNotIn("postBootstrapLiveStartup", p6)
        self.assertNotIn("launchLiveBootstrap", p6)
        self.assertNotIn("provider-model", p6)

    def test_daily_command_summary_uses_user_facing_backfill_state_before_audit(self):
        source = self.source
        summary_start = source.index('title="今日作战台摘要"')
        summary_end = source.index("<summary>开发 / 审计详情</summary>", summary_start)
        summary = source[summary_start:summary_end]
        audit = source[summary_end:]

        self.assertIn("dailyCommandBackgroundTaskState", source)
        self.assertIn('label: "补证状态"', summary)
        self.assertNotIn('label: "后台状态"', source)
        self.assertIn("普通路径不自动补证；需要时在开发详情手动确认", source)
        self.assertIn("手动补证任务提交中；页面可继续查看缓存", source)
        self.assertIn("手动补证未完成；已回到只读查看", source)
        self.assertIn("已有本地补证任务；进度在开发详情", source)
        self.assertIn("live_light 补证入口下沉在开发详情；普通路径只看本地缓存、雷达和量化入口", summary)
        self.assertNotIn("等待手动确认按钮", source)
        self.assertNotIn("cache_only/manual 不创建后台任务", source)
        self.assertNotIn("来源关闭，未创建后台任务", source)
        self.assertNotIn("后台任务未接入", source)
        self.assertNotIn("本会话已创建过，不重复", source)
        self.assertNotIn("正在创建本地后台 task", source)
        self.assertNotIn("创建失败，已降级为只读", source)
        self.assertNotIn("liveBootstrapManualStatus", summary)
        self.assertNotIn("auto status", audit)
        self.assertIn("manual status: {liveBootstrapManualStatus}", audit)
        self.assertLess(source.index('label: "补证状态"'), source.index("<summary>开发 / 审计详情</summary>"))

    def test_live_light_bootstrap_requires_manual_button_not_page_open_autostart(self):
        source = self.source

        self.assertIn("const launchLiveBootstrap = () => {", source)
        self.assertIn('source: "command_center_home_manual"', source)
        self.assertIn("确认 live_light 本地补证 task", source)
        self.assertIn("手动确认后才会创建本地 POST task；页面打开不自动启动", source)
        self.assertIn("页面打开、搜索输入和 render 不直接创建 task", source)
        self.assertIn("Tushare / DeepSeek configured source switches", source)
        self.assertNotIn("Tushare / DeepSeek on open:", source)
        self.assertIn("liveBootstrapManualStatus", source)
        self.assertNotIn("liveBootstrapAutoStatus", source)
        self.assertNotIn('source: "command_center_home_auto"', source)
        self.assertNotIn("cache 渲染完成后才会在 live_light 模式创建一次本地 POST task", source)

    def test_daily_command_page_does_not_embed_provider_model_or_trade_calls(self):
        source = self.source
        forbidden_fragments = (
            "tushare.pro_api",
            "ts.pro_api",
            "deepseek.chat",
            "api.github.com",
            "executeTrade(",
            "placeOrder(",
            "broker.submit",
            "live_order",
        )
        for fragment in forbidden_fragments:
            self.assertNotIn(fragment, source)


if __name__ == "__main__":
    unittest.main()
