import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1] / "desktop"


class FactorQuantHubOrdinaryEntryTests(unittest.TestCase):
    def test_stock_quant_projection_summary_shows_user_decision_fields_first(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")

        self.assertIn('title="股票量化推演"', source)
        self.assertIn("普通用户量化推演摘要", source)
        self.assertIn("下一步、来源、缺口、边界和最近可用缓存", source)
        self.assertIn("ordinaryQuantUserFirstItems", source)
        self.assertIn('aria-label="stock quant ordinary user first summary"', source)
        self.assertIn("ordinaryQuantPlainConclusionItems", source)
        self.assertIn('aria-label="stock quant ordinary plain conclusion"', source)
        self.assertIn('aria-label="stock quant ordinary plain conclusion sentence"', source)
        self.assertIn('aria-label="stock quant ordinary plain conclusion actions"', source)
        self.assertIn("普通结论", source)
        self.assertIn('label: "一句话"', source)
        self.assertIn('label: "缺口"', source)
        self.assertIn('label: "现在做什么"', source)
        self.assertIn('label: "安全说明"', source)
        self.assertIn("真实数据质量、小池研究或模型解释证据还没补齐；当前结果先按本地回放阅读。", source)
        self.assertIn("先看支持/压制和完整次日图谱；需要补新结果或换标的，再回下一票雷达确认。", source)
        self.assertIn("这只是研究辅助，不是买入、卖出、加仓或减仓指令。", source)
        self.assertIn("页面打开、查看结果和切换入口都不会自动创建任务或调用外部服务", source)
        self.assertIn("一屏速读", source)
        self.assertIn("默认先看当前标的、结论、下一步、数据链、图谱/解释和边界", source)
        self.assertIn("任务记录、数据凭证、合同和回放细节继续收起在下方", source)
        self.assertIn('label: "当前标的"', source)
        self.assertIn('label: "现在看什么"', source)
        self.assertIn('label: "下一步"', source)
        self.assertIn('label: "图谱/解释"', source)
        self.assertIn('label: "边界"', source)
        self.assertIn('label: "运行模式"', source)
        self.assertIn('label: "本地缓存"', source)
        self.assertIn('label: "数据链"', source)
        self.assertIn('label: "解释状态"', source)
        self.assertIn('label: "待补证据"', source)
        self.assertIn('label: "降级提示"', source)
        self.assertIn('label: "最近成功回放"', source)
        self.assertIn('label: "雷达搜票回放"', source)
        self.assertIn('label: "上游确认链"', source)
        self.assertIn('label: "确认结果链"', source)
        self.assertIn('label: "P2 三面回放"', source)
        self.assertIn('label: "回放位置"', source)
        self.assertIn('label: "查看顺序"', source)
        self.assertIn('label: "结果组成"', source)
        self.assertIn('label: "P3 可读结论"', source)
        self.assertIn('label: "P3 下一步"', source)
        self.assertIn('label: "P3 边界"', source)
        self.assertIn('label: "数据来源状态"', source)
        self.assertIn('label: "调用记录"', source)
        self.assertIn('label: "结果包"', source)
        self.assertIn('label: "补证方式"', source)
        self.assertIn('label: "缺少证据"', source)
        self.assertIn('label: "阻断/降级"', source)
        self.assertIn('label: "最近可用缓存"', source)
        self.assertIn('label: "任务边界"', source)
        self.assertIn('label: "结果边界"', source)
        self.assertIn('label: "仅供研究"', source)
        self.assertLess(source.index("普通用户量化推演摘要"), source.index('launchTask("/api/factor-quant/run-light"'))
        self.assertLess(source.index("普通用户量化推演摘要"), source.index("高级验收任务"))
        self.assertLess(source.index("普通用户量化推演摘要"), source.index("开发 / 审计指标"))
        self.assertLess(source.index('label: "本地缓存"'), source.index("开发 / 审计指标"))
        self.assertLess(source.index('label: "最近成功回放"'), source.index("开发 / 审计指标"))
        summary_start = source.index("普通用户量化推演摘要")
        summary_end = source.index("高级验收任务", summary_start)
        summary_slice = source[summary_start:summary_end]
        self.assertIn("ordinaryQuantCompactVerticalSliceItems", source)
        self.assertIn('aria-label="stock quant compact vertical slice status"', summary_slice)
        plain_start = summary_slice.index('aria-label="stock quant ordinary plain conclusion"')
        one_screen_start = summary_slice.index("一屏速读")
        plain_end = summary_slice.index("一屏速读", plain_start)
        plain_slice = summary_slice[plain_start:plain_end]
        self.assertLess(plain_start, one_screen_start)
        self.assertIn("MetricGrid items={ordinaryQuantPlainConclusionItems}", plain_slice)
        self.assertIn('href={ordinaryQuantPrimaryActionHref}', plain_slice)
        self.assertNotIn("onClick=", plain_slice)
        self.assertNotIn("launch" + "Task", plain_slice)
        self.assertNotIn("post" + "Task(", plain_slice)
        self.assertNotIn("task、ledger", summary_slice)
        self.assertIn("当前纵切状态", summary_slice)
        self.assertIn("确认链、P2/P3、支持/压制、小池验收和缺口先给结论", summary_slice)
        for compact_label in (
            'label: "确认链"',
            'label: "P2/P3"',
            'label: "支持/压制"',
            'label: "小池验收"',
            'label: "降级/缺口"',
            'label: "边界"',
        ):
            self.assertIn(compact_label, source)
        self.assertIn("因子结果只做研究复核；不创建 provider task、不交易、不改策略", source)
        compact_start = summary_slice.index('aria-label="stock quant compact vertical slice status"')
        compact_end = summary_slice.index('aria-label="stock quant projection primary next action"', compact_start)
        compact_slice = summary_slice[compact_start:compact_end]
        self.assertLess(compact_start, summary_slice.index('aria-label="stock quant projection primary next action"'))
        self.assertNotIn("onClick=", compact_slice)
        self.assertNotIn("launch" + "Task", compact_slice)
        self.assertNotIn("post" + "Task(", compact_slice)
        self.assertIn("candidateRadarProviderApiRows", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_provider_api_rows", source)
        self.assertIn("ordinaryQuantTushareDataCardLedgerReady", source)
        self.assertIn("ordinaryQuantTushareDataCardSummary", source)
        self.assertIn("ordinaryQuantTushareDataCardGap", source)
        self.assertIn("ordinaryQuantTushareDataCardNext", source)
        self.assertIn("ordinaryQuantTushareDataCardItems", source)
        self.assertIn("ordinaryQuantTushareDataCardRows", source)
        self.assertIn('aria-label="stock quant ordinary tushare data card"', summary_slice)
        self.assertIn("确认后 Tushare 数据卡", summary_slice)
        self.assertIn('aria-label="stock quant ordinary tushare data card summary"', summary_slice)
        self.assertIn("MetricGrid items={ordinaryQuantTushareDataCardItems}", summary_slice)
        self.assertIn('aria-label="stock quant ordinary tushare data card rows"', summary_slice)
        self.assertIn("<summary>查看接口回放</summary>", summary_slice)
        self.assertIn("DataLineageTable rows={ordinaryQuantTushareDataCardRows}", summary_slice)
        for tushare_data_card_label in (
            'label: "Tushare 数据卡"',
            'label: "接口回放"',
            'label: "P2 三面"',
            'label: "P3 结论"',
            'label: "模型解释"',
            'label: "缺口"',
            'label: "下一步"',
            'label: "边界"',
        ):
            self.assertIn(tushare_data_card_label, source)
        self.assertIn("不会从 Factor 页调用 Tushare/DeepSeek、创建第二个 task 或交易", source)
        self.assertIn("没有账本时显示等待或阻断，不从 Factor 页补调数据", source)
        self.assertIn("不会调用 Tushare、DeepSeek、GitHub，不交易、不改交易策略", source)
        data_card_start = summary_slice.index('aria-label="stock quant ordinary tushare data card"')
        provider_quick_start = summary_slice.index('aria-label="stock quant provider validation ordinary quick read"')
        data_card_slice = summary_slice[data_card_start:provider_quick_start]
        self.assertLess(compact_start, data_card_start)
        self.assertLess(data_card_start, provider_quick_start)
        self.assertNotIn("onClick=", data_card_slice)
        self.assertNotIn("launch" + "Task", data_card_slice)
        self.assertNotIn("post" + "Task(", data_card_slice)
        self.assertNotIn("fetch(", data_card_slice)
        self.assertNotIn("TaskStatusPanel", data_card_slice)
        self.assertIn("ordinaryFactorTestProviderQuickReadItems", source)
        self.assertIn('aria-label="stock quant provider validation ordinary quick read"', summary_slice)
        self.assertIn("真实验证速读", summary_slice)
        self.assertIn('aria-label="stock quant provider validation quick read sentence"', summary_slice)
        for provider_quick_label in (
            'label: "真实验证"',
            'label: "授权状态"',
            'label: "缺口"',
            'label: "下一步"',
            'label: "边界"',
        ):
            self.assertIn(provider_quick_label, source)
        self.assertIn("真实小池验证必须另行授权", source)
        self.assertIn("打开页面、查看速读和切换锚点都只读本地 cache", source)
        provider_quick_start = summary_slice.index('aria-label="stock quant provider validation ordinary quick read"')
        provider_quick_end = summary_slice.index('aria-label="stock quant mode layered live light evidence boundary"', provider_quick_start)
        provider_quick_slice = summary_slice[provider_quick_start:provider_quick_end]
        self.assertLess(compact_start, provider_quick_start)
        self.assertLess(provider_quick_start, summary_slice.index('aria-label="stock quant projection primary next action"'))
        self.assertNotIn("onClick=", provider_quick_slice)
        self.assertNotIn("launch" + "Task", provider_quick_slice)
        self.assertNotIn("post" + "Task(", provider_quick_slice)
        self.assertIn("ordinaryQuantModeLayeredLiveLightItems", source)
        self.assertIn('aria-label="stock quant mode layered live light evidence boundary"', summary_slice)
        self.assertIn("运行模式分层", summary_slice)
        self.assertIn("cache/render、按钮任务、真实数据、模型解释、生产验收和交易隔离分开显示", summary_slice)
        self.assertIn("live_light 也只能是可审计 task，不是页面渲染外联", summary_slice)
        mode_layer_start = summary_slice.index('aria-label="stock quant mode layered live light evidence boundary"')
        mode_layer_end = summary_slice.index('aria-label="stock quant projection primary next action"', mode_layer_start)
        mode_layer_slice = summary_slice[mode_layer_start:mode_layer_end]
        for mode_layer_label in (
            'label: "缓存渲染层"',
            'label: "按钮任务层"',
            'label: "真实数据层"',
            'label: "模型解释层"',
            'label: "生产验收层"',
            'label: "交易隔离层"',
        ):
            self.assertIn(mode_layer_label, source)
        self.assertIn("GET cache / React render 只读；页面打开、查看结果和本地路由切换不创建 task、不外联", source)
        self.assertIn("manual 或 live_light 补证只能进入显式 POST task / worker / local fallback，本页不自启小池", source)
        self.assertIn("需要 scope hash、payload、call_ledger、样本行和 failure-mode evidence", source)
        self.assertIn("DeepSeek governed executor 单独排期；不作为数据源", source)
        self.assertIn("LTG-03 strict closeout 仍按 snapshot", source)
        self.assertIn("local ticket、dry-run、execution request、matrix 或 sanitizer 不等于 production complete", source)
        self.assertIn("Factor 分数只做研究复核；不接 broker、不创建 order endpoint", source)
        self.assertLess(summary_slice.index('aria-label="stock quant compact vertical slice status"'), mode_layer_start)
        self.assertLess(mode_layer_start, summary_slice.index('aria-label="stock quant projection primary next action"'))
        self.assertNotIn("onClick=", mode_layer_slice)
        self.assertNotIn("launch" + "Task", mode_layer_slice)
        self.assertNotIn("post" + "Task(", mode_layer_slice)
        for engineering_label in (
            'label: "cache"',
            'label: "Tushare"',
            'label: "DeepSeek"',
            'label: "pending"',
            'label: "degraded"',
            'label: "last_successful_cache/result"',
            'label: "ledger"',
            'label: "packet"',
        ):
            self.assertNotIn(engineering_label, summary_slice)
        self.assertIn("ordinaryQuantDegradedSourceLabel", source)
        self.assertIn("degraded：未标记降级", source)
        self.assertIn("DeepSeek 解释已有本地结果；只解释不改数值或动作", source)
        self.assertIn("DeepSeek 待 governed executor；普通页只读状态", source)
        self.assertIn("模型未调用或等待 governed executor", source)
        self.assertNotIn("DeepSeek 解释未生成或等待手动任务", source)
        self.assertNotIn("模型未调用或等待手动任务", source)
        self.assertIn("ordinaryQuantRadarHandoffState", source)
        self.assertIn("ordinaryQuantReplayLocation", source)
        self.assertIn("ordinaryQuantReviewOrder", source)
        self.assertIn("ordinaryQuantResultComposition", source)
        self.assertIn("ordinaryQuantGlobalTushareSourceLabel", source)
        self.assertIn("ordinaryQuantTushareFirstDataChainLabel", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_readback_stage_label", source)
        self.assertIn("candidateRadarSmallDataWriteback.summary_label", source)
        self.assertIn("return `${candidateRadarConfirmedSymbol} Tushare-first：${upstreamStage}`", source)
        self.assertIn('label: "数据链", value: ordinaryQuantTushareFirstDataChainLabel', source)
        self.assertIn("Tushare-first：${ordinaryQuantTushareFirstDataChainLabel}", source)
        self.assertLess(source.index("ordinaryQuantTushareFirstDataChainLabel"), source.index("ordinaryQuantPrimarySummaryItems"))
        self.assertIn("ordinaryQuantP3ReadableConclusion", source)
        self.assertIn("ordinaryQuantP3NextStep", source)
        self.assertIn("ordinaryQuantP3Boundary", source)
        self.assertIn("ordinaryQuantCandidateRadarP3Ready", source)
        self.assertIn("candidateRadarResultQuickRows.length > 0", source)
        self.assertIn("candidateRadarCache.ordinary_result_quick_read_rows", source)
        self.assertIn("candidateRadarCache.ordinary_result_checkpoint_rows", source)
        self.assertIn("candidateRadarCache.search_quant_projection_result_checkpoint_rows", source)
        self.assertIn("candidateRadarInterpretation.interpretation_ready === true", source)
        self.assertIn("Boolean(String(candidateRadarInterpretation.ordinary_result_summary ?? \"\").trim())", source)
        self.assertIn("P3 可读结论：${candidateRadarReadableResult}", source)
        self.assertIn("P3 下一步：${candidateRadarReadableNextStep}", source)
        self.assertIn("P3 边界：${candidateRadarReadableBoundary}", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_result_quick_read_rows / ordinary_result_checkpoint_rows", source)
        self.assertIn("candidateRadarDeepSeekStateRaw", source)
        self.assertIn("candidateRadarOrdinaryDeepSeekState", source)
        self.assertIn("candidateRadarUsesModelOutput", source)
        self.assertIn("candidateRadarCache.ordinary_result_deepseek_governed_executor_status", source)
        self.assertIn("DeepSeek 不用等：Tushare-first、支持/压制和次日图谱可先看", source)
        self.assertIn("DeepSeek 待治理：不阻塞 Tushare-first、支持/压制和次日图谱", source)
        self.assertIn('label: "模型解释"', source)
        self.assertIn('value: candidateRadarOrdinaryDeepSeekState', source)
        self.assertIn('tone: candidateRadarUsesModelOutput ? "warn" : "good"', source)
        self.assertIn("ordinaryQuantResultBoundary", source)
        self.assertIn("ordinaryQuantResultReplayRows", source)
        self.assertIn("ordinaryQuantFullNextSessionRows", source)
        self.assertIn("factorPacketCandidateHandoff", source)
        self.assertIn("factorPacketCandidateHandoffRows", source)
        self.assertIn("factorPacketP3OneScreenSummary", source)
        self.assertIn("factorPacketP3OneScreenRows", source)
        self.assertIn("packet.ordinary_quant_p3_one_screen_summary", source)
        self.assertIn("packet.ordinary_quant_p3_one_screen_items", source)
        self.assertIn("factorPacketP3OneScreenSummary.result_summary", source)
        self.assertIn("factorPacketP3OneScreenSummary.result_next_step", source)
        self.assertIn("factorPacketP3OneScreenSummary.result_boundary", source)
        self.assertIn("factorPacketP3OneScreenSummary.deepseek_governed_executor_status", source)
        self.assertIn("factorPacketP3OneScreenSummary.p3_readable_result_ready === true", source)
        self.assertIn("ordinaryQuantP3OneScreenItems", source)
        self.assertIn('aria-label="stock quant p3 one screen explanation"', source)
        self.assertIn("P3 一屏结论", source)
        self.assertIn("ordinary_quant_p3_one_screen_summary", source)
        self.assertIn("packet.candidate_radar_quant_projection_handoff", source)
        self.assertIn("packet.ordinary_quant_candidate_handoff_rows", source)
        self.assertIn("factorPacketCandidateHandoff.p3_readable_result_ready === true", source)
        self.assertIn("factorPacketCandidateHandoff.ordinary_result_summary", source)
        self.assertIn("factorPacketCandidateHandoff.ordinary_result_next_step", source)
        self.assertIn("factorPacketCandidateHandoff.ordinary_result_boundary", source)
        self.assertIn("factorPacketCandidateHandoff.deepseek_governed_executor_status", source)
        self.assertIn("getCandidateRadarCache", source)
        self.assertIn("candidateRadarSmallDataWriteback", source)
        self.assertIn("candidateRadarConfirmedSymbol", source)
        self.assertIn("packet.latest_confirmed_symbol", source)
        self.assertIn("candidateRadarCache.latest_confirmed_symbol", source)
        self.assertIn("factorPacketCandidateHandoff.symbol", source)
        self.assertIn("candidateRadarLatestTaskId", source)
        self.assertIn("packet.latest_confirmed_task_id", source)
        self.assertIn("candidateRadarCache.latest_confirmed_task_id", source)
        self.assertIn("factorPacketCandidateHandoff.source_task_id", source)
        self.assertIn("candidateRadarCache.search_quant_projection_latest_task_id", source)
        self.assertIn("candidateRadarCache.latest_task_id", source)
        self.assertIn("candidateRadarConfirmedTaskReceiptRows", source)
        self.assertIn("candidateRadarTaskReadbackRows", source)
        self.assertIn("candidateRadarCache.search_quant_projection_confirmed_task_receipt_rows", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_confirmed_task_receipt_rows", source)
        self.assertIn("candidateRadarCache.search_quant_projection_task_readback_rows", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_task_readback_rows", source)
        self.assertIn("candidateRadarLatestTaskStep", source)
        self.assertIn("packet.latest_confirmed_task_current_step", source)
        self.assertIn("candidateRadarCache.latest_confirmed_task_current_step", source)
        self.assertIn("factorPacketCandidateHandoff.source_task_current_step", source)
        self.assertIn("candidateRadarConfirmChainStatus", source)
        self.assertIn("candidateRadarSmallDataStateLabel", source)
        self.assertIn("ordinaryQuantLatestCandidateCheckpointItems", source)
        self.assertIn('aria-label="stock quant latest candidate post confirm checkpoint"', source)
        self.assertIn("确认后量化 checkpoint", source)
        self.assertIn("最近一只票的 task id、P1 确认、P2 三面和 P3 可读结论在量化页可展开复核", source)
        self.assertIn("本 checkpoint 只读 CandidateRadar cache / ledger / packet，不创建 task、不补调 Tushare/DeepSeek", source)
        self.assertIn('aria-label="stock quant readable result local actions"', source)
        self.assertIn('aria-label="open factor support suppress from readable result"', source)
        self.assertIn('aria-label="open full next session from readable result"', source)
        self.assertIn('aria-label="return candidate radar confirm input from readable result"', source)
        self.assertIn("这组入口只切换本地页面或锚点；不创建 task、不调用 Tushare/DeepSeek/GitHub、不写 cache，也不改变 strategy action。", source)
        self.assertIn('label: "确认标的"', source)
        self.assertIn('label: "任务编号"', source)
        self.assertIn('label: "P1 确认"', source)
        self.assertIn('label: "P2 三面"', source)
        self.assertIn('label: "P3 结论"', source)
        self.assertIn('label: "后端回放合同"', source)
        self.assertIn('label: "下一步"', source)
        self.assertIn('label: "边界"', source)
        self.assertIn("task_id=${candidateRadarLatestTaskId}", source)
        self.assertIn("candidateRadarSmallDataWriteback.small_data_writeback_ready === true", source)
        self.assertIn("candidateRadarReceiptCallLedger", source)
        self.assertIn("candidateRadarReceiptRequestParams", source)
        self.assertIn("ordinaryQuantPostConfirmReplayContract", source)
        self.assertIn("ordinaryQuantPostConfirmReplayContractRows", source)
        self.assertIn("ordinary_post_confirm_replay_contract", source)
        self.assertIn("CandidateRadar call_ledger safe params", source)
        self.assertIn("candidate_radar_search_quant_projection_post_confirm_replay_contract.v1", source)
        self.assertIn("等待下一票雷达确认任务回放后端合同", source)
        self.assertIn('aria-label="stock quant post confirm backend replay contract"', source)
        self.assertIn("后端回放合同", source)
        self.assertIn("量化页按同一条确认后合同回放任务、P2 三面和结果入口", source)
        self.assertIn("DataLineageTable rows={ordinaryQuantPostConfirmReplayContractRows}", source)
        self.assertIn("ordinaryQuantTaskSourceReadbackItems", source)
        self.assertIn('aria-label="stock quant p1 task source readback"', source)
        self.assertIn("P1 任务来源回放", source)
        self.assertIn("这张小表只告诉普通用户 P3 结论来自哪次确认 task", source)
        self.assertIn("MetricGrid items={ordinaryQuantTaskSourceReadbackItems}", source)
        self.assertIn("getTasks", source)
        self.assertIn("const [taskIndex, setTaskIndex] = useState<TaskStatusIndex | null>(null);", source)
        self.assertIn("taskIndex?.latest_confirmed_symbol", source)
        self.assertIn("taskIndex?.latest_confirmed_task_id", source)
        self.assertIn("taskIndex?.latest_confirmed_task_status", source)
        self.assertIn("taskIndex?.latest_confirmed_task_current_step", source)
        self.assertIn("ordinaryQuantTaskIndexProgressItems", source)
        self.assertIn('aria-label="stock quant local task index progress watch"', source)
        self.assertIn("本地任务进度", source)
        self.assertIn("GET /api/tasks + Factor cache + CandidateRadar cache", source)
        self.assertIn("任务索引回读未触发外联、未创建 task", source)
        self.assertIn("边用边看：{ordinaryQuantProgressWatchNext}", source)
        self.assertIn("这只来自 GET /api/tasks、Factor cache 和 CandidateRadar cache，不创建第二个 task", source)
        self.assertIn('label: "来源 task"', source)
        self.assertIn('label: "确认回执"', source)
        self.assertIn('label: "任务回放"', source)
        self.assertIn('label: "读取边界"', source)
        self.assertIn('label: "边用边看"', source)
        self.assertIn('label: "最新确认标的"', source)
        self.assertIn('label: "最新任务"', source)
        self.assertIn('label: "当前步骤"', source)
        self.assertIn('label: "只读来源"', source)
        self.assertIn('label: "安全边界"', source)
        self.assertIn("等待 search_quant_projection_confirmed_task_receipt_rows", source)
        self.assertIn("等待 search_quant_projection_task_readback_rows", source)
        self.assertIn('合同项: "任务回执"', source)
        self.assertIn('合同项: "回放顺序"', source)
        self.assertIn('合同项: "P2 三面"', source)
        self.assertIn('合同项: "结果入口"', source)
        self.assertIn("不会从量化页创建第二个 task", source)
        self.assertIn("React render 不补调 provider/model；GET cache 只读", source)
        self.assertIn("call_ledger 只由下一票雷达 POST task / worker 产生", source)
        self.assertIn("rows={ordinaryQuantUpstreamOneScreenRows}", source)
        self.assertIn("candidateRadarOneScreenRows", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_one_screen_action_rows", source)
        self.assertIn("candidateRadarConfirmOutcomeRows", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_confirm_outcome_rows", source)
        self.assertIn("candidateRadarWritebackSurfaceRows", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_writeback_surface_summary_rows", source)
        self.assertIn("ordinaryQuantUpstreamOneScreenRows", source)
        self.assertIn("ordinaryQuantUpstreamOneScreenLabel", source)
        self.assertIn("ordinaryQuantUpstreamConfirmOutcomeRows", source)
        self.assertIn("ordinaryQuantPrimarySummaryItems", source)
        self.assertIn("ordinaryQuantExpandedSummaryItems", source)
        self.assertIn('aria-label="stock quant ordinary summary extra details"', source)
        self.assertIn("<summary>更多量化摘要字段</summary>", source)
        self.assertIn("普通首屏只保留当前标的、结论、下一步、数据链、图谱/解释和安全边界", source)
        user_first_index = source.index('aria-label="stock quant ordinary user first summary"')
        user_first_action_index = source.index('aria-label="stock quant projection primary next action"', user_first_index)
        primary_grid_index = source.index("MetricGrid items={ordinaryQuantPrimarySummaryItems}")
        p3_one_screen_index = source.index('aria-label="stock quant p3 one screen explanation"')
        summary_extra_index = source.index('aria-label="stock quant ordinary summary extra details"')
        readable_result_index = source.index('aria-label="stock quant latest candidate readable result"')
        readable_actions_index = source.index('aria-label="stock quant readable result local actions"', readable_result_index)
        self.assertLess(user_first_index, user_first_action_index)
        self.assertLess(user_first_index, p3_one_screen_index)
        self.assertLess(user_first_index, readable_result_index)
        self.assertLess(p3_one_screen_index, summary_extra_index)
        self.assertLess(summary_extra_index, primary_grid_index)
        self.assertLess(summary_extra_index, readable_result_index)
        self.assertLess(readable_result_index, readable_actions_index)
        p3_one_screen_slice = source[p3_one_screen_index:summary_extra_index]
        self.assertIn("MetricGrid items={ordinaryQuantP3OneScreenItems}", p3_one_screen_slice)
        self.assertIn("只读本地 cache / CandidateRadar handoff", p3_one_screen_slice)
        self.assertNotIn("onClick=", p3_one_screen_slice)
        self.assertNotIn("launchTask", p3_one_screen_slice)
        self.assertNotIn("postTask(", p3_one_screen_slice)
        readable_result_end = source.index('aria-label="stock quant ordinary task provenance details"', readable_result_index)
        readable_result_slice = source[readable_result_index:readable_result_end]
        self.assertIn('href="#factor-score"', readable_result_slice)
        self.assertIn("NEXT_SESSION_CHART_HREF", source)
        self.assertIn('href={NEXT_SESSION_CHART_HREF}', readable_result_slice)
        self.assertIn('href={CANDIDATE_CONFIRM_HREF}', readable_result_slice)
        self.assertIn('aria-label="stock quant readable result source rows"', readable_result_slice)
        self.assertIn("<summary>可读结论来源明细</summary>", readable_result_slice)
        self.assertIn("默认收起，避免普通阅读从工程表开始", readable_result_slice)
        self.assertNotIn("onClick=", readable_result_slice)
        self.assertNotIn("launchTask", readable_result_slice)
        self.assertNotIn("postTask(", readable_result_slice)
        summary_extra_end = source.index("</details>", summary_extra_index)
        summary_extra_slice = source[summary_extra_index:summary_extra_end]
        expanded_items_start = source.index("const ordinaryQuantExpandedSummaryItems")
        expanded_items_end = source.index("return (", expanded_items_start)
        expanded_items_slice = source[expanded_items_start:expanded_items_end]
        self.assertIn("MetricGrid items={ordinaryQuantExpandedSummaryItems}", summary_extra_slice)
        self.assertIn('label: "运行模式"', expanded_items_slice)
        self.assertIn('label: "上游确认链"', expanded_items_slice)
        self.assertIn('label: "补证方式"', expanded_items_slice)
        self.assertIn("ordinaryQuantUpstreamConfirmOutcomeLabel", source)
        self.assertIn("ordinaryQuantSmallDataWritebackState", source)
        self.assertIn("ordinaryQuantP2WritebackBoundary", source)
        self.assertIn("ordinaryQuantUpstreamP2WritebackRows", source)
        self.assertIn("ordinaryQuantUpstreamP2WritebackLabel", source)
        self.assertIn("ordinaryDeepSeekGovernedExecutorState", source)
        self.assertIn("ordinaryDeepSeekGovernedExecutorRows", source)
        self.assertIn('aria-label="stock quant ordinary upstream one screen actions"', source)
        self.assertIn("上游确认一屏行动", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_one_screen_action_rows", source)
        self.assertIn("确认、任务、写回、结果合成量化页上游速读", source)
        self.assertIn("本页只读回放，不创建 task、不调用模型", source)
        self.assertIn('行动: "1. 确认"', source)
        self.assertIn('行动: "2. 任务"', source)
        self.assertIn('行动: "3. 写回"', source)
        self.assertIn('行动: "4. 结果"', source)
        self.assertIn('aria-label="stock quant upstream confirm outcome readback"', source)
        self.assertIn("上游确认结果速读", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_confirm_outcome_rows", source)
        self.assertIn("确认任务是否接收、P2 三面是否回放、P3 量化结果是否可读", source)
        self.assertIn("本页只读回放，不创建第二个 task", source)
        self.assertIn('确认结果: "P1 确认结果"', source)
        self.assertIn('确认结果: "P2 写回结果"', source)
        self.assertIn('确认结果: "P3 回放结果"', source)
        self.assertIn('aria-label="stock quant upstream p2 writeback quick read"', source)
        self.assertIn("P2 小数据三面写回速读", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_writeback_surface_summary_rows", source)
        self.assertIn("普通入口只看 cache、call_ledger、packet 三个写入面是否可回放", source)
        self.assertIn("Factor 页只读回放，不创建 task、不补调 Tushare/DeepSeek", source)
        self.assertIn('写入面: "cache"', source)
        self.assertIn('写入面: "call_ledger"', source)
        self.assertIn('写入面: "packet"', source)
        self.assertIn("P2 小数据只从 CandidateRadar cache / call_ledger / packet 回放", source)
        self.assertIn("Factor 页 GET cache 不创建 task、不补调 Tushare/DeepSeek、不展示 token/key 或 raw log", source)
        self.assertIn("只有下一票雷达确认按钮可创建 Tushare-first POST task；本页不提交上游 task", source)
        self.assertIn("回放入口只切换本地页面/锚点（#next 是本地模块路由，#candidates/... 直达确认输入区，#factor-* 是页内锚点）", source)
        self.assertIn("完整次日图谱入口：从量化推演摘要打开 #next/next-session-chart 图表区域", source)
        self.assertIn('aria-label="stock quant ordinary full next session handoff"', source)
        self.assertIn("完整次日图谱交接", source)
        self.assertIn("从本页打开完整次日图谱只切换 #next/next-session-chart 本地图表区域", source)
        self.assertIn('交接项: "预览状态"', source)
        self.assertIn('交接项: "完整图谱入口"', source)
        self.assertIn('交接项: "阅读顺序"', source)
        self.assertIn("预览只读本地 bridge cache；不会补调 Tushare/DeepSeek，也不会写 operation_zones", source)
        self.assertIn("完整图谱页继续按路径、参考线、操作区、缺口边界复核", source)
        self.assertIn('title="跳到本页支持/压制摘要；只读 Factor cache"', source)
        self.assertIn('title="跳到本页次日图谱预览；不刷新 provider/model"', source)
        self.assertIn('title="切换到完整次日图谱图表区域；只读本地次日图谱数据"', source)
        self.assertIn('title="跳到本页模型解释状态；DeepSeek 仍等 governed executor"', source)
        self.assertIn('title="切换到下一票雷达确认输入区；换标的仍需输入代码并确认"', source)
        self.assertIn('aria-label="stock quant ordinary explainable result replay"', source)
        self.assertIn("三段可解释结果", source)
        self.assertIn("普通结果先按支持/压制、次日图谱预览、模型解释状态阅读", source)
        self.assertIn('结果段: "支持/压制"', source)
        self.assertIn('结果段: "次日图谱预览"', source)
        self.assertIn('结果段: "模型解释状态"', source)
        self.assertIn("只读 Factor cache，不创建 task、不调用 Tushare/DeepSeek", source)
        self.assertIn("预览不改 operation_zones，不写交易动作", source)
        self.assertIn("模型解释不覆盖价格、因子、持仓、操作区或 strategy action", source)
        self.assertIn("ordinaryFactorReviewRows", source)
        self.assertIn('aria-label="stock quant ordinary factor review checklist"', source)
        self.assertIn("因子复核清单", source)
        self.assertIn("按支持、压制、冲突、缺失四类复核", source)
        self.assertIn("普通页只读本地 score cache，不重新排序、不补调 provider/model", source)
        self.assertIn('复核项: "支持"', source)
        self.assertIn('复核项: "压制"', source)
        self.assertIn('复核项: "冲突"', source)
        self.assertIn('复核项: "缺失"', source)
        self.assertIn("支持项多时仍要检查压制和缺失；不能直接当买入理由", source)
        self.assertIn("压制项明显时优先复核次日图谱和风险提示", source)
        self.assertIn("冲突存在时先回到证据来源和图谱路径，不急着推演动作", source)
        self.assertIn("缺失项多时优先看 cache / ledger / packet 和待补证据", source)
        self.assertIn("支持因子只作研究解释，不生成买入指令、不写 strategy action", source)
        self.assertIn("压制因子只提示复核方向，不生成卖出或减仓指令", source)
        self.assertIn("冲突只表示证据分歧，不重排候选、不修改交易动作", source)
        self.assertIn("缺失只提示后续补证，不从页面渲染补调 Tushare/DeepSeek", source)
        self.assertIn("等待下一票雷达搜票生成本地量化推演", source)
        self.assertIn("Factor cache / Next Session preview / DeepSeek status", source)
        self.assertIn("先看支持/压制，再看次日图谱预览，最后看模型解释状态", source)
        self.assertIn("不要从工程审计表开始", source)
        self.assertIn("支持 ${String(score.support_factors?.length ?? 0)} / 压制 ${String(score.suppress_factors?.length ?? 0)}", source)
        self.assertIn("P3 可读结论：${candidateRadarReadableResult}", source)
        self.assertIn("P3 下一步：${candidateRadarReadableNextStep}", source)
        self.assertIn("P3 边界：${candidateRadarReadableBoundary}", source)
        self.assertIn("P3 可读结论：暂无本地量化推演；先回下一票雷达确认代码", source)
        self.assertIn("P3 下一步：回下一票雷达确认输入区输入代码并点击确认；输入股票代码本身不创建 task", source)
        self.assertIn("P3 下一步：按支持/压制 -> 次日图谱预览 -> DeepSeek 状态复核；需要更新才点击按钮创建 POST task", source)
        self.assertIn("P3 边界：普通摘要只读 Factor cache、Next Session preview 和 DeepSeek status；不创建 task、不调用 Tushare/DeepSeek、不写 cache、不改 operation_zones 或 strategy action", source)
        self.assertIn("结果只用于研究复核；支持/压制、次日图谱和模型解释都不能直接变成买卖指令", source)
        self.assertIn('label: "P5 解释治理"', source)
        self.assertNotIn('label: "P5 DeepSeek"', source)
        self.assertIn('aria-label="stock quant ordinary p5 governance details"', source)
        self.assertIn("<summary>P5 解释治理单独补证状态</summary>", source)
        self.assertIn("普通主线先复核 P3 支持/压制、次日图谱预览和缺失证据；DeepSeek governed executor 状态默认收起，只作为高级补证参考。", source)
        self.assertIn('aria-label="stock quant ordinary deepseek governance"', source)
        self.assertIn("DeepSeek 单独治理状态", source)
        self.assertIn("DeepSeek 解释单独补证；不阻塞 Tushare-first、支持/压制和次日图谱；普通页不展示 prompt/output。", source)
        self.assertIn('治理段: "基础结果先行"', source)
        self.assertIn('治理段: "P5 governed executor 准入"', source)
        self.assertIn('治理段: "真实调用门槛"', source)
        self.assertIn('治理段: "普通页降噪"', source)
        self.assertIn('治理段: "输出约束"', source)
        self.assertIn("等待 governed executor；不阻塞 Tushare-first、支持/压制和次日图谱", source)
        self.assertIn("当前只允许本地 prompt preview / sanitizer / cache ledger；真实模型调用仍待 governed executor", source)
        self.assertIn('validation=${String(deepseekValidation.validation_mode ?? "local_sanitizer_only")}', source)
        self.assertIn('model_call=${String(deepseekValidation.model_call_status ?? "not_called")}', source)
        self.assertIn("P5 不阻塞 Tushare-first、Factor cache 或 Next Session", source)
        self.assertIn("真实调用只能在 governed executor 完成后进入受控按钮任务", source)
        self.assertIn("prompt/output 和模型调用明细留在高级审计", source)
        self.assertIn("普通页不展示 prompt/output，只显示是否 skipped/pending/ready", source)
        self.assertIn("结构化输出、重试修复、样本验收和成本证据未齐前不自动调用", source)
        self.assertIn("不把本地预检、票据或矩阵当成生产证据", source)
        self.assertIn("模型解释只辅助阅读，不覆盖价格、factor、持仓、operation_zones 或 strategy action", source)
        self.assertIn("不把空结果当成无风险", source)
        self.assertIn("不从本页补调 provider/model", source)
        self.assertIn("本页链接不重新触发 Tushare-first 或 DeepSeek", source)
        app_source = (ROOT / "src" / "App.tsx").read_text(encoding="utf-8")
        for route_key in ('"next"', '"candidates"', '"factor"'):
            self.assertIn(route_key, app_source)
        self.assertIn("normalizeRouteKey(window.location.hash)", app_source)
        self.assertLess(source.index('label: "查看顺序"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "结果组成"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "P3 可读结论"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "P3 边界"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "结果边界"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "雷达搜票回放"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "上游确认链"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "确认结果链"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "P2 三面回放"'), source.index("高级验收任务"))
        provenance_start = source.index('aria-label="stock quant ordinary task provenance details"')
        provenance_end = source.index('aria-label="stock quant ordinary expanded replay details"', provenance_start)
        checkpoint_start = source.index('aria-label="stock quant latest candidate post confirm checkpoint"', provenance_start)
        checkpoint_slice = source[provenance_start:provenance_end]
        self.assertIn("<summary>任务来源和回放细节</summary>", checkpoint_slice)
        self.assertIn("task id、P1 确认、P2 三面、任务索引和后端回放合同默认收起", checkpoint_slice)
        self.assertLess(source.index('aria-label="stock quant latest candidate readable result"'), provenance_start)
        self.assertLess(provenance_start, checkpoint_start)
        self.assertLess(source.index('aria-label="stock quant latest candidate post confirm checkpoint"'), source.index("开发 / 审计指标"))
        self.assertIn("MetricGrid items={ordinaryQuantLatestCandidateCheckpointItems}", checkpoint_slice)
        self.assertIn('aria-label="stock quant local task index progress watch"', checkpoint_slice)
        self.assertIn("MetricGrid items={ordinaryQuantTaskIndexProgressItems}", checkpoint_slice)
        self.assertIn('aria-label="stock quant p1 task source readback"', checkpoint_slice)
        self.assertIn("MetricGrid items={ordinaryQuantTaskSourceReadbackItems}", checkpoint_slice)
        self.assertIn('aria-label="stock quant post confirm backend replay contract"', checkpoint_slice)
        self.assertIn("DataLineageTable rows={ordinaryQuantPostConfirmReplayContractRows}", checkpoint_slice)
        self.assertLess(
            source.index('aria-label="stock quant latest candidate post confirm checkpoint"'),
            source.index('aria-label="stock quant local task index progress watch"'),
        )
        self.assertLess(
            source.index('aria-label="stock quant local task index progress watch"'),
            source.index('aria-label="stock quant p1 task source readback"'),
        )
        self.assertNotIn("onClick=", checkpoint_slice)
        self.assertNotIn("launch" + "Task", checkpoint_slice)
        self.assertNotIn("post" + "Task(", checkpoint_slice)
        self.assertIn('aria-label="stock quant ordinary expanded replay details"', source)
        self.assertIn("<summary>更多量化回放明细</summary>", source)
        self.assertIn("普通主视图保留一屏速读、P3 可读结论和下一步入口", source)
        expanded_details_start = source.index('aria-label="stock quant ordinary expanded replay details"')
        expanded_details_end = source.index("</details>", expanded_details_start)
        expanded_details_slice = source[expanded_details_start:expanded_details_end]
        self.assertLess(source.index('aria-label="stock quant latest candidate readable result"'), expanded_details_start)
        self.assertLess(expanded_details_start, source.index('aria-label="stock quant ordinary p5 governance details"'))
        self.assertIn('aria-label="stock quant ordinary upstream one screen actions"', expanded_details_slice)
        self.assertIn('aria-label="stock quant upstream p2 writeback quick read"', expanded_details_slice)
        self.assertIn('aria-label="stock quant ordinary explainable result replay"', expanded_details_slice)
        self.assertIn('aria-label="stock quant ordinary factor review checklist"', expanded_details_slice)
        self.assertNotIn("onClick=", expanded_details_slice)
        self.assertNotIn("launch" + "Task", expanded_details_slice)
        self.assertNotIn("post" + "Task(", expanded_details_slice)
        self.assertLess(source.index("上游确认一屏行动"), source.index("三段可解释结果"))
        self.assertLess(source.index("上游确认一屏行动"), source.index("上游确认结果速读"))
        self.assertLess(source.index("上游确认结果速读"), source.index("三段可解释结果"))
        confirm_outcome_start = source.index('aria-label="stock quant upstream confirm outcome readback"')
        confirm_outcome_end = source.index('aria-label="stock quant upstream p2 writeback quick read"', confirm_outcome_start)
        confirm_outcome_slice = source[confirm_outcome_start:confirm_outcome_end]
        self.assertNotIn("onClick=", confirm_outcome_slice)
        self.assertNotIn("launch" + "Task", confirm_outcome_slice)
        self.assertNotIn("post" + "Task(", confirm_outcome_slice)
        p2_writeback_start = source.index('aria-label="stock quant upstream p2 writeback quick read"')
        p2_writeback_end = source.index('aria-label="stock quant ordinary cache ledger packet handoff"', p2_writeback_start)
        p2_writeback_slice = source[p2_writeback_start:p2_writeback_end]
        self.assertNotIn("onClick=", p2_writeback_slice)
        self.assertNotIn("launch" + "Task", p2_writeback_slice)
        self.assertNotIn("post" + "Task(", p2_writeback_slice)
        self.assertLess(source.index("上游确认一屏行动"), source.index("高级验收任务"))
        self.assertLess(source.index("上游确认一屏行动"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("上游确认结果速读"), source.index("高级验收任务"))
        self.assertLess(source.index("上游确认结果速读"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("P2 小数据三面写回速读"), source.index("高级验收任务"))
        self.assertLess(source.index("P2 小数据三面写回速读"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("上游确认结果速读"), source.index("P2 小数据三面写回速读"))
        self.assertLess(source.index("P2 小数据三面写回速读"), source.index("三段可解释结果"))
        self.assertLess(source.index("三段可解释结果"), source.index("高级验收任务"))
        self.assertLess(source.index("三段可解释结果"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("三段可解释结果"), source.index("完整次日图谱交接"))
        self.assertLess(source.index("完整次日图谱交接"), source.index("因子复核清单"))
        self.assertLess(source.index("三段可解释结果"), source.index("因子复核清单"))
        self.assertLess(source.index("因子复核清单"), source.index('aria-label="stock quant ordinary p5 governance details"'))
        self.assertLess(source.index('aria-label="stock quant ordinary p5 governance details"'), source.index("DeepSeek 单独治理状态"))
        self.assertLess(source.index('aria-label="stock quant ordinary p5 governance details"'), source.index("模型解释 / 高级开关"))
        self.assertLess(source.index("因子复核清单"), source.index("高级验收任务"))
        self.assertLess(source.index("因子复核清单"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("DeepSeek 单独治理状态"), source.index("模型解释 / 高级开关"))
        self.assertLess(source.index("DeepSeek 单独治理状态"), source.index("DeepSeek 解释治理审计"))
        self.assertIn("ordinaryFactorTestProviderSmallPoolItems", source)
        self.assertIn('aria-label="stock quant ordinary factor test provider small pool status"', source)
        self.assertIn("LTG-03 真实小池验收", source)
        self.assertIn("普通页先说明真实小池验收是否已经运行、下一步是否需要授权、哪些证据仍缺", source)
        self.assertIn("当前只读本地 cache 和历史 ticket", source)
        self.assertIn("不从页面渲染或查看结果创建 provider 任务", source)
        self.assertIn('label: "LTG-03"', source)
        self.assertIn('label: "本地样本"', source)
        self.assertIn('label: "真实验收"', source)
        self.assertIn('label: "本地 scope"', source)
        self.assertIn('label: "授权前置"', source)
        self.assertIn('label: "还缺"', source)
        self.assertIn("真实小池验收已有直接证据", source)
        self.assertIn("真实小池验收未运行；等待授权", source)
        self.assertIn("本地执行请求已绑定 scope；下一步只能是用户授权后的 provider task", source)
        self.assertIn("还缺真实 provider task、样本行、rolling IC/ICIR、成本、中性化、PIT/bias 和 promotion review", source)
        self.assertIn("本卡只读 Factor cache；不触发 dry-run、execution request 或 provider task；真实小池验收只能在用户明确授权后走 POST task", source)
        self.assertIn("本地 light observations、本地 scope 或执行请求都不能当作生产级 Factor Test 验收完成", source)
        self.assertIn("ordinaryFactorTestProductionStageItems", source)
        self.assertIn("factorTestProductionStageScopeManifest", source)
        self.assertIn("factorTestProductionStageScopeRows", source)
        self.assertIn('aria-label="stock quant ordinary factor test production stage scope"', source)
        self.assertIn("LTG-03 生产阶段清单", source)
        self.assertIn("普通页直接显示 factor_test_production_stage_scope_manifest", source)
        self.assertIn("本地可见阶段、provider 直接证据和仍待补的生产阶段分开看", source)
        self.assertIn('label: "生产阶段"', source)
        self.assertIn('label: "本地可见"', source)
        self.assertIn('label: "直接证据"', source)
        self.assertIn("真实 provider evidence；生产完成前必须补真实 provider task、ledger 和样本行", source)
        self.assertIn("生产完成前必须补真实 provider task、ledger 和样本行", source)
        self.assertIn("factor_test_production_stage_scope_manifest 只展示 direct evidence / pending 缺口", source)
        self.assertIn('aria-label="stock quant ordinary factor test production stage rows"', source)
        self.assertIn("不调用 Tushare/DeepSeek/GitHub、不计算生产 IC/Rank IC/ICIR、不进入 strategy action", source)
        small_pool_start = source.index('aria-label="stock quant ordinary factor test provider small pool status"')
        small_pool_end = source.index('aria-label="stock quant ordinary summary extra details"', small_pool_start)
        small_pool_slice = source[small_pool_start:small_pool_end]
        self.assertIn("MetricGrid items={ordinaryFactorTestProviderSmallPoolItems}", small_pool_slice)
        self.assertIn("MetricGrid items={ordinaryFactorTestProductionStageItems}", small_pool_slice)
        self.assertIn("DataLineageTable rows={factorTestProductionStageScopeRows}", small_pool_slice)
        self.assertNotIn("onClick=", small_pool_slice)
        self.assertNotIn("launch" + "Task", small_pool_slice)
        self.assertNotIn("post" + "Task(", small_pool_slice)
        self.assertNotIn("provider-backed 小池验证已完成", small_pool_slice)
        self.assertNotIn("真实 provider 小池验证未完成", small_pool_slice)
        self.assertNotIn("真实 Tushare 小池必须另行授权 POST task", small_pool_slice)
        self.assertLess(source.index("LTG-03 真实小池验收"), source.index("高级验收任务"))
        self.assertLess(source.index("LTG-03 真实小池验收"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("LTG-03 生产阶段清单"), source.index("高级验收任务"))
        self.assertLess(source.index("LTG-03 生产阶段清单"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("P2/P3 接通和下一步"), source.index("LTG-03 真实小池验收"))
        self.assertLess(source.index("LTG-03 真实小池验收"), source.index("LTG-03 生产阶段清单"))

    def test_stock_quant_task_index_progress_watch_is_read_only(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")
        watch_start = source.index('aria-label="stock quant local task index progress watch"')
        watch_end = source.index('aria-label="stock quant p1 task source readback"', watch_start)
        watch = source[watch_start:watch_end]

        self.assertIn("本地任务进度", watch)
        self.assertIn("ordinaryQuantTaskIndexProgressItems", watch)
        self.assertIn("GET /api/tasks + Factor cache + CandidateRadar cache", source)
        self.assertIn("taskIndexReadbackSafe", source)
        self.assertIn("taskIndex.external_calls_triggered !== true", source)
        self.assertIn("taskIndex.latest_confirmed_symbol_creates_task_from_readback !== true", source)
        self.assertIn('aria-label="stock quant local task index progress actions"', watch)
        self.assertIn('href="#tasks"', watch)
        self.assertIn('href="#factor-score"', watch)
        self.assertIn('href={NEXT_SESSION_CHART_HREF}', watch)
        self.assertIn("这只来自 GET /api/tasks、Factor cache 和 CandidateRadar cache", watch)
        self.assertIn("不创建第二个 task、不补调 Tushare/DeepSeek、不真实交易", watch)
        self.assertNotIn("onClick=", watch)
        self.assertNotIn("launch" + "Task", watch)
        self.assertNotIn("post" + "Task(", watch)

    def test_stock_quant_projection_explains_evidence_task_mode(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")

        self.assertIn("ordinaryQuantEvidenceTaskState", source)
        self.assertIn("等待本地缓存后再确认补证方式", source)
        self.assertIn("cache_only 只读查看，不创建补证任务", source)
        self.assertIn("manual 只允许用户按钮创建 POST task", source)
        self.assertIn("live_light 可由后台 task 补证；本页仍只读轮询缓存", source)
        self.assertIn("live_full 深度补证预留，默认关闭", source)
        self.assertIn("ordinaryQuantCacheButtonLabel", source)
        self.assertIn("ordinaryQuantRefreshButtonLabel", source)
        self.assertIn("ordinaryQuantRunLightButtonLabel", source)
        self.assertIn("查看本地缓存只读取 GET cache；不会创建 task、不会调用 Tushare 或 DeepSeek", source)
        self.assertIn("手动刷新数据会创建按钮门控 POST task；不从 React render 直连 provider/model", source)
        self.assertIn("运行轻量推演会创建按钮门控 POST task；DeepSeek 整理仍在高级开关", source)
        self.assertIn("title={ordinaryQuantCacheButtonLabel}", source)
        self.assertIn("title={ordinaryQuantRefreshButtonLabel}", source)
        self.assertIn("title={ordinaryQuantRunLightButtonLabel}", source)
        self.assertLess(source.index('label: "补证方式"'), source.index("高级验收任务"))

    def test_stock_quant_projection_reads_mode_without_bootstrap_task_launcher(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")

        self.assertIn("getBootstrapStatus", source)
        self.assertIn("refreshBootstrapStatus", source)
        self.assertIn("runtimeModeLabel", source)
        self.assertIn("cache_only（只读缓存，不外联）", source)
        self.assertIn("manual（仅手动按钮任务）", source)
        self.assertIn("live_light（轻量后台 task 口径，仍不在渲染中外联）", source)
        self.assertIn("live_full（预留，默认关闭）", source)
        self.assertIn("本页 GET cache 只读；手动刷新、轻量推演、模型整理或 live_light 补证都必须走 POST task", source)
        self.assertNotIn("postBootstrapLiveStartup", source)
        self.assertNotIn("/api/bootstrap/live-startup", source)
        self.assertNotIn("postBootstrapProviderModelExecutionRequest", source)
        self.assertNotIn("/api/bootstrap/provider-model-execution-request", source)

    def test_engineering_details_are_demoted_behind_details_blocks(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")

        self.assertIn('className="developer-audit-details"', source)
        self.assertIn("高级验收任务", source)
        self.assertIn("开发 / 审计指标", source)
        self.assertIn("评分图表 lineage 审计", source)
        self.assertIn("DeepSeek 解释治理审计", source)
        self.assertIn("最近任务回执", source)
        self.assertIn("Provider、model、receipt、runbook、QA blocker 和 LTG 细项默认收起", source)
        self.assertIn("普通路径只保留查看缓存、手动刷新和轻量推演", source)
        self.assertIn("模型解释 / 高级开关", source)
        self.assertIn("DeepSeek governed executor 单独补", source)
        self.assertIn('aria-label="stock quant ordinary p5 governance details"', source)
        self.assertIn("<summary>P5 解释治理单独补证状态</summary>", source)
        self.assertLess(source.index("DeepSeek 单独治理状态"), source.index("模型解释 / 高级开关"))
        self.assertLess(source.index("普通路径只保留查看缓存、手动刷新和轻量推演"), source.index("模型解释 / 高级开关"))
        self.assertLess(source.index("模型解释 / 高级开关"), source.index("整理模型解释</button>"))
        self.assertLess(source.index("模型解释 / 高级开关"), source.index("轻量推演完成后自动整理解释"))
        model_switch_start = source.index("模型解释 / 高级开关")
        model_switch_end = source.index("</details>", model_switch_start)
        model_switch_slice = source[model_switch_start:model_switch_end]
        self.assertIn("模型解释默认手动触发", model_switch_slice)
        self.assertIn("勾选自动整理后，轻量推演完成可继续整理解释", model_switch_slice)
        advanced_tasks_start = source.index("高级验收任务")
        self.assertNotIn(
            "模型解释默认手动触发",
            source[model_switch_end:advanced_tasks_start],
        )
        ordinary_actions_start = source.rindex(
            '<div className="actions">',
            0,
            source.index("title={ordinaryQuantCacheButtonLabel}"),
        )
        ordinary_actions_end = source.index("</div>", ordinary_actions_start)
        ordinary_actions_slice = source[ordinary_actions_start:ordinary_actions_end]
        self.assertNotIn("整理模型解释", ordinary_actions_slice)
        self.assertNotIn("轻量推演完成后自动整理解释", ordinary_actions_slice)
        self.assertLess(source.index("最近任务回执"), source.index("<TaskLaunchReceipt receipt={taskReceipt} />"))
        self.assertLess(source.index("最近任务回执"), source.index("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />"))
        self.assertLess(source.index("普通用户量化推演摘要"), source.index("最近任务回执"))
        self.assertLess(source.index("开发 / 审计指标"), source.index('label: "provider blockers"'))
        self.assertLess(source.index("评分图表 lineage 审计"), source.index("评分图表数据合同"))
        self.assertLess(source.index("DeepSeek 解释"), source.index("DeepSeek 解释治理审计"))

    def test_stock_quant_projection_page_does_not_embed_provider_model_or_trade_calls(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")
        forbidden_fragments = (
            "tushare.pro_api",
            "ts.pro_api",
            "deepseek.chat",
            "api.github.com",
            "executeTrade(",
            "placeOrder(",
            "broker.submit",
            "live_order",
        )
        for fragment in forbidden_fragments:
            self.assertNotIn(fragment, source)


if __name__ == "__main__":
    unittest.main()
