import unittest
from pathlib import Path


class CandidateRadarP1ProviderButtonTests(unittest.TestCase):
    def test_provider_acceptance_button_is_explicit_tushare_first_after_execution_request(self):
        root = Path(__file__).resolve().parents[1]
        source = (
            root / "desktop" / "src" / "routes" / "CandidateRadar.tsx"
        ).read_text(encoding="utf-8")

        submit_start = source.index("const launchQuantProjection = () =>")
        submit_end = source.index("const launchQuantProjectionAcceptanceDryRun = () =>", submit_start)
        submit_slice = source[submit_start:submit_end]
        provider_start = source.index("const launchQuantProjectionProviderModelAcceptance = () =>")
        provider_end = source.index("const launchWorkerExecutionRequest = () =>", provider_start)
        provider_slice = source[provider_start:provider_end]
        execution_request_start = source.index("search_quant_projection_execution_request_receipt")
        execution_request_slice = source[execution_request_start:source.index("<DataLineageTable rows={objectRow(searchQuantProjectionExecutionRequest)}", execution_request_start)]
        radar_summary_start = source.index('title="普通用户雷达摘要"')
        radar_summary_slice = source[radar_summary_start:source.index('title="下一票候选池"', radar_summary_start)]
        ordinary_quant_start = source.index('title="搜票量化推演"')
        ordinary_quant_slice = source[ordinary_quant_start:source.index('<details className="developer-audit-details">', ordinary_quant_start)]

        self.assertIn("postCandidateRadarQuantProjectionProviderModelAcceptance", source)
        self.assertIn('scan_mode: "quant_projection_provider_model_acceptance"', provider_slice)
        self.assertIn("operator_approved: true", provider_slice)
        self.assertIn("acceptance_scope_hash: String(searchQuantProjectionExecutionRequest.acceptance_scope_hash ?? \"\")", provider_slice)
        self.assertIn("include_deepseek: false", provider_slice)
        self.assertIn('requested_by: "candidate_radar_page"', provider_slice)
        self.assertIn("确认 Tushare-first 补证", execution_request_slice)
        self.assertIn("disabled={!searchQuantProjectionExecutionRequest.acceptance_scope_hash}", execution_request_slice)
        self.assertIn("POST task 触发 Tushare light provider ledger", execution_request_slice)
        self.assertIn("DeepSeek 保持 skipped", execution_request_slice)
        self.assertIn("不交易、不改 strategy action", execution_request_slice)
        self.assertIn("点击后本区域会显示任务创建记录和状态", execution_request_slice)
        self.assertIn("成功后自动刷新本地 cache", execution_request_slice)
        self.assertIn("search_quant_provider_model_acceptance_receipt / call_ledger / packet", execution_request_slice)
        self.assertIn("不在 React render 里补调 provider", execution_request_slice)
        self.assertIn("<TaskLaunchReceipt receipt={taskReceipt} />", execution_request_slice)
        self.assertIn("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />", execution_request_slice)
        self.assertIn("quantProjectionTushareFirstState", ordinary_quant_slice)
        self.assertIn("quantProjectionSubmitting", ordinary_quant_slice)
        self.assertIn("quantProjectionSubmitError", ordinary_quant_slice)
        self.assertIn("quantProjectionSubmitErrorLabel", ordinary_quant_slice)
        self.assertIn("quantProjectionSubmitFailureMessage", source)
        self.assertIn("quantProjectionP1ConfirmGateRows", source)
        self.assertIn('aria-label="quant projection p1 confirm gate checklist"', ordinary_quant_slice)
        self.assertIn("P1 确认门控清单", ordinary_quant_slice)
        self.assertIn("先看代码是否通过本地校验，再点击一次确认按钮", ordinary_quant_slice)
        self.assertIn("失败先回 P0 联通恢复", ordinary_quant_slice)
        self.assertIn("这张表只读页面状态，不创建 task", ordinary_quant_slice)
        self.assertIn('门控项: "1. 输入代码"', source)
        self.assertIn('门控项: "2. 确认按钮"', source)
        self.assertIn('门控项: "3. 任务接收"', source)
        self.assertIn('门控项: "4. 回放结果"', source)
        self.assertIn("允许动作: \"按钮门控 POST /api/candidate-radar/quant-projection\"", source)
        self.assertIn("只有确认按钮可创建 Tushare-first task；DeepSeek skipped，不交易", source)
        self.assertIn("轮询本地 FastAPI 任务状态；不补调 provider/model，不写交易动作", source)
        self.assertIn("cache / ledger / packet 回放不创建第二个 task，不覆盖 strategy action", source)
        self.assertLess(
            ordinary_quant_slice.index('aria-label="quant projection p1 confirm gate checklist"'),
            ordinary_quant_slice.index('label: "确认状态"'),
        )
        self.assertIn("quantProjectionCanLaunch", ordinary_quant_slice)
        self.assertIn("任务提交中：正在创建 Tushare-first POST task", source)
        self.assertIn("正在提交 Tushare-first 后台任务；请等待本地 task id", source)
        self.assertIn("确认任务正在提交：按钮已暂时禁用", source)
        self.assertIn("确认任务创建失败：未生成 task id", source)
        self.assertIn("页面不会补调 provider/model", source)
        self.assertIn("确认任务创建失败：${quantProjectionSubmitError}", source)
        self.assertIn("本地 FastAPI 后端未连接；请先用一键启动器恢复连接。", source)
        self.assertIn("本地任务接口返回失败；请稍后重试或查看系统健康页。", source)
        self.assertIn("quantProjectionSubmitAriaLabel", source)
        self.assertIn("quantProjectionInputBoundaryLabel", source)
        self.assertIn("quantProjectionSubmitButtonLabel", source)
        self.assertIn("title={quantProjectionInputBoundaryLabel}", ordinary_quant_slice)
        self.assertIn("title={quantProjectionSubmitButtonLabel}", ordinary_quant_slice)
        self.assertIn("aria-label={quantProjectionSubmitAriaLabel}", ordinary_quant_slice)
        self.assertIn("disabled={quantProjectionSubmitDisabled}", radar_summary_slice)
        self.assertIn('{quantProjectionSubmitting ? "提交中..." : "确认并生成 3.0 量化推演"}', radar_summary_slice)
        self.assertIn("disabled={quantProjectionSubmitDisabled}", ordinary_quant_slice)
        self.assertIn('{quantProjectionSubmitting ? "提交中..." : "确认并生成 3.0 量化推演"}', ordinary_quant_slice)
        self.assertIn("点击确认才创建 ${quantProjectionSymbolValidation.normalized} 的 Tushare-first POST task；DeepSeek skipped，成功后通过 GET cache 回放", source)
        self.assertIn("按钮不可用原因：先输入股票代码；输入本身不会创建 task", source)
        self.assertIn("search_quant_projection_small_data_writeback_summary", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.summary_label", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_summary", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_next_step", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_boundary", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_stage_label", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_provenance_summary", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_readback_rows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_writeback_action_rows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_writeback_surface_summary_rows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_provider_api_rows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_tushare_first_chain_rows", source)
        self.assertIn("quantProjectionTushareFirstChainRows", source)
        self.assertIn("const quantProjectionConfirmHandoffRows = quantProjectionTushareFirstChainRows.length ? quantProjectionTushareFirstChainRows", source)
        self.assertIn("优先读取服务端 ordinary_tushare_first_chain_rows", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataOrdinaryReadbackRows", source)
        self.assertIn("quantProjectionSmallDataActionRows", source)
        self.assertIn("quantProjectionWritebackSurfaceSummaryRows", source)
        self.assertIn("quantProjectionWritebackSurfaceRows", source)
        self.assertIn("quantProjectionWritebackIntegrityPacketRows", source)
        self.assertIn("quantProjectionWritebackIntegrityRows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_writeback_integrity_rows", source)
        self.assertIn("quantProjectionSmallDataRows.map", source)
        self.assertIn("写入位置: displayText(row.surface)", source)
        self.assertIn("当前状态: displayText(row.ordinary_label ?? row.status)", source)
        self.assertIn("行动: displayText(row[\"行动\"] ?? row.action_key)", source)
        self.assertIn("用户下一步: displayText(row[\"用户下一步\"] ?? row.next_action, quantProjectionSmallDataNextStep)", source)
        self.assertIn("写入面: displayText(row[\"写入面\"] ?? row.surface)", source)
        self.assertIn("回放来源: displayText(row[\"回放来源\"] ?? row.readback_source, \"GET /api/candidate-radar/cache\")", source)
        self.assertIn("是否齐备: displayText(row[\"是否齐备\"] ?? row.integrity_state)", source)
        self.assertIn("GET cache 只读回放；React render 不补调 provider/model", source)
        self.assertIn('aria-label="quant projection ordinary small data writeback targets"', ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary p2 writeback integrity"', ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary writeback surface summary"', ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary small data writeback actions"', ordinary_quant_slice)
        self.assertIn("P2 三面完整性检查", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_writeback_integrity_rows", ordinary_quant_slice)
        self.assertIn("普通用户只看 cache、call_ledger、packet 三面是否齐备", ordinary_quant_slice)
        self.assertIn("这张表只读回放，不创建 task", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionWritebackIntegrityRows}", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_writeback_surface_summary_rows", ordinary_quant_slice)
        self.assertIn("普通入口只看 cache、call_ledger、packet 三个写入面是否可回放", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionWritebackSurfaceRows}", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_writeback_action_rows", ordinary_quant_slice)
        self.assertIn("不会从回放行创建 task", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionSmallDataActionRows}", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionSmallDataWritebackRows}", ordinary_quant_slice)
        self.assertLess(
            ordinary_quant_slice.index('aria-label="quant projection ordinary p2 writeback integrity"'),
            ordinary_quant_slice.index('aria-label="quant projection ordinary writeback surface summary"'),
        )
        self.assertIn("quantProjectionSmallDataStageLabel", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataProvenance", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataRows", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionSmallDataRows}", ordinary_quant_slice)
        self.assertIn("quantProjectionProviderApiRows", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionProviderApiRows}", ordinary_quant_slice)
        self.assertIn("Tushare light 接口回放", ordinary_quant_slice)
        self.assertIn("trade_cal / daily / daily_basic / moneyflow", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataReady", ordinary_quant_slice)
        self.assertIn("quantProjectionSmallDataNextStep", ordinary_quant_slice)
        self.assertIn('label: "小数据回放"', ordinary_quant_slice)
        self.assertIn('label: "小数据下一步"', ordinary_quant_slice)
        self.assertIn("当前读回来自 GET cache 的本地 packet", source)
        self.assertIn("search_quant_projection_interpretation_summary", source)
        self.assertIn("quantProjectionInterpretationState", ordinary_quant_slice)
        self.assertIn("ordinaryResultSurfaceLabel", source)
        self.assertIn("quantProjectionOrdinaryResultReadbackRows", source)
        self.assertIn("quantProjectionOrdinaryResultQuickReadRows", source)
        self.assertIn("quantProjectionOrdinaryResultQuickRows", source)
        self.assertIn("quantProjectionModelGovernanceRows", source)
        self.assertIn("quantProjectionDeepSeekGovernanceRows", source)
        self.assertIn("quantProjectionOrdinaryResultActionRows", source)
        self.assertIn("ordinary_result_action_rows", source)
        self.assertIn("ordinary_result_quick_read_rows", source)
        self.assertIn("ordinary_model_governance_rows", source)
        self.assertIn("ordinaryResultSurfaceLabel(row.surface)", source)
        self.assertIn("当前状态: displayText(row.ordinary_label ?? row.status)", source)
        self.assertIn("来源: displayText(row.readback_source, \"cache / ledger / packet\")", source)
        self.assertIn("边界: displayText(row.boundary, quantProjectionOrdinaryResultBoundary)", source)
        self.assertIn("结论: displayText(row[\"结论\"] ?? row.quick_read_item)", source)
        self.assertIn("证据: displayText(row[\"证据\"] ?? row.evidence, quantProjectionOrdinaryResultEvidence)", source)
        self.assertIn("数据来源", ordinary_quant_slice)
        self.assertIn("量化推演", ordinary_quant_slice)
        self.assertIn("次日图谱", ordinary_quant_slice)
        self.assertIn("安全边界", ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary explainable result quick read"', ordinary_quant_slice)
        self.assertIn("P3 结果速读", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_result_quick_read_rows", ordinary_quant_slice)
        self.assertIn("不会从结果速读创建 task 或调用模型", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionOrdinaryResultQuickRows}", ordinary_quant_slice)
        self.assertIn('aria-label="quant projection ordinary deepseek governance status"', ordinary_quant_slice)
        self.assertIn("P5 DeepSeek 治理状态", ordinary_quant_slice)
        self.assertIn("优先读取服务端 ordinary_model_governance_rows", ordinary_quant_slice)
        self.assertIn("不会从治理状态创建 task 或调用模型", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionDeepSeekGovernanceRows}", ordinary_quant_slice)
        self.assertIn("治理项: displayText(row[\"治理项\"] ?? row.governance_item)", source)
        self.assertIn("rows={quantProjectionOrdinaryResultRows}", ordinary_quant_slice)
        self.assertIn("可解释结果行动", ordinary_quant_slice)
        self.assertIn("rows={quantProjectionOrdinaryResultActionRows}", ordinary_quant_slice)
        self.assertIn("读可读结论、回放量化推演、打开次日图谱", ordinary_quant_slice)
        self.assertIn(
            '<details className="developer-audit-details" aria-label="quant projection task cache packet readback">',
            ordinary_quant_slice,
        )
        self.assertIn("<summary>任务 / cache packet 回放详情</summary>", ordinary_quant_slice)
        self.assertIn("普通入口只保留任务状态轨和结果速读", ordinary_quant_slice)
        self.assertIn('label: "解释结果"', ordinary_quant_slice)
        self.assertIn('label: "解释下一步"', ordinary_quant_slice)
        self.assertNotIn("确认 Tushare-first 补证", ordinary_quant_slice)
        self.assertNotIn("disabled={!searchQuantProjectionExecutionRequest.acceptance_scope_hash}", ordinary_quant_slice)
        self.assertIn('label: "Tushare-first"', ordinary_quant_slice)
        self.assertIn('label: "最近任务"', ordinary_quant_slice)
        self.assertIn('label: "任务回放"', ordinary_quant_slice)
        self.assertIn('label: "结果回放"', ordinary_quant_slice)
        self.assertIn("quantProjectionLatestTaskState", ordinary_quant_slice)
        self.assertIn("quantProjectionTaskReadbackState", ordinary_quant_slice)
        self.assertIn("quantProjectionResultReplayState", ordinary_quant_slice)
        self.assertIn("quantProjectionReplayDestinationPacketRows", source)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_replay_destination_rows", source)
        self.assertIn("search_quant_provider_model_acceptance_receipt / call_ledger / packet", source)
        self.assertIn("最近任务只显示本地 FastAPI 返回的 task id 和安全步骤", ordinary_quant_slice)
        self.assertIn("最近任务会优先从本地 cache / packet 回放 task id 和安全 current_step", ordinary_quant_slice)
        self.assertIn("GET cache 不会因此补调 provider", ordinary_quant_slice)
        self.assertIn("不在普通页面展开审计表", ordinary_quant_slice)
        self.assertIn("DeepSeek 保持 skipped", ordinary_quant_slice)
        self.assertIn("确认后创建 Tushare-first 按钮门控 POST task / worker", ordinary_quant_slice)
        self.assertIn("不交易、不改 strategy action", ordinary_quant_slice)
        self.assertIn("if (!quantProjectionCanSubmit || quantProjectionSubmitting) return;", submit_slice)
        self.assertIn("setQuantProjectionSubmitting(true);", submit_slice)
        self.assertIn('setQuantProjectionSubmitError("");', submit_slice)
        self.assertIn("setQuantProjectionSubmitError(quantProjectionSubmitFailureMessage(res.error));", submit_slice)
        self.assertIn("}).finally(() => setQuantProjectionSubmitting(false));", submit_slice)
        self.assertNotIn("postCandidateRadarQuantProjectionProviderModelAcceptance", submit_slice)
        self.assertNotIn("operator_approved", submit_slice)
        self.assertIn("include_deepseek: false", submit_slice)
        self.assertIn("user_approved: true", submit_slice)
        self.assertIn("refreshCache();", submit_slice)
        self.assertIn("任务接收后立即回读本地 cache receipt", ordinary_quant_slice)
        self.assertNotIn("fetch(", source)
        self.assertNotIn("TUSHARE_TOKEN", source)
        self.assertNotIn("DEEPSEEK_API_KEY", source)
        self.assertNotIn("GITHUB_TOKEN", source)


if __name__ == "__main__":
    unittest.main()
