import unittest
from pathlib import Path


class CandidateRadarOrdinaryEntryTests(unittest.TestCase):
    def setUp(self):
        self.root = Path(__file__).resolve().parents[1]
        self.page = (self.root / "desktop" / "src" / "routes" / "CandidateRadar.tsx").read_text(
            encoding="utf-8"
        )
        self.handoff = (self.root / "docs" / "codex_handoff_protocol.md").read_text(
            encoding="utf-8"
        )
        self.task_status_panel = (
            self.root / "desktop" / "src" / "components" / "TaskStatusPanel.tsx"
        ).read_text(encoding="utf-8")

    def test_candidate_radar_has_ordinary_user_summary_before_audit_details(self):
        self.assertIn("<h1>下一票雷达</h1>", self.page)
        self.assertIn('title="普通用户雷达摘要"', self.page)
        self.assertIn('title="下一票候选池"', self.page)
        self.assertIn('title="搜票量化推演"', self.page)
        self.assertIn("生成 3.0 量化推演", self.page)

        for required_label in (
            'label: "下一步"',
            'label: "主下一步"',
            'label: "主下一步边界"',
            'label: "P0 交接"',
            'label: "P1 主路径"',
            'label: "P1 主路径边界"',
            'label: "P2 三面"',
            'label: "候选分组"',
            'label: "扫描范围"',
            'label: "候选来源"',
            'label: "评分说明"',
            'label: "可选补证"',
            'label: "本地缓存"',
            'label: "数据链"',
            'label: "解释状态"',
            'label: "待补证据"',
            'label: "降级提示"',
            'label: "最近成功回放"',
            'label: "缺少证据"',
            'label: "阻断/降级"',
            'label: "最近可用缓存"',
            'label: "任务边界"',
            'label: "仅供研究"',
        ):
            self.assertIn(required_label, self.page)
        summary_start = self.page.index('title="普通用户雷达摘要"')
        summary_end = self.page.index('title="下一票候选池"', summary_start)
        summary_slice = self.page[summary_start:summary_end]
        for engineering_label in (
            'label: "cache"',
            'label: "Tushare"',
            'label: "DeepSeek"',
            'label: "pending"',
            'label: "degraded"',
            'label: "last_successful_cache/result"',
        ):
            self.assertNotIn(engineering_label, summary_slice)
        self.assertIn('aria-label="candidate radar ordinary summary extra details"', summary_slice)
        self.assertIn("<summary>摘要细节</summary>", summary_slice)
        summary_extra_start = summary_slice.index('aria-label="candidate radar ordinary summary extra details"')
        summary_extra_end = summary_slice.index('aria-label="candidate radar first screen quant projection confirmation"', summary_extra_start)
        summary_primary_slice = summary_slice[:summary_extra_start]
        summary_extra_slice = summary_slice[summary_extra_start:summary_extra_end]
        for downshifted_label in (
            'label: "候选来源"',
            'label: "评分说明"',
            'label: "P1 回放顺序"',
            'label: "P1 确认后等待"',
            'label: "P2 checkpoint"',
            'label: "P2 写入边界"',
            'label: "结果位置"',
        ):
            self.assertNotIn(downshifted_label, summary_primary_slice)
            self.assertIn(downshifted_label, summary_extra_slice)
        self.assertIn('label: "任务边界"', summary_primary_slice)
        self.assertIn("候选来源、评分说明、P1 回放顺序、P2 checkpoint 和结果位置默认收起", summary_extra_slice)

        self.assertLess(self.page.index('title="普通用户雷达摘要"'), self.page.index("<summary>开发 / 审计指标</summary>"))
        self.assertLess(self.page.index('title="下一票候选池"'), self.page.index("<summary>扫描覆盖 / 验收审计</summary>"))
        self.assertIn("const candidateRadarP0Blocked = Boolean(error)", self.page)
        self.assertIn('    ? "先恢复 P0 本地联通"', self.page)
        self.assertIn('    : "输入股票代码并点击确认";', self.page)
        self.assertIn("ordinaryPrimaryActionLabel", self.page)
        self.assertIn("ordinaryPrimaryActionBoundary", self.page)
        self.assertIn("回一键启动预检恢复联通", self.page)
        self.assertIn("输入代码并确认", self.page)
        self.assertIn("P0 未联通时主下一步只跳转一键启动预检", self.page)
        self.assertIn("不创建快扫 task、不调用 provider/model", self.page)
        self.assertIn("主下一步跳到搜票确认区；输入只做本地校验，只有确认按钮创建 Tushare-first POST task", self.page)
        self.assertIn("本地快扫和输入股票池保留为可选补证；主路径走搜票确认", self.page)
        self.assertIn('href="#candidate-radar-search-quant-projection"', self.page)
        self.assertIn('id="candidate-radar-search-quant-projection"', self.page)
        self.assertIn("candidateRadarP0HandoffPacketRows", self.page)
        self.assertIn("desktopPreflight.p0_to_p1_ordinary_handoff_rows", self.page)
        self.assertIn("candidateRadarP0HandoffRows", self.page)
        self.assertIn("candidateRadarP0HandoffLabel", self.page)
        self.assertIn('<details className="developer-audit-details" aria-label="candidate radar ordinary p0 local connection diagnostics">', self.page)
        self.assertIn("<summary>P0 本地联通诊断</summary>", self.page)
        self.assertIn("首页已经提供本地 FastAPI 接线速读", self.page)
        self.assertIn("普通主线默认收起 P0 联通表", self.page)
        self.assertIn('aria-label="candidate radar p0 to p1 preflight handoff"', self.page)
        self.assertIn("P0 到 P1 交接回读", self.page)
        self.assertIn("优先读取 desktop preflight 的 p0_to_p1_ordinary_handoff_rows", self.page)
        self.assertIn("四段 ready 后只切到搜票量化推演卡；输入保持静默，确认按钮才创建 Tushare-first POST task", self.page)
        self.assertIn("ordinaryP1ConfirmPathLabel", self.page)
        self.assertIn("ordinaryP1ConfirmPathBoundary", self.page)
        self.assertIn("ordinaryP1ConfirmPathRows", self.page)
        self.assertIn("ordinaryP1ToP3StageRailState", self.page)
        self.assertIn("ordinaryP1ToP3StageRailSteps", self.page)
        self.assertIn('aria-label="candidate radar p1 direct confirmation handoff"', self.page)
        self.assertIn("P1 直接确认入口", self.page)
        self.assertIn("这个入口只做本地锚点跳转", self.page)
        self.assertIn('aria-label="candidate radar p2 three surface quick status"', self.page)
        self.assertIn("P2 三面速读", self.page)
        self.assertIn("cache、call_ledger、packet 是否进入本地回放", self.page)
        self.assertIn('aria-label="candidate radar p3 first screen result quick read"', self.page)
        self.assertIn("P3 结果首屏速读", self.page)
        self.assertIn("本速读不创建 task、不调用 DeepSeek、不生成交易动作", self.page)
        self.assertIn("首屏直接回放服务端 ordinary_result_quick_read_rows", self.page)
        self.assertIn("P1 主路径：点击确认创建 ${quantProjectionSymbolValidation.normalized} 的 Tushare-first POST task", self.page)
        self.assertIn("P1 主路径：先输入股票代码；输入只做本地校验，确认按钮才创建 Tushare-first task", self.page)
        self.assertIn("P1 主路径只允许确认按钮创建 Tushare-first task", self.page)
        self.assertIn("搜索输入、页面打开、React render、GET cache 和结果链接都不外联", self.page)
        self.assertIn('aria-label="candidate radar ordinary p1 to p3 stage rail"', self.page)
        self.assertIn("P1 到 P3 阶段速览", self.page)
        self.assertIn("这条状态轨只读本地输入、task receipt 和 cache 回放", self.page)
        self.assertIn('label: "输入静默"', self.page)
        self.assertIn('label: "确认按钮"', self.page)
        self.assertIn('label: "任务接收"', self.page)
        self.assertIn('label: "P2 三面"', self.page)
        self.assertIn('label: "P3 速读"', self.page)
        self.assertIn('"POST task ready"', self.page)
        self.assertIn('"cache/ledger/packet"', self.page)
        self.assertIn('"可解释结果"', self.page)
        p0_diagnostics_index = self.page.index('aria-label="candidate radar ordinary p0 local connection diagnostics"')
        p0_gate_index = self.page.index('aria-label="candidate radar ordinary p0 frontend backend readiness"', p0_diagnostics_index)
        p0_handoff_index = self.page.index('aria-label="candidate radar p0 to p1 preflight handoff"', p0_gate_index)
        primary_action_index = self.page.index('aria-label="candidate radar primary next action"', p0_gate_index)
        next_user_actions_index = self.page.index('aria-label="candidate radar next user actions"', primary_action_index)
        p1_to_p3_rail_index = self.page.index('aria-label="candidate radar ordinary p1 to p3 stage rail"', p0_gate_index)
        p5_detail_index = self.page.index('aria-label="candidate radar ordinary p5 governance details"', p0_gate_index)
        p6_detail_index = self.page.index('aria-label="candidate radar ordinary p6 strict closeout handoff"', p0_gate_index)
        action_slice_end = self.page.index('aria-label="candidate radar ordinary audit shortcuts"', next_user_actions_index)
        action_slice = self.page[primary_action_index:action_slice_end]
        direct_handoff_index = self.page.index('aria-label="candidate radar p1 direct confirmation handoff"')
        p2_quick_status_index = self.page.index('aria-label="candidate radar p2 three surface quick status"')
        p3_first_screen_index = self.page.index('aria-label="candidate radar p3 first screen result quick read"')
        p3_first_screen_slice = self.page[p3_first_screen_index:p0_diagnostics_index]
        self.assertIn("rows={quantProjectionOrdinaryResultQuickRows}", p3_first_screen_slice)
        self.assertIn("现在能读什么、结果从哪里来、还缺什么", p3_first_screen_slice)
        self.assertLess(p0_gate_index, p0_handoff_index)
        self.assertLess(direct_handoff_index, p0_gate_index)
        self.assertLess(direct_handoff_index, p2_quick_status_index)
        self.assertLess(p2_quick_status_index, p3_first_screen_index)
        self.assertLess(p3_first_screen_index, p0_diagnostics_index)
        self.assertLess(p0_diagnostics_index, p0_gate_index)
        self.assertLess(p3_first_screen_index, p0_gate_index)
        self.assertLess(p2_quick_status_index, p0_gate_index)
        self.assertLess(p0_handoff_index, p1_to_p3_rail_index)
        self.assertLess(p0_gate_index, p1_to_p3_rail_index)
        self.assertLess(p1_to_p3_rail_index, primary_action_index)
        self.assertLess(primary_action_index, next_user_actions_index)
        self.assertLess(next_user_actions_index, action_slice_end)
        self.assertLess(action_slice_end, p5_detail_index)
        self.assertLess(p5_detail_index, p6_detail_index)
        self.assertIn('aria-label="radar summary quant projection symbol"', action_slice)
        self.assertIn('onClick={launchQuantProjection}', action_slice)
        self.assertIn("确认并生成 3.0 量化推演", action_slice)
        self.assertIn('href="#factor"', action_slice)
        self.assertIn('href="#next"', action_slice)
        self.assertNotIn("postCandidateRadarQuantProjectionProviderModelAcceptance", action_slice)
        self.assertNotIn("launchQuantProjectionAcceptanceDryRun", action_slice)
        self.assertIn("quantProjectionOneScreenPacketRows", self.page)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_one_screen_action_rows", self.page)
        self.assertIn("quantProjectionOneScreenActionRows", self.page)
        self.assertIn('aria-label="candidate radar ordinary one screen actions"', self.page)
        self.assertIn("一屏行动摘要", self.page)
        self.assertIn("优先读取服务端 ordinary_one_screen_action_rows", self.page)
        self.assertIn("确认、任务、写回、结果合成一张普通用户表", self.page)
        self.assertIn("只读回放本地状态，不从摘要创建 task", self.page)
        self.assertIn("rows={quantProjectionOneScreenActionRows}", self.page)
        self.assertIn('aria-label="candidate radar ordinary p2 p3 replay checklist"', self.page)
        self.assertIn("确认后先看这张只读索引", self.page)
        self.assertIn("确认回执、任务回放、数据接口和 P3 结果速读都来自本地 cache / ledger / packet", self.page)
        self.assertIn("不会创建 task、不会补调 Tushare/DeepSeek", self.page)
        self.assertIn("rows={quantProjectionReadbackIndexRows}", self.page)
        self.assertIn('行动: "1. 确认"', self.page)
        self.assertIn('行动: "2. 任务"', self.page)
        self.assertIn('行动: "3. 写回"', self.page)
        self.assertIn('行动: "4. 结果"', self.page)
        self.assertIn('aria-label="candidate radar ordinary p1 p2 detail readback"', self.page)
        self.assertIn("<summary>P1/P2 细节回放</summary>", self.page)
        self.assertIn("一屏行动摘要已经覆盖普通下一步", self.page)
        self.assertIn("确认链路、P1 路径和 P2 三面核对默认收起", self.page)
        self.assertIn("quantProjectionConfirmedChainQuickRows", self.page)
        self.assertIn('aria-label="candidate radar ordinary confirmed chain quick read"', self.page)
        self.assertIn("确认后链路速读", self.page)
        self.assertIn("普通用户先看这张确认后链路速读", self.page)
        self.assertIn('链路节点: "1. 点击确认"', self.page)
        self.assertIn('链路节点: "2. Tushare-first"', self.page)
        self.assertIn('链路节点: "3. P2 三面写回"', self.page)
        self.assertIn('链路节点: "4. P3 可解释结果"', self.page)
        self.assertIn('链路节点: "5. 结果入口"', self.page)
        self.assertIn("只有确认按钮会创建 POST task；页面打开、搜索输入、React render 和 GET cache 不外联", self.page)
        self.assertIn("Tushare 只允许在 POST task / worker 内调用；DeepSeek 默认 skipped，等 governed executor", self.page)
        self.assertIn('aria-label="candidate radar ordinary p1 confirm path"', self.page)
        self.assertIn("P1 普通确认路径", self.page)
        self.assertIn("普通用户先看这条 P1 路径", self.page)
        self.assertIn('阶段: "1. 输入股票代码"', self.page)
        self.assertIn('阶段: "2. 点击确认按钮"', self.page)
        self.assertIn('阶段: "3. 看任务接收"', self.page)
        self.assertIn('阶段: "4. 回放本地结果"', self.page)
        self.assertIn("只有确认按钮会 POST /api/candidate-radar/quant-projection", self.page)
        primary_action_start = self.page.index('aria-label="candidate radar primary next action"')
        primary_action_end = self.page.index('aria-label="candidate radar next user actions"', primary_action_start)
        primary_action_slice = self.page[primary_action_start:primary_action_end]
        self.assertIn('href="#candidate-radar-search-quant-projection"', primary_action_slice)
        self.assertNotIn("launchQuickScan", primary_action_slice)
        self.assertIn('href="#desktop"', self.page)
        self.assertIn('aria-label="open p0 desktop preflight from radar summary"', self.page)
        self.assertIn("ordinaryCandidateGroupLabel", self.page)
        self.assertIn("ordinaryScanScopeLabel", self.page)
        self.assertIn("ordinaryCandidateSourceLabel", self.page)
        self.assertIn("ordinaryScoringReasonLabel", self.page)
        self.assertIn("Top ${ordinaryCandidateTopCount} / Watch ${ordinaryCandidateWatchCount} / Excluded ${ordinaryCandidateExcludedCount}", self.page)
        self.assertIn("模式：${String(cache.scan_mode ?? \"cache_only\")}", self.page)
        self.assertIn("范围：${String(scanExecutionSummary.scan_family ?? localPoolAudit.input_source ?? \"本地缓存\")}", self.page)
        self.assertIn("按本地缓存顺序展示；评分理由不足会作为缺口显示", self.page)
        self.assertIn("不重排、不生成交易动作", self.page)
        self.assertIn("候选分组：{ordinaryCandidateGroupLabel}", self.page)
        self.assertIn("ordinaryOptionalNextClick", self.page)
        self.assertIn("ordinaryCandidateReviewRows", self.page)
        self.assertIn("证据摘要: displayText(row.evidence_chain_summary", self.page)
        self.assertIn("按本地缓存顺序复核；不重排、不重算分数、不生成交易动作", self.page)
        self.assertIn('title="候选复核清单"', self.page)
        self.assertIn("普通入口只显示标的、分数、状态、证据摘要和边界；原始 candidate_rows 下沉到详情", self.page)
        self.assertIn("<summary>原始 candidate_rows 审计</summary>", self.page)
        self.assertLess(self.page.index('title="候选复核清单"'), self.page.index("<summary>原始 candidate_rows 审计</summary>"))
        self.assertIn("需要更新时再运行本地快扫", self.page)
        self.assertIn("搜单票时输入代码后点击生成 3.0 量化推演", self.page)
        self.assertIn("ordinaryPendingSourceLabel", self.page)
        self.assertIn("ordinaryDegradedSourceLabel", self.page)
        self.assertIn("pending：", self.page)
        self.assertIn("degraded：", self.page)
        self.assertIn("本地候选缓存可用", self.page)
        self.assertIn("手动触发或关闭", self.page)
        self.assertIn("live_light 已配置；仍需确认按钮触发 Tushare-first task", self.page)
        self.assertIn("待 governed executor；不作为数据源或动作", self.page)
        self.assertIn("雷达摘要只读展示候选缓存", self.page)
        self.assertIn("manual/live_light 补证必须走 POST task / worker", self.page)
        self.assertIn('aria-label="candidate radar primary next action"', self.page)
        self.assertIn('href="#candidate-pool"', self.page)
        self.assertIn('id="candidate-pool"', self.page)
        self.assertIn("候选不是买入指令；不真实交易、不下单、不改交易策略", self.page)
        summary_start = self.page.index('title="普通用户雷达摘要"')
        self.assertIn("普通用户先看上方雷达摘要、候选池和搜票量化推演", self.page)
        self.assertIn("普通用户无需先打开工程审计；默认先看候选、确认结果和本地回放。", self.page)
        self.assertIn('aria-label="candidate radar ordinary audit shortcuts"', self.page)
        self.assertIn("<summary>高级诊断入口</summary>", self.page)
        self.assertIn("工程审计明细继续默认收起", self.page)
        self.assertIn("完整 call ledger、release gate 和配置状态下沉", self.page)
        self.assertIn('<a href="#audit">调用审计</a>', self.page)
        self.assertIn('<a href="#settings">配置健康</a>', self.page)
        self.assertIn('id="settings" className="developer-audit-details"', self.page)
        self.assertIn('aria-label="candidate radar settings audit details"', self.page)
        self.assertIn('id="audit" className="developer-audit-details"', self.page)
        self.assertIn('aria-label="candidate radar developer audit details"', self.page)
        self.assertIn('<details className="developer-audit-details" aria-label="candidate radar result delta audit details">', self.page)
        self.assertIn("<summary>结果变化 / 浏览器差异审计</summary>", self.page)
        self.assertIn("结果变化 diff 和 browser visual delta 属于 P4/P6 审计补证", self.page)
        result_delta_audit_index = self.page.index('aria-label="candidate radar result delta audit details"')
        candidate_priority_index = self.page.index('title="候选优先级说明"')
        self.assertLess(result_delta_audit_index, candidate_priority_index)
        result_delta_audit = self.page[result_delta_audit_index:candidate_priority_index]
        self.assertIn('title="雷达结果变化清晰度"', result_delta_audit)
        self.assertIn("普通路径继续先看候选优先级说明、候选复核清单和搜票结果", result_delta_audit)
        ordinary_audit_shortcuts_index = self.page.index('aria-label="candidate radar ordinary audit shortcuts"')
        self.assertLess(self.page.index('title="搜票量化推演"'), self.page.index('id="settings" className="developer-audit-details"'))
        self.assertLess(self.page.index('title="搜票量化推演"'), self.page.index('id="audit" className="developer-audit-details"'))
        self.assertLess(summary_start, ordinary_audit_shortcuts_index)
        self.assertLess(ordinary_audit_shortcuts_index, self.page.index('id="settings" className="developer-audit-details"'))
        self.assertLess(ordinary_audit_shortcuts_index, self.page.index('id="audit" className="developer-audit-details"'))
        self.assertIn('<details className="developer-audit-details" aria-label="candidate radar ordinary p5 governance details">', self.page)
        self.assertIn("<summary>P5 DeepSeek 单独补证状态</summary>", self.page)
        self.assertIn("P4 已将 P5 治理状态下沉到主行动之后", self.page)
        self.assertIn("P4 已将 14 LTG strict closeout 交接下沉到主行动之后", self.page)
        self.assertLess(self.page.index('aria-label="candidate radar ordinary p3 result handoff index"'), self.page.index('aria-label="candidate radar ordinary p5 governance details"'))
        self.assertLess(self.page.index('aria-label="candidate radar primary next action"'), self.page.index('aria-label="candidate radar ordinary p5 governance details"'))
        self.assertLess(ordinary_audit_shortcuts_index, self.page.index('aria-label="candidate radar ordinary p5 governance details"'))
        self.assertLess(self.page.index('aria-label="candidate radar ordinary p5 governance details"'), self.page.index('aria-label="candidate radar ordinary p6 strict closeout handoff"'))
        self.assertLess(
            self.page.index('aria-label="candidate radar ordinary p1 to p3 stage rail"'),
            self.page.index('aria-label="candidate radar ordinary one screen actions"'),
        )
        self.assertLess(
            self.page.index('aria-label="candidate radar ordinary one screen actions"'),
            self.page.index('aria-label="quant projection submit recovery quick read"'),
        )
        self.assertLess(
            self.page.index('aria-label="quant projection submit recovery quick read"'),
            self.page.index('aria-label="quant projection ordinary confirm outcome quick read"'),
        )
        self.assertLess(
            self.page.index('aria-label="quant projection ordinary confirm outcome quick read"'),
            self.page.index('aria-label="candidate radar p1 tushare first chain quick read"'),
        )
        self.assertLess(
            self.page.index('aria-label="candidate radar p1 tushare first chain quick read"'),
            self.page.index('aria-label="candidate radar ordinary p3 explainable result quick read"'),
        )
        self.assertLess(
            self.page.index('aria-label="candidate radar ordinary one screen actions"'),
            self.page.index('aria-label="candidate radar ordinary p2 p3 replay checklist"'),
        )
        self.assertLess(
            self.page.index('aria-label="candidate radar ordinary p2 p3 replay checklist"'),
            self.page.index('aria-label="candidate radar ordinary p1 p2 detail readback"'),
        )
        self.assertLess(
            self.page.index('aria-label="candidate radar ordinary p1 p2 detail readback"'),
            self.page.index('aria-label="candidate radar ordinary p3 result handoff index"'),
        )
        self.assertLess(
            self.page.index('aria-label="candidate radar ordinary p1 p2 detail readback"'),
            self.page.index('aria-label="candidate radar ordinary confirmed chain quick read"'),
        )
        self.assertLess(
            self.page.index('aria-label="candidate radar ordinary p1 to p3 stage rail"'),
            self.page.index('aria-label="candidate radar ordinary confirmed chain quick read"'),
        )
        self.assertLess(
            self.page.index('aria-label="candidate radar ordinary confirmed chain quick read"'),
            self.page.index('aria-label="candidate radar ordinary p1 confirm path"'),
        )
        self.assertNotIn(
            '工程审计明细默认收起；完整 call ledger、release gate 和配置状态在 <a href="#audit">调用审计</a> / <a href="#settings">配置健康</a>。',
            self.page,
        )
        deepseek_label_start = self.page.index("const ordinaryDeepSeekSourceLabel")
        deepseek_label_end = self.page.index("const ordinaryProviderGapLabel", deepseek_label_start)
        deepseek_label_slice = self.page[deepseek_label_start:deepseek_label_end]
        summary_end = self.page.index('title="下一票候选池"', summary_start)
        summary_slice = self.page[summary_start:summary_end]
        self.assertIn("待 governed executor；不作为数据源或动作", deepseek_label_slice)
        self.assertNotIn("轻量实时后台任务", deepseek_label_slice)
        self.assertNotIn("轻量实时后台任务", summary_slice)
        self.assertIn('{ label: "解释状态", value: ordinaryDeepSeekSourceLabel }', summary_slice)
        self.assertNotIn('DeepSeek", value: bootstrapLiveLight.deepseek_on_open === true ? "轻量实时后台任务"', summary_slice)

    def test_candidate_radar_p1_direct_handoff_is_local_navigation_only(self):
        direct_start = self.page.index('aria-label="candidate radar p1 direct confirmation handoff"')
        direct_end = self.page.index('aria-label="candidate radar p2 three surface quick status"', direct_start)
        direct = self.page[direct_start:direct_end]

        self.assertIn('aria-label="candidate radar p1 direct confirmation handoff"', direct)
        self.assertIn("P1 直接确认入口", direct)
        self.assertIn("先确认本地 FastAPI 已接上", direct)
        self.assertIn("跳到搜票确认区输入代码", direct)
        self.assertIn("输入仍然静默", direct)
        self.assertIn("只有确认按钮会创建 Tushare-first POST task", direct)
        self.assertIn('aria-label="candidate radar p1 direct confirmation actions"', direct)
        self.assertIn('href={candidateRadarP0Blocked ? "#desktop" : "#candidate-radar-search-quant-projection"}', direct)
        self.assertIn('href="#tasks"', direct)
        self.assertNotIn("onClick=", direct)
        self.assertNotIn("postCandidateRadarQuantProjection", direct)
        self.assertNotIn("launchQuantProjection", direct)

    def test_candidate_radar_p2_three_surface_quick_status_is_read_only(self):
        summary_start = self.page.index('aria-label="candidate radar p2 three surface quick status"')
        summary_end = self.page.index('aria-label="candidate radar ordinary p0 frontend backend readiness"', summary_start)
        quick = self.page[summary_start:summary_end]

        self.assertIn("P2 三面速读", quick)
        self.assertIn("确认按钮完成后先看这里", quick)
        self.assertIn("cache、call_ledger、packet 是否进入本地回放", quick)
        self.assertIn("不创建 task、不补调 Tushare/DeepSeek", quick)
        self.assertIn('label: "三面状态"', quick)
        self.assertIn("quantProjectionSmallDataStageLabel", quick)
        self.assertIn('label: "三面组成"', quick)
        self.assertIn("quantProjectionSmallDataWritebackSurfaces", quick)
        self.assertIn('label: "完整度"', quick)
        self.assertIn("quantProjectionWritebackCheckpointLabel", quick)
        self.assertIn('label: "边界"', quick)
        self.assertIn("quantProjectionSmallDataReadbackContract", quick)
        self.assertNotIn("onClick=", quick)
        self.assertNotIn("postCandidateRadarQuantProjection", quick)
        self.assertNotIn("launchQuantProjection", quick)

    def test_candidate_radar_p3_first_screen_result_quick_read_is_read_only(self):
        summary_start = self.page.index('aria-label="candidate radar p3 first screen result quick read"')
        summary_end = self.page.index('aria-label="candidate radar ordinary p0 frontend backend readiness"', summary_start)
        quick = self.page[summary_start:summary_end]

        self.assertIn("P3 结果首屏速读", quick)
        self.assertIn("P2 三面之后直接看这里", quick)
        self.assertIn("可读结论、来源、下一步和安全边界", quick)
        self.assertIn("本地 cache / ledger / packet", quick)
        self.assertIn("本速读不创建 task、不调用 DeepSeek、不生成交易动作", quick)
        self.assertIn("<MetricGrid items={quantProjectionP3ResultSummaryItems} />", quick)
        self.assertNotIn("onClick=", quick)
        self.assertNotIn("postCandidateRadarQuantProjection", quick)
        self.assertNotIn("launchQuantProjection", quick)

    def test_candidate_radar_p1_to_p3_stage_rail_is_read_only_before_tables(self):
        summary_start = self.page.index('title="普通用户雷达摘要"')
        summary_end = self.page.index('title="下一票候选池"', summary_start)
        summary = self.page[summary_start:summary_end]
        rail_start = summary.index('aria-label="candidate radar ordinary p1 to p3 stage rail"')
        p1_table_start = summary.index('aria-label="candidate radar ordinary p1 confirm path"')
        rail = summary[rail_start:p1_table_start]

        self.assertLess(rail_start, p1_table_start)
        self.assertIn("<StateClarityRail", rail)
        self.assertIn('label="candidate radar ordinary p1 to p3 stage rail"', rail)
        self.assertIn("state={ordinaryP1ToP3StageRailState}", rail)
        self.assertIn("steps={ordinaryP1ToP3StageRailSteps}", rail)
        self.assertNotIn("onClick=", rail)
        self.assertNotIn("postCandidateRadarQuantProjection", rail)
        self.assertNotIn("launchQuantProjection", rail)

    def test_candidate_radar_confirmed_chain_quick_read_is_read_only_before_p1_details(self):
        summary_start = self.page.index('title="普通用户雷达摘要"')
        summary_end = self.page.index('title="下一票候选池"', summary_start)
        summary = self.page[summary_start:summary_end]
        quick_start = summary.index('aria-label="candidate radar ordinary confirmed chain quick read"')
        p1_table_start = summary.index('aria-label="candidate radar ordinary p1 confirm path"')
        quick = summary[quick_start:p1_table_start]

        self.assertLess(quick_start, p1_table_start)
        self.assertIn("确认后链路速读", quick)
        self.assertIn("quantProjectionConfirmedChainQuickRows", quick)
        self.assertIn("<DataLineageTable", quick)
        self.assertNotIn("onClick=", quick)
        self.assertNotIn("postCandidateRadarQuantProjection", quick)
        self.assertNotIn("launchQuantProjection", quick)

    def test_three_ordinary_entrances_show_summaries_before_developer_audit(self):
        pages = {
            "daily": {
                "path": self.root / "desktop" / "src" / "routes" / "CommandCenterHome.tsx",
                "summary": 'title="今日作战台摘要"',
                "audit": "<summary>开发 / 审计详情</summary>",
                "boundary": "dailyCommandTaskBoundary",
            },
            "quant": {
                "path": self.root / "desktop" / "src" / "routes" / "FactorQuantHub.tsx",
                "summary": 'title="普通用户量化推演摘要"',
                "audit": "<summary>开发 / 审计指标</summary>",
                "boundary": "ordinaryQuantTaskBoundary",
            },
            "radar": {
                "path": self.root / "desktop" / "src" / "routes" / "CandidateRadar.tsx",
                "summary": 'title="普通用户雷达摘要"',
                "audit": "<summary>开发 / 审计指标</summary>",
                "boundary": "ordinaryTaskBoundary",
            },
        }

        for name, config in pages.items():
            with self.subTest(name=name):
                text = config["path"].read_text(encoding="utf-8")
                self.assertLess(text.index(config["summary"]), text.index(config["audit"]))
                self.assertLess(text.index('label: "任务边界"'), text.index(config["audit"]))
                self.assertIn(config["boundary"], text)
                self.assertIn("不在 React 渲染中直连 Tushare 或 DeepSeek", text)
                if name == "daily":
                    self.assertIn("dailyCommandUsableShortestPathRows", text)
                    self.assertIn("dailyCommandCandidateLatestTaskId", text)
                    self.assertIn("candidateQuantSmallDataWriteback.latest_task_id", text)
                    self.assertIn("candidateQuantReceipt.latest_task_id", text)
                    self.assertIn("candidate_radar_cache_latest_task", text)
                    self.assertIn("dailyCommandLatestTaskIsReplay = dailyCommandLatestTask.cache_replay_only === true || Boolean(dailyCommandCandidateLatestTaskId && !dailyCommandLatestTask.task_id)", text)
                    self.assertIn("dailyCommandLatestTaskId && !dailyCommandLatestTaskIsReplay ? <TaskStatusPanel taskId={dailyCommandLatestTaskId} /> : null", text)
                    self.assertIn("最近任务来自 CandidateRadar cache 只读回放，不启动 TaskStatusPanel 轮询", text)
                    self.assertIn('aria-label="daily command usable shortest path"', text)
                    self.assertIn("使用者可用化最短路径", text)
                    self.assertIn("当前执行目标是 Command Center 3.0 使用者可用化最短路径，不是 14 LTG strict closeout 完成声明", text)
                    self.assertIn('阶段: "P0 一键启动和本地联通"', text)
                    self.assertIn('阶段: "P1 确认按钮触发 Tushare-first"', text)
                    self.assertIn('阶段: "P2 小数据写入 cache / ledger / packet"', text)
                    self.assertIn('阶段: "P3 候选、量化推演、次日图谱"', text)
                    self.assertIn('阶段: "P4 工程审计噪音下沉"', text)
                    self.assertIn('阶段: "P5 DeepSeek governed executor 单独补"', text)
                    self.assertIn('阶段: "P6 回到 14 LTG direct evidence"', text)
                    self.assertIn("页面打开、React render 和 GET cache 只读；不启动服务、不外联、不读取 token/key", text)
                    self.assertIn("只有确认按钮创建 POST task / worker，DeepSeek skipped", text)
                    self.assertIn("governed executor 完成前不真实调用 DeepSeek", text)
                    self.assertIn("strict closeout 仍是 0/14", text)
                    self.assertIn("P0-P5 可用化 checkpoint 不是 14 LTG 完成", text)
                    self.assertIn("mock、matrix、sanitizer、local receipt 不能关闭 LTG", text)
                    self.assertLess(
                        text.index('aria-label="daily command usable shortest path"'),
                        text.index(config["audit"]),
                    )

    def test_search_quant_projection_keeps_task_boundary_visible(self):
        self.assertIn("normalizeAshareSymbolInput", self.page)
        self.assertIn("explicit_market_suffix", self.page)
        self.assertIn("inferred_market_suffix", self.page)
        self.assertIn("require_6_digits_or_suffix", self.page)
        self.assertIn("unsupported_a_share_prefix", self.page)
        self.assertIn("symbol: normalizeAshareSymbolInput(searchSymbol).normalized", self.page)
        self.assertIn("searchSymbol.trim()", self.page)
        self.assertIn("quantProjectionSymbolValidation.valid", self.page)
        self.assertIn("quantProjectionSubmitting", self.page)
        self.assertIn("quantProjectionSubmitError", self.page)
        self.assertIn("quantProjectionSubmitErrorLabel", self.page)
        self.assertIn("quantProjectionFailedSubmitLedgerRows", self.page)
        self.assertIn("quantProjectionP0SubmitRecoveryRows", self.page)
        self.assertIn("frontend_backend_auto_link_attempted", self.page)
        self.assertIn("frontend_backend_auto_link_next_action", self.page)
        self.assertIn("scripts/check_command_center_3.command", self.page)
        self.assertIn("scripts/start_command_center_3.command", self.page)
        self.assertIn("quantProjectionSubmitFailureMessage", self.page)
        self.assertIn("quantProjectionTaskReceiptInputMismatch", self.page)
        self.assertIn("quantProjectionInputSessionState", self.page)
        self.assertIn("Boolean(taskReceipt?.ok || quantProjectionPersistedTaskId)", self.page)
        self.assertIn("quantProjectionCanLaunch", self.page)
        self.assertIn("quantProjectionConfirmedSymbol", self.page)
        self.assertIn("quantProjectionSummaryGuidance", self.page)
        self.assertIn("quantProjectionConfirmChainState", self.page)
        self.assertIn("searchQuantProjectionConfirmChainCheckpoint", self.page)
        self.assertIn("cache.search_quant_projection_confirm_chain_checkpoint", self.page)
        self.assertIn("quantProjectionConfirmChainCheckpointLabel", self.page)
        self.assertIn('label: "确认代码"', self.page)
        self.assertIn('label: "确认链路"', self.page)
        self.assertIn('label: "P1 checkpoint"', self.page)
        self.assertIn('String(searchQuantProjectionConfirmChainCheckpoint.status ?? "等待确认按钮")', self.page)
        self.assertIn("未确认；输入框不会创建任务", self.page)
        self.assertIn("已确认输入：${quantProjectionSymbolValidation.normalized}", self.page)
        self.assertIn("摘要搜票已确认 ${quantProjectionSymbolValidation.normalized}", self.page)
        self.assertIn("下一步点击“确认并生成 3.0 量化推演”，创建 Tushare-first 按钮门控 POST task，DeepSeek skipped", self.page)
        self.assertIn("摘要搜票暂未通过本地校验：${quantProjectionSymbolValidation.reason}；不会创建 task", self.page)
        self.assertIn("摘要搜票等待输入代码；输入框只做本地校验，不创建 task", self.page)
        self.assertIn("请输入 6 位 A 股代码或 002008.SZ 这类后缀", self.page)
        self.assertIn("本地确认代码：${quantProjectionSymbolValidation.normalized}", self.page)
        self.assertIn("本地格式阻断：${quantProjectionSymbolValidation.reason}", self.page)
        self.assertIn("先输入并确认股票代码，按钮启用后再点击生成 3.0 量化推演", self.page)
        self.assertIn("确认代码后点击生成 3.0 量化推演", self.page)
        self.assertIn("quantProjectionSubmitHint", self.page)
        self.assertIn("任务提交中：正在创建 Tushare-first POST task", self.page)
        self.assertIn("正在提交 Tushare-first 后台任务；请等待本地 task id", self.page)
        self.assertIn("确认任务正在提交：按钮已暂时禁用", self.page)
        self.assertIn('if (error === "missing_task_id")', self.page)
        self.assertIn("const acceptedTaskId = String(res.data?.task_id ?? res.data?.task?.task_id ?? \"\");", self.page)
        self.assertIn("if (res.ok && acceptedTaskId) {", self.page)
        self.assertIn("setTaskId(acceptedTaskId);", self.page)
        self.assertIn("const refreshQuantProjectionReadback = () =>", self.page)
        self.assertIn("refreshBootstrapStatus();", self.page)
        self.assertIn("refreshQuantProjectionReadback();", self.page)
        self.assertIn('setQuantProjectionSubmitError(quantProjectionSubmitFailureMessage("missing_task_id"));', self.page)
        self.assertIn("setTaskReceipt(null);", self.page)
        submit_start = self.page.index("const launchQuantProjection = () =>")
        submit_end = self.page.index("const launchQuantProjectionAcceptanceDryRun = () =>", submit_start)
        submit_slice = self.page[submit_start:submit_end]
        self.assertEqual(submit_slice.count('setTaskId("");'), 3)
        self.assertIn("P0 未联通：先用一键启动预检恢复 FastAPI、bootstrap status、desktop preflight、本机连接证据和 candidate cache", self.page)
        self.assertIn("P0 stability check", self.page)
        self.assertIn("p0_stability=${desktopP0StabilityReady}", self.page)
        self.assertIn("p0_local_link=${desktopP0LocalLinkReady}", self.page)
        self.assertIn("p0_connection_evidence=${desktopP0ConnectionEvidenceReady}", self.page)
        self.assertIn("stability check 或本机连接回读只作为 P1 UI 闸门证据", self.page)
        self.assertIn("本页不会从输入或渲染创建 Tushare-first task", self.page)
        self.assertIn("正在提交 Tushare-first 后台链；请等待本地 task id，页面不会重复创建第二个 task。", self.page)
        self.assertIn("当前输入与最近任务不一致：先重新点击确认创建当前代码的 task，旧回执只作为历史回放。", self.page)
        self.assertIn("当前输入已有历史 task 回放", self.page)
        self.assertIn("再次点击确认会创建新的 Tushare-first POST task，旧回放只作为参考。", self.page)
        self.assertIn("当前代码已有历史回放；再次点击确认会创建新的 Tushare-first 后台链，旧回放保留为参考。", self.page)
        self.assertIn("当前代码已在本地显示；按钮未启用时先看不可用原因，输入本身不会创建 task 或调用 Tushare/DeepSeek。", self.page)
        self.assertIn("旧 task 属于 ${quantProjectionAcceptedTaskSymbol}", self.page)
        self.assertIn("当前输入 ${quantProjectionSymbolValidation.normalized} 需重新点击确认", self.page)
        self.assertIn("页面不会把旧回执归属到新代码", self.page)
        self.assertIn("quantProjectionTaskPanelStaleForCurrentInput", self.page)
        self.assertIn("quantProjectionTaskPanelStaleNotice", self.page)
        self.assertIn("旧任务面板暂不显示，避免把旧 task 当成当前输入的回放", self.page)
        self.assertIn("旧任务面板暂不显示，需重新点击确认", self.page)
        self.assertIn("修改输入只切换本地输入会话", self.page)
        self.assertIn("不会取消已创建后台 task、不创建新 task、不调用 Tushare/DeepSeek", self.page)
        self.assertIn("最近任务属于 ${quantProjectionAcceptedTaskSymbol}", self.page)
        self.assertIn("task_receipt_stale_for_input", self.page)
        self.assertIn("确认任务创建失败：未生成 task id；请检查本地后端连接后重试", self.page)
        self.assertIn("确认任务创建失败：${quantProjectionSubmitError}", self.page)
        self.assertIn("本地 FastAPI 后端未连接；请先用一键启动器恢复连接。", self.page)
        self.assertIn("frontend_submit_exception", self.page)
        self.assertIn("确认按钮请求未完成；请确认本地后端连接后重试。", self.page)
        self.assertIn("本地任务接口返回失败；请稍后重试或查看系统健康页。", self.page)
        self.assertIn("未创建可回放 task", self.page)
        self.assertIn('setQuantProjectionSubmitError("")', self.page)
        self.assertIn('setQuantProjectionSubmitError(quantProjectionSubmitFailureMessage("frontend_submit_exception"))', self.page)
        self.assertIn("disabled={quantProjectionSubmitDisabled}", self.page)
        self.assertIn('{quantProjectionSubmitting ? "提交中..." : "确认并生成 3.0 量化推演"}', self.page)
        self.assertIn("仅输入不会创建 task，也不会调用 Tushare 或 DeepSeek", self.page)
        self.assertIn("点击确认后提交 Tushare-first 后台链", self.page)
        self.assertIn("服务端凭据缺失时只写本地阻断", self.page)
        self.assertIn("确认任务已接收：先看 TaskStatusPanel，再通过 GET cache 回放 Tushare ledger、量化推演和次日图谱", self.page)
        self.assertIn("凭据可用才写 provider ledger，凭据缺失只写本地阻断；DeepSeek skipped", self.page)
        self.assertIn("quantProjectionPersistedTaskId", self.page)
        self.assertIn("quantProjectionPersistedTaskStep", self.page)
        self.assertIn("quantProjectionTaskReadbackState", self.page)
        self.assertIn("quantProjectionTaskCacheReadbackRows", self.page)
        self.assertIn("confirmedTaskReceiptLabel", self.page)
        self.assertIn("quantProjectionPersistedConfirmedTaskReceiptRows", self.page)
        self.assertIn("quantProjectionConfirmedTaskReceiptRows", self.page)
        self.assertIn("quantProjectionAcceptedPayload", self.page)
        self.assertIn("ordinary_confirmed_task_receipt_rows", self.page)
        self.assertIn("ordinary_task_readback_rows", self.page)
        self.assertIn("ordinary_confirm_trigger_boundary_rows", self.page)
        self.assertIn("ordinary_confirm_outcome_rows", self.page)
        self.assertIn("quantProjectionConfirmOutcomePacketRows", self.page)
        self.assertIn("quantProjectionConfirmTriggerPacketRows", self.page)
        self.assertIn("quantProjectionConfirmTriggerBoundaryRows", self.page)
        self.assertIn("quantProjectionOrdinaryResultRows", self.page)
        self.assertIn("quantProjectionOrdinaryResultQuickReadRows", self.page)
        self.assertIn("quantProjectionOrdinaryResultQuickRows", self.page)
        self.assertIn("quantProjectionModelGovernanceRows", self.page)
        self.assertIn("quantProjectionDeepSeekGovernanceRows", self.page)
        self.assertIn("ordinary_result_readback_rows", self.page)
        self.assertIn("ordinary_result_quick_read_rows", self.page)
        self.assertIn("ordinary_model_governance_rows", self.page)
        self.assertIn('label: "确认状态"', self.page)
        self.assertIn('label: "安全边界"', self.page)
        self.assertIn("不交易、不改 strategy action；DeepSeek 等 governed executor", self.page)
        self.assertIn("任务回放：${quantProjectionPersistedTaskId} /", self.page)
        self.assertIn("cache 回放", self.page)
        self.assertIn('label: "任务回放"', self.page)
        self.assertIn("quantProjectionConfirmHandoffRows", self.page)
        self.assertIn("quantProjectionOrdinaryEndToEndRows", self.page)
        self.assertIn('aria-label="quant projection ordinary end to end path"', self.page)
        self.assertIn("四步端到端路径", self.page)
        self.assertIn("先确认本地连接，再输入代码、点击确认、回放结果", self.page)
        self.assertIn('步骤: "1. 打开 3.0"', self.page)
        self.assertIn('步骤: "2. 输入代码"', self.page)
        self.assertIn('步骤: "3. 点击确认"', self.page)
        self.assertIn('步骤: "4. 回放结果"', self.page)
        self.assertIn("用一键启动器打开页面；若确认失败，先恢复本地 FastAPI 连接", self.page)
        self.assertIn("页面已进入只读 cache 状态", self.page)
        self.assertIn("FastAPI 启动、页面打开、React render、GET cache 不调用 Tushare/DeepSeek/GitHub", self.page)
        self.assertIn("只有确认按钮创建 Tushare-first POST task / worker；DeepSeek skipped，不交易", self.page)
        self.assertIn("结果只从 cache / ledger / packet 回放；链接不重新创建 task、不改 strategy action", self.page)
        self.assertIn('aria-label="quant projection ordinary confirmation handoff"', self.page)
        self.assertIn("确认后链路回放：优先读取服务端 ordinary_tushare_first_chain_rows；输入只校验，点击确认才创建 Tushare-first 后台任务，结果只从本地 cache / ledger / packet 回放。", self.page)
        self.assertIn('aria-label="quant projection ordinary confirm trigger boundary"', self.page)
        self.assertIn("P1 触发边界", self.page)
        self.assertIn("优先读取服务端 ordinary_confirm_trigger_boundary_rows", self.page)
        self.assertIn("输入只校验，确认按钮才创建 Tushare-first POST task，GET cache 和 React render 只回放本地结果", self.page)
        self.assertIn('触发点: "1. 输入股票代码"', self.page)
        self.assertIn('触发点: "2. 确认按钮"', self.page)
        self.assertIn('触发点: "3. Tushare-first task ledger"', self.page)
        self.assertIn('触发点: "4. GET cache 回放"', self.page)
        self.assertIn("输入框只做本地校验；不创建 task、不调用 Tushare/DeepSeek/GitHub", self.page)
        self.assertIn("POST /api/candidate-radar/quant-projection", self.page)
        self.assertIn("Tushare 只允许在按钮门控 POST task / worker 内调用", self.page)
        self.assertIn("GET cache、React render、结果链接只回放本地结果；不创建第二个 task", self.page)
        self.assertIn('aria-label="quant projection confirmed task receipt readback"', self.page)
        self.assertIn("确认任务接收回执", self.page)
        self.assertIn("点击确认后先看这张回执：它只回放本地 POST task 是否接收、Tushare-first / DeepSeek skipped 参数和安全步骤，不补调数据源或模型。", self.page)
        self.assertIn('回执项: "task_id"', self.page)
        self.assertIn('回执项: "Tushare-first 链路"', self.page)
        self.assertIn('回执项: "安全步骤"', self.page)
        self.assertIn('回执项: "结果去向"', self.page)
        self.assertIn("include_tushare=${String(quantProjectionAcceptedPayload.include_tushare ?? true)}", self.page)
        self.assertIn("include_deepseek=${String(quantProjectionAcceptedPayload.include_deepseek ?? false)}", self.page)
        self.assertIn("回执项: confirmedTaskReceiptLabel(row.receipt_item)", self.page)
        self.assertIn("GET cache 只读回放；不创建任务、不补调数据源或模型", self.page)
        self.assertIn("task id 来自按钮门控 POST 或 cache packet 回放；GET cache 不创建任务", self.page)
        self.assertIn("只有 POST task / worker 可调用 Tushare；React render、搜索输入、GET cache 不外联", self.page)
        self.assertIn("DeepSeek 等 governed executor；不真实交易、不改 strategy action", self.page)
        self.assertIn("quantProjectionPostConfirmActionRows", self.page)
        self.assertIn("quantProjectionOrdinaryConfirmOutcomeRows", self.page)
        self.assertIn("quantProjectionConfirmReplayStage", self.page)
        self.assertIn("quantProjectionConfirmReplayStageRows", self.page)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_confirm_replay_stage_rows", self.page)
        self.assertIn("quantProjectionConfirmReplayStageRows.length ? quantProjectionConfirmReplayStageRows", self.page)
        self.assertIn('label: "P1/P2 当前阶段"', self.page)
        self.assertIn("P1 ready：点击确认后创建 Tushare-first POST task", self.page)
        self.assertIn("P1 accepted：任务已接收；等待 TaskStatusPanel success 后刷新 cache", self.page)
        self.assertIn("P2 ready：cache / ledger / packet 已进入本地回放", self.page)
        self.assertIn("P1 blocked：确认任务未创建；先恢复本地 FastAPI 连接", self.page)
        self.assertIn('aria-label="quant projection ordinary confirm outcome quick read"', self.page)
        self.assertIn("P1 确认结果速读", self.page)
        self.assertIn("优先读取服务端 ordinary_confirm_outcome_rows：点击确认后先看任务是否接收、P2 三面是否回放、P3 入口是否可读；这张速读表不创建第二个任务。", self.page)
        self.assertIn('速读项: "P1/P2 当前阶段"', self.page)
        self.assertIn('速读项: displayText(row["速读项"] ?? row.stage_key)', self.page)
        self.assertIn("阶段只由本地 task receipt / cache 推导；不创建 task、不补调 provider/model", self.page)
        self.assertIn("GET cache 只读回放；不创建 task、不补调 provider/model", self.page)
        self.assertIn('速读项: "确认任务"', self.page)
        self.assertIn('速读项: "任务编号"', self.page)
        self.assertIn('速读项: "结果回放"', self.page)
        self.assertIn("只解释确认按钮是否创建本地 POST task；不会从摘要补调 provider/model", self.page)
        self.assertIn("TaskStatusPanel 只轮询本地 FastAPI，完成后刷新 cache", self.page)
        self.assertIn("结果只从 cache / ledger / packet 回放；不交易、不改 strategy action", self.page)
        self.assertIn("quantProjectionPostConfirmPacketRows", self.page)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_post_confirm_action_rows", self.page)
        self.assertIn("quantProjectionPostConfirmPacketRows.length ? quantProjectionPostConfirmPacketRows", self.page)
        self.assertIn("quantProjectionTaskSuccessRefreshRows", self.page)
        self.assertIn("quantProjectionPostConfirmOneScreenItems", self.page)
        self.assertIn('aria-label="candidate radar post confirm one screen outcome"', self.page)
        self.assertIn("确认后一屏结果", self.page)
        self.assertIn("任务是否接收、P2 三面是否回放、P3 结论是否可读和下一步入口都在一屏内", self.page)
        self.assertIn("这条结果条只读本地 task receipt 与 cache / ledger / packet，不创建第二个 task", self.page)
        self.assertIn('label: "任务接收"', self.page)
        self.assertIn('label: "当前阶段"', self.page)
        self.assertIn('label: "P2 三面"', self.page)
        self.assertIn('label: "P3 结论"', self.page)
        self.assertIn('label: "下一步入口"', self.page)
        self.assertIn('label: "只读边界"', self.page)
        self.assertIn("只读回放 task receipt / cache / ledger / packet；不创建第二个 task、不交易、不改 action", self.page)
        self.assertIn("quantProjectionFirstScreenTaskContractItems", self.page)
        self.assertIn('aria-label="candidate radar first screen p1 task contract quick read"', self.page)
        self.assertIn("确认按钮任务链速读", self.page)
        self.assertIn("普通用户不用展开链路详情也能看到", self.page)
        self.assertIn('label: "POST 路由"', self.page)
        self.assertIn('value: "POST /api/candidate-radar/quant-projection"', self.page)
        self.assertIn('label: "task_type"', self.page)
        self.assertIn('value: "run_candidate_radar_quant_projection"', self.page)
        self.assertIn('label: "触发方式"', self.page)
        self.assertIn("只在确认按钮点击后创建；输入、页面打开、React render 和 GET cache 静默", self.page)
        self.assertIn('label: "写回三面"', self.page)
        self.assertIn('value: "cache / call_ledger / packet"', self.page)
        self.assertIn('label: "交易边界"', self.page)
        self.assertIn("不真实交易、不下单、不改 strategy action", self.page)
        first_screen_start = self.page.index('aria-label="candidate radar first screen quant projection confirmation"')
        first_screen_contract_index = self.page.index('aria-label="candidate radar first screen p1 task contract quick read"', first_screen_start)
        one_screen_result_index = self.page.index('aria-label="candidate radar post confirm one screen outcome"', first_screen_start)
        p1_chain_details_index = self.page.index('aria-label="candidate radar first screen p1 chain details"', first_screen_start)
        post_confirm_guide_index = self.page.index('aria-label="candidate radar first screen post confirm readback guide"', first_screen_start)
        p1_details_index = self.page.index('aria-label="candidate radar ordinary p1 p2 detail readback"', first_screen_start)
        self.assertIn("<summary>P1 链路与确认后清单</summary>", self.page)
        self.assertIn("按钮路由、回放清单和链路排障默认收起", self.page)
        self.assertLess(first_screen_contract_index, one_screen_result_index)
        self.assertLess(first_screen_contract_index, p1_chain_details_index)
        self.assertLess(one_screen_result_index, post_confirm_guide_index)
        self.assertLess(one_screen_result_index, p1_chain_details_index)
        self.assertLess(p1_chain_details_index, post_confirm_guide_index)
        self.assertLess(one_screen_result_index, p1_details_index)
        first_screen_contract_slice = self.page[first_screen_contract_index:one_screen_result_index]
        self.assertIn("MetricGrid items={quantProjectionFirstScreenTaskContractItems}", first_screen_contract_slice)
        self.assertNotIn("postCandidateRadarQuantProjection", first_screen_contract_slice)
        self.assertNotIn("postTask(", first_screen_contract_slice)
        self.assertNotIn("onClick=", first_screen_contract_slice)
        one_screen_result_slice = self.page[one_screen_result_index:post_confirm_guide_index]
        self.assertIn("MetricGrid items={quantProjectionPostConfirmOneScreenItems}", one_screen_result_slice)
        self.assertNotIn("postCandidateRadarQuantProjection", one_screen_result_slice)
        self.assertNotIn("postTask(", one_screen_result_slice)
        self.assertIn('aria-label="quant projection post confirm user actions"', self.page)
        self.assertIn("确认后看什么", self.page)
        self.assertIn("点击确认后先看任务编号和 TaskStatusPanel，再刷新本地 cache，最后回放量化推演和次日图谱", self.page)
        self.assertIn('行动: "1. 看任务编号"', self.page)
        self.assertIn('行动: "2. 看任务进度"', self.page)
        self.assertIn('行动: "3. 刷新本地 cache"', self.page)
        self.assertIn('行动: "4. 回放结果"', self.page)
        self.assertIn("TaskStatusPanel 可轮询本地 FastAPI", self.page)
        self.assertIn("等待 success 后刷新本地 cache", self.page)
        self.assertIn("GET cache 只读回放，不补调 provider/model、不泄露 token/key", self.page)
        self.assertIn("只切换 #factor/#next 锚点，不重新创建 task、不改 strategy action", self.page)
        self.assertIn('aria-label="quant projection task success refresh checklist"', self.page)
        self.assertIn("任务成功后自动回读", self.page)
        self.assertIn("TaskStatusPanel success 后调用 refreshQuantProjectionReadback：只回读 CandidateRadar cache 和 bootstrap status", self.page)
        self.assertIn("再让用户看 P2 三面与 P3 结果入口；不会创建第二个 task", self.page)
        self.assertIn("DataLineageTable rows={quantProjectionTaskSuccessRefreshRows}", self.page)
        self.assertIn('回读项: "1. TaskStatusPanel success"', self.page)
        self.assertIn('回读项: "2. cache / ledger / packet"', self.page)
        self.assertIn('回读项: "3. 结果入口"', self.page)
        self.assertIn("调用 refreshQuantProjectionReadback，回读 CandidateRadar cache 和 bootstrap status", self.page)
        self.assertIn("refreshCache() 只读取 GET /api/candidate-radar/cache", self.page)
        self.assertIn("TaskStatusPanel 只轮询本地 FastAPI；success 回调不创建第二个 task、不补调 Tushare/DeepSeek", self.page)
        self.assertIn("GET cache 只读；不展示 raw log、token/key 或 provider error", self.page)
        self.assertIn('步骤: "输入校验"', self.page)
        self.assertIn('步骤: "点击确认"', self.page)
        self.assertIn('步骤: "Tushare 写入"', self.page)
        self.assertIn('步骤: "结果回放"', self.page)
        self.assertIn("搜索输入、React render、GET cache 不外联", self.page)
        self.assertIn("只有用户确认后才进入后台链", self.page)
        self.assertIn("凭据缺失只写本地阻断，不补调 DeepSeek", self.page)
        self.assertIn("不交易、不改 strategy action", self.page)
        self.assertIn("quantProjectionSmallDataWritebackStatus", self.page)
        self.assertIn("quantProjectionSmallDataWritebackRows", self.page)
        self.assertIn("quantProjectionSmallDataTargetRows", self.page)
        self.assertIn("quantProjectionSmallDataActionRows", self.page)
        self.assertIn("quantProjectionWritebackSurfaceSummaryRows", self.page)
        self.assertIn("quantProjectionWritebackSurfaceRows", self.page)
        self.assertIn("quantProjectionWritebackRecoveryRows", self.page)
        self.assertIn("quantProjectionWritebackRecoveryDisplayRows", self.page)
        self.assertIn("quantProjectionP2WritebackRailState", self.page)
        self.assertIn("quantProjectionP2WritebackRailSteps", self.page)
        self.assertIn("const quantProjectionSmallDataExplicitReady", self.page)
        self.assertIn("const quantProjectionSmallDataPartialLedgerReady", self.page)
        self.assertIn("const quantProjectionSmallDataReady = quantProjectionSmallDataExplicitReady", self.page)
        self.assertIn("cache / packet 仍等待小数据三面 ready", self.page)
        self.assertIn("部分恢复：call_ledger 已回放，cache / packet 仍等待小数据三面 ready。", self.page)
        self.assertNotIn(
            "small_data_writeback_ready === true || quantProjectionProviderLedgerReady",
            self.page,
        )
        self.assertIn("ordinary_writeback_target_rows", self.page)
        self.assertIn("ordinary_writeback_action_rows", self.page)
        self.assertIn("ordinary_writeback_surface_summary_rows", self.page)
        self.assertIn("ordinary_writeback_recovery_rows", self.page)
        self.assertLess(
            self.page.index("quantProjectionSmallDataTargetRows.length"),
            self.page.index("quantProjectionSmallDataOrdinaryReadbackRows.length"),
        )
        self.assertIn('aria-label="quant projection ordinary small data writeback targets"', self.page)
        self.assertIn('aria-label="quant projection ordinary writeback surface summary"', self.page)
        self.assertIn('aria-label="quant projection ordinary small data writeback actions"', self.page)
        self.assertIn('aria-label="candidate radar ordinary p2 writeback rail"', self.page)
        self.assertIn('label="candidate radar ordinary p2 writeback rail"', self.page)
        self.assertIn("P2 三面状态轨", self.page)
        self.assertIn("先扫 cache、call_ledger、packet 三面是否可读", self.page)
        self.assertIn("这条状态轨只读本地回放，不展示接口级 raw log", self.page)
        self.assertIn('label: "cache"', self.page)
        self.assertIn('label: "call_ledger"', self.page)
        self.assertIn('label: "packet"', self.page)
        self.assertIn('label: "只读边界"', self.page)
        p2_rail_start = self.page.index('aria-label="candidate radar ordinary p2 writeback rail"')
        p2_surface_start = self.page.index('aria-label="candidate radar ordinary p2 writeback surfaces"')
        p2_rail_slice = self.page[p2_rail_start:p2_surface_start]
        self.assertIn("<StateClarityRail", p2_rail_slice)
        self.assertNotIn("onClick=", p2_rail_slice)
        self.assertNotIn("postCandidateRadarQuantProjection", p2_rail_slice)
        self.assertIn("小数据写入位置", self.page)
        self.assertIn("P2 写入面速读", self.page)
        self.assertIn("优先读取服务端 ordinary_writeback_surface_summary_rows", self.page)
        self.assertIn("普通入口只看 cache、call_ledger、packet 三个写入面是否可回放", self.page)
        self.assertIn("GET cache 不创建 task", self.page)
        self.assertIn('aria-label="candidate radar ordinary p2 writeback recovery"', self.page)
        self.assertIn("P2 阻断恢复速读", self.page)
        self.assertIn("区分任务等待、服务端凭据阻断和 DeepSeek 单独补", self.page)
        self.assertIn("它只读本地 cache，不创建任务", self.page)
        self.assertIn("确认按钮是唯一可创建 Tushare-first 后台链路的普通入口。", self.page)
        self.assertIn("DeepSeek governed executor 单独补；P2 阻断恢复不等待模型。", self.page)
        self.assertIn("不会创建 task、不调用 provider/model", self.page)
        self.assertIn("小数据行动清单", self.page)
        self.assertIn("优先读取服务端 ordinary_writeback_action_rows", self.page)
        self.assertIn("看任务、看 ledger、刷新 cache、回放结果", self.page)
        self.assertIn("不会从回放行创建 task", self.page)
        self.assertIn("小数据写入位置可回放：cache、call_ledger、packet 已有本地读回；普通入口只显示位置和状态。", self.page)
        self.assertIn("小数据写入等待后台完成：先看任务状态，成功后刷新本地 cache 回放 cache、call_ledger、packet。", self.page)
        self.assertIn("小数据写入等待确认按钮：输入或搜索不会写 cache、call_ledger、packet。", self.page)
        self.assertIn('写入位置: "cache"', self.page)
        self.assertIn('写入位置: "call_ledger"', self.page)
        self.assertIn('写入位置: "packet"', self.page)
        self.assertIn("接口级明细下沉到高级状态", self.page)
        self.assertIn("普通页面不展示 token/key、raw log 或 provider error", self.page)
        self.assertIn("packet 不包含凭据、不生成交易动作、不覆盖 strategy action", self.page)
        self.assertIn(
            '<details className="developer-audit-details" aria-label="quant projection task cache packet readback">',
            self.page,
        )
        self.assertIn("<summary>任务 / cache packet 回放详情</summary>", self.page)
        self.assertIn("任务回放清单", self.page)
        self.assertIn(
            "普通入口只保留任务状态轨和结果速读；task id、safe current_step、cache packet 明细默认收起。",
            self.page,
        )
        self.assertIn("任务编号和安全步骤优先从本地 cache / packet 回放", self.page)
        self.assertIn("TaskStatusPanel 只轮询本地 FastAPI 任务状态", self.page)
        self.assertIn('回放项: "task_id"', self.page)
        self.assertIn('回放项: "current_step"', self.page)
        self.assertIn('回放项: "TaskStatusPanel"', self.page)
        self.assertIn("GET cache 只读回放 task id，不创建 task、不补调 provider/model", self.page)
        self.assertIn("只展示 safe current_step；不展示 raw log、token/key 或 provider error", self.page)
        self.assertIn("轮询本地任务状态，不调用 Tushare/DeepSeek/GitHub、不写交易动作", self.page)
        self.assertIn('aria-label="quant projection ordinary explainable result readback"', self.page)
        self.assertIn('id="factor" aria-label="quant projection factor replay anchor"', self.page)
        self.assertIn('id="next" aria-label="quant projection ordinary explainable result readback"', self.page)
        self.assertIn("quantProjectionReadbackIndexRows", self.page)
        self.assertIn('aria-label="quant projection ordinary readback index"', self.page)
        self.assertIn('aria-label="quant projection ordinary explainable result quick read"', self.page)
        self.assertIn('aria-label="quant projection ordinary deepseek governance status"', self.page)
        self.assertIn("解释结果清单", self.page)
        self.assertIn("P2/P3 回放清单", self.page)
        self.assertIn("读取本地 packet 回放索引", self.page)
        self.assertIn("确认回执、任务回放、数据接口和 P3 结果速读都只做本地回放", self.page)
        self.assertIn('回放清单: "确认回执"', self.page)
        self.assertIn('回放清单: "任务回放"', self.page)
        self.assertIn('回放清单: "数据接口回放"', self.page)
        self.assertIn('回放清单: "P3 结果速读"', self.page)
        self.assertIn("可回放项: Number(counts.search_quant_projection_confirmed_task_receipt_row_count", self.page)
        self.assertIn('只读边界: policy.search_quant_projection_confirmed_task_receipt_rows_are_cache_only === false ? "待复核" : "只读回放"', self.page)
        self.assertIn("counts.search_quant_projection_confirmed_task_receipt_row_count", self.page)
        self.assertIn("counts.search_quant_projection_task_readback_row_count", self.page)
        self.assertIn("counts.search_quant_projection_provider_api_row_count", self.page)
        self.assertIn("policy.search_quant_projection_confirmed_task_receipt_rows_are_cache_only", self.page)
        self.assertIn("policy.search_quant_projection_task_readback_rows_are_cache_only", self.page)
        self.assertIn("policy.search_quant_projection_provider_api_rows_are_cache_only", self.page)
        self.assertIn("数据接口行只读回放 ledger 状态；React render 不调用 provider/model", self.page)
        self.assertIn("结果速读不创建 task、不调用模型、不生成交易动作", self.page)
        result_readback_start = self.page.index('aria-label="quant projection ordinary explainable result readback"')
        result_quick_start = self.page.index('aria-label="quant projection ordinary explainable result quick read"', result_readback_start)
        result_checkpoint_start = self.page.index('aria-label="quant projection ordinary result checkpoint"', result_quick_start)
        result_handoff_start = self.page.index('aria-label="quant projection ordinary result handoff index"', result_checkpoint_start)
        ordinary_readback_slice = self.page[result_readback_start:result_quick_start]
        self.assertNotIn("直接读取 packet 顶层 counts / policy", ordinary_readback_slice)
        self.assertNotIn('索引: "Provider API"', ordinary_readback_slice)
        self.assertNotIn('只读策略:', ordinary_readback_slice)
        self.assertLess(result_quick_start, result_checkpoint_start)
        self.assertLess(result_checkpoint_start, result_handoff_start)
        self.assertIn("P3 结果速读", self.page)
        self.assertIn("优先读取服务端 ordinary_result_quick_read_rows", self.page)
        self.assertIn('aria-label="candidate radar ordinary p3 result checkpoint"', self.page)
        self.assertIn('aria-label="quant projection ordinary result checkpoint"', self.page)
        self.assertIn("P3 结果检查点", self.page)
        self.assertIn("ordinary_result_checkpoint_rows", self.page)
        self.assertIn("rows={quantProjectionOrdinaryResultCheckpointRows}", self.page)
        self.assertIn("确认可读结论、来源、缺口和安全字段", self.page)
        self.assertIn("这张检查点表只读本地 cache，不创建 task、不调用模型", self.page)
        self.assertIn("quantProjectionOrdinaryResultHandoffRows", self.page)
        self.assertIn("ordinary_result_handoff_rows", self.page)
        self.assertIn('aria-label="quant projection ordinary result handoff index"', self.page)
        self.assertIn("P3 结果入口索引", self.page)
        self.assertIn("优先读取服务端 ordinary_result_handoff_rows", self.page)
        self.assertIn("把可读结论、量化推演、次日图谱和候选池绑定到同一个本地来源任务", self.page)
        self.assertIn("链接只切换入口，不创建 task", self.page)
        self.assertIn('来源任务: displayText(row["来源任务"] ?? row.source_task_id, "waiting_confirm_task")', self.page)
        self.assertIn("先看可读结论、来源组成、回放来源和待补证据", self.page)
        self.assertIn("不会从结果速读创建 task 或调用模型", self.page)
        self.assertIn("P5 DeepSeek 治理状态", self.page)
        self.assertIn("优先读取服务端 ordinary_model_governance_rows", self.page)
        self.assertIn("只看执行门控、输出范围和是否阻塞基础图谱", self.page)
        self.assertIn("不会从治理状态创建 task 或调用模型", self.page)
        self.assertIn("quantProjectionDeepSeekChecklistRows", self.page)
        self.assertIn("quantProjectionDeepSeekReadinessRows", self.page)
        self.assertIn("quantProjectionDeepSeekContractRows", self.page)
        self.assertIn("ordinary_deepseek_governed_executor_checklist_rows", self.page)
        self.assertIn("ordinary_deepseek_governed_executor_readiness_rows", self.page)
        self.assertIn("ordinary_deepseek_governed_executor_contract_rows", self.page)
        self.assertIn('aria-label="candidate radar ordinary p5 governed executor contract"', self.page)
        self.assertIn('aria-label="quant projection ordinary deepseek governed executor contract"', self.page)
        self.assertIn("P5 DeepSeek 单独补证合同", self.page)
        self.assertIn("未来 DeepSeek 只能作为单独 P5 按钮任务", self.page)
        self.assertIn("明确未来单独 P5 task、model_ledger、sanitizer、output acceptance、安全字段和不阻塞 P1/P2/P3", self.page)
        self.assertIn('aria-label="quant projection ordinary deepseek governed executor checklist"', self.page)
        self.assertIn('aria-label="quant projection ordinary deepseek governed executor readiness"', self.page)
        self.assertIn("P5 governed executor readiness", self.page)
        self.assertIn("说明何时才允许单独补 DeepSeek、当前为什么不能调、以及后续只能写安全摘要", self.page)
        self.assertIn("这张表只读回放，不创建 task、不调用模型", self.page)
        self.assertIn("P5 governed executor 补证清单", self.page)
        self.assertIn("model_ledger、sanitizer/redaction、output acceptance、安全回退和不覆盖 action 都必须先满足", self.page)
        self.assertIn("这张清单不创建 task、不调用模型", self.page)
        deepseek_details_start = self.page.index('aria-label="quant projection ordinary deepseek governance status"')
        deepseek_contract_index = self.page.index('aria-label="quant projection ordinary deepseek governed executor contract"', deepseek_details_start)
        deepseek_readiness_index = self.page.index('aria-label="quant projection ordinary deepseek governed executor readiness"', deepseek_details_start)
        deepseek_checklist_index = self.page.index('aria-label="quant projection ordinary deepseek governed executor checklist"', deepseek_details_start)
        self.assertLess(deepseek_contract_index, deepseek_readiness_index)
        self.assertLess(deepseek_readiness_index, deepseek_checklist_index)
        self.assertIn('检查项: displayText(row["检查项"] ?? row.check_key)', self.page)
        self.assertIn("普通入口只回放数据来源、量化推演、次日图谱和安全边界", self.page)
        self.assertIn("原始 receipt、prompt 或审计字段仍下沉在详情中", self.page)
        self.assertIn('结论: "现在能读什么"', self.page)
        self.assertIn('结论: "结果从哪里回放"', self.page)
        self.assertIn('结论: "还缺什么"', self.page)
        self.assertIn('治理项: "执行门控"', self.page)
        self.assertIn('治理项: "输出范围"', self.page)
        self.assertIn('治理项: "不阻塞基础图谱"', self.page)
        self.assertIn('回放项: "数据来源"', self.page)
        self.assertIn('回放项: "量化推演"', self.page)
        self.assertIn('回放项: "次日图谱"', self.page)
        self.assertIn('回放项: "安全边界"', self.page)
        self.assertIn("GET cache 只读回放已有账本；不补调 Tushare、DeepSeek 或 worker", self.page)
        self.assertIn("次日图谱只读回放本地 cache；缺口只作为待补证据，不创建交易动作", self.page)
        self.assertIn("DeepSeek 未参与；候选雷达不是买入指令；真实交易路径隔离", self.page)
        self.assertIn('aria-label="quant projection replay destinations"', self.page)
        self.assertIn('href="#factor" title="切换到股票量化推演模块；只读 cache / ledger / packet，不创建 task" aria-label="replay generated stock quant projection"', self.page)
        self.assertIn('href="#next" title="切换到次日图谱模块；只读本地 next-session cache，不创建 task" aria-label="replay generated next session map"', self.page)
        self.assertIn('href="#candidate-pool" title="跳回本页候选池锚点；不重新扫描、不创建 task" aria-label="return to candidate pool after quant projection"', self.page)
        self.assertLess(self.page.index('id="factor"'), self.page.index('title="搜票量化推演"'))
        self.assertLess(self.page.index('id="next"'), self.page.index('href="#next" title="切换到次日图谱模块；只读本地 next-session cache，不创建 task" aria-label="replay generated next session map"'))
        self.assertIn("回放股票量化推演", self.page)
        self.assertIn("回放次日图谱", self.page)
        self.assertIn("回放入口区分本地模块路由和页内锚点", self.page)
        self.assertIn("#factor/#next 切换到量化推演和次日图谱模块", self.page)
        self.assertIn("#candidate-pool 留在候选池", self.page)
        self.assertIn("quantProjectionReplayDestinationState", self.page)
        self.assertIn("quantProjectionReplayDestinationNextStep", self.page)
        self.assertIn("quantProjectionReplayDestinationPacketRows", self.page)
        self.assertIn("quantProjectionReplayDestinationRows", self.page)
        self.assertIn("searchQuantProjectionSmallDataWriteback.ordinary_replay_destination_rows", self.page)
        self.assertIn("const quantProjectionReplayDestinationRows = quantProjectionReplayDestinationPacketRows.length ? quantProjectionReplayDestinationPacketRows", self.page)
        self.assertIn('aria-label="quant projection replay destination readiness"', self.page)
        self.assertIn("结果入口待确认：当前只是本地导航；不会创建 task 或刷新 provider/model", self.page)
        self.assertIn("结果入口等待缓存：先看 TaskStatusPanel，任务完成并刷新 cache 后再回放", self.page)
        self.assertIn("结果入口可回放：读取本地 cache / ledger / packet，不额外刷新外部数据或模型", self.page)
        self.assertIn("结果入口暂停：确认任务未创建；先恢复本地后端连接，再重新点击确认", self.page)
        self.assertIn('入口: "股票量化推演"', self.page)
        self.assertIn('入口: "次日图谱"', self.page)
        self.assertIn('入口: "候选池"', self.page)
        self.assertIn("href #factor 是本地量化推演模块路由；只切换模块，不发 POST task、不调 Tushare/DeepSeek", self.page)
        self.assertIn("href #next 是本地次日图谱模块路由；只切换模块，不生成交易动作、不覆盖 strategy action", self.page)
        self.assertIn("href #candidate-pool 是本页候选池锚点；Radar candidate 不是交易指令；真实交易路径继续隔离", self.page)
        self.assertIn('aria-label="quant projection advanced status readback"', self.page)
        self.assertIn("<summary>高级状态回放</summary>", self.page)
        quant_projection_start = self.page.index('title="搜票量化推演"')
        p1_p2_details_index = self.page.index('aria-label="quant projection ordinary p1 p2 engineering details"', quant_projection_start)
        trigger_boundary_index = self.page.index('aria-label="quant projection ordinary confirm trigger boundary"', quant_projection_start)
        compact_confirm_index = self.page.index('label: "确认状态"', quant_projection_start)
        end_to_end_index = self.page.index('aria-label="quant projection ordinary end to end path"', quant_projection_start)
        handoff_index = self.page.index('aria-label="quant projection ordinary confirmation handoff"', quant_projection_start)
        receipt_index = self.page.index('aria-label="quant projection confirmed task receipt readback"', quant_projection_start)
        post_confirm_index = self.page.index('aria-label="quant projection post confirm user actions"', quant_projection_start)
        small_data_writeback_index = self.page.index('aria-label="quant projection ordinary small data writeback targets"', quant_projection_start)
        writeback_surface_index = self.page.index('aria-label="quant projection ordinary writeback surface summary"', quant_projection_start)
        ordinary_result_index = self.page.index('aria-label="quant projection ordinary explainable result readback"', quant_projection_start)
        readback_index = self.page.index('aria-label="quant projection ordinary readback index"', quant_projection_start)
        ordinary_result_quick_index = self.page.index('aria-label="quant projection ordinary explainable result quick read"', quant_projection_start)
        ordinary_result_checkpoint_index = self.page.index('aria-label="quant projection ordinary result checkpoint"', quant_projection_start)
        ordinary_result_handoff_index = self.page.index('aria-label="quant projection ordinary result handoff index"', quant_projection_start)
        deepseek_governance_index = self.page.index('aria-label="quant projection ordinary deepseek governance status"', quant_projection_start)
        replay_destinations_index = self.page.index('aria-label="quant projection replay destinations"', quant_projection_start)
        replay_readiness_index = self.page.index('aria-label="quant projection replay destination readiness"', quant_projection_start)
        task_readback_index = self.page.index('aria-label="quant projection task cache packet readback"', quant_projection_start)
        advanced_index = self.page.index("<summary>高级状态回放</summary>", quant_projection_start)
        provider_replay_index = self.page.index('aria-label="quant projection tushare light api replay"', quant_projection_start)
        record_details_index = self.page.index("<summary>搜票推演记录详情</summary>", quant_projection_start)
        self.assertIn("<summary>P1/P2 任务与写入详情</summary>", self.page)
        self.assertLess(p1_p2_details_index, trigger_boundary_index)
        self.assertLess(trigger_boundary_index, compact_confirm_index)
        self.assertLess(trigger_boundary_index, advanced_index)
        self.assertLess(compact_confirm_index, advanced_index)
        self.assertLess(compact_confirm_index, end_to_end_index)
        self.assertLess(end_to_end_index, handoff_index)
        self.assertLess(handoff_index, small_data_writeback_index)
        self.assertLess(handoff_index, receipt_index)
        self.assertLess(receipt_index, post_confirm_index)
        self.assertLess(post_confirm_index, small_data_writeback_index)
        self.assertLess(small_data_writeback_index, writeback_surface_index)
        self.assertLess(writeback_surface_index, ordinary_result_index)
        self.assertLess(ordinary_result_index, readback_index)
        self.assertLess(readback_index, ordinary_result_quick_index)
        self.assertLess(ordinary_result_quick_index, ordinary_result_checkpoint_index)
        self.assertLess(ordinary_result_checkpoint_index, ordinary_result_handoff_index)
        self.assertLess(ordinary_result_handoff_index, deepseek_governance_index)
        self.assertLess(ordinary_result_index, ordinary_result_quick_index)
        self.assertLess(deepseek_governance_index, replay_destinations_index)
        self.assertLess(small_data_writeback_index, ordinary_result_index)
        self.assertLess(ordinary_result_index, replay_destinations_index)
        self.assertLess(replay_destinations_index, replay_readiness_index)
        self.assertLess(replay_readiness_index, task_readback_index)
        self.assertLess(task_readback_index, advanced_index)
        self.assertLess(advanced_index, provider_replay_index)
        self.assertLess(provider_replay_index, record_details_index)
        self.assertIn("页面刷新后，最近任务会优先从本地 cache / packet 回放 task id 和安全 current_step", self.page)
        self.assertIn("GET cache 不会因此补调 provider", self.page)
        self.assertIn("确认按钮只提交后台链路", self.page)
        self.assertIn("服务端凭据可用才写入 Tushare call_ledger / cache / packet", self.page)
        self.assertIn("GET cache 和 React render 不补调 provider", self.page)
        self.assertIn("DeepSeek 默认 skipped，需 governed executor 完成后再单独补", self.page)
        self.assertIn('aria-live="polite"', self.page)
        self.assertLess(
            self.page.index('label: "确认代码"', quant_projection_start),
            self.page.index('label: "任务边界"', quant_projection_start),
        )
        self.assertIn("输入不触发外联；点击确认后只经 POST task / worker 后台运行", self.page)
        self.assertIn("React 渲染不直连 Tushare 或 DeepSeek", self.page)
        self.assertIn("Tushare 小全量数据写入 call_ledger", self.page)
        self.assertIn("待 governed executor / model_ledger 后再展示缓存", self.page)
        self.assertIn("DeepSeek 保持 skipped", self.page)
        self.assertIn("ordinary_readback_summary", self.page)
        self.assertIn("ordinary_readback_next_step", self.page)
        self.assertIn("ordinary_readback_boundary", self.page)
        self.assertIn("ordinary_readback_surfaces_label", self.page)
        self.assertIn("ordinary_provider_api_rows", self.page)
        self.assertIn("quantProjectionProviderApiRows", self.page)
        self.assertIn('aria-label="quant projection tushare light api replay"', self.page)
        self.assertIn("Tushare light 接口回放", self.page)
        self.assertIn("trade_cal / daily / daily_basic / moneyflow", self.page)
        self.assertIn("表格只读，不补调数据源或模型", self.page)
        self.assertIn('label: "小数据下一步"', self.page)
        self.assertIn("小数据回放只读取本地 cache / ledger / packet", self.page)
        self.assertIn("推演解释只整理已有证据；不覆盖价格、持仓、因子、操作区或交易策略", self.page)

    def test_p1_symbol_input_is_shared_and_silent_until_confirm(self):
        self.assertIn(
            "const quantProjectionCanSubmit = quantProjectionSymbolReady && quantProjectionP0Ready;",
            self.page,
        )
        self.assertIn("const quantProjectionHistoricalTaskMatchesInput =", self.page)
        self.assertNotIn("quantProjectionTaskAlreadyAcceptedForInput", self.page)
        self.assertIn("const quantProjectionSubmitDisabled = !quantProjectionCanSubmit || quantProjectionSubmitting;", self.page)
        self.assertEqual(self.page.count("setSearchSymbol(event.target.value);"), 3)
        self.assertEqual(self.page.count("onClick={launchQuantProjection}"), 3)
        self.assertIn('aria-label="candidate radar first screen quant projection symbol"', self.page)
        self.assertIn('aria-label="radar summary quant projection symbol"', self.page)
        self.assertIn('aria-label="search quant projection symbol"', self.page)
        self.assertIn("输入股票代码只做本地校验；不会创建任务，也不会调用 Tushare 或 DeepSeek", self.page)
        self.assertIn("点击确认才创建 ${quantProjectionSymbolValidation.normalized} 的 Tushare-first POST task", self.page)
        submit_start = self.page.index("const launchQuantProjection = () =>")
        submit_end = self.page.index("const launchQuantProjectionAcceptanceDryRun = () =>", submit_start)
        submit_slice = self.page[submit_start:submit_end]
        self.assertIn("if (!quantProjectionCanSubmit || quantProjectionSubmitting) return;", submit_slice)
        self.assertIn("void postCandidateRadarQuantProjection({", submit_slice)
        self.assertNotIn("setSearchSymbol(event.target.value);", submit_slice)

    def test_ordinary_quant_projection_submit_does_not_auto_chain_provider_model(self):
        submit_start = self.page.index("const launchQuantProjection = () =>")
        submit_end = self.page.index("const launchQuantProjectionAcceptanceDryRun = () =>", submit_start)
        submit_slice = self.page[submit_start:submit_end]
        summary_start = self.page.index('title="普通用户雷达摘要"')
        summary_end = self.page.index('title="下一票候选池"', summary_start)
        summary_slice = self.page[summary_start:summary_end]
        confirm_quick_start = self.page.index('aria-label="quant projection ordinary confirm outcome quick read"', summary_start)
        post_confirm_start = self.page.index('aria-label="quant projection post confirm user actions"')
        post_confirm_end = self.page.index('aria-label="quant projection ordinary small data writeback targets"', post_confirm_start)
        post_confirm_slice = self.page[post_confirm_start:post_confirm_end]
        task_status_start = self.page.index('aria-label="quant projection tushare-first task status"')
        task_status_end = self.page.index('aria-label="quant projection confirm chain explanation details"', task_status_start)
        task_status_slice = self.page[task_status_start:task_status_end]

        self.assertIn("postCandidateRadarQuantProjection({", submit_slice)
        self.assertIn('scan_mode: "search_quant_projection"', submit_slice)
        self.assertIn("symbol: normalizeAshareSymbolInput(searchSymbol).normalized", submit_slice)
        self.assertIn("include_tushare: true", submit_slice)
        self.assertIn("include_deepseek: false", submit_slice)
        self.assertIn("user_approved: true", submit_slice)
        self.assertIn('requested_by: "candidate_radar_page"', submit_slice)
        self.assertIn('.catch(() => {', submit_slice)
        self.assertIn('quantProjectionSubmitFailureMessage("frontend_submit_exception")', submit_slice)
        self.assertIn("setQuantProjectionSubmitting(false)", submit_slice)
        self.assertNotIn("run_provider_model_now", submit_slice)
        self.assertNotIn("operator_approved", submit_slice)
        self.assertNotIn("quant-projection-provider-model-acceptance", submit_slice)

        self.assertIn("查看本地缓存", summary_slice)
        self.assertIn("运行本地快扫", summary_slice)
        self.assertIn("确认并生成 3.0 量化推演", summary_slice)
        self.assertIn("disabled={quantProjectionSubmitDisabled}", summary_slice)
        self.assertIn('{quantProjectionSubmitting ? "提交中..." : "确认并生成 3.0 量化推演"}', summary_slice)
        self.assertIn("quantProjectionSubmitErrorLabel", summary_slice)
        self.assertIn('aria-label="candidate radar p0 submit failure recovery"', summary_slice)
        self.assertIn("优先读取 POST 失败 envelope 里的 frontend_backend_auto_link ledger", summary_slice)
        self.assertIn("恢复提示只读展示，不自动重试、不创建 task", summary_slice)
        self.assertIn('aria-label="candidate radar ordinary expanded p1 p3 readback details"', summary_slice)
        self.assertIn("<summary>更多回放明细</summary>", summary_slice)
        self.assertIn("普通主视图保留 P1 确认、任务状态、P2 三面速读和 P3 首屏结果", summary_slice)
        self.assertIn("{quantProjectionInputSessionState}", summary_slice)
        self.assertIn('href="#factor"', summary_slice)
        self.assertIn("{quantProjectionSummaryGuidance}", summary_slice)
        self.assertIn("quantProjectionOrdinaryConfirmOutcomeRows", summary_slice)
        self.assertIn("P1 确认结果速读", summary_slice)
        self.assertIn("优先读取服务端 ordinary_confirm_outcome_rows", summary_slice)
        self.assertIn("任务是否接收、P2 三面是否回放、P3 入口是否可读", summary_slice)
        self.assertIn("quantProjectionOneScreenActionRows", summary_slice)
        self.assertIn('aria-label="candidate radar ordinary one screen actions"', summary_slice)
        self.assertIn("一屏行动摘要", summary_slice)
        self.assertIn("确认、任务、写回、结果合成一张普通用户表", summary_slice)
        self.assertIn("rows={quantProjectionOneScreenActionRows}", summary_slice)
        self.assertIn('aria-label="candidate radar ordinary p2 p3 replay checklist"', summary_slice)
        self.assertIn("确认后先看这张只读索引", summary_slice)
        self.assertIn("确认回执、任务回放、数据接口和 P3 结果速读都来自本地 cache / ledger / packet", summary_slice)
        self.assertIn("不会创建 task、不会补调 Tushare/DeepSeek", summary_slice)
        self.assertIn("rows={quantProjectionReadbackIndexRows}", summary_slice)
        self.assertIn('aria-label="candidate radar ordinary p1 p2 detail readback"', summary_slice)
        self.assertIn("<summary>P1/P2 细节回放</summary>", summary_slice)
        self.assertIn("确认链路、P1 路径和 P2 三面核对默认收起", summary_slice)
        self.assertIn("ordinaryP1ConfirmPathRows", summary_slice)
        self.assertIn("P1 普通确认路径", summary_slice)
        self.assertIn('aria-label="candidate radar ordinary p1 confirm path"', summary_slice)
        self.assertIn("普通用户先看这条 P1 路径", summary_slice)
        self.assertIn('aria-label="candidate radar ordinary p2 writeback rail"', summary_slice)
        self.assertIn("P2 三面状态轨", summary_slice)
        self.assertIn("state={quantProjectionP2WritebackRailState}", summary_slice)
        self.assertIn("steps={quantProjectionP2WritebackRailSteps}", summary_slice)
        self.assertIn('aria-label="candidate radar ordinary p2 writeback surfaces"', summary_slice)
        self.assertIn("P2 小数据三面回放", summary_slice)
        self.assertIn("普通用户确认后看这张表：cache、call_ledger、packet 三面是否可回放", summary_slice)
        self.assertIn("它只读取本地 cache，不创建 task、不补调 Tushare/DeepSeek", summary_slice)
        self.assertIn("rows={quantProjectionWritebackSurfaceRows}", summary_slice)
        self.assertIn("quantProjectionP3ResultSummaryItems", self.page)
        self.assertIn('aria-label="candidate radar ordinary p3 result summary strip"', summary_slice)
        self.assertIn("<MetricGrid items={quantProjectionP3ResultSummaryItems} />", summary_slice)
        self.assertIn('aria-label="quant projection ordinary p3 result summary strip"', self.page)
        self.assertIn('label: "可读结论"', self.page)
        self.assertIn('label: "数据来源"', self.page)
        self.assertIn('label: "安全边界"', self.page)
        self.assertIn('aria-label="quant projection p0 submit failure recovery"', self.page)
        self.assertIn("确认按钮失败后先看本地联通恢复包", self.page)
        self.assertIn("check-only 不启动服务", self.page)
        self.assertIn("页面不会补调数据源或模型", self.page)
        self.assertIn('aria-label="candidate radar ordinary p2 writeback recovery"', summary_slice)
        self.assertIn("rows={quantProjectionWritebackRecoveryDisplayRows}", summary_slice)
        self.assertIn('label: "P2 三面"', summary_slice)
        self.assertIn('aria-live="polite"', summary_slice)
        self.assertIn('aria-label="candidate radar primary next action"', summary_slice)
        self.assertIn('aria-label="candidate radar next user actions"', summary_slice)
        self.assertLess(summary_slice.index('aria-label="candidate radar primary next action"'), summary_slice.index('aria-label="candidate radar next user actions"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar p3 first screen result quick read"'), summary_slice.index('aria-label="candidate radar ordinary expanded p1 p3 readback details"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary expanded p1 p3 readback details"'), summary_slice.index('aria-label="candidate radar ordinary p1 to p3 stage rail"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p1 to p3 stage rail"'), summary_slice.index('aria-label="candidate radar ordinary one screen actions"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary one screen actions"'), summary_slice.index('aria-label="quant projection submit recovery quick read"'))
        self.assertLess(summary_slice.index('aria-label="quant projection submit recovery quick read"'), summary_slice.index('aria-label="quant projection ordinary confirm outcome quick read"'))
        self.assertLess(summary_slice.index('aria-label="quant projection ordinary confirm outcome quick read"'), summary_slice.index('aria-label="candidate radar p1 tushare first chain quick read"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar p1 tushare first chain quick read"'), summary_slice.index('aria-label="candidate radar ordinary p2 p3 replay checklist"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary one screen actions"'), summary_slice.index('aria-label="candidate radar ordinary p2 p3 replay checklist"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p2 p3 replay checklist"'), summary_slice.index('aria-label="candidate radar ordinary p1 p2 detail readback"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p1 p2 detail readback"'), summary_slice.index('aria-label="candidate radar ordinary p1 confirm path"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p1 confirm path"'), summary_slice.index('aria-label="candidate radar ordinary p2 writeback rail"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p2 writeback rail"'), summary_slice.index('aria-label="candidate radar ordinary p2 writeback surfaces"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p1 p2 detail readback"'), summary_slice.index('aria-label="candidate radar ordinary p3 explainable result quick read"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p3 result summary strip"'), summary_slice.index('aria-label="candidate radar ordinary p3 explainable result quick read"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p3 explainable result quick read"'), summary_slice.index('aria-label="candidate radar ordinary p3 result checkpoint"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p3 result checkpoint"'), summary_slice.index('aria-label="candidate radar ordinary p3 result handoff index"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar primary next action"'), summary_slice.index('aria-label="candidate radar ordinary p5 governance details"'))
        self.assertLess(summary_slice.index('aria-label="candidate radar ordinary p5 governance details"'), summary_slice.index('aria-label="candidate radar ordinary p6 strict closeout handoff"'))
        self.assertLess(summary_slice.index("{quantProjectionSummaryGuidance}"), summary_slice.index('aria-label="candidate radar next user actions"'))
        self.assertNotIn("launchQuantProjectionAcceptanceDryRun", summary_slice)
        self.assertNotIn("launchQuantProjectionExecutionRequest", summary_slice)
        self.assertNotIn("launchProviderParityDryRun", summary_slice)
        self.assertNotIn("provider-model", summary_slice)
        self.assertNotIn("launchQuantProjectionAcceptanceDryRun", self.page[confirm_quick_start:summary_end])
        self.assertNotIn("launchQuantProjectionExecutionRequest", self.page[confirm_quick_start:summary_end])
        self.assertNotIn("launchQuantProjectionProviderModelAcceptance", self.page[confirm_quick_start:summary_end])
        self.assertIn("quantProjectionPostConfirmActionRows", post_confirm_slice)
        self.assertIn("刷新本地 cache", post_confirm_slice)
        self.assertNotIn("launchQuantProjectionAcceptanceDryRun", post_confirm_slice)
        self.assertNotIn("launchQuantProjectionExecutionRequest", post_confirm_slice)
        self.assertNotIn("launchQuantProjectionProviderModelAcceptance", post_confirm_slice)
        self.assertNotIn("quant-projection-provider-model-acceptance", post_confirm_slice)
        self.assertIn("quantProjectionTaskSuccessRefreshRows", task_status_slice)
        self.assertIn("TaskStatusPanel", task_status_slice)
        self.assertIn("任务成功后自动回读", task_status_slice)
        self.assertNotIn("launchQuantProjectionAcceptanceDryRun", task_status_slice)
        self.assertNotIn("launchQuantProjectionExecutionRequest", task_status_slice)
        self.assertNotIn("launchQuantProjectionProviderModelAcceptance", task_status_slice)
        self.assertNotIn("quant-projection-provider-model-acceptance", task_status_slice)

    def test_tushare_first_handoff_matches_ordinary_submit_boundary(self):
        self.assertIn("Candidate Radar searched-symbol confirmation must be reported through the active checkpoint", self.handoff)
        self.assertIn("confirmed search may submit bounded Tushare provider work through POST task and call ledger", self.handoff)
        self.assertIn("ordinary confirm action may create the Tushare-first backend task chain", self.handoff)
        self.assertIn("keeps DeepSeek skipped", self.handoff)
        self.assertIn("does not require the old `run_provider_model_now` switch", self.handoff)
        self.assertIn("page open, search typing, React render, and GET cache stay silent", self.handoff)
        self.assertNotIn("DeepSeek is requested into the explanation ledger/governance path", self.handoff)
        self.assertNotIn("automatic v4/pro execution", self.handoff)

    def test_task_status_panel_surfaces_tushare_first_ledger_for_ordinary_users(self):
        panel = self.task_status_panel
        self.assertIn("const tushareProviderRows = callLedger.filter(isTushareProviderLedgerRow)", panel)
        self.assertIn("const tushareProviderSuccessCount", panel)
        self.assertIn("Tushare ${tushareProviderSuccessCount}/${tushareProviderRows.length} 个接口已写入主任务 call_ledger", panel)
        self.assertIn('aria-label="task status tushare first ledger quick read"', panel)
        self.assertIn("Tushare-first 速读：普通用户先看主任务是否已回放接口级 ledger", panel)
        self.assertIn("Tushare ${tushareProviderSuccessCount}/${tushareProviderRows.length} 个接口已写入 task.call_ledger", panel)
        self.assertIn("DeepSeek skipped / 未调用；P1/P2/P3 不等待模型", panel)
        self.assertIn("DeepSeek governed executor 单独补，不阻塞 Tushare-first 和基础图谱", panel)
        self.assertIn("TaskStatusPanel 只读当前 task.call_ledger；不补调 Tushare、DeepSeek 或 GitHub。", panel)
        self.assertIn("不交易、不改 strategy action", panel)
        self.assertNotIn("postCandidateRadarQuantProjectionProviderModelAcceptance", panel)
        self.assertNotIn("launchQuantProjectionProviderModelAcceptance", panel)

    def test_candidate_radar_restores_persisted_task_panel_without_creating_new_task(self):
        self.assertIn(
            "TaskStatusPanel 可恢复本地状态轮询，不创建新 task、不补调 Tushare/DeepSeek",
            self.page,
        )
        self.assertIn("(quantProjectionTaskVisible || Boolean(quantProjectionPersistedTaskId)) && !quantProjectionTaskPanelStaleForCurrentInput", self.page)
        self.assertIn(
            'quantProjectionTaskPanelStaleForCurrentInput ? "" : quantProjectionTaskVisible && taskId ? taskId : quantProjectionPersistedTaskId',
            self.page,
        )
        self.assertIn("const manualTaskPanelVisible = Boolean(taskId);", self.page)
        self.assertIn(
            "暂无可轮询任务；点击确认按钮或手动任务后才显示 TaskStatusPanel",
            self.page,
        )

    def test_candidate_radar_page_does_not_embed_provider_or_trade_calls(self):
        forbidden_fragments = (
            "tushare.pro_api",
            "ts.pro_api",
            "deepseek.chat",
            "api.github.com",
            "fetch(",
            "executeTrade(",
            "placeOrder(",
            "broker.submit",
            "live_order",
        )
        for fragment in forbidden_fragments:
            self.assertNotIn(fragment, self.page)


if __name__ == "__main__":
    unittest.main()
