from __future__ import annotations

import json
import unittest
from pathlib import Path


ROOT = Path("desktop")


class CommandCenter3FrontendScaffoldTests(unittest.TestCase):
    def test_desktop_scaffold_files_exist(self):
        expected = [
            ROOT / "package.json",
            ROOT / "vite.config.ts",
            ROOT / "src" / "App.tsx",
            ROOT / "src" / "api" / "client.ts",
            ROOT / "src" / "components" / "JsonDetails.tsx",
            ROOT / "src" / "components" / "MetricGrid.tsx",
            ROOT / "src" / "components" / "NextSessionChart.tsx",
            ROOT / "src" / "components" / "TaskStatusPanel.tsx",
            ROOT / "src" / "routes" / "AShareEvidenceRadar.tsx",
            ROOT / "src" / "routes" / "CallLedgerAudit.tsx",
            ROOT / "src" / "routes" / "CandidateRadar.tsx",
            ROOT / "src" / "routes" / "DataCapabilityConsole.tsx",
            ROOT / "src" / "routes" / "DataHealthTimeline.tsx",
            ROOT / "src" / "routes" / "DesktopShellPreflight.tsx",
            ROOT / "src" / "routes" / "DisciplineLoop.tsx",
            ROOT / "src" / "routes" / "FactorQuantHub.tsx",
            ROOT / "src" / "routes" / "HealthStatus.tsx",
            ROOT / "src" / "routes" / "MarketContext.tsx",
            ROOT / "src" / "routes" / "MigrationStatus.tsx",
            ROOT / "src" / "routes" / "ModelStrategy.tsx",
            ROOT / "src" / "routes" / "PacketRegistry.tsx",
            ROOT / "src" / "routes" / "PositionContext.tsx",
            ROOT / "src" / "routes" / "QuantBacktestLab.tsx",
            ROOT / "src" / "routes" / "RecoveryCenter.tsx",
            ROOT / "src" / "routes" / "RiskGuardrails.tsx",
            ROOT / "src" / "routes" / "StorageOverview.tsx",
            ROOT / "src" / "routes" / "StrategyTrace.tsx",
            ROOT / "src" / "routes" / "TaskCatalog.tsx",
            ROOT / "src" / "routes" / "TradeReviewLab.tsx",
            ROOT / "src" / "routes" / "WorkerRuntime.tsx",
            ROOT / "src-tauri" / "tauri.conf.json",
            ROOT / "src-tauri" / "src" / "main.rs",
        ]
        for path in expected:
            with self.subTest(path=path):
                self.assertTrue(path.exists())

    def test_package_scripts_and_dependencies(self):
        package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
        self.assertIn("dev", package["scripts"])
        self.assertIn("build", package["scripts"])
        self.assertIn("tauri", package["scripts"])
        self.assertIn("react", package["dependencies"])
        self.assertIn("echarts", package["dependencies"])

    def test_frontend_uses_api_client_and_button_gated_tasks(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")

        self.assertIn("/api/factor-quant/cache", client)
        self.assertIn("/api/migration/status", client)
        self.assertIn("/api/model-strategy/cache", client)
        self.assertIn("/api/storage", client)
        self.assertIn("/api/desktop/preflight-cache", client)
        self.assertIn("/api/factor-quant/refresh-data", source)
        self.assertIn("/api/factor-quant/run-light", source)
        self.assertIn("/api/factor-quant/deepseek-explain", source)
        self.assertIn("多因子量化不是交易建议", source)
        self.assertIn("只整理已有结构化结果", source)
        self.assertIn("summary / support_notes / suppress_notes", source)
        self.assertNotIn("tushare_adapter", source)
        self.assertNotIn("DEEPSEEK", source)
        self.assertNotIn("GITHUB_TOKEN", source)

    def test_factor_quant_page_renders_structured_research_boundaries(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")

        self.assertIn("factor_library", source)
        self.assertIn("runtime.factor_values", source)
        self.assertIn("support_factors", source)
        self.assertIn("suppress_factors", source)
        self.assertIn("missing_factors", source)
        self.assertIn("conflict_factors", source)
        self.assertIn("governance", source)
        self.assertIn("next_session_bridge", source)
        self.assertIn("does_not_modify_operation_zones", source)
        self.assertIn("research_context", source)
        self.assertIn("risk_boundaries", source)
        self.assertIn("因子库", source)
        self.assertIn("运行值", source)
        self.assertIn("评分桶", source)
        self.assertIn("治理边界", source)
        self.assertIn("次日图谱桥接", source)
        self.assertIn("风险边界", source)
        self.assertIn("DataLineageTable", source)
        self.assertNotIn("strategy_execution_packet.action =", source)

    def test_app_persists_desktop_route_without_streamlit_rerun(self):
        source = (ROOT / "src" / "App.tsx").read_text(encoding="utf-8")

        self.assertIn("stock_ming_command_center_3_route", source)
        self.assertIn("readInitialRoute", source)
        self.assertIn("normalizeRouteKey", source)
        self.assertIn("window.localStorage", source)
        self.assertIn("window.location.hash", source)
        self.assertIn("window.history.replaceState", source)
        self.assertIn("hashchange", source)
        self.assertIn("onNavigate={navigateRoute}", source)
        self.assertIn('"factor"', source)
        self.assertIn('"next"', source)
        self.assertIn('"desktop"', source)
        self.assertIn('"models"', source)
        self.assertIn("DesktopShellPreflight", source)
        self.assertIn("ModelStrategy", source)
        self.assertNotIn("streamlit", source.lower())

    def test_read_only_pages_render_structured_cache_without_direct_python_calls(self):
        route_dir = ROOT / "src" / "routes"
        page_names = [
            "CommandCenterHome.tsx",
            "AShareEvidenceRadar.tsx",
            "CallLedgerAudit.tsx",
            "CandidateRadar.tsx",
            "DataCapabilityConsole.tsx",
            "DataHealthTimeline.tsx",
            "DesktopShellPreflight.tsx",
            "DisciplineLoop.tsx",
            "HealthStatus.tsx",
            "MarketContext.tsx",
            "NextSessionMap.tsx",
            "ModelStrategy.tsx",
            "FactorQuantHub.tsx",
            "ChokepointScan.tsx",
            "SerenityMethodRadar.tsx",
            "PacketRegistry.tsx",
            "PositionContext.tsx",
            "QuantBacktestLab.tsx",
            "RecoveryCenter.tsx",
            "RiskGuardrails.tsx",
            "MigrationStatus.tsx",
            "StorageOverview.tsx",
            "TaskCatalog.tsx",
            "StrategyTrace.tsx",
            "TradeReviewLab.tsx",
            "WorkerRuntime.tsx",
            "LegacyTools.tsx",
        ]
        forbidden = ["tushare_adapter", "akshare", "DeepSeek(", "GITHUB_TOKEN", "process.env"]
        for name in page_names:
            source = (route_dir / name).read_text(encoding="utf-8")
            with self.subTest(page=name):
                self.assertIn("PacketCard", source)
                for needle in forbidden:
                    self.assertNotIn(needle, source)

        self.assertIn("MetricGrid", (route_dir / "CommandCenterHome.tsx").read_text(encoding="utf-8"))
        home_source = (route_dir / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        self.assertIn("sqlite_meta", home_source)
        self.assertIn("Parquet / DuckDB Storage", home_source)
        self.assertIn("daily / moneyflow / factor_values", home_source)
        self.assertIn("Command Center 3.0 迁移基线", home_source)
        self.assertIn("只读展示，不重新估算", home_source)
        self.assertIn("DeepSeek 模型策略", home_source)
        self.assertIn("getModelStrategyCache", home_source)
        self.assertIn("model_rows", home_source)
        self.assertIn("progress_baseline", home_source)
        self.assertIn("external_calls_triggered", home_source)
        self.assertIn("不展示 token/key", home_source)
        self.assertNotIn("DEEPSEEK_API_KEY", home_source)
        self.assertIn("does_not_modify_action", (route_dir / "NextSessionMap.tsx").read_text(encoding="utf-8"))
        self.assertIn("allow_core_action", (route_dir / "FactorQuantHub.tsx").read_text(encoding="utf-8"))
        self.assertIn("enters_strategy_action", (route_dir / "ChokepointScan.tsx").read_text(encoding="utf-8"))
        self.assertIn("enters_chokepoint_score", (route_dir / "SerenityMethodRadar.tsx").read_text(encoding="utf-8"))
        migration_source = (route_dir / "MigrationStatus.tsx").read_text(encoding="utf-8")
        self.assertIn("getMigrationStatus", migration_source)
        self.assertIn("只读、不重新估算、不外联", migration_source)
        self.assertIn("does_not_execute_trades", migration_source)
        self.assertNotIn("postTask", migration_source)

        app_source = (ROOT / "src" / "App.tsx").read_text(encoding="utf-8")
        layout_source = (ROOT / "src" / "components" / "Layout.tsx").read_text(encoding="utf-8")
        self.assertIn("HealthStatus", app_source)
        self.assertIn("CallLedgerAudit", app_source)
        self.assertIn("MarketContext", app_source)
        self.assertIn("ModelStrategy", app_source)
        self.assertIn("DisciplineLoop", app_source)
        self.assertIn("AShareEvidenceRadar", app_source)
        self.assertIn("CandidateRadar", app_source)
        self.assertIn("DataCapabilityConsole", app_source)
        self.assertIn("DataHealthTimeline", app_source)
        self.assertIn("DesktopShellPreflight", app_source)
        self.assertIn("PacketRegistry", app_source)
        self.assertIn("PositionContext", app_source)
        self.assertIn("QuantBacktestLab", app_source)
        self.assertIn("RecoveryCenter", app_source)
        self.assertIn("RiskGuardrails", app_source)
        self.assertIn("MigrationStatus", app_source)
        self.assertIn("StorageOverview", app_source)
        self.assertIn("TaskCatalog", app_source)
        self.assertIn("StrategyTrace", app_source)
        self.assertIn("TradeReviewLab", app_source)
        self.assertIn("WorkerRuntime", app_source)
        self.assertIn('"health"', layout_source)
        self.assertIn('"audit"', layout_source)
        self.assertIn('"market"', layout_source)
        self.assertIn('"models"', layout_source)
        self.assertIn('"discipline"', layout_source)
        self.assertIn('"evidence"', layout_source)
        self.assertIn('"candidates"', layout_source)
        self.assertIn('"dataCapability"', layout_source)
        self.assertIn('"dataHealth"', layout_source)
        self.assertIn('"desktop"', layout_source)
        self.assertIn('"packets"', layout_source)
        self.assertIn('"position"', layout_source)
        self.assertIn('"quant"', layout_source)
        self.assertIn('"recovery"', layout_source)
        self.assertIn('"risk"', layout_source)
        self.assertIn('"migration"', layout_source)
        self.assertIn('"storage"', layout_source)
        self.assertIn('"tasks"', layout_source)
        self.assertIn('"strategy"', layout_source)
        self.assertIn('"tradeReview"', layout_source)
        self.assertIn('"worker"', layout_source)
        self.assertIn("健康", layout_source)
        self.assertIn("调用审计", layout_source)
        self.assertIn("证据雷达", layout_source)
        self.assertIn("候选雷达", layout_source)
        self.assertIn("数据能力", layout_source)
        self.assertIn("数据健康", layout_source)
        self.assertIn("桌面壳", layout_source)
        self.assertIn("Packet", layout_source)
        self.assertIn("持仓画像", layout_source)
        self.assertIn("量化回测", layout_source)
        self.assertIn("恢复中心", layout_source)
        self.assertIn("风险护栏", layout_source)
        self.assertIn("迁移状态", layout_source)
        self.assertIn("存储层", layout_source)
        self.assertIn("任务目录", layout_source)
        self.assertIn("策略 Trace", layout_source)
        self.assertIn("交易复盘", layout_source)
        self.assertIn("Worker", layout_source)
        self.assertIn("市场环境", layout_source)
        self.assertIn("模型策略", layout_source)
        self.assertIn("交易纪律", layout_source)

    def test_model_strategy_page_reads_configured_models_without_model_call(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "ModelStrategy.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/model-strategy/cache", client)
        self.assertIn("getModelStrategyCache", client)
        self.assertIn("getModelStrategyCache", home)
        self.assertIn("DeepSeek 模型策略", home)
        self.assertIn("getModelStrategyCache", page)
        self.assertIn("GET /api/model-strategy/cache", page)
        self.assertIn("DEEPSEEK_EXPLAIN_MODEL", page)
        self.assertIn("DEEPSEEK_FAST_MODEL", page)
        self.assertIn("DEEPSEEK_DEFAULT_MODEL", page)
        self.assertIn("调用点不得硬编码模型名", page)
        self.assertIn("does_not_call_deepseek", page)
        self.assertIn("post_task_required_for_model_call", page)
        self.assertIn("local_deepseek_model_strategy_cache", page)
        self.assertIn("DataLineageTable", page)
        self.assertIn("不会调用 DeepSeek", page)
        self.assertIn("不修改 strategy action", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("TUSHARE_TOKEN", page)
        self.assertNotIn("GITHUB_TOKEN", page)
        self.assertNotIn("fetch(", page)

    def test_desktop_shell_preflight_page_is_cache_only_and_read_only(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "DesktopShellPreflight.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/desktop/preflight-cache", client)
        self.assertIn("getDesktopPreflightCache", client)
        self.assertIn("getDesktopPreflightCache", home)
        self.assertIn("桌面壳预检 cache", home)
        self.assertIn("getDesktopPreflightCache", page)
        self.assertIn("GET /api/desktop/preflight-cache", page)
        self.assertIn("只读检查本地 scaffold", page)
        self.assertIn("does_not_run_npm_install", page)
        self.assertIn("does_not_run_npm_build", page)
        self.assertIn("does_not_run_tauri", page)
        self.assertIn("does_not_run_cargo", page)
        self.assertIn("Rust/Cargo", page)
        self.assertIn("Vite", page)
        self.assertIn("Tauri", page)
        self.assertIn("DataLineageTable", page)
        self.assertIn("local_desktop_shell_preflight_cache", page)
        self.assertIn("不会调用 Tushare、DeepSeek 或 GitHub", page)
        self.assertIn("不读取 token/key", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("不修改 strategy action", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("TUSHARE_TOKEN", page)
        self.assertNotIn("GITHUB_TOKEN", page)
        self.assertNotIn("npm install &&", page)
        self.assertNotIn("cargo build", page)

    def test_task_panel_polls_fastapi_task_endpoint(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        panel = (ROOT / "src" / "components" / "TaskStatusPanel.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/tasks", client)
        self.assertIn("/api/tasks/catalog", client)
        self.assertIn("/api/tasks/${encodeURIComponent(taskId)}/cancel", client)
        self.assertIn("getTask(taskId)", panel)
        self.assertIn("mergeTaskEnvelope", panel)
        self.assertIn("res.call_ledger", panel)
        self.assertIn("res.warnings", panel)
        self.assertIn("cancelTask", panel)
        self.assertIn("本地取消任务", panel)
        self.assertIn("manual_cancel_from_task_status_panel", panel)
        self.assertIn("不调用 Tushare、DeepSeek 或 GitHub", panel)
        self.assertIn("setInterval", panel)
        self.assertIn("local_fallback", panel)
        self.assertIn("onSuccess", panel)
        self.assertIn("call_ledger", panel)
        self.assertIn("status_history", panel)
        self.assertIn("statusHistory.length", panel)
        self.assertIn("external_calls_triggered", panel)
        self.assertIn("does_not_execute_trades", panel)
        self.assertIn("does_not_modify_strategy_action", panel)
        self.assertIn("DataLineageTable", panel)

    def test_health_page_reads_startup_state_without_external_calls(self):
        page = (ROOT / "src" / "routes" / "HealthStatus.tsx").read_text(encoding="utf-8")

        self.assertIn("getHealth", page)
        self.assertIn("getMigrationStatus", page)
        self.assertIn("GET /health 只读", page)
        self.assertIn("external_calls_on_startup", page)
        self.assertIn("real_trading_enabled", page)
        self.assertIn("deepseek_model_strategy", page)
        self.assertIn("不在调用点硬编码", page)
        self.assertIn("不展示密钥", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_call_ledger_audit_page_reads_local_audit_without_external_work(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "CallLedgerAudit.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/audit/cache", client)
        self.assertIn("getAuditCache", page)
        self.assertIn("getAuditCache", home)
        self.assertIn("GET /api/audit/cache", page)
        self.assertIn("local_call_ledger_audit_cache", page)
        self.assertIn("cache API 与 task call_ledger", page)
        self.assertIn("command_center_3_task_status_index", page)
        self.assertIn("任务状态 index", page)
        self.assertIn("不调用 Tushare、DeepSeek、GitHub 或 Redis", page)
        self.assertIn("不刷新数据", page)
        self.assertIn("不运行回测", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("不修改 strategy action", page)
        self.assertIn("audit_is_read_only", page)
        self.assertIn("post_task_required_for_external_work", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

        factor_page = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")
        self.assertIn("onSuccess={refreshCache}", factor_page)
        home_source = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        self.assertIn("getTaskCatalog", home_source)
        self.assertIn("type TaskStatusIndex", home_source)
        self.assertIn("setTaskIndex", home_source)
        self.assertIn("task_status_index", home_source)
        self.assertIn("taskIndex?.call_ledger_count", home_source)
        self.assertIn("taskIndex?.external_calls_triggered", home_source)
        self.assertIn("does_not_execute_trades", home_source)
        self.assertIn("POST task 才可能触发外部请求", home_source)
        self.assertIn("call_ledger_required_for_all", home_source)

        task_catalog_page = (ROOT / "src" / "routes" / "TaskCatalog.tsx").read_text(encoding="utf-8")
        client_source = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        self.assertIn("TaskStatusIndex", client_source)
        self.assertIn("call_ledger_count", client_source)
        self.assertIn("getTaskCatalog", task_catalog_page)
        self.assertIn("getTasks", task_catalog_page)
        self.assertIn("cancelTask", task_catalog_page)
        self.assertIn("GET /api/tasks", task_catalog_page)
        self.assertIn("POST /api/tasks/{task_id}/cancel", task_catalog_page)
        self.assertIn("任务记录", task_catalog_page)
        self.assertIn("任务状态总览", task_catalog_page)
        self.assertIn("command_center_3_task_status_index", task_catalog_page)
        self.assertIn("task_status_index", task_catalog_page)
        self.assertIn("taskIndex?.call_ledger_count", task_catalog_page)
        self.assertIn("taskIndex?.external_calls_triggered", task_catalog_page)
        self.assertIn("taskIndex?.does_not_execute_trades", task_catalog_page)
        self.assertIn("get_tasks_cache_only", task_catalog_page)
        self.assertIn("call_ledger_required_for_all", task_catalog_page)
        self.assertIn("POST task 才可能触发外部请求", task_catalog_page)
        self.assertIn("local_task_cancel", task_catalog_page)
        self.assertIn("cancelled_by_user_no_external_call", task_catalog_page)
        self.assertIn("不会调用 Tushare、DeepSeek 或 GitHub", task_catalog_page)
        self.assertIn("external_calls_triggered: task.external_calls_triggered === true", task_catalog_page)
        self.assertIn("tushare_called: task.tushare_called === true", task_catalog_page)
        self.assertIn("deepseek_called: task.deepseek_called === true", task_catalog_page)
        self.assertIn("github_called: task.github_called === true", task_catalog_page)
        self.assertIn("does_not_execute_trades: task.does_not_execute_trades !== false", task_catalog_page)
        self.assertIn("does_not_modify_strategy_action: task.does_not_modify_strategy_action !== false", task_catalog_page)
        self.assertIn("does_not_execute_trades", task_catalog_page)
        self.assertIn("does_not_modify_strategy_action", task_catalog_page)
        self.assertNotIn("postTask", task_catalog_page)

    def test_worker_runtime_page_reads_runtime_cache_without_starting_backends(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "WorkerRuntime.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/worker/cache", client)
        self.assertIn("getWorkerRuntimeCache", page)
        self.assertIn("getWorkerRuntimeCache", home)
        self.assertIn("GET /api/worker/cache", page)
        self.assertIn("local_worker_runtime_cache", page)
        self.assertIn("task_status_summary", page)
        self.assertIn("Task status index 摘要", page)
        self.assertIn("task_status_index", page)
        self.assertIn("task_status_call_ledger_count", page)
        self.assertIn("taskStatus.call_ledger_count", page)
        self.assertIn("taskStatus.external_calls_triggered", page)
        self.assertIn("不会连接 Redis", page)
        self.assertIn("不会启动 Celery worker", page)
        self.assertIn("不会启动 APScheduler", page)
        self.assertIn("不会调度真实任务", page)
        self.assertIn("不调用 Tushare、DeepSeek 或 GitHub", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("不修改 strategy action", page)
        self.assertIn("does_not_ping_redis", page)
        self.assertIn("does_not_start_celery_worker", page)
        self.assertIn("does_not_start_scheduler", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)
        self.assertNotIn("COMMAND_CENTER_REDIS_URL", page)

    def test_storage_page_reads_storage_cache_without_external_calls(self):
        page = (ROOT / "src" / "routes" / "StorageOverview.tsx").read_text(encoding="utf-8")
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")

        self.assertIn("getStorageOverview", page)
        self.assertIn("getFactorValuesStorage", page)
        self.assertIn("getStorageDataset", page)
        self.assertIn("/api/storage/${encodeURIComponent(dataset)}", client)
        self.assertIn("Parquet / DuckDB Storage", page)
        self.assertIn("daily / moneyflow / factor_values", page)
        self.assertIn("GET /api/storage/{dataset}", page)
        self.assertIn("数据集明细", page)
        self.assertIn("daily / moneyflow 样例", page)
        self.assertIn('"daily"', page)
        self.assertIn('"moneyflow"', page)
        self.assertIn("cache API 永不外联", page)
        self.assertIn("external_calls_triggered", page)
        self.assertIn("does_not_execute_trades", page)
        self.assertIn("does_not_modify_strategy_action", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_trade_review_page_reads_local_review_cache_without_external_calls(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "TradeReviewLab.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/trade-review/cache", client)
        self.assertIn("getTradeReviewCache", page)
        self.assertIn("GET /api/trade-review/cache", page)
        self.assertIn("trade_review_log.jsonl", page)
        self.assertIn("cache-only", page)
        self.assertIn("不会调用 Tushare、DeepSeek 或 GitHub", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("不会修改 strategy_execution_packet.action", page)
        self.assertIn("local_trade_review_log", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_quant_backtest_page_reads_quant_cache_without_running_backtester(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "QuantBacktestLab.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/quant/cache", client)
        self.assertIn("getQuantCache", page)
        self.assertIn("GET /api/quant/cache", page)
        self.assertIn("command_center_quant_packet", page)
        self.assertIn("不运行 backtester", page)
        self.assertIn("不调用 Tushare、DeepSeek 或 GitHub", page)
        self.assertIn("不能直接修改 strategy action", page)
        self.assertIn("回测收益不代表未来收益", page)
        self.assertIn("local_quant_backtest_cache", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_position_context_page_reads_position_cache_without_external_work(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "PositionContext.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/position/cache", client)
        self.assertIn("getPositionCache", page)
        self.assertIn("getPositionCache", home)
        self.assertIn("GET /api/position/cache", page)
        self.assertIn("holding_action", page)
        self.assertIn("position_risk_budget", page)
        self.assertIn("risk_breakdown", page)
        self.assertIn("safety_line", page)
        self.assertIn("不会调用 Tushare、DeepSeek 或 GitHub", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("不自动下单", page)
        self.assertIn("不修改持仓或 strategy action", page)
        self.assertIn("local_position_context_cache", page)
        self.assertIn("does_not_modify_holdings", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_candidate_radar_page_reads_candidate_cache_without_market_scan(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "CandidateRadar.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/candidate-radar/cache", client)
        self.assertIn("getCandidateRadarCache", page)
        self.assertIn("getCandidateRadarCache", home)
        self.assertIn("GET /api/candidate-radar/cache", page)
        self.assertIn("radar_packet", page)
        self.assertIn("next_ticket_candidates", page)
        self.assertIn("不会自动全市场扫描", page)
        self.assertIn("候选不是买入指令", page)
        self.assertIn("不会调用 Tushare、DeepSeek 或 GitHub", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("不自动下单", page)
        self.assertIn("不修改 strategy action", page)
        self.assertIn("local_candidate_radar_cache", page)
        self.assertIn("does_not_scan_market", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_risk_guardrails_page_reads_cache_without_clearing_risks(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "RiskGuardrails.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/risk/cache", client)
        self.assertIn("getRiskGuardrailsCache", page)
        self.assertIn("getRiskGuardrailsCache", home)
        self.assertIn("GET /api/risk/cache", page)
        self.assertIn("risk_alerts", page)
        self.assertIn("execution_guardrail_overview", page)
        self.assertIn("legacy_decision_chain_summary", page)
        self.assertIn("local_risk_guardrails_cache", page)
        self.assertIn("不会调用 Tushare、DeepSeek 或 GitHub", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("不自动下单", page)
        self.assertIn("不修改 strategy action", page)
        self.assertIn("不清除风险标记", page)
        self.assertIn("风险护栏不是交易指令", page)
        self.assertIn("does_not_modify_holdings", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_strategy_trace_page_reads_strategy_cache_without_action_mutation(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "StrategyTrace.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/strategy/cache", client)
        self.assertIn("getStrategyCache", page)
        self.assertIn("GET /api/strategy/cache", page)
        self.assertIn("strategy_execution_packet", page)
        self.assertIn("command_center_decision_packet", page)
        self.assertIn("不会调用 Tushare、DeepSeek 或 GitHub", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("不自动下单", page)
        self.assertIn("不修改 strategy action", page)
        self.assertIn("local_strategy_trace_cache", page)
        self.assertIn("action_source", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_market_context_page_reads_market_cache_without_refreshing_quotes(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "MarketContext.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/market/cache", client)
        self.assertIn("getMarketContextCache", page)
        self.assertIn("getMarketContextCache", home)
        self.assertIn("GET /api/market/cache", page)
        self.assertIn("market_packet", page)
        self.assertIn("market_profile_evidence", page)
        self.assertIn("moneyflow_packet", page)
        self.assertIn("margin_packet", page)
        self.assertIn("limit_emotion_packet", page)
        self.assertIn("dragon_tiger_packet", page)
        self.assertIn("chip_packet", page)
        self.assertIn("local_market_context_cache", page)
        self.assertIn("不会调用 Tushare、AkShare、yfinance、DeepSeek 或 GitHub", page)
        self.assertIn("不刷新行情", page)
        self.assertIn("不会执行真实交易", page)
        self.assertIn("不修改 strategy action", page)
        self.assertIn("市场环境不是交易指令", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_discipline_loop_page_reads_cache_without_running_backtest(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "DisciplineLoop.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/discipline/cache", client)
        self.assertIn("getDisciplineLoopCache", page)
        self.assertIn("getDisciplineLoopCache", home)
        self.assertIn("GET /api/discipline/cache", page)
        self.assertIn("discipline_packet", page)
        self.assertIn("decision_loop_status", page)
        self.assertIn("today_action", page)
        self.assertIn("full_refresh_steps", page)
        self.assertIn("local_discipline_loop_cache", page)
        self.assertIn("不会运行回测", page)
        self.assertIn("不会满血刷新", page)
        self.assertIn("不会重算 action", page)
        self.assertIn("不修改 strategy action", page)
        self.assertIn("不会执行真实交易", page)
        self.assertIn("纪律分数和胜率不是买卖指令", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_a_share_evidence_page_reads_cache_without_external_calls(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "AShareEvidenceRadar.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/evidence/cache", client)
        self.assertIn("getEvidenceCache", page)
        self.assertIn("GET /api/evidence/cache", page)
        self.assertIn("A 股证据雷达", page)
        self.assertIn("事实血缘", page)
        self.assertIn("cache API 永不外联", page)
        self.assertIn("不调用 Tushare、DeepSeek、GitHub", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("strategy action", page)
        self.assertIn("local_a_share_evidence_cache", page)
        self.assertIn("lineage_enters_core_action", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_data_capability_page_reads_cache_without_provider_ping(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "DataCapabilityConsole.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/data-capability/cache", client)
        self.assertIn("getDataCapabilityCache", page)
        self.assertIn("GET /api/data-capability/cache", page)
        self.assertIn("数据能力", page)
        self.assertIn("Provider 状态", page)
        self.assertIn("接口级健康账本", page)
        self.assertIn("cache API 永不外联", page)
        self.assertIn("不 ping Tushare、AkShare、yfinance、Supabase", page)
        self.assertIn("不调用 DeepSeek 或 GitHub", page)
        self.assertIn("strategy action", page)
        self.assertIn("local_data_capability_cache", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_data_health_page_reads_timeline_cache_without_provider_ping(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "DataHealthTimeline.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/data-health/cache", client)
        self.assertIn("getDataHealthCache", page)
        self.assertIn("getDataHealthCache", home)
        self.assertIn("GET /api/data-health/cache", page)
        self.assertIn("data_health_timeline", page)
        self.assertIn("provider_data_capability_cockpit", page)
        self.assertIn("a_share_capability_matrix", page)
        self.assertIn("local_data_health_timeline_cache", page)
        self.assertIn("不会 ping Tushare、AkShare、yfinance、Supabase", page)
        self.assertIn("不调用 DeepSeek 或 GitHub", page)
        self.assertIn("不会刷新数据", page)
        self.assertIn("不修改 strategy action", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_recovery_center_page_reads_cache_without_running_recovery_actions(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "RecoveryCenter.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/recovery/cache", client)
        self.assertIn("getRecoveryCenterCache", page)
        self.assertIn("getRecoveryCenterCache", home)
        self.assertIn("GET /api/recovery/cache", page)
        self.assertIn("data_recovery_actions", page)
        self.assertIn("tool_recovery_actions", page)
        self.assertIn("recovery_result_timeline", page)
        self.assertIn("provider_recovery_matrix", page)
        self.assertIn("data_gap_report", page)
        self.assertIn("local_recovery_center_cache", page)
        self.assertIn("恢复动作只是手动建议", page)
        self.assertIn("不会调用 Tushare、AkShare、yfinance、DeepSeek 或 GitHub", page)
        self.assertIn("不会执行恢复动作", page)
        self.assertIn("不会修改 strategy action", page)
        self.assertIn("不会执行真实交易", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_chokepoint_page_shows_research_only_task_boundaries(self):
        page = (ROOT / "src" / "routes" / "ChokepointScan.tsx").read_text(encoding="utf-8")

        self.assertIn("getChokepointCache", page)
        self.assertIn("/api/chokepoint/run", page)
        self.assertIn("const refreshCache", page)
        self.assertIn("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />", page)
        self.assertIn("GET cache 不运行瓶颈扫描", page)
        self.assertIn("cache API 永不外联", page)
        self.assertIn("手动 POST task", page)
        self.assertIn("DeepSeek 只可整理解释，不作为数据源", page)
        self.assertIn("研究解释不进入 strategy action", page)
        self.assertIn("不写回次日操作图谱", page)
        self.assertIn("不执行真实交易", page)
        self.assertIn("cache_api_external_calls_triggered", page)
        self.assertIn("legacy_analysis_method_cache", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_packet_registry_page_reads_packet_cache_without_external_calls(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "PacketRegistry.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/packets", client)
        self.assertIn("encodeURIComponent(packetKey)", client)
        self.assertIn("getPackets", page)
        self.assertIn("getPacket", page)
        self.assertIn("GET /api/packets", page)
        self.assertIn("GET /api/packets/{packet_key} 永不外联", page)
        self.assertIn("cache API 永不外联", page)
        self.assertIn("选中 Packet 边界", page)
        self.assertIn("选中 Packet call_ledger", page)
        self.assertIn("external_calls_triggered", page)
        self.assertIn("tushare_called", page)
        self.assertIn("deepseek_called", page)
        self.assertIn("github_called", page)
        self.assertIn("does_not_execute_trades", page)
        self.assertIn("call_ledger_count", page)
        self.assertIn("does_not_modify_strategy_action", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_serenity_page_shows_local_baseline_and_decision_boundaries(self):
        page = (ROOT / "src" / "routes" / "SerenityMethodRadar.tsx").read_text(encoding="utf-8")

        self.assertIn("getSerenityCache", page)
        self.assertIn("/api/serenity/github-probe", page)
        self.assertIn("const refreshCache", page)
        self.assertIn("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />", page)
        self.assertIn("本地方法来源基线", page)
        self.assertIn("GitHub 当前状态为未校验", page)
        self.assertIn("手动 POST task", page)
        self.assertIn("防幻觉演进", page)
        self.assertIn("方法归纳", page)
        self.assertIn("决策边界", page)
        self.assertIn("技术血缘", page)
        self.assertIn("source_type", page)
        self.assertIn("user_screenshot_baseline", page)
        self.assertIn("enters_strategy_action", page)
        self.assertIn("enters_chokepoint_score", page)
        self.assertIn("enters_next_session_projection", page)
        self.assertIn("enters_deepseek_prompt", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)

    def test_legacy_page_declares_streamlit_as_guarded_legacy_surface(self):
        client = (ROOT / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        home = (ROOT / "src" / "routes" / "CommandCenterHome.tsx").read_text(encoding="utf-8")
        page = (ROOT / "src" / "routes" / "LegacyTools.tsx").read_text(encoding="utf-8")

        self.assertIn("/api/legacy/cache", client)
        self.assertIn("getLegacyBridgeCache", page)
        self.assertIn("getLegacyBridgeCache", home)
        self.assertIn("legacy_migration_map", page)
        self.assertIn("legacy_packet_migration_checklist", page)
        self.assertIn("old_workspace_packet_bridge", page)
        self.assertIn("old_workspace_data_absence_ledger", page)
        self.assertIn("local_legacy_bridge_cache", page)
        self.assertIn("不会打开 Streamlit", page)
        self.assertIn("不运行旧工具", page)
        self.assertIn("legacy/admin/debug", page)
        self.assertIn("普通主流程请使用 Command Center 3", page)
        self.assertIn("不会创建任务", page)
        self.assertIn("不调用 Tushare、DeepSeek 或 GitHub", page)
        self.assertIn("不会绕过 strategy_execution_packet", page)
        self.assertIn("真实交易", page)
        self.assertIn("自动下单", page)
        self.assertIn("DataLineageTable", page)
        self.assertNotIn("postTask", page)
        self.assertNotIn("tushare_adapter", page)
        self.assertNotIn("DEEPSEEK_API_KEY", page)
        self.assertNotIn("GITHUB_TOKEN", page)

    def test_next_session_chart_uses_cache_payload_without_trade_mutation(self):
        page = (ROOT / "src" / "routes" / "NextSessionMap.tsx").read_text(encoding="utf-8")
        chart = (ROOT / "src" / "components" / "NextSessionChart.tsx").read_text(encoding="utf-8")

        self.assertIn("NextSessionChart", page)
        self.assertIn("chart_payload", page)
        self.assertIn("GET /api/next-session/cache", page)
        self.assertIn("POST /api/next-session/generate", page)
        self.assertIn("const refreshCache", page)
        self.assertIn("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />", page)
        self.assertIn("cache_only", page)
        self.assertIn("does_not_modify_action", page)
        self.assertIn("does_not_modify_operation_zones", page)
        self.assertIn("情景路径", page)
        self.assertIn("参考线", page)
        self.assertIn("操作区", page)
        self.assertIn("历史 close 样例", page)
        self.assertIn("图表风险提示", page)
        self.assertIn("DataLineageTable", page)
        self.assertIn("uses_real_daily_close", page)
        self.assertIn("is_exact_next_session_packet", page)
        self.assertIn("EChartPanel", chart)
        self.assertIn("historical_points", chart)
        self.assertIn("scenario_series", chart)
        self.assertIn("reference_lines", chart)
        self.assertIn("operation_zones", chart)
        self.assertIn("referenceColor", chart)
        self.assertIn("referenceLineType", chart)
        self.assertIn("zoneColor", chart)
        self.assertIn("T0 分割线", chart)
        self.assertIn("markArea", chart)
        self.assertIn("lineStyle", chart)
        self.assertIn("price_range", chart)
        self.assertNotIn("strategy_execution_packet.action", chart)
        self.assertNotIn("operation_zones =", chart)


if __name__ == "__main__":
    unittest.main()
