import unittest
from pathlib import Path


class StorageWorkerOrdinaryEntryTests(unittest.TestCase):
    def setUp(self):
        self.root = Path(__file__).resolve().parents[1]
        self.storage_page = (
            self.root / "desktop" / "src" / "routes" / "StorageOverview.tsx"
        ).read_text(encoding="utf-8")
        self.worker_page = (
            self.root / "desktop" / "src" / "routes" / "WorkerRuntime.tsx"
        ).read_text(encoding="utf-8")

    def test_storage_first_screen_is_readable_before_audit_tables(self):
        page = self.storage_page
        head_start = page.index("<h1>存储层</h1>")
        first_screen_start = page.index('aria-label="storage ordinary first screen status"')
        metrics_start = page.index('<MetricGrid\n        items={[', first_screen_start)
        blocker_start = page.index('title="Storage production blocker audit"')
        first_screen = page[first_screen_start:metrics_start]

        self.assertLess(head_start, first_screen_start)
        self.assertLess(first_screen_start, blocker_start)
        self.assertIn("storageOrdinaryFirstScreenSentence", page[:blocker_start])
        self.assertIn("storageOrdinaryFirstScreenItems", page[:blocker_start])
        self.assertIn("storageCurrentResultDataDate", page[:blocker_start])
        self.assertIn("storageCurrentResultFreshnessState", page[:blocker_start])
        self.assertIn("storageCurrentResultFreshnessLabel", page[:blocker_start])
        self.assertIn("本地数据底座一眼状态", first_screen)
        self.assertIn('aria-label="storage ordinary first screen sentence"', first_screen)
        self.assertIn("MetricGrid items={storageOrdinaryFirstScreenItems}", first_screen)
        self.assertIn('label: "日期/新鲜度"', page[:blocker_start])
        self.assertIn('label: "data_date / freshness"', page[:blocker_start])
        self.assertIn('currentResult.data_date', page[:blocker_start])
        self.assertIn('currentResult.freshness_state', page[:blocker_start])
        self.assertIn('currentResultReadback.data_date', page[:blocker_start])
        self.assertIn('currentResultReadback.freshness_state', page[:blocker_start])
        self.assertIn('${storageCurrentResultFreshnessLabel} 已有可回放 current-result', page[:blocker_start])
        self.assertIn('aria-label="storage ordinary first screen safe actions"', first_screen)
        self.assertIn("onClick={refreshStorage}", first_screen)
        self.assertIn('href="#worker"', first_screen)
        self.assertIn('href="#migration"', first_screen)
        self.assertIn('aria-label="storage ordinary physical evidence task strip"', first_screen)
        self.assertIn("物理证据按钮", first_screen)
        self.assertIn('aria-label="storage ordinary physical evidence sentence"', first_screen)
        self.assertIn("storagePhysicalEvidenceActionItems", page[:blocker_start])
        self.assertIn("用户现在可以从首屏生成 physical execution request", first_screen)
        self.assertIn("两个按钮都只写本地 task/packet 状态", first_screen)
        self.assertIn('aria-label="storage ordinary physical evidence actions"', first_screen)
        self.assertIn("onClick={launchPhysicalExecutionRequest}", first_screen)
        self.assertIn("onClick={launchPhysicalExecutionPhaseA}", first_screen)
        self.assertIn("disabled={!storagePhysicalExecutionRequestCanLaunch}", first_screen)
        self.assertIn("disabled={!storagePhysicalExecutionPhaseACanLaunch}", first_screen)
        self.assertIn("TaskLaunchReceipt receipt={physicalExecutionRequestReceipt}", first_screen)
        self.assertIn("TaskStatusPanel taskId={physicalExecutionRequestTaskId}", first_screen)
        self.assertIn("TaskLaunchReceipt receipt={physicalExecutionPhaseAReceipt}", first_screen)
        self.assertIn("TaskStatusPanel taskId={physicalExecutionPhaseATaskId}", first_screen)
        self.assertIn('href="#storage-physical-execution-details"', first_screen)
        self.assertIn("GET storage 只读", page[:blocker_start])
        self.assertIn("不写 Parquet/manifest、不删除 artifacts、不调用 provider/model、不交易", page[:blocker_start])
        self.assertIn("刷新只读取本地 GET cache", first_screen)
        self.assertIn("不创建 task、不写文件、不调用 Tushare/DeepSeek/GitHub、不下单", first_screen)
        self.assertIn("首屏按钮是显式 POST local task", first_screen)
        self.assertIn("Phase A 仍不是 production storage complete", first_screen)
        self.assertIn('id="storage-physical-execution-details"', page)
        self.assertNotIn("postStorage", first_screen)

    def test_storage_app_visible_now_summary_is_read_only_before_task_buttons(self):
        page = self.storage_page
        head_start = page.index("<h1>存储层</h1>")
        visible_start = page.index('aria-label="storage app visible now summary"')
        first_screen_start = page.index('aria-label="storage ordinary first screen status"')
        physical_task_start = page.index('aria-label="storage ordinary physical evidence task strip"')
        blocker_start = page.index('title="Storage production blocker audit"')
        visible_slice = page[visible_start:first_screen_start]

        self.assertLess(head_start, visible_start)
        self.assertLess(visible_start, first_screen_start)
        self.assertLess(visible_start, physical_task_start)
        self.assertLess(visible_start, blocker_start)
        self.assertIn("storageAppVisibleNowSentence", page[:blocker_start])
        self.assertIn("storageAppVisibleNowItems", page[:blocker_start])
        self.assertIn("打开 app 能看到什么", visible_slice)
        self.assertIn('aria-label="storage app visible now sentence"', visible_slice)
        self.assertIn("{storageAppVisibleNowSentence}", visible_slice)
        self.assertIn("MetricGrid items={storageAppVisibleNowItems}", visible_slice)
        self.assertIn('label: "日期/新鲜度"', page[:blocker_start])
        self.assertIn("storageCurrentResultFreshnessLabel", page[:blocker_start])
        self.assertIn('等待 data_date', page[:blocker_start])
        self.assertIn('等待 freshness', page[:blocker_start])
        self.assertIn('aria-label="storage app visible now local actions"', visible_slice)
        self.assertIn('href="#worker"', visible_slice)
        self.assertIn('href="#storage-physical-execution-details"', visible_slice)
        self.assertIn('href="#migration"', visible_slice)
        self.assertIn('label: "数据底座"', page)
        self.assertIn('label: "元数据"', page)
        self.assertIn('label: "物理证据"', page)
        self.assertIn('label: "下一步入口"', page)
        self.assertIn('label: "支撑页"', page)
        self.assertIn('label: "安全边界"', page)
        self.assertIn("打开 app 能看到本地数据底座", page)
        self.assertIn("Worker runtime / LTG 总账 / 物理执行详情", page)
        self.assertIn("只读速读和本地锚点；不写 Parquet、不创建 task、不外联、不交易", page)
        self.assertIn("普通链接只切换本地页面或锚点", visible_slice)
        self.assertIn("不创建 task、不写 Parquet/manifest、不删除 artifacts", visible_slice)
        self.assertIn("不调用 Tushare/DeepSeek/GitHub、不交易、不改 strategy action", visible_slice)
        self.assertNotIn("onClick=", visible_slice)
        self.assertNotIn("TaskLaunchReceipt", visible_slice)
        self.assertNotIn("TaskStatusPanel", visible_slice)
        self.assertNotIn("launchPhysicalExecution", visible_slice)

    def test_worker_first_screen_is_readable_before_audit_tables(self):
        page = self.worker_page
        head_start = page.index("<h1>Worker 运行时</h1>")
        first_screen_start = page.index('aria-label="worker ordinary first screen status"')
        metrics_start = page.index('<MetricGrid\n        items={[', first_screen_start)
        audit_start = page.index('title="Worker runtime 来源"')
        first_screen = page[first_screen_start:metrics_start]

        self.assertLess(head_start, first_screen_start)
        self.assertLess(first_screen_start, audit_start)
        self.assertIn("workerOrdinaryFirstScreenSentence", page[:audit_start])
        self.assertIn("workerOrdinaryFirstScreenItems", page[:audit_start])
        self.assertIn("workerRuntimeQaActionItems", page[:audit_start])
        self.assertIn("运行时一眼状态", first_screen)
        self.assertIn('aria-label="worker ordinary first screen sentence"', first_screen)
        self.assertIn("MetricGrid items={workerOrdinaryFirstScreenItems}", first_screen)
        self.assertIn('aria-label="worker ordinary first screen safe actions"', first_screen)
        self.assertIn("onClick={refreshCache}", first_screen)
        self.assertIn('href="#storage"', first_screen)
        self.assertIn('href="#tasks"', first_screen)
        self.assertIn('aria-label="worker ordinary runtime qa task strip"', first_screen)
        self.assertIn("Runtime QA 本地按钮", first_screen)
        self.assertIn('aria-label="worker ordinary runtime qa task sentence"', first_screen)
        self.assertIn("用户现在可以从首屏按顺序生成 runtime QA request", first_screen)
        self.assertIn("这些按钮只创建本地 task receipt/status", first_screen)
        self.assertIn('aria-label="worker ordinary runtime qa actions"', first_screen)
        self.assertIn("onClick={launchRuntimeQaExecutionRequest}", first_screen)
        self.assertIn("onClick={launchRuntimeQaDryRun}", first_screen)
        self.assertIn("onClick={launchRuntimeQaExecution}", first_screen)
        self.assertIn("disabled={!runtimeQaExecutionRequestCanLaunch || runtimeQaExecutionRequestRunning}", first_screen)
        self.assertIn("disabled={!runtimeQaDryRunCanLaunch || runtimeQaDryRunRunning}", first_screen)
        self.assertIn("disabled={!runtimeQaExecutionCanLaunch || runtimeQaExecutionRunning}", first_screen)
        self.assertIn("TaskLaunchReceipt receipt={runtimeQaExecutionRequestReceipt}", first_screen)
        self.assertIn("TaskStatusPanel taskId={runtimeQaExecutionRequestTaskId}", first_screen)
        self.assertIn("TaskLaunchReceipt receipt={runtimeQaDryRunReceipt}", first_screen)
        self.assertIn("TaskStatusPanel taskId={runtimeQaDryRunTaskId}", first_screen)
        self.assertIn("TaskLaunchReceipt receipt={runtimeQaExecutionReceipt}", first_screen)
        self.assertIn("TaskStatusPanel taskId={runtimeQaExecutionTaskId}", first_screen)
        self.assertIn('href="#worker-runtime-qa-details"', first_screen)
        self.assertIn("GET worker 只读", page[:audit_start])
        self.assertIn("不启动 Celery/Redis/APScheduler、不派发任务、不调用 provider/model、不交易", page[:audit_start])
        self.assertIn("刷新只读取本地 GET cache", first_screen)
        self.assertIn("除显式 Runtime QA 按钮外，首屏不会创建 task", first_screen)
        self.assertIn("Runtime QA 首屏按钮是显式 POST local task", first_screen)
        self.assertIn("local execution 仍不是 production worker complete", first_screen)
        self.assertIn('id="worker-runtime-qa-details"', page)
        self.assertNotIn("runWorker", first_screen)

    def test_worker_app_visible_now_summary_is_read_only_before_task_buttons(self):
        page = self.worker_page
        head_start = page.index("<h1>Worker 运行时</h1>")
        visible_start = page.index('aria-label="worker app visible now summary"')
        first_screen_start = page.index('aria-label="worker ordinary first screen status"')
        runtime_task_start = page.index('aria-label="worker ordinary runtime qa task strip"')
        gate_start = page.index('title="LTG-06 worker strict closeout gate"')
        visible_slice = page[visible_start:first_screen_start]

        self.assertLess(head_start, visible_start)
        self.assertLess(visible_start, first_screen_start)
        self.assertLess(visible_start, runtime_task_start)
        self.assertLess(visible_start, gate_start)
        self.assertIn("workerAppVisibleNowSentence", page[:gate_start])
        self.assertIn("workerAppVisibleNowItems", page[:gate_start])
        self.assertIn("打开 app 能看到什么", visible_slice)
        self.assertIn('aria-label="worker app visible now sentence"', visible_slice)
        self.assertIn("{workerAppVisibleNowSentence}", visible_slice)
        self.assertIn("MetricGrid items={workerAppVisibleNowItems}", visible_slice)
        self.assertIn('aria-label="worker app visible now local actions"', visible_slice)
        self.assertIn('href="#storage"', visible_slice)
        self.assertIn('href="#worker-runtime-qa-details"', visible_slice)
        self.assertIn('href="#tasks"', visible_slice)
        self.assertIn('label: "运行状态"', page)
        self.assertIn('label: "任务/log"', page)
        self.assertIn('label: "Runtime QA"', page)
        self.assertIn('label: "Celery/Redis"', page)
        self.assertIn('label: "下一步入口"', page)
        self.assertIn('label: "安全边界"', page)
        self.assertIn("打开 app 能看到 Worker 当前状态", page)
        self.assertIn("只读速读和本地锚点；不创建 task、不启动 Celery/Redis", page)
        self.assertIn("普通链接只切换本地页面或锚点", visible_slice)
        self.assertIn("不创建 task、不启动 Celery/Redis/APScheduler、不 ping Redis", visible_slice)
        self.assertIn("不派发 provider/model task、不调用 Tushare/DeepSeek/GitHub、不交易", visible_slice)
        self.assertIn("不改 strategy action", visible_slice)
        self.assertNotIn("onClick=", visible_slice)
        self.assertNotIn("TaskLaunchReceipt", visible_slice)
        self.assertNotIn("TaskStatusPanel", visible_slice)
        self.assertNotIn("launchRuntimeQa", visible_slice)
        self.assertNotIn("runWorker", visible_slice)


if __name__ == "__main__":
    unittest.main()
