import unittest
from pathlib import Path


class NextSessionMapOrdinaryEntryTests(unittest.TestCase):
    def setUp(self):
        self.root = Path(__file__).resolve().parents[1]
        self.page = (self.root / "desktop" / "src" / "routes" / "NextSessionMap.tsx").read_text(
            encoding="utf-8"
        )

    def test_next_session_hides_stale_chart_payload_for_latest_confirmed_symbol(self):
        self.assertIn("const rawChartPayload = packet.chart_payload", self.page)
        self.assertIn("const ordinaryResultReplaySummary", self.page)
        self.assertIn("ordinaryResultReplaySummary.chart_ready_for_confirmed_symbol === true", self.page)
        self.assertIn("ordinaryResultReplaySummary.chart_stale_for_confirmed_symbol === true", self.page)
        self.assertIn("const chartPayload = chartReadyForConfirmedSymbol ? rawChartPayload : undefined;", self.page)
        self.assertIn("has_drawable_data: false", self.page)
        self.assertIn("chart_ready_for_confirmed_symbol: false", self.page)
        self.assertIn("chart_stale_for_confirmed_symbol: chartStaleForConfirmedSymbol", self.page)
        self.assertIn('status: chartStaleForConfirmedSymbol ? "stale_for_latest_confirmed_symbol" : rawChartSummary.status', self.page)
        self.assertIn("<NextSessionChart payload={chartPayload} />", self.page)

    def test_next_session_has_three_step_ordinary_result_replay_before_audit(self):
        summary_start = self.page.index('title="普通用户次日图谱摘要"')
        audit_start = self.page.index('<details id="next-session-audit"')
        ordinary_slice = self.page[summary_start:audit_start]
        source_before_audit = self.page[:audit_start]

        self.assertLess(summary_start, audit_start)
        app_first_start = ordinary_slice.index('aria-label="next session app first research read"')
        plain_start = ordinary_slice.index('aria-label="next session ordinary plain conclusion"')
        decision_start = ordinary_slice.index('aria-label="next session first screen readable decision"')
        app_first_slice = ordinary_slice[app_first_start:plain_start]
        plain_slice = ordinary_slice[plain_start:decision_start]
        self.assertLess(app_first_start, plain_start)
        self.assertLess(plain_start, decision_start)
        self.assertLess(
            ordinary_slice.index('aria-label="next session app first research read"'),
            ordinary_slice.index('data-page-state="next_session_ordinary_cache_state"'),
        )
        self.assertIn("nextSessionAppFirstResearchReadSentence", source_before_audit)
        self.assertIn("nextSessionAppFirstResearchReadItems", source_before_audit)
        self.assertIn("本地投研速读", app_first_slice)
        self.assertIn('aria-label="next session app first research read sentence"', app_first_slice)
        self.assertIn("MetricGrid items={ordinaryNextMetricItems(nextSessionAppFirstResearchReadItems)}", app_first_slice)
        self.assertIn('aria-label="next session app first research read actions"', app_first_slice)
        for app_first_label in (
            'label: "现在能看"',
            'label: "读图顺序"',
            'label: "证据来源"',
            'label: "degraded 缺口"',
            'label: "下一步入口"',
            'label: "研究边界"',
        ):
            self.assertIn(app_first_label, source_before_audit)
        self.assertIn("路径 -> 参考线 -> 操作区 -> 缺口", source_before_audit)
        self.assertIn("图谱和操作区只做条件复核", source_before_audit)
        self.assertIn("链接只切换本地页面或锚点，不创建后台流程", app_first_slice)
        self.assertIn('href={nextSessionOrdinaryProgressCheckpointAnchor}', app_first_slice)
        self.assertIn('href="#next-session-chart"', app_first_slice)
        self.assertIn('href="#factor"', app_first_slice)
        self.assertIn('href={CANDIDATE_CONFIRM_HREF}', app_first_slice)
        self.assertNotIn("onClick=", app_first_slice)
        self.assertNotIn("launch" + "Task", app_first_slice)
        self.assertNotIn("post" + "Task(", app_first_slice)
        self.assertNotIn("TaskStatusPanel", app_first_slice)
        self.assertIn("nextSessionPlainConclusion", source_before_audit)
        self.assertIn("nextSessionPlainGap", source_before_audit)
        self.assertIn("nextSessionPlainNow", source_before_audit)
        self.assertIn("nextSessionPlainSafety", source_before_audit)
        self.assertIn("nextSessionPlainConclusionItems", source_before_audit)
        self.assertIn("普通结论", plain_slice)
        self.assertIn('aria-label="next session ordinary plain conclusion sentence"', plain_slice)
        self.assertIn("MetricGrid items={ordinaryNextMetricItems(nextSessionPlainConclusionItems)}", plain_slice)
        self.assertIn("还没有可读次日图谱；先回下一票雷达确认股票。", source_before_audit)
        self.assertIn("完整次日图谱还要手动生成。", source_before_audit)
        self.assertIn("生产替代证据还没补齐；当前图谱先按本地路径、参考线和操作区阅读。", source_before_audit)
        self.assertIn("先看图表路径和参考线，再看操作区。", source_before_audit)
        self.assertIn("图谱只做条件路径复核，不是买入、卖出、加仓或下单指令。", source_before_audit)
        for plain_label in (
            'label: "一句话"',
            'label: "缺口"',
            'label: "现在做什么"',
            'label: "安全说明"',
        ):
            self.assertIn(plain_label, source_before_audit)
        self.assertIn("页面打开、查看结果和切换入口都不会自动创建任务、调用外部服务或改写操作区", plain_slice)
        self.assertNotIn("onClick=", plain_slice)
        self.assertNotIn("launch" + "Task", plain_slice)
        self.assertNotIn("post" + "Task(", plain_slice)
        self.assertNotIn("cache / ledger", plain_slice)
        self.assertNotIn("task", plain_slice)
        self.assertNotIn("retained signal", plain_slice)
        self.assertNotIn("capability coverage", plain_slice)
        self.assertIn("ordinaryResultReplayStatus", source_before_audit)
        self.assertIn("ordinaryResultReplayRows", source_before_audit)
        self.assertIn("packetOrdinaryResultReplayRows", source_before_audit)
        self.assertIn("packet.ordinary_result_replay_rows", source_before_audit)
        self.assertIn("packet.ordinary_result_replay_status", source_before_audit)
        self.assertIn("packetCandidateRadarP3Handoff", source_before_audit)
        self.assertIn("packet.candidate_radar_p3_handoff", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffReady", source_before_audit)
        self.assertIn("packetCandidateRadarP2HandoffReady", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffSymbol", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffSourceTask", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffSummary", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffNextStep", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffBoundary", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffDeepSeekState", source_before_audit)
        self.assertIn("nextSessionPacketHandoffLabel", source_before_audit)
        self.assertIn("本地次日图谱数据已接上", source_before_audit)
        self.assertIn("本地次日图谱数据等待 CandidateRadar P3 结果", source_before_audit)
        self.assertIn("fallbackOrdinaryResultReplayRows", source_before_audit)
        self.assertIn("packetOrdinaryResultReplayRows.length", source_before_audit)
        self.assertIn("ordinaryInterpretationActionRows", source_before_audit)
        self.assertIn("ordinaryDeepSeekGovernanceRows", source_before_audit)
        self.assertIn("ordinaryChartReviewRows", source_before_audit)
        self.assertIn("nextSessionResultHandoffRows", source_before_audit)
        self.assertIn("nextSessionP3OneMinuteReadRows", source_before_audit)
        self.assertIn("nextSessionOperationZoneQuickReadRows", source_before_audit)
        self.assertIn("getCandidateRadarCache", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback", source_before_audit)
        self.assertIn("candidateRadarWritebackSurfaceRows", source_before_audit)
        self.assertIn("candidateRadarWritebackSurfaceReady", source_before_audit)
        self.assertIn("candidateRadarWritebackSurfaceStatus", source_before_audit)
        self.assertIn("candidateRadarWritebackSurfaceBoundary", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_writeback_surface_summary_rows", source_before_audit)
        self.assertIn("packetCandidateRadarP2HandoffReady ||", source_before_audit)
        self.assertIn("P2 三面已由 next-session handoff 回放：本地缓存、数据凭证、结果包可读；cache / call_ledger / packet 可读", source_before_audit)
        self.assertIn("P2 三面已回放：本地缓存、数据凭证、结果包可读；cache / call_ledger / packet 都可读", source_before_audit)
        self.assertIn("P2 三面只读 CandidateRadar cache / call_ledger / packet；图谱页不创建 task、不补调 Tushare/DeepSeek。", source_before_audit)
        self.assertIn("candidateRadarOneScreenRows", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_one_screen_action_rows", source_before_audit)
        self.assertIn("candidateRadarConfirmOutcomeRows", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_confirm_outcome_rows", source_before_audit)
        self.assertIn("candidateRadarConfirmedSymbol", source_before_audit)
        self.assertIn("candidateRadarConfirmedSymbolLabel", source_before_audit)
        self.assertIn("candidateRadarSourceTaskLabel", source_before_audit)
        self.assertIn("packet.latest_confirmed_symbol", source_before_audit)
        self.assertIn("candidateRadarCache.latest_confirmed_symbol", source_before_audit)
        self.assertIn("packet.latest_confirmed_task_id", source_before_audit)
        self.assertIn("candidateRadarCache.latest_confirmed_task_id", source_before_audit)
        self.assertIn("getTasks", source_before_audit)
        self.assertIn("const [taskIndex, setTaskIndex] = useState<TaskStatusIndex | null>(null);", source_before_audit)
        self.assertIn("taskIndex?.latest_confirmed_symbol", source_before_audit)
        self.assertIn("taskIndex?.latest_confirmed_task_id", source_before_audit)
        self.assertIn("taskIndex?.latest_confirmed_task_status", source_before_audit)
        self.assertIn("taskIndex?.latest_confirmed_task_current_step", source_before_audit)
        self.assertIn("nextSessionTaskIndexProgressItems", source_before_audit)
        self.assertIn('aria-label="next session local task index progress watch"', ordinary_slice)
        self.assertIn("本地任务进度", ordinary_slice)
        self.assertIn("GET /api/tasks + 本地次日图谱数据 + CandidateRadar cache", source_before_audit)
        self.assertIn("任务索引回读未触发外联、未创建 task", source_before_audit)
        self.assertIn("边用边看：{nextSessionProgressWatchNext}", ordinary_slice)
        self.assertIn("这只来自 GET /api/tasks、本地次日图谱数据和 CandidateRadar cache，不创建第二个 task", ordinary_slice)
        self.assertIn("candidateRadarCache.search_quant_projection_latest_task_id", source_before_audit)
        self.assertIn("candidateRadarCache.latest_task_id", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffSymbol ||", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffSourceTask ||", source_before_audit)
        self.assertIn("candidateRadarConfirmedTaskReceiptRows", source_before_audit)
        self.assertIn("candidateRadarTaskReadbackRows", source_before_audit)
        self.assertIn("candidateRadarCache.search_quant_projection_confirmed_task_receipt_rows", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_confirmed_task_receipt_rows", source_before_audit)
        self.assertIn("candidateRadarCache.search_quant_projection_task_readback_rows", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_task_readback_rows", source_before_audit)
        self.assertIn("nextSessionTaskSourceReadbackItems", source_before_audit)
        self.assertIn("当前确认标的：${candidateRadarConfirmedSymbol}", source_before_audit)
        self.assertIn("等待下一票雷达确认标的", source_before_audit)
        self.assertIn("等待下一票雷达确认 task", source_before_audit)
        self.assertIn("candidateRadarCache.ordinary_result_quick_read_rows", source_before_audit)
        self.assertIn("candidateRadarCache.ordinary_result_handoff_rows", source_before_audit)
        self.assertIn("candidateRadarInterpretation.ordinary_result_quick_read_rows", source_before_audit)
        self.assertIn("candidateRadarInterpretation.ordinary_result_handoff_rows", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffSummary ||", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffNextStep ||", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffBoundary ||", source_before_audit)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_result_quick_read_rows / ordinary_result_handoff_rows", source_before_audit)
        self.assertIn("candidateRadarDeepSeekStateRaw", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffDeepSeekState ||", source_before_audit)
        self.assertIn("candidateRadarOrdinaryDeepSeekState", source_before_audit)
        self.assertIn("candidateRadarUsesModelOutput", source_before_audit)
        self.assertIn("packetCandidateRadarP3Handoff.uses_deepseek_output === true", source_before_audit)
        self.assertIn("packetCandidateRadarP3Handoff.uses_model_output === true", source_before_audit)
        self.assertIn("candidateRadarCache.ordinary_result_deepseek_governed_executor_status", source_before_audit)
        self.assertIn("DeepSeek 不用等：Tushare-first 和次日图谱可先看", source_before_audit)
        self.assertIn("DeepSeek 待治理：不阻塞 Tushare-first、P2 写入或 P3 图谱", source_before_audit)
        self.assertIn("nextSessionUpstreamOneScreenRows", source_before_audit)
        self.assertIn("nextSessionUpstreamOneScreenLabel", source_before_audit)
        self.assertIn("nextSessionUpstreamConfirmOutcomeRows", source_before_audit)
        self.assertIn("nextSessionUpstreamConfirmOutcomeLabel", source_before_audit)
        self.assertIn("packetOrdinaryChartReviewRows", source_before_audit)
        self.assertIn("packet.ordinary_chart_review_rows", source_before_audit)
        self.assertIn("packetOrdinaryConditionQuickReadRows", source_before_audit)
        self.assertIn("packet.ordinary_condition_quick_read_rows", source_before_audit)
        self.assertIn("fallbackNextSessionOperationZoneQuickReadRows", source_before_audit)
        self.assertIn("packetOrdinaryConditionQuickReadRows.length", source_before_audit)
        self.assertIn("fallbackOrdinaryChartReviewRows", source_before_audit)
        self.assertIn("packetOrdinaryChartReviewRows.length", source_before_audit)
        self.assertIn("nextSessionLastResultLabel", source_before_audit)
        self.assertIn("candidateRadarReadableResultReady", source_before_audit)
        self.assertIn("nextSessionReadableStatusLabel", source_before_audit)
        self.assertIn("nextSessionReadableNextClick", source_before_audit)
        self.assertIn("nextSessionReadableLastResultLabel", source_before_audit)
        self.assertIn("nextSessionReadableChartReviewOrder", source_before_audit)
        self.assertIn("nextSessionGeneratePayload", source_before_audit)
        self.assertIn("if (!candidateRadarConfirmedSymbol) return;", source_before_audit)
        self.assertIn('postTask("/api/next-session/generate", nextSessionGeneratePayload)', source_before_audit)
        self.assertIn("refreshTaskIndex();", source_before_audit)
        self.assertIn("refreshCache();", source_before_audit)
        self.assertIn('schema_version: "next_session_confirmed_symbol_generate_payload.v1"', source_before_audit)
        self.assertIn('source: "next_session_map_manual_generate_button"', source_before_audit)
        self.assertIn("symbol: candidateRadarConfirmedSymbol", source_before_audit)
        self.assertIn("source_task_id: candidateRadarSourceTaskLabel.includes(\"等待\") ? \"\" : candidateRadarSourceTaskLabel", source_before_audit)
        self.assertIn('candidate_readback_source: "CandidateRadar cache / ledger / packet"', source_before_audit)
        self.assertIn("p2_small_data_ready: candidateRadarWritebackSurfaceReady", source_before_audit)
        self.assertIn("p3_readable_result_ready: candidateRadarReadableResultReady", source_before_audit)
        self.assertIn("manual_button_required: true", source_before_audit)
        self.assertIn("const nextSessionGenerateButtonDisabled = !candidateRadarConfirmedSymbol", source_before_audit)
        self.assertIn("为 ${candidateRadarConfirmedSymbol} 生成完整次日图谱", source_before_audit)
        self.assertIn("为 ${candidateRadarConfirmedSymbol} 生成完整图谱", source_before_audit)
        self.assertIn("等待下一票雷达确认标的后才能生成完整次日图谱", source_before_audit)
        self.assertIn("cache_get_external_calls_triggered: false", source_before_audit)
        self.assertIn("react_render_external_calls_triggered: false", source_before_audit)
        self.assertIn("deepseek_execution_requested: false", source_before_audit)
        self.assertIn("does_not_include_token_or_raw_log: true", source_before_audit)
        self.assertIn("does_not_execute_trades: true", source_before_audit)
        self.assertIn("does_not_modify_operation_zones: true", source_before_audit)
        self.assertIn("nextSessionOrdinaryProgressCheckpointItems", source_before_audit)
        self.assertIn("nextSessionOrdinaryProgressCheckpointAnchor", source_before_audit)
        self.assertIn("nextSessionOrdinaryProgressCheckpointLabel", source_before_audit)
        self.assertIn("nextSessionUsableNowItems", source_before_audit)
        self.assertIn("packetCandidateRadarP3HandoffReady ||", source_before_audit)
        self.assertIn("上游搜票结论可读：完整图谱等待手动生成", source_before_audit)
        self.assertIn("上游结论可读，完整图谱等待手动生成", source_before_audit)
        self.assertIn("只读回放；生成必须手动按钮；不调用 DeepSeek、不交易、不改操作区", source_before_audit)
        self.assertIn("只读回放；生成必须手动按钮；DeepSeek 单独补；不交易、不改操作区", source_before_audit)
        self.assertIn("已回放：本地缓存、数据凭证、结果包", source_before_audit)
        self.assertIn("已回放搜票结论，图谱待生成", source_before_audit)
        self.assertIn("先看已确认标的和 Tushare-first 结论；完整图谱可手动生成", source_before_audit)
        self.assertIn("上游结果：${candidateRadarConfirmedSymbol}；${candidateRadarReadableResult}", source_before_audit)
        self.assertIn("先读已确认标的、Tushare-first 结论和 P2 三面；完整图谱可手动生成", source_before_audit)
        self.assertIn("candidate_readable_result_replay_chart_pending", source_before_audit)
        self.assertIn("chartSummary.has_drawable_data === true || candidateRadarReadableResultReady ? \"good\" : \"warn\"", source_before_audit)
        self.assertIn("!candidateRadarReadableResultReady && (packet.status === \"cache_missing\"", source_before_audit)
        self.assertIn("nextSessionOrdinaryReplayBoundaryBlocked", source_before_audit)
        self.assertIn("evidence_gap_clear", source_before_audit)
        self.assertIn("research_boundary_ready", source_before_audit)
        usable_now_start = ordinary_slice.index('aria-label="next session ordinary usable now strip"')
        task_progress_start = ordinary_slice.index('aria-label="next session local task index progress watch"')
        checkpoint_start = ordinary_slice.index('aria-label="next session ordinary progress checkpoint"')
        self.assertLess(usable_now_start, task_progress_start)
        self.assertLess(task_progress_start, checkpoint_start)
        usable_now_slice = ordinary_slice[usable_now_start:task_progress_start]
        task_progress_slice = ordinary_slice[task_progress_start:checkpoint_start]
        self.assertIn("现在可读状态", usable_now_slice)
        self.assertIn("MetricGrid items={nextSessionUsableNowItems}", usable_now_slice)
        self.assertIn('label: "图谱状态"', source_before_audit)
        self.assertIn('label: "Next cache handoff"', source_before_audit)
        self.assertIn("value: nextSessionPacketHandoffLabel", source_before_audit)
        self.assertIn("tone: packetCandidateRadarP3HandoffReady ? \"good\" : \"warn\"", source_before_audit)
        self.assertIn("search_quant_canonical_result_lineage", source_before_audit)
        self.assertIn("candidateRadarCanonicalTaskId", source_before_audit)
        self.assertIn("candidateRadarFactsPackageHash", source_before_audit)
        self.assertIn("candidateRadarModelLedgerId", source_before_audit)
        self.assertIn("candidateRadarSameTaskFactModelReady", source_before_audit)
        self.assertIn("canonical_same_task_fact_model_result_version_ready", source_before_audit)
        self.assertIn("same_task_fact_model_result_version_ready", source_before_audit)
        self.assertIn('label: "同源结果"', source_before_audit)
        self.assertIn('label: "模型账本"', source_before_audit)
        self.assertIn("同一 task ${candidateRadarCanonicalTaskId}", source_before_audit)
        self.assertIn("facts package ${candidateRadarFactsPackageHash}", source_before_audit)
        self.assertIn("result_version ${candidateRadarCurrentResultVersion}", source_before_audit)
        self.assertIn("model_ledger_id ${candidateRadarModelLedgerId}", source_before_audit)
        self.assertIn('label: "P3 结论"', source_before_audit)
        self.assertIn('label: "P2 三面"', source_before_audit)
        self.assertIn('label: "操作区"', source_before_audit)
        self.assertIn('label: "现在点哪"', source_before_audit)
        self.assertIn('label: "安全边界"', source_before_audit)
        self.assertIn("这条只合成图谱可绘制、P3 结论、P2 三面、操作区和下一步；不创建 task、不调用 Tushare/DeepSeek、不改操作区或 strategy action。", usable_now_slice)
        self.assertNotIn("onClick=", usable_now_slice)
        self.assertNotIn("launch" + "Task", usable_now_slice)
        self.assertNotIn("post" + "Task(", usable_now_slice)
        self.assertIn("本地任务进度", task_progress_slice)
        self.assertIn("MetricGrid items={nextSessionTaskIndexProgressItems}", task_progress_slice)
        self.assertIn('aria-label="next session local task index progress actions"', task_progress_slice)
        self.assertIn('href="#tasks"', task_progress_slice)
        self.assertIn('href="#next-session-chart"', task_progress_slice)
        self.assertIn('href="#factor"', task_progress_slice)
        self.assertNotIn("onClick=", task_progress_slice)
        self.assertNotIn("launch" + "Task", task_progress_slice)
        self.assertNotIn("post" + "Task(", task_progress_slice)
        metric_start = ordinary_slice.index("<MetricGrid")
        metric_end = ordinary_slice.index("<StateClarityRail", metric_start)
        summary_metric_slice = ordinary_slice[metric_start:metric_end]
        self.assertIn('label: "当前标的"', summary_metric_slice)
        self.assertIn("value: candidateRadarConfirmedSymbolLabel", summary_metric_slice)
        self.assertIn("value: nextSessionReadableNextClick", summary_metric_slice)
        self.assertIn("value: nextSessionReadableLastResultLabel", summary_metric_slice)
        self.assertIn("value: nextSessionReadableChartReviewOrder", summary_metric_slice)
        self.assertIn('label: "生成血缘"', summary_metric_slice)
        self.assertIn("value: nextSessionGeneratePayload.source_task_id", summary_metric_slice)
        self.assertIn('label: "本地缓存"', summary_metric_slice)
        self.assertIn('label: "数据链"', summary_metric_slice)
        self.assertIn('label: "解释状态"', summary_metric_slice)
        self.assertIn('label: "P5 解释治理"', summary_metric_slice)
        self.assertIn('label: "待补证据"', summary_metric_slice)
        self.assertIn('label: "降级提示"', summary_metric_slice)
        self.assertIn("nextSessionP5GovernanceLabel", source_before_audit)
        self.assertIn("P5 解释治理：DeepSeek 单独补证，不阻塞 P3 图谱复核", source_before_audit)
        for engineering_label in (
            'label: "cache"',
            'label: "Tushare"',
            'label: "DeepSeek"',
            'label: "pending"',
            'label: "degraded"',
        ):
            self.assertNotIn(engineering_label, summary_metric_slice)
        checkpoint_start = ordinary_slice.index('aria-label="next session ordinary progress checkpoint"')
        rail_start = ordinary_slice.index('label="next session ordinary replay status"')
        checkpoint_slice = ordinary_slice[checkpoint_start:rail_start]
        self.assertIn("当前图谱 checkpoint", checkpoint_slice)
        self.assertIn("MetricGrid items={nextSessionOrdinaryProgressCheckpointItems}", checkpoint_slice)
        self.assertIn('aria-label="next session ordinary progress checkpoint actions"', checkpoint_slice)
        self.assertIn('href={nextSessionOrdinaryProgressCheckpointAnchor}', checkpoint_slice)
        self.assertIn('href="#next-session-chart"', checkpoint_slice)
        self.assertIn('href={CANDIDATE_CONFIRM_HREF}', checkpoint_slice)
        self.assertIn("链接只切换本地页面或锚点，不创建 task、不调用 Tushare/DeepSeek", checkpoint_slice)
        self.assertNotIn("onClick=", checkpoint_slice)
        self.assertNotIn("launch" + "Task", checkpoint_slice)
        self.assertNotIn("post" + "Task(", checkpoint_slice)
        self.assertIn('label: "缺口边界"', source_before_audit)
        self.assertIn('label: "上游确认链"', source_before_audit)
        self.assertIn('label: "确认结果链"', source_before_audit)
        self.assertIn('value: candidateRadarOrdinaryDeepSeekState', ordinary_slice)
        self.assertIn('tone: candidateRadarUsesModelOutput ? "warn" : "good"', ordinary_slice)
        rail_start = ordinary_slice.index('label="next session ordinary replay status"')
        handoff_start = ordinary_slice.index('aria-label="next session p3 result handoff quick read"')
        rail_slice = ordinary_slice[rail_start:handoff_start]
        self.assertIn("普通图谱状态：雷达/量化回放 / 图表路径 / 操作区 / 缺口边界", rail_slice)
        self.assertIn("P5 解释治理继续收起为单独补证", rail_slice)
        self.assertNotIn("DeepSeek 状态", rail_slice)
        one_minute_start = ordinary_slice.index('aria-label="next session p3 one minute read"')
        handoff_start = ordinary_slice.index('aria-label="next session p3 result handoff quick read"')
        self.assertLess(one_minute_start, handoff_start)
        one_minute_slice = ordinary_slice[one_minute_start:handoff_start]
        self.assertIn("P3 一分钟读图", one_minute_slice)
        self.assertIn("普通用户先看这张表：用一分钟确认来源、可读结论、操作区、缺口和回流入口", one_minute_slice)
        self.assertIn("DataLineageTable rows={nextSessionP3OneMinuteReadRows}", one_minute_slice)
        self.assertNotIn("onClick=", one_minute_slice)
        self.assertNotIn("launch" + "Task", one_minute_slice)
        self.assertNotIn("post" + "Task(", one_minute_slice)
        self.assertIn('aria-label="next session p3 result handoff quick read"', ordinary_slice)
        self.assertIn("P3 结果交接速读", ordinary_slice)
        self.assertIn("先看来源、结论、缺口和操作区边界", ordinary_slice)
        self.assertIn("DataLineageTable rows={nextSessionResultHandoffRows}", ordinary_slice)
        self.assertIn('aria-label="next session ordinary operation zone quick read"', ordinary_slice)
        self.assertIn("操作区解释速读", ordinary_slice)
        self.assertIn("普通用户先按路径、参考线、操作区的顺序读", ordinary_slice)
        self.assertIn("操作区只是条件区间和复核提示，不是买卖、下单或 strategy action", ordinary_slice)
        self.assertIn("优先读取本地缓存里的条件速读", ordinary_slice)
        self.assertIn("旧缓存缺字段时才使用前端 fallback", ordinary_slice)
        self.assertIn("DataLineageTable rows={nextSessionOperationZoneQuickReadRows}", ordinary_slice)
        latest_candidate_start = ordinary_slice.index('aria-label="next session latest candidate readable result"')
        latest_candidate_end = ordinary_slice.index('aria-label="next session p3 one minute read"', latest_candidate_start)
        latest_candidate_slice = ordinary_slice[latest_candidate_start:latest_candidate_end]
        self.assertIn("nextSessionLatestCandidateReadableSentence", source_before_audit)
        self.assertIn("P3 结论：${candidateRadarReadableResult}", source_before_audit)
        self.assertIn("完整图谱等待手动生成", source_before_audit)
        self.assertIn('aria-label="next session latest candidate readable sentence"', latest_candidate_slice)
        self.assertIn("{nextSessionLatestCandidateReadableSentence}", latest_candidate_slice)
        self.assertLess(
            latest_candidate_slice.index('aria-label="next session latest candidate readable sentence"'),
            latest_candidate_slice.index("<MetricGrid"),
        )
        self.assertIn('label: "来源任务"', latest_candidate_slice)
        self.assertIn("value: candidateRadarSourceTaskLabel", latest_candidate_slice)
        self.assertIn('label: "P2 小数据"', latest_candidate_slice)
        self.assertIn("candidateRadarWritebackSurfaceStatus", latest_candidate_slice)
        self.assertIn('label: "P2 边界"', latest_candidate_slice)
        self.assertIn("value: candidateRadarWritebackSurfaceBoundary", latest_candidate_slice)
        self.assertIn('aria-label="next session p1 task source readback"', latest_candidate_slice)
        self.assertIn("P1 任务来源回放", latest_candidate_slice)
        self.assertIn("这张小表只说明 P3 图谱结论来自哪次确认 task", latest_candidate_slice)
        self.assertIn("MetricGrid items={nextSessionTaskSourceReadbackItems}", latest_candidate_slice)
        self.assertIn('label: "来源 task"', source_before_audit)
        self.assertIn('label: "确认回执"', source_before_audit)
        self.assertIn('label: "任务回放"', source_before_audit)
        self.assertIn('label: "读取边界"', source_before_audit)
        self.assertIn("等待 search_quant_projection_confirmed_task_receipt_rows", source_before_audit)
        self.assertIn("等待 search_quant_projection_task_readback_rows", source_before_audit)
        self.assertIn('aria-label="next session readable result local actions"', latest_candidate_slice)
        readable_actions_start = latest_candidate_slice.index('aria-label="next session readable result local actions"')
        self.assertLess(
            latest_candidate_slice.index('aria-label="next session latest candidate readable sentence"'),
            readable_actions_start,
        )
        readable_actions_end = latest_candidate_slice.index("</div>", readable_actions_start)
        readable_actions_slice = latest_candidate_slice[readable_actions_start:readable_actions_end]
        self.assertIn('href="#next-session-chart"', readable_actions_slice)
        self.assertIn('href="#factor"', readable_actions_slice)
        self.assertIn('href={CANDIDATE_CONFIRM_HREF}', readable_actions_slice)
        self.assertIn("查看图谱区域", readable_actions_slice)
        self.assertIn("查看支持/压制", readable_actions_slice)
        self.assertIn("回下一票雷达", readable_actions_slice)
        self.assertNotIn("onClick=", readable_actions_slice)
        self.assertNotIn("launch" + "Task", readable_actions_slice)
        self.assertNotIn("post" + "Task(", readable_actions_slice)
        task_source_start = latest_candidate_slice.index('aria-label="next session p1 task source readback"')
        task_source_end = latest_candidate_slice.index('aria-label="next session readable result local actions"', task_source_start)
        task_source_slice = latest_candidate_slice[task_source_start:task_source_end]
        self.assertNotIn("onClick=", task_source_slice)
        self.assertNotIn("launch" + "Task", task_source_slice)
        self.assertNotIn("post" + "Task(", task_source_slice)
        self.assertIn("这组入口只切换本地页面或锚点；不创建 task、不调用 Tushare/DeepSeek/GitHub、不写 cache，也不改变操作区或 strategy action。", latest_candidate_slice)
        operation_zone_start = ordinary_slice.index('aria-label="next session ordinary operation zone quick read"')
        upstream_details_start = ordinary_slice.index('aria-label="next session upstream readback details"')
        self.assertIn("<summary>上游确认链路详情</summary>", ordinary_slice)
        self.assertIn("普通首屏先读 P3 图谱", ordinary_slice)
        self.assertLess(operation_zone_start, upstream_details_start)
        upstream_details_end = ordinary_slice.index("</details>", upstream_details_start)
        upstream_details_slice = ordinary_slice[upstream_details_start:upstream_details_end]
        self.assertIn('aria-label="next session upstream one screen actions"', upstream_details_slice)
        self.assertIn("上游确认一屏行动", upstream_details_slice)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_one_screen_action_rows", upstream_details_slice)
        self.assertIn("确认、任务、写回、结果合成图谱页上游速读", upstream_details_slice)
        self.assertIn("本页只读回放，不创建 task、不调用模型", upstream_details_slice)
        self.assertIn("DataLineageTable rows={nextSessionUpstreamOneScreenRows}", upstream_details_slice)
        self.assertIn('aria-label="next session upstream confirm outcome readback"', upstream_details_slice)
        self.assertIn("上游确认结果速读", upstream_details_slice)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_confirm_outcome_rows", upstream_details_slice)
        self.assertIn("确认任务是否接收、P2 三面是否回放、P3 图谱入口是否可读", upstream_details_slice)
        self.assertIn("本页只读回放，不创建第二个 task", upstream_details_slice)
        self.assertIn("DataLineageTable rows={nextSessionUpstreamConfirmOutcomeRows}", upstream_details_slice)
        self.assertNotIn("onClick=", upstream_details_slice)
        self.assertNotIn("launch" + "Task", upstream_details_slice)
        self.assertNotIn("post" + "Task(", upstream_details_slice)
        self.assertIn('aria-label="next session ordinary expanded chart replay details"', ordinary_slice)
        self.assertIn("<summary>更多图谱回放明细</summary>", ordinary_slice)
        self.assertIn("普通主视图保留 P3 一分钟读图、结果交接和操作区速读", ordinary_slice)
        expanded_details_start = ordinary_slice.index('aria-label="next session ordinary expanded chart replay details"')
        self.assertLess(upstream_details_start, expanded_details_start)
        self.assertIn('速读项: "1. 先读路径"', source_before_audit)
        self.assertIn('速读项: "2. 再读操作区"', source_before_audit)
        self.assertIn('速读项: "3. 动作隔离"', source_before_audit)
        self.assertIn("等待操作区 cache；不能把空操作区解释成无风险", source_before_audit)
        self.assertIn("边界正常：前端只读，不改 action 或操作区", source_before_audit)
        self.assertIn("次日图谱不下单、不写 strategy action；DeepSeek 也不能覆盖操作区", source_before_audit)
        self.assertIn('交接段: "1. 来源"', source_before_audit)
        self.assertIn('交接段: "2. 结论"', source_before_audit)
        self.assertIn('交接段: "3. 缺口"', source_before_audit)
        self.assertIn('交接段: "4. 操作区"', source_before_audit)
        self.assertIn('读图顺序: "1. 来源"', source_before_audit)
        self.assertIn('读图顺序: "2. 可读结论"', source_before_audit)
        self.assertIn('读图顺序: "3. 操作区"', source_before_audit)
        self.assertIn('读图顺序: "4. 缺口"', source_before_audit)
        self.assertIn('读图顺序: "5. 回流"', source_before_audit)
        self.assertIn('行动: "1. 确认"', source_before_audit)
        self.assertIn('行动: "2. 任务"', source_before_audit)
        self.assertIn('行动: "3. 写回"', source_before_audit)
        self.assertIn('行动: "4. 结果"', source_before_audit)
        self.assertIn('确认结果: "P1 确认结果"', source_before_audit)
        self.assertIn('确认结果: "P2 写回结果"', source_before_audit)
        self.assertIn('确认结果: "P3 回放结果"', source_before_audit)
        self.assertIn("GET cache 只读；不创建 task、不调用 Tushare/DeepSeek/GitHub", source_before_audit)
        self.assertIn("缺口只提示下一步；GET cache 和 React render 不补调 provider/model", source_before_audit)
        self.assertIn("local route handoff #candidates/.../#factor", source_before_audit)
        self.assertIn("三段结果回放", ordinary_slice)
        self.assertIn("三段结果回放优先读取服务端 ordinary_result_replay_rows", ordinary_slice)
        self.assertIn("旧 packet 缺字段时才使用前端 fallback", ordinary_slice)
        self.assertIn("DataLineageTable rows={ordinaryResultReplayRows}", ordinary_slice)
        self.assertIn('aria-label="next session ordinary interpretation actions"', ordinary_slice)
        self.assertIn("解释性行动清单", ordinary_slice)
        self.assertIn("先确认图谱是否可绘制，再读路径/参考线、操作区和缺口", ordinary_slice)
        self.assertIn("DataLineageTable rows={ordinaryInterpretationActionRows}", ordinary_slice)
        self.assertIn('aria-label="next session ordinary p5 governance details"', ordinary_slice)
        self.assertIn("<summary>P5 解释治理单独补证状态</summary>", ordinary_slice)
        self.assertIn("普通主线先复核 P3 图谱来源、路径、参考线和操作区；DeepSeek governed executor 状态默认收起，只作为高级补证参考。", ordinary_slice)
        self.assertIn('aria-label="next session ordinary deepseek governance"', ordinary_slice)
        self.assertIn("解释治理单独补证状态", ordinary_slice)
        self.assertIn("DeepSeek 解释单独补证；基础图谱先按本地 cache 回放", ordinary_slice)
        self.assertIn("DataLineageTable rows={ordinaryDeepSeekGovernanceRows}", ordinary_slice)
        self.assertIn('aria-label="next session ordinary chart review checklist"', ordinary_slice)
        self.assertIn("图谱复核清单", ordinary_slice)
        self.assertIn("按图表路径、参考线、操作区、缺少证据复核", ordinary_slice)
        self.assertIn("优先读取服务端 ordinary_chart_review_rows", ordinary_slice)
        self.assertIn("DataLineageTable rows={ordinaryChartReviewRows}", ordinary_slice)
        self.assertIn("下一票雷达", source_before_audit)
        self.assertIn("股票量化推演", source_before_audit)
        self.assertIn("次日图谱", source_before_audit)
        self.assertIn('复核项: "图表路径"', source_before_audit)
        self.assertIn('复核项: "参考线"', source_before_audit)
        self.assertIn('复核项: "操作区"', source_before_audit)
        self.assertIn('复核项: "缺少证据"', source_before_audit)
        self.assertIn('行动: "1. 确认图谱状态"', source_before_audit)
        self.assertIn('行动: "2. 读路径和参考线"', source_before_audit)
        self.assertIn('行动: "3. 读操作区"', source_before_audit)
        self.assertIn('行动: "4. 读缺口并回流"', source_before_audit)
        self.assertIn('治理段: "数据源边界"', source_before_audit)
        self.assertIn('治理段: "模型状态"', source_before_audit)
        self.assertIn('治理段: "阻塞关系"', source_before_audit)
        self.assertIn('治理段: "真实调用门槛"', source_before_audit)
        self.assertIn('label: "最近结果"', ordinary_slice)
        self.assertIn("最近结果：", source_before_audit)
        self.assertIn("只读取图表路径；不重算价格、不调用数据源或模型", source_before_audit)
        self.assertIn("参考线只作研究复核，不生成买卖动作", source_before_audit)
        self.assertIn("不改操作区、不下单、不写 strategy action", source_before_audit)
        self.assertIn("缺口只提示后续补证，不把空结果解释成无风险", source_before_audit)
        self.assertIn("输入和页面打开不外联", source_before_audit)
        self.assertIn("只有确认按钮可创建 Tushare-first 后台 task", source_before_audit)
        self.assertIn("只有下一票雷达确认按钮可创建 Tushare-first POST task；图谱页不提交上游 task", source_before_audit)
        self.assertIn("本页只读 cache，不补调 Tushare 或 DeepSeek", source_before_audit)
        self.assertIn("DeepSeek governed executor 单独补", source_before_audit)
        self.assertIn("操作区只表示条件区间和复核提示", source_before_audit)
        self.assertIn("只读 chart_summary；不创建 task、不调用 Tushare/DeepSeek/GitHub", source_before_audit)
        self.assertIn("只解释本地路径和参考线；不重算价格、不写 strategy action", source_before_audit)
        self.assertIn("不改操作区、不下单、不把区域当交易指令", source_before_audit)
        self.assertIn("GET cache 和 React render 不补调 provider/model", source_before_audit)
        self.assertIn("DeepSeek 不作为数据源，不覆盖图谱路径、价格、参考线或操作区", source_before_audit)
        self.assertIn("普通页不展示 prompt/output，不从页面渲染调用模型", source_before_audit)
        self.assertIn("P5 DeepSeek 不阻塞 Tushare-first、Factor cache 或次日基础图谱", source_before_audit)
        self.assertIn("GET cache、React render 和普通链接都不调用 DeepSeek", source_before_audit)
        self.assertIn('href={CANDIDATE_CONFIRM_HREF}', ordinary_slice)
        self.assertIn('href="#factor"', ordinary_slice)
        self.assertIn('id="next-session-chart"', self.page)
        self.assertIn('id="next-session-generate-actions"', ordinary_slice)
        self.assertIn('aria-label="next session manual generate actions"', ordinary_slice)
        self.assertIn("disabled={nextSessionGenerateButtonDisabled}", ordinary_slice)
        self.assertIn("{nextSessionGenerateButtonText}", ordinary_slice)
        advanced_generation_start = ordinary_slice.index('aria-label="next session advanced generation actions"')
        advanced_generation_end = ordinary_slice.index("</details>", advanced_generation_start)
        advanced_generation_slice = ordinary_slice[advanced_generation_start:advanced_generation_end]
        self.assertIn("<summary>数据生成 / 高级操作</summary>", advanced_generation_slice)
        self.assertIn('id="next-session-generate-actions"', advanced_generation_slice)
        self.assertIn("{nextSessionGenerateButtonText}", advanced_generation_slice)
        self.assertNotIn("onClick={launchTask}", ordinary_slice[:advanced_generation_start])
        self.assertIn('aria-label="next session local cache actions"', ordinary_slice[:advanced_generation_start])
        self.assertIn('title="跳到本页完整次日图谱区域；只读本地次日图谱数据"', ordinary_slice)
        self.assertIn('title="切换到下一票雷达确认输入区；换标的仍需确认按钮"', ordinary_slice)
        self.assertIn('title="切换到股票量化推演模块；只读 Factor cache 回放"', ordinary_slice)
        self.assertIn("回放入口只切换本地模块路由（#candidates/... 直达确认输入区，#factor 到量化推演）", source_before_audit)
        self.assertIn("这些回放入口只做本地模块路由切换", ordinary_slice)
        app_source = (self.root / "desktop" / "src" / "App.tsx").read_text(encoding="utf-8")
        for route_key in ('"candidates"', '"factor"', '"next"'):
            self.assertIn(route_key, app_source)
        self.assertIn("normalizeRouteKey(window.location.hash)", app_source)
        self.assertIn('aria-label="next session ordinary audit shortcuts"', ordinary_slice)
        self.assertIn("<summary>高级诊断入口</summary>", ordinary_slice)
        self.assertIn("详细证据继续默认收起", ordinary_slice)
        self.assertIn('href="#next-session-audit"', ordinary_slice)
        self.assertIn("QA、promotion、cache ledger 和原始 packet 下沉", ordinary_slice)
        self.assertIn('aria-label="next session task receipt details"', ordinary_slice)
        self.assertIn("<summary>任务回执详情</summary>", ordinary_slice)
        self.assertIn("本地 POST task 回执、QA 审查回执和 promotion 审查回执默认收起", ordinary_slice)
        receipt_details_start = self.page.index('aria-label="next session task receipt details"')
        receipt_details_end = self.page.index("</details>", receipt_details_start)
        receipt_details_slice = self.page[receipt_details_start:receipt_details_end]
        self.assertIn("<TaskLaunchReceipt receipt={taskReceipt} />", receipt_details_slice)
        self.assertIn("<TaskLaunchReceipt receipt={browserQaReceipt} />", receipt_details_slice)
        self.assertIn("<TaskLaunchReceipt receipt={streamlitParityReceipt} />", receipt_details_slice)
        self.assertIn("<TaskLaunchReceipt receipt={productionPromotionReceipt} />", receipt_details_slice)
        self.assertNotIn("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />", receipt_details_slice)
        self.assertLess(receipt_details_end, self.page.index("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />"))
        self.assertIn('id="next-session-audit"', self.page)
        self.assertIn('aria-label="next session developer audit details"', self.page)
        self.assertLess(self.page.index('aria-label="next session ordinary audit shortcuts"'), audit_start)
        self.assertLess(self.page.index('aria-label="next session task receipt details"'), audit_start)
        self.assertLess(audit_start, self.page.index("开发 / 审计指标", audit_start))
        self.assertLess(audit_start, self.page.index("GET cache envelope call_ledger", audit_start))
        replay_heading = ordinary_slice.index("<h3>三段结果回放</h3>")
        interpretation_heading = ordinary_slice.index("<h3>解释性行动清单</h3>")
        review_heading = ordinary_slice.index("<h3>图谱复核清单</h3>")
        self.assertLess(ordinary_slice.index("P3 结果交接速读"), replay_heading)
        self.assertLess(ordinary_slice.index("P3 结果交接速读"), ordinary_slice.index("操作区解释速读"))
        self.assertLess(ordinary_slice.index("操作区解释速读"), replay_heading)
        self.assertLess(ordinary_slice.index("P3 结果交接速读"), review_heading)
        self.assertLess(replay_heading, review_heading)
        self.assertLess(replay_heading, interpretation_heading)
        self.assertLess(interpretation_heading, review_heading)
        self.assertLess(review_heading, ordinary_slice.index('aria-label="next session ordinary p5 governance details"'))
        self.assertLess(ordinary_slice.index('aria-label="next session ordinary p5 governance details"'), ordinary_slice.index("解释治理单独补证状态"))
        self.assertLess(ordinary_slice.index("解释治理单独补证状态"), ordinary_slice.index('aria-label="next session replay handoff actions"'))
        self.assertLess(review_heading, ordinary_slice.index('aria-label="next session replay handoff actions"'))

        self.assertNotIn('label: "QA runbook"', ordinary_slice)
        self.assertNotIn('label: "promotion review"', ordinary_slice)
        self.assertNotIn('label: "cache envelope ledger"', ordinary_slice)
        self.assertNotIn("browserQaEvidenceRows", ordinary_slice)
        self.assertNotIn("productionPromotionReviewRows", ordinary_slice)
        self.assertNotIn("GET cache envelope call_ledger", ordinary_slice)
        self.assertNotIn("raw prompt", ordinary_slice)
        self.assertNotIn("raw output", ordinary_slice)

    def test_next_session_task_index_progress_watch_is_read_only(self):
        summary_start = self.page.index('title="普通用户次日图谱摘要"')
        checkpoint_start = self.page.index('aria-label="next session ordinary progress checkpoint"', summary_start)
        summary = self.page[summary_start:checkpoint_start]
        watch_start = summary.index('aria-label="next session local task index progress watch"')
        watch = summary[watch_start:]

        self.assertIn("本地任务进度", watch)
        self.assertIn("nextSessionTaskIndexProgressItems", watch)
        self.assertIn('label: "边用边看"', self.page)
        self.assertIn('label: "最新确认标的"', self.page)
        self.assertIn('label: "最新任务"', self.page)
        self.assertIn('label: "当前步骤"', self.page)
        self.assertIn('label: "只读来源"', self.page)
        self.assertIn("GET /api/tasks + 本地次日图谱数据 + CandidateRadar cache", self.page)
        self.assertIn("taskIndexReadbackSafe", self.page)
        self.assertIn("taskIndex.external_calls_triggered !== true", self.page)
        self.assertIn("taskIndex.latest_confirmed_symbol_creates_task_from_readback !== true", self.page)
        self.assertIn('aria-label="next session local task index progress actions"', watch)
        self.assertIn('href="#tasks"', watch)
        self.assertIn('href="#next-session-chart"', watch)
        self.assertIn('href="#factor"', watch)
        self.assertIn("这只来自 GET /api/tasks、本地次日图谱数据和 CandidateRadar cache", watch)
        self.assertIn("不创建第二个 task、不补调 Tushare/DeepSeek、不真实交易，也不改操作区", watch)
        self.assertNotIn("onClick=", watch)
        self.assertNotIn("launch" + "Task", watch)
        self.assertNotIn("post" + "Task(", watch)

    def test_next_session_first_screen_decision_is_readable_and_safe(self):
        summary_start = self.page.index('title="普通用户次日图谱摘要"')
        audit_start = self.page.index('<details id="next-session-audit"')
        usable_now_start = self.page.index('aria-label="next session ordinary usable now strip"', summary_start)
        decision_start = self.page.index('aria-label="next session first screen readable decision"', summary_start)
        decision_end = self.page.index('<MetricGrid\n        items={[', decision_start)
        decision = self.page[decision_start:decision_end]
        source_before_audit = self.page[:audit_start]

        self.assertLess(summary_start, decision_start)
        self.assertLess(decision_start, usable_now_start)
        self.assertIn("nextSessionFirstScreenReadableSentence", source_before_audit)
        self.assertIn("nextSessionFirstScreenItems", source_before_audit)
        self.assertIn("当前股票", source_before_audit)
        self.assertIn("最近结果", source_before_audit)
        self.assertIn("下一步", source_before_audit)
        self.assertIn("证据缺口", source_before_audit)
        self.assertIn("只读来源", source_before_audit)
        self.assertIn("操作边界", source_before_audit)
        self.assertIn('aria-label="next session first screen readable sentence"', decision)
        self.assertIn("{ordinaryNextText(nextSessionFirstScreenReadableSentence)}", decision)
        self.assertIn("MetricGrid items={ordinaryNextMetricItems(nextSessionFirstScreenItems)}", decision)
        self.assertIn('aria-label="next session first screen safe actions"', decision)
        self.assertIn('href={nextSessionOrdinaryProgressCheckpointAnchor}', decision)
        self.assertIn('aria-label="open next session first screen primary next step"', decision)
        self.assertIn("onClick={refreshCache}", decision)
        self.assertIn('aria-label="refresh next session cache from first screen"', decision)
        self.assertIn('href={CANDIDATE_CONFIRM_HREF}', decision)
        self.assertIn("首屏只汇总当前股票、最近结果、下一步、缺口原因和操作区边界", decision)
        self.assertIn("查看缓存只读本地缓存", decision)
        self.assertIn("链接只切换本地锚点，不创建后台流程、不刷新外部数据或模型、不下单", decision)
        self.assertNotIn("launch" + "Task", decision)
        self.assertNotIn("post" + "Task(", decision)

    def test_next_session_app_visible_now_summary_is_first_screen_read_only(self):
        summary_start = self.page.index('title="普通用户次日图谱摘要"')
        audit_start = self.page.index('<details id="next-session-audit"')
        decision_start = self.page.index('aria-label="next session first screen readable decision"', summary_start)
        visible_start = self.page.index('aria-label="next session app visible now summary"', summary_start)
        live_light_start = self.page.index('aria-label="next session live light evidence layers"', summary_start)
        visible = self.page[visible_start:live_light_start]
        source_before_audit = self.page[:audit_start]

        self.assertLess(decision_start, visible_start)
        self.assertLess(visible_start, live_light_start)
        self.assertLess(visible_start, audit_start)
        self.assertIn("nextSessionAppVisibleNowSentence", source_before_audit)
        self.assertIn("nextSessionAppVisibleNowItems", source_before_audit)
        self.assertIn("打开 app 能看到 ${candidateRadarConfirmedSymbolLabel} 的完整次日图谱", source_before_audit)
        self.assertIn("打开 app 能看到 ${candidateRadarConfirmedSymbolLabel} 的上游搜票结论", source_before_audit)
        self.assertIn("打开 app 能看到降级等待态", source_before_audit)
        self.assertIn('label: "打开可见"', source_before_audit)
        self.assertIn('label: "先读哪里"', source_before_audit)
        self.assertIn('label: "来源层"', source_before_audit)
        self.assertIn('label: "明确降级"', source_before_audit)
        self.assertIn('label: "数据能力"', source_before_audit)
        self.assertIn("nextSessionDataCapabilityReviewLabel", source_before_audit)
        self.assertIn("Tushare 数据凭证、权限、空窗口或本地结果包缺口去数据能力页复核；本页不探测接口。", source_before_audit)
        self.assertIn('label: "下一步按钮"', source_before_audit)
        self.assertIn("打开 app 能看到什么", visible)
        self.assertIn('aria-label="next session app visible now sentence"', visible)
        self.assertIn("{ordinaryNextText(nextSessionAppVisibleNowSentence)}", visible)
        self.assertIn("MetricGrid items={ordinaryNextMetricItems(nextSessionAppVisibleNowItems)}", visible)
        self.assertIn('aria-label="next session app visible now local actions"', visible)
        self.assertIn('href={nextSessionOrdinaryProgressCheckpointAnchor}', visible)
        self.assertIn('href={CANDIDATE_CONFIRM_HREF}', visible)
        self.assertIn('href={DATA_CAPABILITY_HREF}', visible)
        self.assertIn('aria-label="open data capability from next session visible now summary"', visible)
        self.assertIn('href="#factor"', visible)
        self.assertIn("这个条带只回答普通用户打开页面能看到什么", visible)
        self.assertIn("普通链接只切换本地页面或锚点", visible)
        self.assertIn("不创建后台流程、不刷新外部数据或模型、不交易、不改操作区", visible)
        self.assertNotIn("onClick=", visible)
        self.assertNotIn("launch" + "Task", visible)
        self.assertNotIn("post" + "Task(", visible)
        self.assertNotIn("TaskStatusPanel", visible)

    def test_next_session_live_light_mode_layers_are_first_screen_read_only(self):
        summary_start = self.page.index('title="普通用户次日图谱摘要"')
        audit_start = self.page.index('<details id="next-session-audit"')
        decision_start = self.page.index('aria-label="next session first screen readable decision"', summary_start)
        live_light_start = self.page.index('aria-label="next session live light evidence layers"', summary_start)
        compass_start = self.page.index('aria-label="next session ordinary review compass"', summary_start)
        usable_now_start = self.page.index('aria-label="next session ordinary usable now strip"', summary_start)
        live_light = self.page[live_light_start:compass_start]
        source_before_audit = self.page[:audit_start]

        self.assertLess(decision_start, live_light_start)
        self.assertLess(live_light_start, compass_start)
        self.assertLess(compass_start, usable_now_start)
        self.assertLess(live_light_start, audit_start)
        self.assertIn("nextSessionLiveLightModeLabel", source_before_audit)
        self.assertIn("nextSessionLiveLightNextStep", source_before_audit)
        self.assertIn("nextSessionLiveLightEvidenceItems", source_before_audit)
        self.assertIn("cache-live: 本地次日图谱可读", source_before_audit)
        self.assertIn("handoff-light: 上游搜票结论可读，完整图谱待按钮生成", source_before_audit)
        self.assertIn("degraded-light: 暂无本地 cache，只显示等待和回流入口", source_before_audit)
        self.assertIn("cache-check: 等待可绘制图谱，先看本地 cache 状态", source_before_audit)
        self.assertIn('label: "运行模式"', source_before_audit)
        self.assertIn('label: "数据层"', source_before_audit)
        self.assertIn('label: "证据层"', source_before_audit)
        self.assertIn('label: "模型层"', source_before_audit)
        self.assertIn('label: "缺口层"', source_before_audit)
        self.assertIn('label: "动作层"', source_before_audit)
        self.assertIn('label: "轻量下一步"', source_before_audit)
        self.assertIn("nextSessionTushareSourceLabel", source_before_audit)
        self.assertIn("nextSessionReplayOrigin", source_before_audit)
        self.assertIn("nextSessionP5GovernanceLabel", source_before_audit)
        self.assertIn("nextSessionMissingEvidence", source_before_audit)
        self.assertIn("仅供研究；不下单、不改操作区或 strategy action", source_before_audit)
        self.assertIn("运行模式分层", live_light)
        self.assertIn("MetricGrid items={ordinaryNextMetricItems(nextSessionLiveLightEvidenceItems)}", live_light)
        self.assertIn("轻量实时证据只读本地缓存、下一票雷达回放和任务索引", live_light)
        self.assertIn("不会因为页面打开、页面渲染或本地链接刷新外部数据或模型", live_light)
        self.assertIn("不证明长期目标生产替代完成", live_light)
        self.assertNotIn("production_replacement_complete: true", live_light)
        self.assertNotIn("onClick=", live_light)
        self.assertNotIn("launch" + "Task", live_light)
        self.assertNotIn("post" + "Task(", live_light)

    def test_next_session_tushare_data_card_is_first_screen_read_only(self):
        summary_start = self.page.index('title="普通用户次日图谱摘要"')
        audit_start = self.page.index('<details id="next-session-audit"')
        decision_start = self.page.index('aria-label="next session first screen readable decision"', summary_start)
        live_light_start = self.page.index('aria-label="next session live light evidence layers"', summary_start)
        data_card_start = self.page.index('aria-label="next session ordinary tushare data card"', summary_start)
        compass_start = self.page.index('aria-label="next session ordinary review compass"', summary_start)
        usable_now_start = self.page.index('aria-label="next session ordinary usable now strip"', summary_start)
        data_card = self.page[data_card_start:compass_start]
        source_before_audit = self.page[:audit_start]

        self.assertLess(decision_start, live_light_start)
        self.assertLess(live_light_start, data_card_start)
        self.assertLess(data_card_start, compass_start)
        self.assertLess(compass_start, usable_now_start)
        self.assertLess(data_card_start, audit_start)
        self.assertIn("candidateRadarProviderApiRows", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_provider_api_rows", source_before_audit)
        self.assertIn("nextSessionTushareDataCardReady", source_before_audit)
        self.assertIn("nextSessionTushareDataCardSummary", source_before_audit)
        self.assertIn("nextSessionTushareDataCardGap", source_before_audit)
        self.assertIn("nextSessionTushareDataCardNext", source_before_audit)
        self.assertIn("nextSessionTushareDataCardItems", source_before_audit)
        self.assertIn("nextSessionTushareDataCardRows", source_before_audit)
        self.assertIn("确认后 Tushare 数据卡可读", source_before_audit)
        self.assertIn("确认后 Tushare 数据卡等待回写", source_before_audit)
        self.assertIn("Tushare-first 账本可读；完整次日图谱还需手动生成或等待本地 cache。", source_before_audit)
        self.assertIn("缺 Tushare call_ledger；等待确认任务、本地阻断或后续授权回写。", source_before_audit)
        self.assertIn("先看上游 Tushare-first 结论，再手动生成完整次日图谱。", source_before_audit)
        self.assertIn('label: "Tushare 数据卡"', source_before_audit)
        self.assertIn('label: "接口回放"', source_before_audit)
        self.assertIn('label: "P2 三面"', source_before_audit)
        self.assertIn('label: "P3 图谱"', source_before_audit)
        self.assertIn('label: "缺口"', source_before_audit)
        self.assertIn('label: "下一步"', source_before_audit)
        self.assertIn('label: "边界"', source_before_audit)
        self.assertIn("trade_cal / daily / daily_basic / moneyflow", source_before_audit)
        self.assertIn("CandidateRadar ordinary_provider_api_rows", source_before_audit)
        self.assertIn("次日图谱只读本地 cache / call_ledger / packet；不创建第二个 task", source_before_audit)
        self.assertIn("确认后数据链状态", data_card)
        self.assertIn('aria-label="next session ordinary tushare data card summary"', data_card)
        self.assertIn("{ordinaryNextText(nextSessionTushareDataCardSummary)}", data_card)
        self.assertIn("MetricGrid items={ordinaryNextMetricItems(nextSessionTushareDataCardItems)}", data_card)
        self.assertIn('aria-label="next session ordinary tushare data card rows"', data_card)
        self.assertIn("<summary>接口回放明细</summary>", data_card)
        self.assertIn("DataLineageTable rows={nextSessionTushareDataCardRows}", data_card)
        self.assertIn("优先读取下一票雷达的普通接口回放", data_card)
        self.assertIn("旧缓存缺字段时显示轻量接口回退", data_card)
        self.assertIn("确认后数据链状态只整理已有下一票雷达回放和本地次日图谱缓存", data_card)
        self.assertIn("不会创建第二个后台流程、刷新外部数据或模型", data_card)
        self.assertIn("不交易、不改操作区或交易动作", data_card)
        self.assertNotIn("onClick=", data_card)
        self.assertNotIn("launch" + "Task", data_card)
        self.assertNotIn("post" + "Task(", data_card)
        self.assertNotIn("TaskStatusPanel", data_card)

    def test_next_session_review_compass_is_first_screen_read_only(self):
        summary_start = self.page.index('title="普通用户次日图谱摘要"')
        decision_start = self.page.index('aria-label="next session first screen readable decision"', summary_start)
        compass_start = self.page.index('aria-label="next session ordinary review compass"', summary_start)
        evidence_factory_start = self.page.index('aria-label="next session ordinary evidence factory task strip"', summary_start)
        usable_now_start = self.page.index('aria-label="next session ordinary usable now strip"', summary_start)
        metric_start = evidence_factory_start
        compass = self.page[compass_start:metric_start]
        evidence_factory_end = self.page.index('label: "主下一步"', evidence_factory_start)
        evidence_factory = self.page[evidence_factory_start:evidence_factory_end]
        audit_start = self.page.index('<details id="next-session-audit"')
        source_before_audit = self.page[:audit_start]

        self.assertLess(decision_start, compass_start)
        self.assertLess(compass_start, evidence_factory_start)
        self.assertLess(evidence_factory_start, usable_now_start)
        self.assertIn("nextSessionOrdinaryReviewCompassItems", source_before_audit)
        self.assertIn("nextSessionOrdinaryReviewCompassRows", source_before_audit)
        self.assertIn("次日图谱复核顺序", compass)
        self.assertIn("先看图表路径和参考线，再看操作区条件", compass)
        self.assertIn("不是买卖、下单或加仓指令", compass)
        self.assertIn("MetricGrid items={ordinaryNextMetricItems(nextSessionOrdinaryReviewCompassItems)}", compass)
        self.assertIn('aria-label="next session ordinary review compass actions"', compass)
        self.assertIn('href="#next-session-chart"', compass)
        self.assertIn('href="#factor"', compass)
        self.assertIn('href={CANDIDATE_CONFIRM_HREF}', compass)
        self.assertIn('aria-label="next session ordinary review compass rows"', compass)
        self.assertIn("复核顺序明细", compass)
        self.assertIn("DataLineageTable rows={nextSessionOrdinaryReviewCompassRows}", compass)
        self.assertIn("不证明 LTG-08 production replacement", compass)
        self.assertIn("读图罗盘只切换本地锚点和页面入口", compass)
        self.assertIn("不真实交易，也不改操作区或 strategy action", compass)
        self.assertIn('label: "先看哪里"', source_before_audit)
        self.assertIn('label: "再看什么"', source_before_audit)
        self.assertIn('label: "怎么判断"', source_before_audit)
        self.assertIn('label: "回流入口"', source_before_audit)
        self.assertIn('label: "只读来源"', source_before_audit)
        self.assertIn('label: "安全边界"', source_before_audit)
        self.assertIn('复核顺序: "1. 图表路径"', source_before_audit)
        self.assertIn('复核顺序: "2. 参考线和操作区"', source_before_audit)
        self.assertIn('复核顺序: "3. 缺口和回流"', source_before_audit)
        self.assertIn('复核顺序: "4. 仅供研究"', source_before_audit)
        self.assertNotIn("onClick=", compass)
        self.assertNotIn("launch" + "Task", compass)
        self.assertNotIn("post" + "Task(", compass)
        self.assertIn("nextSessionEvidenceFactoryItems", source_before_audit)
        self.assertIn("LTG-08 本地证据按钮", evidence_factory)
        self.assertIn("same-packet retained signal/capability coverage", evidence_factory)
        self.assertIn('aria-label="next session ordinary evidence factory actions"', evidence_factory)
        self.assertIn("onClick={reviewBrowserQa}", evidence_factory)
        self.assertIn("onClick={reviewStreamlitParity}", evidence_factory)
        self.assertIn("onClick={reviewProductionPromotion}", evidence_factory)
        self.assertIn("<TaskStatusPanel taskId={browserQaTaskId} onSuccess={refreshCache} />", evidence_factory)
        self.assertIn("local review 仍不是 production replacement complete", evidence_factory)


if __name__ == "__main__":
    unittest.main()
