import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1] / "desktop"


class FactorQuantHubOrdinaryEntryTests(unittest.TestCase):
    def test_stock_quant_projection_summary_shows_user_decision_fields_first(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")

        self.assertIn('title="股票量化推演"', source)
        self.assertIn("普通用户量化推演摘要", source)
        self.assertIn("下一步、来源、缺口、边界和最近可用缓存", source)
        self.assertIn('label: "下一步"', source)
        self.assertIn('label: "运行模式"', source)
        self.assertIn('label: "本地缓存"', source)
        self.assertIn('label: "数据链"', source)
        self.assertIn('label: "解释状态"', source)
        self.assertIn('label: "待补证据"', source)
        self.assertIn('label: "降级提示"', source)
        self.assertIn('label: "最近成功回放"', source)
        self.assertIn('label: "雷达搜票回放"', source)
        self.assertIn('label: "上游确认链"', source)
        self.assertIn('label: "确认结果链"', source)
        self.assertIn('label: "P2 三面回放"', source)
        self.assertIn('label: "回放位置"', source)
        self.assertIn('label: "查看顺序"', source)
        self.assertIn('label: "结果组成"', source)
        self.assertIn('label: "P3 可读结论"', source)
        self.assertIn('label: "P3 下一步"', source)
        self.assertIn('label: "P3 边界"', source)
        self.assertIn('label: "数据来源状态"', source)
        self.assertIn('label: "调用记录"', source)
        self.assertIn('label: "结果包"', source)
        self.assertIn('label: "补证方式"', source)
        self.assertIn('label: "缺少证据"', source)
        self.assertIn('label: "阻断/降级"', source)
        self.assertIn('label: "最近可用缓存"', source)
        self.assertIn('label: "任务边界"', source)
        self.assertIn('label: "结果边界"', source)
        self.assertIn('label: "仅供研究"', source)
        self.assertLess(source.index("普通用户量化推演摘要"), source.index('launchTask("/api/factor-quant/run-light"'))
        self.assertLess(source.index("普通用户量化推演摘要"), source.index("高级验收任务"))
        self.assertLess(source.index("普通用户量化推演摘要"), source.index("开发 / 审计指标"))
        self.assertLess(source.index('label: "本地缓存"'), source.index("开发 / 审计指标"))
        self.assertLess(source.index('label: "最近成功回放"'), source.index("开发 / 审计指标"))
        summary_start = source.index("普通用户量化推演摘要")
        summary_end = source.index("高级验收任务", summary_start)
        summary_slice = source[summary_start:summary_end]
        for engineering_label in (
            'label: "cache"',
            'label: "Tushare"',
            'label: "DeepSeek"',
            'label: "pending"',
            'label: "degraded"',
            'label: "last_successful_cache/result"',
            'label: "ledger"',
            'label: "packet"',
        ):
            self.assertNotIn(engineering_label, summary_slice)
        self.assertIn("ordinaryQuantDegradedSourceLabel", source)
        self.assertIn("degraded：未标记降级", source)
        self.assertIn("DeepSeek 解释已有本地结果；只解释不改数值或动作", source)
        self.assertIn("DeepSeek 待 governed executor；普通页只读状态", source)
        self.assertIn("模型未调用或等待 governed executor", source)
        self.assertNotIn("DeepSeek 解释未生成或等待手动任务", source)
        self.assertNotIn("模型未调用或等待手动任务", source)
        self.assertIn("ordinaryQuantRadarHandoffState", source)
        self.assertIn("ordinaryQuantReplayLocation", source)
        self.assertIn("ordinaryQuantReviewOrder", source)
        self.assertIn("ordinaryQuantResultComposition", source)
        self.assertIn("ordinaryQuantP3ReadableConclusion", source)
        self.assertIn("ordinaryQuantP3NextStep", source)
        self.assertIn("ordinaryQuantP3Boundary", source)
        self.assertIn("ordinaryQuantResultBoundary", source)
        self.assertIn("ordinaryQuantResultReplayRows", source)
        self.assertIn("ordinaryQuantFullNextSessionRows", source)
        self.assertIn("getCandidateRadarCache", source)
        self.assertIn("candidateRadarSmallDataWriteback", source)
        self.assertIn("candidateRadarOneScreenRows", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_one_screen_action_rows", source)
        self.assertIn("candidateRadarConfirmOutcomeRows", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_confirm_outcome_rows", source)
        self.assertIn("candidateRadarWritebackSurfaceRows", source)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_writeback_surface_summary_rows", source)
        self.assertIn("ordinaryQuantUpstreamOneScreenRows", source)
        self.assertIn("ordinaryQuantUpstreamOneScreenLabel", source)
        self.assertIn("ordinaryQuantUpstreamConfirmOutcomeRows", source)
        self.assertIn("ordinaryQuantUpstreamConfirmOutcomeLabel", source)
        self.assertIn("ordinaryQuantSmallDataWritebackState", source)
        self.assertIn("ordinaryQuantP2WritebackBoundary", source)
        self.assertIn("ordinaryQuantUpstreamP2WritebackRows", source)
        self.assertIn("ordinaryQuantUpstreamP2WritebackLabel", source)
        self.assertIn("ordinaryDeepSeekGovernedExecutorState", source)
        self.assertIn("ordinaryDeepSeekGovernedExecutorRows", source)
        self.assertIn('aria-label="stock quant ordinary upstream one screen actions"', source)
        self.assertIn("上游确认一屏行动", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_one_screen_action_rows", source)
        self.assertIn("确认、任务、写回、结果合成量化页上游速读", source)
        self.assertIn("本页只读回放，不创建 task、不调用模型", source)
        self.assertIn('行动: "1. 确认"', source)
        self.assertIn('行动: "2. 任务"', source)
        self.assertIn('行动: "3. 写回"', source)
        self.assertIn('行动: "4. 结果"', source)
        self.assertIn('aria-label="stock quant upstream confirm outcome readback"', source)
        self.assertIn("上游确认结果速读", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_confirm_outcome_rows", source)
        self.assertIn("确认任务是否接收、P2 三面是否回放、P3 量化结果是否可读", source)
        self.assertIn("本页只读回放，不创建第二个 task", source)
        self.assertIn('确认结果: "P1 确认结果"', source)
        self.assertIn('确认结果: "P2 写回结果"', source)
        self.assertIn('确认结果: "P3 回放结果"', source)
        self.assertIn('aria-label="stock quant upstream p2 writeback quick read"', source)
        self.assertIn("P2 小数据三面写回速读", source)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_writeback_surface_summary_rows", source)
        self.assertIn("普通入口只看 cache、call_ledger、packet 三个写入面是否可回放", source)
        self.assertIn("Factor 页只读回放，不创建 task、不补调 Tushare/DeepSeek", source)
        self.assertIn('写入面: "cache"', source)
        self.assertIn('写入面: "call_ledger"', source)
        self.assertIn('写入面: "packet"', source)
        self.assertIn("P2 小数据只从 CandidateRadar cache / call_ledger / packet 回放", source)
        self.assertIn("Factor 页 GET cache 不创建 task、不补调 Tushare/DeepSeek、不展示 token/key 或 raw log", source)
        self.assertIn("只有下一票雷达确认按钮可创建 Tushare-first POST task；本页不提交上游 task", source)
        self.assertIn("回放入口只切换本地页面/锚点（#next/#candidates 是本地模块路由，#factor-* 是页内锚点）", source)
        self.assertIn("完整次日图谱入口：从量化推演摘要打开 #next 本地模块路由", source)
        self.assertIn('aria-label="stock quant ordinary full next session handoff"', source)
        self.assertIn("完整次日图谱交接", source)
        self.assertIn("从本页打开完整次日图谱只切换 #next 本地模块", source)
        self.assertIn('交接项: "预览状态"', source)
        self.assertIn('交接项: "完整图谱入口"', source)
        self.assertIn('交接项: "阅读顺序"', source)
        self.assertIn("预览只读本地 bridge cache；不会补调 Tushare/DeepSeek，也不会写 operation_zones", source)
        self.assertIn("完整图谱页继续按路径、参考线、操作区、缺口边界复核", source)
        self.assertIn('title="跳到本页支持/压制摘要；只读 Factor cache"', source)
        self.assertIn('title="跳到本页次日图谱预览；不刷新 provider/model"', source)
        self.assertIn('title="切换到完整次日图谱模块；只读本地 next-session cache"', source)
        self.assertIn('title="跳到本页模型解释状态；DeepSeek 仍等 governed executor"', source)
        self.assertIn('title="切换到下一票雷达模块；换标的仍需输入代码并确认"', source)
        self.assertIn('aria-label="stock quant ordinary explainable result replay"', source)
        self.assertIn("三段可解释结果", source)
        self.assertIn("普通结果先按支持/压制、次日图谱预览、模型解释状态阅读", source)
        self.assertIn('结果段: "支持/压制"', source)
        self.assertIn('结果段: "次日图谱预览"', source)
        self.assertIn('结果段: "模型解释状态"', source)
        self.assertIn("只读 Factor cache，不创建 task、不调用 Tushare/DeepSeek", source)
        self.assertIn("预览不改 operation_zones，不写交易动作", source)
        self.assertIn("模型解释不覆盖价格、因子、持仓、操作区或 strategy action", source)
        self.assertIn("ordinaryFactorReviewRows", source)
        self.assertIn('aria-label="stock quant ordinary factor review checklist"', source)
        self.assertIn("因子复核清单", source)
        self.assertIn("按支持、压制、冲突、缺失四类复核", source)
        self.assertIn("普通页只读本地 score cache，不重新排序、不补调 provider/model", source)
        self.assertIn('复核项: "支持"', source)
        self.assertIn('复核项: "压制"', source)
        self.assertIn('复核项: "冲突"', source)
        self.assertIn('复核项: "缺失"', source)
        self.assertIn("支持项多时仍要检查压制和缺失；不能直接当买入理由", source)
        self.assertIn("压制项明显时优先复核次日图谱和风险提示", source)
        self.assertIn("冲突存在时先回到证据来源和图谱路径，不急着推演动作", source)
        self.assertIn("缺失项多时优先看 cache / ledger / packet 和待补证据", source)
        self.assertIn("支持因子只作研究解释，不生成买入指令、不写 strategy action", source)
        self.assertIn("压制因子只提示复核方向，不生成卖出或减仓指令", source)
        self.assertIn("冲突只表示证据分歧，不重排候选、不修改交易动作", source)
        self.assertIn("缺失只提示后续补证，不从页面渲染补调 Tushare/DeepSeek", source)
        self.assertIn("等待下一票雷达搜票生成本地量化推演", source)
        self.assertIn("Factor cache / Next Session preview / DeepSeek status", source)
        self.assertIn("先看支持/压制，再看次日图谱预览，最后看模型解释状态", source)
        self.assertIn("不要从工程审计表开始", source)
        self.assertIn("支持 ${String(score.support_factors?.length ?? 0)} / 压制 ${String(score.suppress_factors?.length ?? 0)}", source)
        self.assertIn("P3 可读结论：暂无本地量化推演；先回下一票雷达确认代码", source)
        self.assertIn("P3 下一步：回下一票雷达输入代码并点击确认；输入股票代码本身不创建 task", source)
        self.assertIn("P3 下一步：按支持/压制 -> 次日图谱预览 -> DeepSeek 状态复核；需要更新才点击按钮创建 POST task", source)
        self.assertIn("P3 边界：普通摘要只读 Factor cache、Next Session preview 和 DeepSeek status；不创建 task、不调用 Tushare/DeepSeek、不写 cache、不改 operation_zones 或 strategy action", source)
        self.assertIn("结果只用于研究复核；支持/压制、次日图谱和模型解释都不能直接变成买卖指令", source)
        self.assertIn('label: "P5 解释治理"', source)
        self.assertNotIn('label: "P5 DeepSeek"', source)
        self.assertIn('aria-label="stock quant ordinary p5 governance details"', source)
        self.assertIn("<summary>P5 解释治理单独补证状态</summary>", source)
        self.assertIn("普通主线先复核 P3 支持/压制、次日图谱预览和缺失证据；DeepSeek governed executor 状态默认收起，只作为高级补证参考。", source)
        self.assertIn('aria-label="stock quant ordinary deepseek governance"', source)
        self.assertIn("DeepSeek 单独治理状态", source)
        self.assertIn("DeepSeek 解释单独补证；不阻塞 Tushare-first、支持/压制和次日图谱；普通页不展示 prompt/output。", source)
        self.assertIn('治理段: "基础结果先行"', source)
        self.assertIn('治理段: "P5 governed executor 准入"', source)
        self.assertIn('治理段: "真实调用门槛"', source)
        self.assertIn('治理段: "普通页降噪"', source)
        self.assertIn('治理段: "输出约束"', source)
        self.assertIn("等待 governed executor；不阻塞 Tushare-first、支持/压制和次日图谱", source)
        self.assertIn("当前只允许本地 prompt preview / sanitizer / cache ledger；真实模型调用仍待 governed executor", source)
        self.assertIn('validation=${String(deepseekValidation.validation_mode ?? "local_sanitizer_only")}', source)
        self.assertIn('model_call=${String(deepseekValidation.model_call_status ?? "not_called")}', source)
        self.assertIn("P5 不阻塞 Tushare-first、Factor cache 或 Next Session", source)
        self.assertIn("真实调用只能在 governed executor 完成后进入受控按钮任务", source)
        self.assertIn("prompt/output 和模型调用明细留在高级审计", source)
        self.assertIn("普通页不展示 prompt/output，只显示是否 skipped/pending/ready", source)
        self.assertIn("结构化输出、重试修复、样本验收和成本证据未齐前不自动调用", source)
        self.assertIn("不把本地预检、票据或矩阵当成生产证据", source)
        self.assertIn("模型解释只辅助阅读，不覆盖价格、factor、持仓、operation_zones 或 strategy action", source)
        self.assertIn("不把空结果当成无风险", source)
        self.assertIn("不从本页补调 provider/model", source)
        self.assertIn("本页链接不重新触发 Tushare-first 或 DeepSeek", source)
        app_source = (ROOT / "src" / "App.tsx").read_text(encoding="utf-8")
        for route_key in ('"next"', '"candidates"', '"factor"'):
            self.assertIn(route_key, app_source)
        self.assertIn("normalizeRouteKey(window.location.hash)", app_source)
        self.assertLess(source.index('label: "查看顺序"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "结果组成"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "P3 可读结论"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "P3 边界"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "结果边界"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "雷达搜票回放"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "上游确认链"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "确认结果链"'), source.index("高级验收任务"))
        self.assertLess(source.index('label: "P2 三面回放"'), source.index("高级验收任务"))
        self.assertLess(source.index("上游确认一屏行动"), source.index("三段可解释结果"))
        self.assertLess(source.index("上游确认一屏行动"), source.index("上游确认结果速读"))
        self.assertLess(source.index("上游确认结果速读"), source.index("三段可解释结果"))
        confirm_outcome_start = source.index('aria-label="stock quant upstream confirm outcome readback"')
        confirm_outcome_end = source.index('aria-label="stock quant upstream p2 writeback quick read"', confirm_outcome_start)
        confirm_outcome_slice = source[confirm_outcome_start:confirm_outcome_end]
        self.assertNotIn("onClick=", confirm_outcome_slice)
        self.assertNotIn("launch" + "Task", confirm_outcome_slice)
        self.assertNotIn("post" + "Task(", confirm_outcome_slice)
        p2_writeback_start = source.index('aria-label="stock quant upstream p2 writeback quick read"')
        p2_writeback_end = source.index('aria-label="stock quant ordinary cache ledger packet handoff"', p2_writeback_start)
        p2_writeback_slice = source[p2_writeback_start:p2_writeback_end]
        self.assertNotIn("onClick=", p2_writeback_slice)
        self.assertNotIn("launch" + "Task", p2_writeback_slice)
        self.assertNotIn("post" + "Task(", p2_writeback_slice)
        self.assertLess(source.index("上游确认一屏行动"), source.index("高级验收任务"))
        self.assertLess(source.index("上游确认一屏行动"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("上游确认结果速读"), source.index("高级验收任务"))
        self.assertLess(source.index("上游确认结果速读"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("P2 小数据三面写回速读"), source.index("高级验收任务"))
        self.assertLess(source.index("P2 小数据三面写回速读"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("上游确认结果速读"), source.index("P2 小数据三面写回速读"))
        self.assertLess(source.index("P2 小数据三面写回速读"), source.index("三段可解释结果"))
        self.assertLess(source.index("三段可解释结果"), source.index("高级验收任务"))
        self.assertLess(source.index("三段可解释结果"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("三段可解释结果"), source.index("完整次日图谱交接"))
        self.assertLess(source.index("完整次日图谱交接"), source.index("因子复核清单"))
        self.assertLess(source.index("三段可解释结果"), source.index("因子复核清单"))
        self.assertLess(source.index("因子复核清单"), source.index('aria-label="stock quant ordinary p5 governance details"'))
        self.assertLess(source.index('aria-label="stock quant ordinary p5 governance details"'), source.index("DeepSeek 单独治理状态"))
        self.assertLess(source.index('aria-label="stock quant ordinary p5 governance details"'), source.index("模型解释 / 高级开关"))
        self.assertLess(source.index("因子复核清单"), source.index("高级验收任务"))
        self.assertLess(source.index("因子复核清单"), source.index("开发 / 审计指标"))
        self.assertLess(source.index("DeepSeek 单独治理状态"), source.index("模型解释 / 高级开关"))
        self.assertLess(source.index("DeepSeek 单独治理状态"), source.index("DeepSeek 解释治理审计"))

    def test_stock_quant_projection_explains_evidence_task_mode(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")

        self.assertIn("ordinaryQuantEvidenceTaskState", source)
        self.assertIn("等待本地缓存后再确认补证方式", source)
        self.assertIn("cache_only 只读查看，不创建补证任务", source)
        self.assertIn("manual 只允许用户按钮创建 POST task", source)
        self.assertIn("live_light 可由后台 task 补证；本页仍只读轮询缓存", source)
        self.assertIn("live_full 深度补证预留，默认关闭", source)
        self.assertIn("ordinaryQuantCacheButtonLabel", source)
        self.assertIn("ordinaryQuantRefreshButtonLabel", source)
        self.assertIn("ordinaryQuantRunLightButtonLabel", source)
        self.assertIn("查看本地缓存只读取 GET cache；不会创建 task、不会调用 Tushare 或 DeepSeek", source)
        self.assertIn("手动刷新数据会创建按钮门控 POST task；不从 React render 直连 provider/model", source)
        self.assertIn("运行轻量推演会创建按钮门控 POST task；DeepSeek 整理仍在高级开关", source)
        self.assertIn("title={ordinaryQuantCacheButtonLabel}", source)
        self.assertIn("title={ordinaryQuantRefreshButtonLabel}", source)
        self.assertIn("title={ordinaryQuantRunLightButtonLabel}", source)
        self.assertLess(source.index('label: "补证方式"'), source.index("高级验收任务"))

    def test_stock_quant_projection_reads_mode_without_bootstrap_task_launcher(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")

        self.assertIn("getBootstrapStatus", source)
        self.assertIn("refreshBootstrapStatus", source)
        self.assertIn("runtimeModeLabel", source)
        self.assertIn("cache_only（只读缓存，不外联）", source)
        self.assertIn("manual（仅手动按钮任务）", source)
        self.assertIn("live_light（轻量后台 task 口径，仍不在渲染中外联）", source)
        self.assertIn("live_full（预留，默认关闭）", source)
        self.assertIn("本页 GET cache 只读；手动刷新、轻量推演、模型整理或 live_light 补证都必须走 POST task", source)
        self.assertNotIn("postBootstrapLiveStartup", source)
        self.assertNotIn("/api/bootstrap/live-startup", source)
        self.assertNotIn("postBootstrapProviderModelExecutionRequest", source)
        self.assertNotIn("/api/bootstrap/provider-model-execution-request", source)

    def test_engineering_details_are_demoted_behind_details_blocks(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")

        self.assertIn('className="developer-audit-details"', source)
        self.assertIn("高级验收任务", source)
        self.assertIn("开发 / 审计指标", source)
        self.assertIn("评分图表 lineage 审计", source)
        self.assertIn("DeepSeek 解释治理审计", source)
        self.assertIn("最近任务回执", source)
        self.assertIn("Provider、model、receipt、runbook、QA blocker 和 LTG 细项默认收起", source)
        self.assertIn("普通路径只保留查看缓存、手动刷新和轻量推演", source)
        self.assertIn("模型解释 / 高级开关", source)
        self.assertIn("DeepSeek governed executor 单独补", source)
        self.assertIn('aria-label="stock quant ordinary p5 governance details"', source)
        self.assertIn("<summary>P5 解释治理单独补证状态</summary>", source)
        self.assertLess(source.index("DeepSeek 单独治理状态"), source.index("模型解释 / 高级开关"))
        self.assertLess(source.index("普通路径只保留查看缓存、手动刷新和轻量推演"), source.index("模型解释 / 高级开关"))
        self.assertLess(source.index("模型解释 / 高级开关"), source.index("整理模型解释</button>"))
        self.assertLess(source.index("模型解释 / 高级开关"), source.index("轻量推演完成后自动整理解释"))
        ordinary_actions_start = source.rindex(
            '<div className="actions">',
            0,
            source.index("title={ordinaryQuantCacheButtonLabel}"),
        )
        ordinary_actions_end = source.index("</div>", ordinary_actions_start)
        ordinary_actions_slice = source[ordinary_actions_start:ordinary_actions_end]
        self.assertNotIn("整理模型解释", ordinary_actions_slice)
        self.assertNotIn("轻量推演完成后自动整理解释", ordinary_actions_slice)
        self.assertLess(source.index("最近任务回执"), source.index("<TaskLaunchReceipt receipt={taskReceipt} />"))
        self.assertLess(source.index("最近任务回执"), source.index("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />"))
        self.assertLess(source.index("普通用户量化推演摘要"), source.index("最近任务回执"))
        self.assertLess(source.index("开发 / 审计指标"), source.index('label: "provider blockers"'))
        self.assertLess(source.index("评分图表 lineage 审计"), source.index("评分图表数据合同"))
        self.assertLess(source.index("DeepSeek 解释"), source.index("DeepSeek 解释治理审计"))

    def test_stock_quant_projection_page_does_not_embed_provider_model_or_trade_calls(self):
        source = (ROOT / "src" / "routes" / "FactorQuantHub.tsx").read_text(encoding="utf-8")
        forbidden_fragments = (
            "tushare.pro_api",
            "ts.pro_api",
            "deepseek.chat",
            "api.github.com",
            "executeTrade(",
            "placeOrder(",
            "broker.submit",
            "live_order",
        )
        for fragment in forbidden_fragments:
            self.assertNotIn(fragment, source)


if __name__ == "__main__":
    unittest.main()
