import unittest
from pathlib import Path


class NextSessionMapOrdinaryEntryTests(unittest.TestCase):
    def setUp(self):
        self.root = Path(__file__).resolve().parents[1]
        self.page = (self.root / "desktop" / "src" / "routes" / "NextSessionMap.tsx").read_text(
            encoding="utf-8"
        )

    def test_next_session_has_three_step_ordinary_result_replay_before_audit(self):
        summary_start = self.page.index('title="普通用户次日图谱摘要"')
        audit_start = self.page.index('<details id="next-session-audit"')
        ordinary_slice = self.page[summary_start:audit_start]
        source_before_audit = self.page[:audit_start]

        self.assertLess(summary_start, audit_start)
        self.assertIn("ordinaryResultReplayStatus", source_before_audit)
        self.assertIn("ordinaryResultReplayRows", source_before_audit)
        self.assertIn("packetOrdinaryResultReplayRows", source_before_audit)
        self.assertIn("packet.ordinary_result_replay_rows", source_before_audit)
        self.assertIn("packet.ordinary_result_replay_status", source_before_audit)
        self.assertIn("fallbackOrdinaryResultReplayRows", source_before_audit)
        self.assertIn("packetOrdinaryResultReplayRows.length", source_before_audit)
        self.assertIn("ordinaryInterpretationActionRows", source_before_audit)
        self.assertIn("ordinaryDeepSeekGovernanceRows", source_before_audit)
        self.assertIn("ordinaryChartReviewRows", source_before_audit)
        self.assertIn("nextSessionResultHandoffRows", source_before_audit)
        self.assertIn("nextSessionP3OneMinuteReadRows", source_before_audit)
        self.assertIn("nextSessionOperationZoneQuickReadRows", source_before_audit)
        self.assertIn("getCandidateRadarCache", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback", source_before_audit)
        self.assertIn("candidateRadarOneScreenRows", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_one_screen_action_rows", source_before_audit)
        self.assertIn("candidateRadarConfirmOutcomeRows", source_before_audit)
        self.assertIn("candidateRadarSmallDataWriteback.ordinary_confirm_outcome_rows", source_before_audit)
        self.assertIn("candidateRadarCache.ordinary_result_quick_read_rows", source_before_audit)
        self.assertIn("candidateRadarCache.ordinary_result_handoff_rows", source_before_audit)
        self.assertIn("candidateRadarInterpretation.ordinary_result_quick_read_rows", source_before_audit)
        self.assertIn("candidateRadarInterpretation.ordinary_result_handoff_rows", source_before_audit)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_result_quick_read_rows / ordinary_result_handoff_rows", source_before_audit)
        self.assertIn("nextSessionUpstreamOneScreenRows", source_before_audit)
        self.assertIn("nextSessionUpstreamOneScreenLabel", source_before_audit)
        self.assertIn("nextSessionUpstreamConfirmOutcomeRows", source_before_audit)
        self.assertIn("nextSessionUpstreamConfirmOutcomeLabel", source_before_audit)
        self.assertIn("packetOrdinaryChartReviewRows", source_before_audit)
        self.assertIn("packet.ordinary_chart_review_rows", source_before_audit)
        self.assertIn("packetOrdinaryConditionQuickReadRows", source_before_audit)
        self.assertIn("packet.ordinary_condition_quick_read_rows", source_before_audit)
        self.assertIn("fallbackNextSessionOperationZoneQuickReadRows", source_before_audit)
        self.assertIn("packetOrdinaryConditionQuickReadRows.length", source_before_audit)
        self.assertIn("fallbackOrdinaryChartReviewRows", source_before_audit)
        self.assertIn("packetOrdinaryChartReviewRows.length", source_before_audit)
        self.assertIn("nextSessionLastResultLabel", source_before_audit)
        self.assertIn("nextSessionOrdinaryReplayBoundaryBlocked", source_before_audit)
        self.assertIn("evidence_gap_clear", source_before_audit)
        self.assertIn("research_boundary_ready", source_before_audit)
        metric_start = ordinary_slice.index("<MetricGrid")
        metric_end = ordinary_slice.index("<StateClarityRail", metric_start)
        summary_metric_slice = ordinary_slice[metric_start:metric_end]
        self.assertIn('label: "本地缓存"', summary_metric_slice)
        self.assertIn('label: "数据链"', summary_metric_slice)
        self.assertIn('label: "解释状态"', summary_metric_slice)
        self.assertIn('label: "P5 解释治理"', summary_metric_slice)
        self.assertIn('label: "待补证据"', summary_metric_slice)
        self.assertIn('label: "降级提示"', summary_metric_slice)
        self.assertIn("nextSessionP5GovernanceLabel", source_before_audit)
        self.assertIn("P5 解释治理：DeepSeek 单独补证，不阻塞 P3 图谱复核", source_before_audit)
        for engineering_label in (
            'label: "cache"',
            'label: "Tushare"',
            'label: "DeepSeek"',
            'label: "pending"',
            'label: "degraded"',
        ):
            self.assertNotIn(engineering_label, summary_metric_slice)
        self.assertIn('label: "缺口边界"', source_before_audit)
        self.assertIn('label: "上游确认链"', source_before_audit)
        self.assertIn('label: "确认结果链"', source_before_audit)
        rail_start = ordinary_slice.index('label="next session ordinary replay status"')
        handoff_start = ordinary_slice.index('aria-label="next session p3 result handoff quick read"')
        rail_slice = ordinary_slice[rail_start:handoff_start]
        self.assertIn("普通图谱状态：雷达/量化回放 / 图表路径 / 操作区 / 缺口边界", rail_slice)
        self.assertIn("P5 解释治理继续收起为单独补证", rail_slice)
        self.assertNotIn("DeepSeek 状态", rail_slice)
        upstream_start = ordinary_slice.index('aria-label="next session upstream one screen actions"')
        one_minute_start = ordinary_slice.index('aria-label="next session p3 one minute read"')
        handoff_start = ordinary_slice.index('aria-label="next session p3 result handoff quick read"')
        self.assertLess(upstream_start, one_minute_start)
        upstream_slice = ordinary_slice[upstream_start:one_minute_start]
        self.assertIn("上游确认一屏行动", upstream_slice)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_one_screen_action_rows", upstream_slice)
        self.assertIn("确认、任务、写回、结果合成图谱页上游速读", upstream_slice)
        self.assertIn("本页只读回放，不创建 task、不调用模型", upstream_slice)
        self.assertIn("DataLineageTable rows={nextSessionUpstreamOneScreenRows}", upstream_slice)
        self.assertNotIn("onClick=", upstream_slice)
        self.assertNotIn("launch" + "Task", upstream_slice)
        self.assertNotIn("post" + "Task(", upstream_slice)
        confirm_outcome_start = ordinary_slice.index('aria-label="next session upstream confirm outcome readback"')
        self.assertLess(upstream_start, confirm_outcome_start)
        self.assertLess(confirm_outcome_start, one_minute_start)
        confirm_outcome_slice = ordinary_slice[confirm_outcome_start:one_minute_start]
        self.assertIn("上游确认结果速读", confirm_outcome_slice)
        self.assertIn("优先读取 CandidateRadar 的 ordinary_confirm_outcome_rows", confirm_outcome_slice)
        self.assertIn("确认任务是否接收、P2 三面是否回放、P3 图谱入口是否可读", confirm_outcome_slice)
        self.assertIn("本页只读回放，不创建第二个 task", confirm_outcome_slice)
        self.assertIn("DataLineageTable rows={nextSessionUpstreamConfirmOutcomeRows}", confirm_outcome_slice)
        self.assertNotIn("onClick=", confirm_outcome_slice)
        self.assertNotIn("launch" + "Task", confirm_outcome_slice)
        self.assertNotIn("post" + "Task(", confirm_outcome_slice)
        self.assertLess(one_minute_start, handoff_start)
        one_minute_slice = ordinary_slice[one_minute_start:handoff_start]
        self.assertIn("P3 一分钟读图", one_minute_slice)
        self.assertIn("普通用户先看这张表：用一分钟确认来源、可读结论、operation_zones、缺口和回流入口", one_minute_slice)
        self.assertIn("DataLineageTable rows={nextSessionP3OneMinuteReadRows}", one_minute_slice)
        self.assertNotIn("onClick=", one_minute_slice)
        self.assertNotIn("launch" + "Task", one_minute_slice)
        self.assertNotIn("post" + "Task(", one_minute_slice)
        self.assertIn('aria-label="next session p3 result handoff quick read"', ordinary_slice)
        self.assertIn("P3 结果交接速读", ordinary_slice)
        self.assertIn("先看来源、结论、缺口和操作区边界", ordinary_slice)
        self.assertIn("DataLineageTable rows={nextSessionResultHandoffRows}", ordinary_slice)
        self.assertIn('aria-label="next session ordinary operation zone quick read"', ordinary_slice)
        self.assertIn("操作区解释速读", ordinary_slice)
        self.assertIn("普通用户先按路径、参考线、操作区的顺序读", ordinary_slice)
        self.assertIn("operation_zones 只是条件区间和复核提示，不是买卖、下单或 strategy action", ordinary_slice)
        self.assertIn("优先读取本地缓存里的条件速读", ordinary_slice)
        self.assertIn("旧缓存缺字段时才使用前端 fallback", ordinary_slice)
        self.assertIn("DataLineageTable rows={nextSessionOperationZoneQuickReadRows}", ordinary_slice)
        self.assertIn('速读项: "1. 先读路径"', source_before_audit)
        self.assertIn('速读项: "2. 再读操作区"', source_before_audit)
        self.assertIn('速读项: "3. 动作隔离"', source_before_audit)
        self.assertIn("等待 operation_zones cache；不能把空操作区解释成无风险", source_before_audit)
        self.assertIn("边界正常：前端只读，不改 action 或 operation_zones", source_before_audit)
        self.assertIn("次日图谱不下单、不写 strategy action；DeepSeek 也不能覆盖 operation_zones", source_before_audit)
        self.assertIn('交接段: "1. 来源"', source_before_audit)
        self.assertIn('交接段: "2. 结论"', source_before_audit)
        self.assertIn('交接段: "3. 缺口"', source_before_audit)
        self.assertIn('交接段: "4. 操作区"', source_before_audit)
        self.assertIn('读图顺序: "1. 来源"', source_before_audit)
        self.assertIn('读图顺序: "2. 可读结论"', source_before_audit)
        self.assertIn('读图顺序: "3. 操作区"', source_before_audit)
        self.assertIn('读图顺序: "4. 缺口"', source_before_audit)
        self.assertIn('读图顺序: "5. 回流"', source_before_audit)
        self.assertIn('行动: "1. 确认"', source_before_audit)
        self.assertIn('行动: "2. 任务"', source_before_audit)
        self.assertIn('行动: "3. 写回"', source_before_audit)
        self.assertIn('行动: "4. 结果"', source_before_audit)
        self.assertIn('确认结果: "P1 确认结果"', source_before_audit)
        self.assertIn('确认结果: "P2 写回结果"', source_before_audit)
        self.assertIn('确认结果: "P3 回放结果"', source_before_audit)
        self.assertIn("GET cache 只读；不创建 task、不调用 Tushare/DeepSeek/GitHub", source_before_audit)
        self.assertIn("缺口只提示下一步；GET cache 和 React render 不补调 provider/model", source_before_audit)
        self.assertIn("local route handoff #candidates/#factor", source_before_audit)
        self.assertIn("三段结果回放", ordinary_slice)
        self.assertIn("三段结果回放优先读取服务端 ordinary_result_replay_rows", ordinary_slice)
        self.assertIn("旧 packet 缺字段时才使用前端 fallback", ordinary_slice)
        self.assertIn("DataLineageTable rows={ordinaryResultReplayRows}", ordinary_slice)
        self.assertIn('aria-label="next session ordinary interpretation actions"', ordinary_slice)
        self.assertIn("解释性行动清单", ordinary_slice)
        self.assertIn("先确认图谱是否可绘制，再读路径/参考线、操作区和缺口", ordinary_slice)
        self.assertIn("DataLineageTable rows={ordinaryInterpretationActionRows}", ordinary_slice)
        self.assertIn('aria-label="next session ordinary p5 governance details"', ordinary_slice)
        self.assertIn("<summary>P5 解释治理单独补证状态</summary>", ordinary_slice)
        self.assertIn("普通主线先复核 P3 图谱来源、路径、参考线和 operation_zones；DeepSeek governed executor 状态默认收起，只作为高级补证参考。", ordinary_slice)
        self.assertIn('aria-label="next session ordinary deepseek governance"', ordinary_slice)
        self.assertIn("解释治理单独补证状态", ordinary_slice)
        self.assertIn("DeepSeek 解释单独补证；基础图谱先按本地 cache 回放", ordinary_slice)
        self.assertIn("DataLineageTable rows={ordinaryDeepSeekGovernanceRows}", ordinary_slice)
        self.assertIn('aria-label="next session ordinary chart review checklist"', ordinary_slice)
        self.assertIn("图谱复核清单", ordinary_slice)
        self.assertIn("按图表路径、参考线、操作区、缺少证据复核", ordinary_slice)
        self.assertIn("优先读取服务端 ordinary_chart_review_rows", ordinary_slice)
        self.assertIn("DataLineageTable rows={ordinaryChartReviewRows}", ordinary_slice)
        self.assertIn("下一票雷达", source_before_audit)
        self.assertIn("股票量化推演", source_before_audit)
        self.assertIn("次日图谱", source_before_audit)
        self.assertIn('复核项: "图表路径"', source_before_audit)
        self.assertIn('复核项: "参考线"', source_before_audit)
        self.assertIn('复核项: "操作区"', source_before_audit)
        self.assertIn('复核项: "缺少证据"', source_before_audit)
        self.assertIn('行动: "1. 确认图谱状态"', source_before_audit)
        self.assertIn('行动: "2. 读路径和参考线"', source_before_audit)
        self.assertIn('行动: "3. 读操作区"', source_before_audit)
        self.assertIn('行动: "4. 读缺口并回流"', source_before_audit)
        self.assertIn('治理段: "数据源边界"', source_before_audit)
        self.assertIn('治理段: "模型状态"', source_before_audit)
        self.assertIn('治理段: "阻塞关系"', source_before_audit)
        self.assertIn('治理段: "真实调用门槛"', source_before_audit)
        self.assertIn('label: "最近结果"', ordinary_slice)
        self.assertIn("最近结果：", source_before_audit)
        self.assertIn("只读取图表路径；不重算价格、不调用数据源或模型", source_before_audit)
        self.assertIn("参考线只作研究复核，不生成买卖动作", source_before_audit)
        self.assertIn("不改 operation_zones、不下单、不写 strategy action", source_before_audit)
        self.assertIn("缺口只提示后续补证，不把空结果解释成无风险", source_before_audit)
        self.assertIn("输入和页面打开不外联", source_before_audit)
        self.assertIn("只有确认按钮可创建 Tushare-first 后台 task", source_before_audit)
        self.assertIn("只有下一票雷达确认按钮可创建 Tushare-first POST task；图谱页不提交上游 task", source_before_audit)
        self.assertIn("本页只读 cache，不补调 Tushare 或 DeepSeek", source_before_audit)
        self.assertIn("DeepSeek governed executor 单独补", source_before_audit)
        self.assertIn("operation_zones 只表示条件区间和复核提示", source_before_audit)
        self.assertIn("只读 chart_summary；不创建 task、不调用 Tushare/DeepSeek/GitHub", source_before_audit)
        self.assertIn("只解释本地路径和参考线；不重算价格、不写 strategy action", source_before_audit)
        self.assertIn("不改 operation_zones、不下单、不把区域当交易指令", source_before_audit)
        self.assertIn("GET cache 和 React render 不补调 provider/model", source_before_audit)
        self.assertIn("DeepSeek 不作为数据源，不覆盖图谱路径、价格、参考线或 operation_zones", source_before_audit)
        self.assertIn("普通页不展示 prompt/output，不从页面渲染调用模型", source_before_audit)
        self.assertIn("P5 DeepSeek 不阻塞 Tushare-first、Factor cache 或次日基础图谱", source_before_audit)
        self.assertIn("GET cache、React render 和普通链接都不调用 DeepSeek", source_before_audit)
        self.assertIn('href="#candidates"', ordinary_slice)
        self.assertIn('href="#factor"', ordinary_slice)
        self.assertIn('title="切换到下一票雷达模块；换标的仍需确认按钮"', ordinary_slice)
        self.assertIn('title="切换到股票量化推演模块；只读 Factor cache 回放"', ordinary_slice)
        self.assertIn("回放入口只切换本地模块路由（#candidates/#factor）", source_before_audit)
        self.assertIn("这些回放入口只做本地模块路由切换", ordinary_slice)
        app_source = (self.root / "desktop" / "src" / "App.tsx").read_text(encoding="utf-8")
        for route_key in ('"candidates"', '"factor"', '"next"'):
            self.assertIn(route_key, app_source)
        self.assertIn("normalizeRouteKey(window.location.hash)", app_source)
        self.assertIn('aria-label="next session ordinary audit shortcuts"', ordinary_slice)
        self.assertIn("<summary>高级诊断入口</summary>", ordinary_slice)
        self.assertIn("工程审计明细继续默认收起", ordinary_slice)
        self.assertIn('href="#next-session-audit"', ordinary_slice)
        self.assertIn("QA、promotion、cache ledger 和原始 packet 下沉", ordinary_slice)
        self.assertIn('aria-label="next session task receipt details"', ordinary_slice)
        self.assertIn("<summary>任务回执详情</summary>", ordinary_slice)
        self.assertIn("本地 POST task 回执、QA 审查回执和 promotion 审查回执默认收起", ordinary_slice)
        receipt_details_start = self.page.index('aria-label="next session task receipt details"')
        receipt_details_end = self.page.index("</details>", receipt_details_start)
        receipt_details_slice = self.page[receipt_details_start:receipt_details_end]
        self.assertIn("<TaskLaunchReceipt receipt={taskReceipt} />", receipt_details_slice)
        self.assertIn("<TaskLaunchReceipt receipt={browserQaReceipt} />", receipt_details_slice)
        self.assertIn("<TaskLaunchReceipt receipt={streamlitParityReceipt} />", receipt_details_slice)
        self.assertIn("<TaskLaunchReceipt receipt={productionPromotionReceipt} />", receipt_details_slice)
        self.assertNotIn("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />", receipt_details_slice)
        self.assertLess(receipt_details_end, self.page.index("<TaskStatusPanel taskId={taskId} onSuccess={refreshCache} />"))
        self.assertIn('id="next-session-audit"', self.page)
        self.assertIn('aria-label="next session developer audit details"', self.page)
        self.assertLess(self.page.index('aria-label="next session ordinary audit shortcuts"'), audit_start)
        self.assertLess(self.page.index('aria-label="next session task receipt details"'), audit_start)
        self.assertLess(audit_start, self.page.index("开发 / 审计指标", audit_start))
        self.assertLess(audit_start, self.page.index("GET cache envelope call_ledger", audit_start))
        self.assertLess(ordinary_slice.index("P3 结果交接速读"), ordinary_slice.index("三段结果回放"))
        self.assertLess(ordinary_slice.index("P3 结果交接速读"), ordinary_slice.index("操作区解释速读"))
        self.assertLess(ordinary_slice.index("操作区解释速读"), ordinary_slice.index("三段结果回放"))
        self.assertLess(ordinary_slice.index("P3 结果交接速读"), ordinary_slice.index("图谱复核清单"))
        self.assertLess(ordinary_slice.index("三段结果回放"), ordinary_slice.index("图谱复核清单"))
        self.assertLess(ordinary_slice.index("三段结果回放"), ordinary_slice.index("解释性行动清单"))
        self.assertLess(ordinary_slice.index("解释性行动清单"), ordinary_slice.index("图谱复核清单"))
        self.assertLess(ordinary_slice.index("图谱复核清单"), ordinary_slice.index('aria-label="next session ordinary p5 governance details"'))
        self.assertLess(ordinary_slice.index('aria-label="next session ordinary p5 governance details"'), ordinary_slice.index("解释治理单独补证状态"))
        self.assertLess(ordinary_slice.index("解释治理单独补证状态"), ordinary_slice.index('aria-label="next session replay handoff actions"'))
        self.assertLess(ordinary_slice.index("图谱复核清单"), ordinary_slice.index('aria-label="next session replay handoff actions"'))

        self.assertNotIn('label: "QA runbook"', ordinary_slice)
        self.assertNotIn('label: "promotion review"', ordinary_slice)
        self.assertNotIn('label: "cache envelope ledger"', ordinary_slice)
        self.assertNotIn("browserQaEvidenceRows", ordinary_slice)
        self.assertNotIn("productionPromotionReviewRows", ordinary_slice)
        self.assertNotIn("GET cache envelope call_ledger", ordinary_slice)
        self.assertNotIn("raw prompt", ordinary_slice)
        self.assertNotIn("raw output", ordinary_slice)


if __name__ == "__main__":
    unittest.main()
